import type { InteractionField, InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import type { TransqAction, TransqInput, TransqResult } from "./core.js"
export type TransqInteractionValues = InteractionValues & { action: TransqAction; paths: string; preview: boolean }
export const defaultTransqInteractionValues: TransqInteractionValues = { action: "plan", paths: "", preview: true }
export function createTransqInteractionSchema(defaults: Partial<TransqInteractionValues> = {}, language: TerminalLanguage = "zh"): TerminalInteractionSchema<TransqInput, TransqResult> {
 const zh=language==="zh", initialValues: TransqInteractionValues={...defaultTransqInteractionValues}; for(const [key,value] of Object.entries(defaults)) if(value!==undefined) initialValues[key]=value
 const fields: InteractionField[]=[{id:"action",label:zh?"队列操作":"Queue action",kind:"select",role:"action",options:[{value:"status",label:zh?"◌ 状态":"Status"},{value:"plan",label:zh?"⌕ 预演队列":"Plan queue"},{value:"run",label:zh?"↳ 整理队列":"Organize queue"}]},{id:"paths",label:zh?"翻译工作区":"Translation roots",kind:"path-list",lines:5,placeholder:zh?"每行一个项目根目录":"One project root per line"},{id:"preview",label:zh?"仅预演":"Preview only",kind:"boolean",visibleWhen:v=>v.action!=="status"}]
 return {id:"transq",title:"TransQ",description:zh?"manga-translator 结果队列看板与安全整理":"Manga-translator result queue workbench",initialValues,fields,view:{sections:[{id:"queue",title:zh?"翻译队列":"Translation queue",fieldIds:fields.map(f=>f.id)}],dashboard:{title:"TransQ",display:v=>({primary:String(v.action??"plan"),secondary:v.preview!==false?"Preview":"Live",metrics:[]})}},toInput:transqInputFromInteractionValues,validate(_v,input){return input.action==="status"||input.paths?.length?null:zh?"至少输入一个翻译工作区。":"Enter at least one translation workspace."},preview:input=>[`${zh?"工作区":"Roots"}: ${input.paths?.length??0}`,input.preview!==false?zh?"安全预演，不改动文件":"Safe preview; files unchanged":zh?"真实整理会移动并删除工作目录":"Live organization moves and removes work folders"],isDangerous:input=>input.action==="run"&&input.preview===false,dangerPrompt:()=>({title:zh?"确认整理翻译队列":"Confirm queue organization",body:zh?"将补齐缺失图片、移动 result，并删除已完成的工作目录。":"Missing images will be copied; results move and work folders are removed.",confirmLabel:zh?"确认整理":"Organize"}),result:r=>({success:r.success,message:r.message,lines:r.data?[`Pending: ${r.data.pendingCount}`,`Ready: ${r.data.readyCount}`,`Conflict: ${r.data.conflictCount}`]:[]})}
}
export function transqInputFromInteractionValues(v:Readonly<InteractionValues>):TransqInput { const action:TransqAction=v.action==="run"||v.action==="status"?v.action:"plan"; return {action,paths:String(v.paths??"").split(/[\r\n;]+/).map(x=>x.trim()).filter(Boolean),preview:action==="plan"||v.preview!==false} }
