/**
 * @migrated-from src/lib/components/ui/emoji-picker/emoji-picker-skin-tone-selector.svelte
 * @source-hash sha256:1d0aa10602afa4b856708e04115abb5040c2cad50b1b84269f4b793a8f9421f3
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { box } from 'svelte-toolbelt';
import { useEmojiPickerSkinToneSelector } from './emoji-picker.svelte.js';
import type { EmojiPickerSkinProps } from './types.js';
import { Button, type ButtonElementProps } from '$lib/components/ui/button';
import { cn } from '$lib/utils.js';

export function EmojiPickerSkinToneSelector(props: EmojiPickerSkinProps) {
  const {
		previewEmoji = '👋',
		variant = 'outline',
		size = 'icon',
		class: className,
		onclick,
		...rest
	} = props
  const skinState = useEmojiPickerSkinToneSelector({
      previewEmoji: box.with(() => previewEmoji)
    });
  return (
    <Fragment>

<Button {...rest} variant={variant} size={size} className={cn('size-8', className)} onClick={(e: Parameters<NonNullable<ButtonElementProps['onclick']>>[0]) => {
		onclick?.(e);
		skinState.cycleSkinTone();
	}}>
	{skinState.preview}
</Button></Fragment>
  )
}
