import type { InteractionField, InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import type { JellyPotAction, JellyPotInput, JellyPotResult } from "./core.js"

export type JellyPotInteractionValues = InteractionValues & { action:JellyPotAction; configPath:string; databasePath:string; mediaPath:string; potplayerPath:string; browserPath:string; recordRun:boolean; dryRun:boolean }

export function createJellyPotInteractionSchema(d:Partial<JellyPotInteractionValues>={}, language:TerminalLanguage="zh"):TerminalInteractionSchema<JellyPotInput,JellyPotResult>{
  const zh=language==="zh", initialValues:JellyPotInteractionValues={action:"status",configPath:"",databasePath:"",mediaPath:"",potplayerPath:"",browserPath:"",recordRun:false,dryRun:true,...d}
  const fields:InteractionField[]=[
    {id:"action",label:zh?"操作":"Action",kind:"select",role:"action",options:[{value:"status",label:zh?"◉ 依赖体检":"◉ Status"},{value:"launch_media",label:zh?"▶ 播放媒体":"▶ Play media"},{value:"open_jellyfin",label:zh?"◇ 打开 Jellyfin":"◇ Open Jellyfin"},{value:"apply_registry",label:zh?"⚠ 应用注册表":"⚠ Apply registry"}]},
    {id:"mediaPath",label:zh?"媒体路径":"Media path",kind:"text"},{id:"configPath",label:zh?"配置文件":"Config file",kind:"text"},{id:"potplayerPath",label:"PotPlayer",kind:"text"},{id:"browserPath",label:zh?"浏览器":"Browser",kind:"text"},{id:"databasePath",label:zh?"运行记录":"Run database",kind:"text"},{id:"recordRun",label:zh?"记录运行":"Record run",kind:"boolean"},{id:"dryRun",label:zh?"仅预演":"Dry run",kind:"boolean"},
  ]
  return {id:"jellypot",title:"JellyPot",description:zh?"Jellyfin 与 PotPlayer 媒体启动工作台":"Jellyfin and PotPlayer launch workbench",initialValues,fields,view:{sections:[{id:"launch",title:zh?"启动参数":"Launch",fieldIds:fields.map(f=>f.id)}],dashboard:{title:"JellyPot",display:v=>({primary:String(v.action),secondary:v.dryRun!==false?"DRY RUN":"LIVE",metrics:[]})}},toInput:v=>({action:v.action as JellyPotAction,configPath:String(v.configPath??""),databasePath:String(v.databasePath??""),mediaPath:String(v.mediaPath??""),potplayerPath:String(v.potplayerPath??""),browserPath:String(v.browserPath??""),recordRun:v.recordRun===true,dryRun:v.dryRun!==false}),validate(_v,i){return i.action==="launch_media"&&!i.mediaPath?.trim()?(zh?"请输入媒体路径。":"Enter a media path."):null},preview:i=>[`${zh?"操作":"Action"}: ${i.action}`,i.mediaPath||i.configPath||"JellyPot"],isDangerous:i=>i.action==="apply_registry"&&i.dryRun===false,dangerPrompt:()=>({title:zh?"确认写入注册表":"Confirm registry write",body:zh?"该操作会调用 regedit 修改 PotPlayer 注册表设置。":"This invokes regedit and changes PotPlayer settings.",confirmLabel:zh?"确认应用":"Apply"}),result:r=>({success:r.success,message:r.message,lines:r.data?[`Checks: ${r.data.checks.length}`,`Commands: ${r.data.commands.length}`,`Errors: ${r.data.errors.length}`]:[]})}
}
