/**
 * @migrated-from src/lib/components/panels/folderPanel/components/FolderToolbar/MoreSettingsTabs.svelte
 * @source-hash sha256:05a7a9a12f95aa609d55bca6d5abe9d2a3da2fae7315ed47e7b330ae09849482
 * @features folder-mega-menu
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import * as Tabs from '$lib/components/ui/tabs';
import type { VirtualMode } from './types';
import ActionTab from './tabs/ActionTab.js';
import DisplayTab from './tabs/DisplayTab.js';
import OtherTab from './tabs/OtherTab.js';
interface Props {
		/** 虚拟模式 */
		virtualMode?: VirtualMode;
		/** 是否显示工具栏提示 */
		showToolbarTooltip?: boolean;
		/** 多选模式 */
		multiSelectMode: boolean;
		/** 缩略图宽度百分比 */
		thumbnailWidthPercent: number;
		/** 横幅宽度百分比 */
		bannerWidthPercent: number;
		/** 文件数量 */
		itemCount: number;
		/** 回调函数 */
		onSetThumbnailWidthPercent: (value: number) => void;
		onSetBannerWidthPercent: (value: number) => void;
		onToggleShowToolbarTooltip: () => void;
		onRefresh?: () => void;
	}

export function MoreSettingsTabs(props: Props) {
  const {
		virtualMode = null,
		showToolbarTooltip = false,
		multiSelectMode,
		thumbnailWidthPercent,
		bannerWidthPercent,
		itemCount,
		onSetThumbnailWidthPercent,
		onSetBannerWidthPercent,
		onToggleShowToolbarTooltip,
		onRefresh
	} = props
  let settingsTab = $state<'action' | 'display' | 'other'>('action');
  return (
    <Fragment>

<div className="bg-muted/20 border-t">
	<Tabs.Root value={settingsTab} onValueChange={(v) => (settingsTab = v as typeof settingsTab)} className="w-full">
		<div className="flex items-center px-2">
			<Tabs.List className="h-8 bg-transparent">
				<Tabs.Trigger value="action" className="h-7 px-3 py-1 text-xs">快捷操作</Tabs.Trigger>
				<Tabs.Trigger value="display" className="h-7 px-3 py-1 text-xs">显示设置</Tabs.Trigger>
				<Tabs.Trigger value="other" className="h-7 px-3 py-1 text-xs">其他</Tabs.Trigger>
			</Tabs.List>
			<div className="flex-1"></div>
			<span className="text-muted-foreground text-[10px]">文件数: {itemCount}</span>
		</div>

		<Tabs.Content value="action" className="mt-0 px-2 py-2">
			<ActionTab multiSelectMode={multiSelectMode} onRefresh={onRefresh}></ActionTab>
		</Tabs.Content>

		<Tabs.Content value="display" className="mt-0 px-2 py-2">
			<DisplayTab thumbnailWidthPercent={thumbnailWidthPercent} bannerWidthPercent={bannerWidthPercent} onSetThumbnailWidthPercent={onSetThumbnailWidthPercent} onSetBannerWidthPercent={onSetBannerWidthPercent}></DisplayTab>
		</Tabs.Content>

		<Tabs.Content value="other" className="mt-0 px-2 py-2">
			<OtherTab virtualMode={virtualMode} showToolbarTooltip={showToolbarTooltip} onToggleShowToolbarTooltip={onToggleShowToolbarTooltip}></OtherTab>
		</Tabs.Content>
	</Tabs.Root>
</div></Fragment>
  )
}
