/**
 * @migrated-from src/lib/cards/folder/cards/BreadcrumbTabCard.svelte
 * @source-hash sha256:5e8abdac39cdc4830e9562799df42826f611a5ce60d19c98bb1897337ce5f35c
 * @features file-browser-navigation
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { X, Plus, Copy, Bookmark, Clock, Folder } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import * as Tabs from '$lib/components/ui/tabs';
import * as ContextMenu from '$lib/components/ui/context-menu';
import * as Tooltip from '$lib/components/ui/tooltip';
import BreadcrumbBar from '$lib/components/panels/folderPanel/components/BreadcrumbBar.js';
import FolderTabBar from '$lib/components/panels/folderPanel/components/FolderTabBar.js';
import { getFolderContext } from '../context/FolderContext.js';
interface Props {
		onNavigate: (path: string) => void;
	}

export function BreadcrumbTabCard(props: Props) {
  const { onNavigate } = props
  const ctx = getFolderContext();

  function handleLocalTabChange(value: string) {
      ctx.switchLocalTab(value);
    }

  function handleLocalCloseTab(tabId: string, e?: MouseEvent) {
      e?.stopPropagation();
      ctx.closeLocalTab(tabId);
    }

  function handleLocalMiddleClick(tabId: string, e: MouseEvent) {
      if (e.button === 1) {
        e.preventDefault();
        ctx.closeLocalTab(tabId);
      }
    }

  function handleLocalDuplicateTab(tabId: string) {
      const tab = ctx.localTabs.find((t) => t.id === tabId);
      if (tab) {
        ctx.createLocalTab(tab.currentPath);
      }
    }
  return (
    <Fragment>

{/*  面包屑导航  */}
<BreadcrumbBar onNavigate={onNavigate} onCreateTab={ctx.isVirtualInstance ? () => ctx.createLocalTab() : undefined} homePath={ctx.homePath} externalPath={ctx.isVirtualInstance ? ctx.initialPath : undefined}></BreadcrumbBar>

{/*  页签栏（非虚拟实例使用全局 FolderTabBar，始终显示以支持右键菜单）  */}
{!ctx.isVirtualInstance ? (<Fragment>
	<FolderTabBar homePath={ctx.homePath}></FolderTabBar>
</Fragment>) : null}

{/*  本地页签栏（虚拟实例使用本地标签管理）  */}
{ctx.isVirtualInstance && ctx.localTabs.length > 1 ? (<Fragment>
	<Tabs.Root value={ctx.localActiveTabId} onValueChange={handleLocalTabChange} className="w-full">
		<div className="flex items-start gap-1 px-1 py-1">
			<Tabs.List className="flex h-auto flex-wrap gap-1 bg-transparent p-0">
				{ctx.localTabs.map((tab) => (<Fragment key={tab.id}>
					<ContextMenu.Root>
						<ContextMenu.Trigger>
							<Tabs.Trigger value={tab.id} className="group h-7 max-w-[160px] min-w-[80px] gap-1 rounded-md px-2.5 text-xs data-[state=active]:shadow-sm" onAuxClick={(e) => handleLocalMiddleClick(tab.id, e)} title={tab.currentPath || tab.title}>
								{ctx.panelMode === 'bookmark' ? (<Fragment>
									<Bookmark className="h-3.5 w-3.5 shrink-0 text-amber-500"></Bookmark>
								</Fragment>) : (<Fragment>{ctx.panelMode === 'history' ? (<Fragment>
									<Clock className="h-3.5 w-3.5 shrink-0 text-blue-500"></Clock>
								</Fragment>) : (<Fragment>
									<Folder className="h-3.5 w-3.5 shrink-0"></Folder>
								</Fragment>)}</Fragment>)}
								<span className="flex-1 truncate text-left">{tab.title}</span>
								{ctx.localTabs.length > 1 ? (<Fragment>
									<span className="hover:bg-destructive/20 flex h-4 w-4 items-center justify-center rounded opacity-0 transition-opacity group-hover:opacity-60 group-hover:hover:opacity-100" onClick={(e) => handleLocalCloseTab(tab.id, e)} onKeyDown={(e) => e.key === 'Enter' && handleLocalCloseTab(tab.id)} role="button" tabIndex="0" title="关闭页签">
										<X className="h-3 w-3"></X>
									</span>
								</Fragment>) : null}
							</Tabs.Trigger>
						</ContextMenu.Trigger>
						<ContextMenu.Content>
							<ContextMenu.Item onClick={() => handleLocalDuplicateTab(tab.id)}>
								<Copy className="mr-2 h-4 w-4"></Copy>
								复制页签
							</ContextMenu.Item>
							{ctx.localTabs.length > 1 ? (<Fragment>
								<ContextMenu.Separator></ContextMenu.Separator>
								<ContextMenu.Item onClick={() => handleLocalCloseTab(tab.id)} className="text-destructive">
									<X className="mr-2 h-4 w-4"></X>
									关闭页签
								</ContextMenu.Item>
							</Fragment>) : null}
						</ContextMenu.Content>
					</ContextMenu.Root>
				</Fragment>))}
			</Tabs.List>

			{/*  新建页签按钮  */}
			<Tooltip.Root>
				<Tooltip.Trigger>
					<Button variant="ghost" size="icon" className="h-7 w-7 shrink-0" onClick={() => ctx.createLocalTab()}>
						<Plus className="h-4 w-4"></Plus>
					</Button>
				</Tooltip.Trigger>
				<Tooltip.Content>
					<p>新建页签</p>
				</Tooltip.Content>
			</Tooltip.Root>
		</div>
	</Tabs.Root>
</Fragment>) : null}</Fragment>
  )
}
