/**
 * @migrated-from src/lib/cards/folder/cards/FileListCard.svelte
 * @source-hash sha256:4c85dbb35851a39aeb62bf5638c73771b06ffd02a5f0d7c2e2f124fb7437d718
 * @features file-browser-navigation
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute ClassDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import type { FsItem } from '$lib/types';
import FolderStack from '$lib/components/panels/folderPanel/components/FolderStack.js';
import FolderTree from '$lib/components/panels/folderPanel/components/FolderTree.js';
import FileTreeView from '$lib/components/panels/file/components/FileTreeView.js';
import InlineTreeList from '$lib/components/panels/folderPanel/components/InlineTreeList.js';
import { getFolderContext } from '../context/FolderContext.js';
import {
		folderTabActions,
		tabSearchResults,
		tabCurrentPath,
		isVirtualPath,
		getVirtualPathType
	} from '$lib/components/panels/folderPanel/stores/folderTabStore';
import { fileBrowserStore } from '$lib/stores/fileBrowser.js';
import {
		loadVirtualPathData,
		subscribeVirtualPathData
	} from '$lib/components/panels/folderPanel/utils/virtualPathLoader';
import { virtualPanelSettingsStore } from '$lib/stores/virtualPanelSettings.js';
interface Props {
		onItemOpen: (item: FsItem) => Promise<void>;
		onItemDelete: (item: FsItem) => void;
		onItemContextMenu: (event: MouseEvent, item: FsItem) => void;
		onOpenFolderAsBook: (item: FsItem) => void;
		onOpenInNewTab: (item: FsItem) => void;
		onNavigate: (path: string) => void;
	}

export function FileListCard(props: Props) {
  const {
		onItemOpen,
		onItemDelete,
		onItemContextMenu,
		onOpenFolderAsBook,
		onOpenInNewTab,
		onNavigate
	} = props
  const ctx = getFolderContext();

  const { folderTreeConfig } = ctx;

  let globalFolderTreeConfigValue = $state<{ visible: boolean; layout: string; size: number }>({
      visible: false,
      layout: 'left',
      size: 200
    });

  let virtualItems = $state<FsItem[]>([]);

  let searchResultItems = $state<FsItem[]>([]);

  let currentPath = $state<string>('');

  let virtualItemTypeFilter = $derived(
      ctx.panelMode === 'history'
        ? virtualPanelSettingsStore.historyItemTypeFilter
        : ctx.panelMode === 'bookmark'
          ? virtualPanelSettingsStore.bookmarkItemTypeFilter
          : 'all'
    );

  $effect(() => {
      const unsub = folderTreeConfig.subscribe((v) => (globalFolderTreeConfigValue = v));
      return () => unsub();
    });

  $effect(() => {
      const unsub = tabSearchResults.subscribe((results) => {
        searchResultItems = results;
      });
      return unsub;
    });

  $effect(() => {
      const unsub = tabCurrentPath.subscribe((path) => {
        currentPath = path;
      });
      return unsub;
    });

  $effect(() => {
      if (!ctx.isVirtualInstance || !ctx.initialPath) return;
      virtualItemTypeFilter;
      // 初始加载
      virtualItems = loadVirtualPathData(ctx.initialPath);
      // 订阅变化
      const unsub = subscribeVirtualPathData(ctx.initialPath, (items) => {
        virtualItems = items;
      });
      return unsub;
    });

  let isSearchTab = $derived(getVirtualPathType(currentPath) === 'search');

  let shouldUseLocalTree = $derived(
      ctx.isVirtualInstance || (isSearchTab && searchResultItems.length > 0)
    );

  let localTreeItems = $derived(ctx.isVirtualInstance ? virtualItems : searchResultItems);

  let effectiveTreeConfig = $derived(ctx.effectiveFolderTreeConfig ?? globalFolderTreeConfigValue);

  const MAX_MOUNTED_FOLDER_TABS = 3;

  let mountedFolderTabIds = $state<string[]>([]);

  function areStringArraysEqual(left: string[], right: string[]): boolean {
      return left.length === right.length && left.every((value, index) => value === right[index]);
    }

  $effect(() => {
      const activeId = ctx.displayActiveTabId;
      const availableIds = new Set(ctx.displayTabs.map((tab) => tab.id));
      if (!activeId) {
        if (mountedFolderTabIds.length > 0) {
          mountedFolderTabIds = [];
        }
        return;
      }

      const nextMountedFolderTabIds = [
        activeId,
        ...mountedFolderTabIds.filter((id) => id !== activeId && availableIds.has(id))
      ].slice(0, Math.min(MAX_MOUNTED_FOLDER_TABS, ctx.displayTabs.length));

      if (!areStringArraysEqual(mountedFolderTabIds, nextMountedFolderTabIds)) {
        mountedFolderTabIds = nextMountedFolderTabIds;
      }
    });

  let renderedFolderTabs = $derived.by(() => {
      const tabs = ctx.displayTabs;
      if (tabs.length <= MAX_MOUNTED_FOLDER_TABS) return tabs;

      const activeId = ctx.displayActiveTabId;
      const mountedIds = new Set(mountedFolderTabIds);
      if (activeId) mountedIds.add(activeId);
      return tabs.filter((tab) => mountedIds.has(tab.id));
    });

  function startTreeResize(e: MouseEvent) {
      e.preventDefault();
      ctx.isResizingTree = true;
      const layout = effectiveTreeConfig.layout;
      // 水平布局（左/右）使用 X 坐标，垂直布局（上/下）使用 Y 坐标
      ctx.resizeStartPos = layout === 'left' || layout === 'right' ? e.clientX : e.clientY;
      ctx.resizeStartSize = effectiveTreeConfig.size;
      document.addEventListener('mousemove', onTreeResize);
      document.addEventListener('mouseup', stopTreeResize);
    }

  function onTreeResize(e: MouseEvent) {
      if (!ctx.isResizingTree) return;
      const layout = effectiveTreeConfig.layout;
      let delta: number;

      switch (layout) {
        case 'left':
          delta = e.clientX - ctx.resizeStartPos;
          break;
        case 'right':
          delta = ctx.resizeStartPos - e.clientX;
          break;
        case 'top':
          delta = e.clientY - ctx.resizeStartPos;
          break;
        case 'bottom':
          delta = ctx.resizeStartPos - e.clientY;
          break;
        default:
          delta = 0;
      }

      const newSize = Math.max(100, Math.min(500, ctx.resizeStartSize + delta));

      // 根据面板模式调用相应的设置方法
      if (ctx.panelMode === 'history') {
        virtualPanelSettingsStore.setHistoryFolderTreeSize(newSize);
      } else if (ctx.panelMode === 'bookmark') {
        virtualPanelSettingsStore.setBookmarkFolderTreeSize(newSize);
      } else {
        // folder 面板使用全局 store
        folderTabActions.setFolderTreeSize(newSize);
      }
    }

  function stopTreeResize() {
      ctx.isResizingTree = false;
      document.removeEventListener('mousemove', onTreeResize);
      document.removeEventListener('mouseup', stopTreeResize);
    }

  function getTreeContainerStyle(layout: string, size: number): string {
      switch (layout) {
        case 'left':
          return `top: 0; left: 0; bottom: 0; width: ${size}px;`;
        case 'right':
          return `top: 0; right: 0; bottom: 0; width: ${size}px;`;
        case 'top':
          return `top: 0; left: 0; right: 0; height: ${size}px;`;
        case 'bottom':
          return `bottom: 0; left: 0; right: 0; height: ${size}px;`;
        default:
          return '';
      }
    }

  function getResizeHandleStyle(layout: string, size: number): string {
      switch (layout) {
        case 'left':
          return `left: ${size}px;`;
        case 'right':
          return `right: ${size}px;`;
        case 'top':
          return `top: ${size}px;`;
        case 'bottom':
          return `bottom: ${size}px;`;
        default:
          return '';
      }
    }

  function getFileListStyle(visible: boolean, layout: string, size: number): string {
      if (!visible) return '';
      switch (layout) {
        case 'left':
          return `left: ${size}px;`;
        case 'right':
          return `right: ${size}px;`;
        case 'top':
          return `top: ${size}px;`;
        case 'bottom':
          return `bottom: ${size}px;`;
        default:
          return '';
      }
    }

  function isHorizontalLayout(layout: string): boolean {
      return layout === 'left' || layout === 'right';
    }
  return (
    <Fragment>

<div className="relative flex-1 overflow-hidden">
	{/*  文件夹树  */}
	{effectiveTreeConfig.visible ? (<Fragment>
		<div className="border-muted bg-muted/10 absolute z-10 overflow-auto" style={getTreeContainerStyle(effectiveTreeConfig.layout, effectiveTreeConfig.size)}>
			{shouldUseLocalTree ? (<Fragment>
				{/*  虚拟路径/搜索结果模式：显示基于当前文件列表的局部树  */}
				<FileTreeView items={localTreeItems} thumbnails={fileBrowserStore.getState().thumbnails} onItemClick={(e) => onItemOpen(e.detail.item)} onItemDoubleClick={(e) => onItemOpen(e.detail.item)} onItemContextMenu={(e) => onItemContextMenu(e.detail.event, e.detail.item)}></FileTreeView>
			</Fragment>) : (<Fragment>
				{/*  普通模式：显示完整的文件系统树  */}
				<FolderTree onNavigate={onNavigate} onContextMenu={onItemContextMenu}></FolderTree>
			</Fragment>)}
		</div>
		{/*  调整手柄  */}
		<button type="button" className={`hover:bg-primary/20 absolute z-20 transition-colors ${isHorizontalLayout(
				effectiveTreeConfig.layout
			)
				? 'top-0 bottom-0 w-2 cursor-ew-resize'
				: 'right-0 left-0 h-2 cursor-ns-resize'}`} style={getResizeHandleStyle(effectiveTreeConfig.layout, effectiveTreeConfig.size)} onMouseDown={startTreeResize} aria-label="调整树视图大小"></button>
	</Fragment>) : null}

	{/*  文件列表区域  */}
	<div className="file-list-container bg-muted/10 absolute inset-0 overflow-hidden" style={getFileListStyle(
			effectiveTreeConfig.visible,
			effectiveTreeConfig.layout,
			effectiveTreeConfig.size
		)}>
		{renderedFolderTabs.map((tab) => (<Fragment key={tab.id}>
			<div className="absolute inset-0">
				{ctx.effectiveInlineTreeMode ? (<Fragment>
					{tab.id === ctx.displayActiveTabId ? (<Fragment>
						<InlineTreeList onItemClick={onItemOpen} onItemDoubleClick={onItemOpen} onItemContextMenu={onItemContextMenu}></InlineTreeList>
					</Fragment>) : null}
				</Fragment>) : (<Fragment>
					<FolderStack tabId={tab.id} initialPath={tab.currentPath || tab.homePath} navigationCommand={ctx.navigationCommand} onItemOpen={onItemOpen} onItemDelete={onItemDelete} onItemContextMenu={onItemContextMenu} onOpenFolderAsBook={onOpenFolderAsBook} onOpenInNewTab={onOpenInNewTab} forceActive={ctx.isVirtualInstance} skipGlobalStore={ctx.isVirtualInstance} overrideMultiSelectMode={ctx.effectiveMultiSelectMode} overrideDeleteMode={ctx.effectiveDeleteMode} overrideViewStyle={ctx.isVirtualInstance
							? (ctx.effectiveViewStyle as 'list' | 'content' | 'banner' | 'thumbnail' | undefined)
							: undefined} overrideSortConfig={ctx.isVirtualInstance ? ctx.effectiveSortConfig : undefined}></FolderStack>
				</Fragment>)}
			</div>
		</Fragment>))}
	</div>
</div>

</Fragment>
  )
}
