import type { ViewMode } from "@/types/workspace"
import type { WSState } from "./types"

export type ComponentViewMode = Exclude<ViewMode, "dashboard">

export const VIEW_MODES: ViewMode[] = ["dashboard", "cards", "dockview", "flow", "lane", "bento"]
export const COMPONENT_VIEW_MODES: ComponentViewMode[] = ["cards", "dockview", "flow", "lane", "bento"]

export const INITIAL_STATE: WSState = {
  theme: "spatial",
  customThemes: [],
  activeCustomThemeName: null,
  fontPreset: "xiranite",
  viewMode: "cards",
  cardLayout: "grid",
  workspaces: [
    { id: "ws-alpha", label: "topbar:workspace.defaults.alpha" },
    { id: "ws-grid", label: "topbar:workspace.defaults.grid" },
    { id: "ws-kern", label: "topbar:workspace.defaults.kern" },
    { id: "ws-net", label: "topbar:workspace.defaults.net" },
    { id: "ws-arch", label: "topbar:workspace.defaults.arch" },
  ],
  activeWorkspaceId: "ws-alpha",
  components: [],
  lanes: [],
  focusedComponentId: null,
  fullscreenComponentId: null,
  selectedComponentIds: [],
  zCounter: 1,
  overlay: null,
  overlayMode: "docked",
  overlayWidth: 440,
  overlayFloatingMetrics: {
    widthRatio: 0.34,
    heightRatio: 0.58,
    xRatio: 0.66,
    yRatio: 0.1,
  },
  grainEnabled: true,
  vignetteDepth: 40,
  grainIntensity: 15,
  actionGlow: true,
  cardElevation: false,
  backendReady: false,
  bgMode: "dot-grid",
  bgImageUrl: "",
  bgOpacity: 30,
  bgBlur: 5,
  bgCoverTopBar: false,
  liquidGlassEnabled: false,
  liquidGlassOpacity: 24,
  liquidGlassBlur: 1,
  liquidGlassDisplacement: 110,
  chromeVisible: true,
  chromePosition: "right",
  chromeStyle: "default",
  chromeIslandScale: 90,
  chromeIslandMotion: 110,
  chromeIslandDelay: 45,
  chromeIslandIdleOffset: -3,
  cardClickAction: "none",
  cardDoubleClickAction: "focus",
  tabDisplayStyle: "underline",
  switchDisplayStyle: "outlined",
}
