/**
 * @migrated-from src/lib/components/panels/folderPanel/components/FolderToolbar/tabs/ActionTab.svelte
 * @source-hash sha256:7de44077433611ca76e35aac095891751fcb9df7eb07b025311ff8caf64ae61e
 * @features folder-mega-menu
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Flame, RefreshCw, Trash2 } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import { folderThumbnailLoader, type WarmupProgress } from '$lib/utils/thumbnail';
import {
		addExcludedPath,
		isPathExcluded,
		removeExcludedPath
	} from '$lib/stores/excludedPaths.js';
import { directoryTreeCache } from '../../../utils/directoryTreeCache';
import {
		unifiedThumbnailStore,
		generateThumbKey,
		type ThumbnailSource,
		type ThumbnailRequest
	} from '$lib/stores/unifiedThumbnailStore.js';
import { showSuccessToast, showErrorToast } from '$lib/utils/toast';
import {
		folderTabActions,
		tabSelectedItems,
		tabItems,
		tabCurrentPath
	} from '../../../stores/folderTabStore';
import * as Progress from '$lib/components/ui/progress';
interface Props {
		/** 多选模式 */
		multiSelectMode: boolean;
		/** 刷新回调 */
		onRefresh?: () => void;
	}

export function ActionTab(props: Props) {
  const { multiSelectMode, onRefresh } = props
  let isWarming = $state(false);

  let warmupProgress = $state<WarmupProgress | null>(null);

  let isReloadingThumbnails = $state(false);

  let reloadThumbnailsProgress = $state<{ current: number; total: number } | null>(null);

  const currentPathStore = tabCurrentPath;

  async function startWarmup() {
      const path = get(currentPathStore);
      if (!path || isWarming) return;

      isWarming = true;
      warmupProgress = null;

      try {
        await folderThumbnailLoader.warmupRecursive(
          path,
          (progress) => {
            warmupProgress = { ...progress };
          },
          3
        );
      } catch (error) {
        console.error('预热失败:', error);
      } finally {
        isWarming = false;
      }
    }

  function cancelWarmup() {
      folderThumbnailLoader.cancelWarmup();
    }

  function handleClearTreeCache() {
      directoryTreeCache.clear();
      onRefresh?.();
    }

  async function handleReloadAllThumbnails() {
      const path = get(currentPathStore);
      if (!path || isReloadingThumbnails) return;

      const tabItemsList = get(tabItems);
      if (tabItemsList.length === 0) {
        showErrorToast('重载缩略图', '当前目录为空');
        return;
      }

      isReloadingThumbnails = true;
      reloadThumbnailsProgress = { current: 0, total: tabItemsList.length };

      try {
        unifiedThumbnailStore.clear();
        const requests: ThumbnailRequest[] = tabItemsList.map((item) => {
          const source: ThumbnailSource = { kind: 'file', path: item.path, fileSize: 0, modified: 0 };
          return { key: generateThumbKey(source, 256), source, maxSize: 256 };
        });
        await unifiedThumbnailStore.requestThumbnails(requests, path, 'visible');
        reloadThumbnailsProgress = { current: tabItemsList.length, total: tabItemsList.length };
        showSuccessToast('重载缩略图', `已重载 ${tabItemsList.length} 个缩略图`);
      } catch (e) {
        console.error('批量重载缩略图失败:', e);
        showErrorToast('重载缩略图', '操作失败');
      } finally {
        isReloadingThumbnails = false;
        reloadThumbnailsProgress = null;
      }
    }

  async function handleReloadSelectedThumbnails() {
      const path = get(currentPathStore);
      if (!path || isReloadingThumbnails) return;

      const selectedItemsSet = get(tabSelectedItems);
      if (selectedItemsSet.size === 0) {
        showErrorToast('重载缩略图', '没有选中的文件');
        return;
      }

      isReloadingThumbnails = true;
      reloadThumbnailsProgress = { current: 0, total: selectedItemsSet.size };

      try {
        unifiedThumbnailStore.clear();
        const requests: ThumbnailRequest[] = [...selectedItemsSet].map((itemPath) => {
          const source: ThumbnailSource = { kind: 'file', path: itemPath, fileSize: 0, modified: 0 };
          return { key: generateThumbKey(source, 256), source, maxSize: 256 };
        });
        await unifiedThumbnailStore.requestThumbnails(requests, path, 'visible');
        reloadThumbnailsProgress = { current: selectedItemsSet.size, total: selectedItemsSet.size };
        showSuccessToast('重载缩略图', `已重载 ${selectedItemsSet.size} 个缩略图`);
      } catch (e) {
        console.error('批量重载选中缩略图失败:', e);
        showErrorToast('重载缩略图', '操作失败');
      } finally {
        isReloadingThumbnails = false;
        reloadThumbnailsProgress = null;
      }
    }
  return (
    <Fragment>

<div className="flex flex-wrap items-center gap-2">
	<Button variant="outline" size="sm" className={`h-7 text-xs ${isWarming ? 'border-orange-500 text-orange-500' : ''}`} onClick={isWarming ? cancelWarmup : startWarmup}>
		<Flame className="mr-1 h-3 w-3"></Flame>
		{isWarming ? '取消预热' : '预热目录'}
	</Button>
	<Button variant="outline" size="sm" className="h-7 text-xs" onClick={() => folderTabActions.toggleRecursiveMode()}>
		递归显示
	</Button>
	<Button variant="outline" size="sm" className="h-7 text-xs" onClick={handleClearTreeCache}>
		<RefreshCw className="mr-1 h-3 w-3"></RefreshCw>
		刷新树
	</Button>
	<Button variant="outline" size="sm" className="h-7 text-xs" onClick={() => folderTabActions.clearHistory()}>
		清除历史
	</Button>
	{$currentPathStore && !isPathExcluded($currentPathStore) ? (<Fragment>
		<Button variant="outline" size="sm" className="h-7 text-xs" onClick={() => $currentPathStore && addExcludedPath($currentPathStore)}>
			<Trash2 className="mr-1 h-3 w-3"></Trash2>
			排除目录
		</Button>
	</Fragment>) : (<Fragment>{$currentPathStore ? (<Fragment>
		<Button variant="destructive" size="sm" className="h-7 text-xs" onClick={() => $currentPathStore && removeExcludedPath($currentPathStore)}>
			取消排除
		</Button>
	</Fragment>) : null}</Fragment>)}
	<Button variant="outline" size="sm" className={`h-7 text-xs ${isReloadingThumbnails ? 'border-blue-500 text-blue-500' : ''}`} onClick={handleReloadAllThumbnails} disabled={isReloadingThumbnails}>
		<RefreshCw className={`mr-1 h-3 w-3 ${isReloadingThumbnails ? 'animate-spin' : ''}`}></RefreshCw>
		{isReloadingThumbnails && reloadThumbnailsProgress
			? `重载中 (${reloadThumbnailsProgress.current}/${reloadThumbnailsProgress.total})`
			: '重载所有缩略图'}
	</Button>
	{multiSelectMode ? (<Fragment>
		<Button variant="outline" size="sm" className={`h-7 text-xs ${isReloadingThumbnails ? 'border-blue-500 text-blue-500' : ''}`} onClick={handleReloadSelectedThumbnails} disabled={isReloadingThumbnails}>
			<RefreshCw className={`mr-1 h-3 w-3 ${isReloadingThumbnails ? 'animate-spin' : ''}`}></RefreshCw>
			重载选中缩略图
		</Button>
	</Fragment>) : null}
</div>

{/*  预热进度条  */}
{warmupProgress ? (<Fragment>
	<div className="mt-2 border-t pt-2">
		<div className="text-muted-foreground flex items-center justify-between text-[10px]">
			<span className="max-w-[200px] truncate">🔥 {warmupProgress.current}</span>
			<span>{warmupProgress.completed}/{warmupProgress.total}</span>
		</div>
		<Progress.Root value={warmupProgress.total ? (warmupProgress.completed / warmupProgress.total) * 100 : 0} className="mt-1 h-1.5"></Progress.Root>
	</div>
</Fragment>) : null}</Fragment>
  )
}
