/**
 * @migrated-from src/lib/components/panels/folderPanel/components/FolderToolbar/tabs/DisplayTab.svelte
 * @source-hash sha256:04d5473f3644d6c754368996f7bc0b1d2854cdffcfaff979cc4219226581d8dc
 * @features folder-mega-menu
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Eye, Image, Grid3x3, LayoutGrid } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import {
		hoverPreviewSettings,
		hoverPreviewEnabled,
		hoverPreviewDelayMs
	} from '$lib/stores/hoverPreviewSettings.js';
import { fileBrowserStore } from '$lib/stores/fileBrowser.js';
interface Props {
		/** 缩略图宽度百分比 */
		thumbnailWidthPercent: number;
		/** 横幅宽度百分比 */
		bannerWidthPercent: number;
		/** 回调函数 */
		onSetThumbnailWidthPercent: (value: number) => void;
		onSetBannerWidthPercent: (value: number) => void;
	}

export function DisplayTab(props: Props) {
  const {
		thumbnailWidthPercent,
		bannerWidthPercent,
		onSetThumbnailWidthPercent,
		onSetBannerWidthPercent
	} = props
  return (
    <Fragment>

<div className="flex flex-wrap items-center gap-4 text-xs">
	{/*  悬停预览  */}
	<div className="flex items-center gap-2">
		<Eye className="text-muted-foreground h-3.5 w-3.5"></Eye>
		<span className="text-muted-foreground">预览:</span>
		<Button variant={$hoverPreviewEnabled ? 'default' : 'outline'} size="sm" className="h-6 px-2 text-xs" onClick={() => hoverPreviewSettings.toggle()}>
			{$hoverPreviewEnabled ? '开' : '关'}
		</Button>
		{$hoverPreviewEnabled ? (<Fragment>
			<select className="bg-background h-6 rounded border px-1 text-xs" value={$hoverPreviewDelayMs} onChange={(e) =>
					hoverPreviewSettings.setDelayMs(parseInt((e.target as HTMLSelectElement).value))}>
				<option value="200">200ms</option>
				<option value="500">500ms</option>
				<option value="800">800ms</option>
				<option value="1200">1200ms</option>
			</select>
		</Fragment>) : null}
	</div>

	{/*  文件夹多图自适应预览  */}
	<div className="flex items-center gap-2">
		<LayoutGrid className="text-muted-foreground h-3.5 w-3.5"></LayoutGrid>
		<span className="text-muted-foreground">多图预览:</span>
		<Button variant={$fileBrowserStore.folderPreviewGrid ? 'default' : 'outline'} size="sm" className="h-6 px-2 text-xs" onClick={() => fileBrowserStore.setFolderPreviewGrid(!$fileBrowserStore.folderPreviewGrid)}>
			{$fileBrowserStore.folderPreviewGrid ? '开' : '关'}
		</Button>
		{$fileBrowserStore.folderPreviewGrid ? (<Fragment>
			<select className="bg-background h-6 rounded border px-1 text-xs" value={$fileBrowserStore.folderPreviewCount} onChange={(e) =>
					fileBrowserStore.setFolderPreviewCount(parseInt((e.target as HTMLSelectElement).value))}>
				<option value="4">4图 (2x2)</option>
				<option value="9">9图 (3x3)</option>
				<option value="16">16图 (4x4)</option>
			</select>
		</Fragment>) : null}
	</div>

	{/*  缩略图大小  */}
	<div className="flex items-center gap-2">
		<Grid3x3 className="text-muted-foreground h-3.5 w-3.5"></Grid3x3>
		<span className="text-muted-foreground">缩略图:</span>
		<input type="range" min="10" max="90" value={thumbnailWidthPercent} onInput={(e) => onSetThumbnailWidthPercent(parseInt((e.target as HTMLInputElement).value))} className="accent-primary h-4 w-20" />
		<span className="text-muted-foreground w-10">{Math.round(48 + (thumbnailWidthPercent - 10) * 3)}px</span>
	</div>

	{/*  横幅大小  */}
	<div className="flex items-center gap-2">
		<Image className="text-muted-foreground h-3.5 w-3.5"></Image>
		<span className="text-muted-foreground">横幅:</span>
		<input type="range" min="20" max="100" step="10" value={bannerWidthPercent} onInput={(e) => onSetBannerWidthPercent(parseInt((e.target as HTMLInputElement).value))} className="accent-primary h-4 w-20" />
		<span className="text-muted-foreground w-10">{Math.floor(100 / bannerWidthPercent)}列</span>
	</div>
</div></Fragment>
  )
}
