/**
 * @migrated-from src/lib/components/panels/folderPanel/components/FolderToolbar/tabs/OtherTab.svelte
 * @source-hash sha256:fc5db3e3e2e941966aec5fc77c03d0ed9b62bea1134d0791ca34cce92653cb41
 * @features folder-mega-menu
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Settings2, FolderSync, Star, MousePointerClick, ChevronUp } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import { historySettingsStore } from '$lib/stores/historySettings.js';
import { fileBrowserStore } from '$lib/stores/fileBrowser.js';
import { getDefaultRating, saveDefaultRating } from '$lib/stores/emm/storage';
import type { VirtualMode } from '../types';
interface Props {
		/** 虚拟模式 */
		virtualMode?: VirtualMode;
		/** 是否显示工具栏提示 */
		showToolbarTooltip?: boolean;
		/** 回调函数 */
		onToggleShowToolbarTooltip: () => void;
	}

export function OtherTab(props: Props) {
  const {
		virtualMode = null,
		showToolbarTooltip = false,
		onToggleShowToolbarTooltip
	} = props
  return (
    <Fragment>

<div className="flex flex-wrap items-center gap-4 text-xs">
	{/*  工具栏 Tooltip 开关（仅在历史/书签模式下显示）  */}
	{virtualMode ? (<Fragment>
		<div className="flex items-center gap-2">
			<Settings2 className="text-muted-foreground h-3.5 w-3.5"></Settings2>
			<span className="text-muted-foreground">工具栏提示:</span>
			<Button variant={showToolbarTooltip ? 'default' : 'outline'} size="sm" className="h-6 px-2 text-xs" onClick={onToggleShowToolbarTooltip}>
				{showToolbarTooltip ? '开' : '关'}
			</Button>
			<span className="text-muted-foreground/60 text-[10px]"> 鼠标悬停时显示按钮提示 </span>
		</div>
	</Fragment>) : null}

	{/*  同步文件夹开关（仅在历史/书签模式下显示）  */}
	{virtualMode ? (<Fragment>
		<div className="flex items-center gap-2">
			<FolderSync className="text-muted-foreground h-3.5 w-3.5"></FolderSync>
			<span className="text-muted-foreground">同步文件夹:</span>
			<Button variant={virtualMode === 'history'
					? historySettingsStore.syncFileTreeOnHistorySelect
						? 'default'
						: 'outline'
					: historySettingsStore.syncFileTreeOnBookmarkSelect
						? 'default'
						: 'outline'} size="sm" className="h-6 px-2 text-xs" onClick={() => {
					if (virtualMode === 'history') {
						historySettingsStore.setSyncFileTreeOnHistorySelect(
							!historySettingsStore.syncFileTreeOnHistorySelect
						);
					} else {
						historySettingsStore.setSyncFileTreeOnBookmarkSelect(
							!historySettingsStore.syncFileTreeOnBookmarkSelect
						);
					}
				}}>
				{virtualMode === 'history' ? (<Fragment>
					{historySettingsStore.syncFileTreeOnHistorySelect ? '开' : '关'}
				</Fragment>) : (<Fragment>
					{historySettingsStore.syncFileTreeOnBookmarkSelect ? '开' : '关'}
				</Fragment>)}
			</Button>
			<span className="text-muted-foreground/60 text-[10px]">
				点击项目时自动在文件夹页签打开所在目录
			</span>
		</div>
	</Fragment>) : null}

	{/*  默认评分  */}
	<div className="flex items-center gap-2">
		<Star className="text-muted-foreground h-3.5 w-3.5"></Star>
		<span className="text-muted-foreground">默认评分:</span>
		<input type="number" min="0" max="5" step="0.1" value={getDefaultRating()} onChange={(e) => {
				const value = parseFloat((e.target as HTMLInputElement).value);
				if (!isNaN(value) && value >= 0 && value <= 5) {
					saveDefaultRating(value);
				}
			}} className="bg-background h-6 w-14 rounded border px-2 text-center text-xs" />
		<div className="flex gap-1">
			{[3.5, 4.0, 4.5, 5.0].map((rating) => (<Fragment>
				<Button variant={getDefaultRating() === rating ? 'default' : 'outline'} size="sm" className="h-6 px-1.5 text-[10px]" onClick={() => saveDefaultRating(rating)}>
					{rating}
				</Button>
			</Fragment>))}
		</div>
	</div>

	{/*  双击空白处行为  */}
	<div className="flex items-center gap-2">
		<MousePointerClick className="text-muted-foreground h-3.5 w-3.5"></MousePointerClick>
		<span className="text-muted-foreground">双击空白:</span>
		<select className="bg-background h-6 rounded border px-1 text-xs" value={$fileBrowserStore.doubleClickEmptyAction} onChange={(e) =>
				fileBrowserStore.setDoubleClickEmptyAction(
					(e.target as HTMLSelectElement).value as 'none' | 'goUp' | 'goBack'
				)}>
			<option value="none">无操作</option>
			<option value="goUp">返回上级</option>
			<option value="goBack">后退</option>
		</select>
	</div>

	<div className="flex items-center gap-2">
		<MousePointerClick className="text-muted-foreground h-3.5 w-3.5"></MousePointerClick>
		<span className="text-muted-foreground">单击空白:</span>
		<select className="bg-background h-6 rounded border px-1 text-xs" value={$fileBrowserStore.singleClickEmptyAction} onChange={(e) =>
				fileBrowserStore.setSingleClickEmptyAction(
					(e.target as HTMLSelectElement).value as 'none' | 'goUp' | 'goBack'
				)}>
			<option value="none">无操作</option>
			<option value="goUp">返回上级</option>
			<option value="goBack">后退</option>
		</select>
	</div>

	<div className="flex items-center gap-2">
		<ChevronUp className="text-muted-foreground h-3.5 w-3.5"></ChevronUp>
		<span className="text-muted-foreground">返回按钮:</span>
		<Button variant={$fileBrowserStore.showEmptyAreaBackButton ? 'default' : 'outline'} size="sm" className="h-6 px-2 text-xs" onClick={() =>
				fileBrowserStore.setShowEmptyAreaBackButton(!$fileBrowserStore.showEmptyAreaBackButton)}>
			{$fileBrowserStore.showEmptyAreaBackButton ? '显示' : '隐藏'}
		</Button>
		<span className="text-muted-foreground/60 text-[10px]"> 列表底部显示返回按钮 </span>
	</div>
</div></Fragment>
  )
}
