/**
 * @migrated-from src/lib/cards/info/AmbientBackgroundCard.svelte
 * @source-hash sha256:e7ed31ea4c7feca500574dcfb3f1c82d3f6cd41fecb1845fb1da4bf014fe106c
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute ClassDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { settingsManager, type NeoViewSettings } from '$lib/settings/settingsManager';
import { RotateCcw } from 'lucide-react';

export function AmbientBackgroundCard() {
  const ambientStyleOptions = [
      { value: 'gentle', label: '柔和', desc: '缓慢轻微的移动' },
      { value: 'vibrant', label: '鲜艳', desc: '类似灵动岛效果' },
      { value: 'dynamic', label: '动感', desc: '快速大幅的移动' }
    ] as const;

  const modeOptions = [
      { value: 'solid', label: '固定颜色', icon: '🎨', desc: '使用设置的背景颜色' },
      { value: 'auto', label: '自动匹配', icon: '🖼️', desc: '从图片边缘提取主色调' },
      { value: 'ambient', label: '流光溢彩', icon: '✨', desc: '类似灵动岛的流动渐变' },
      { value: 'aurora', label: '极光', icon: '🌌', desc: '北极光波动效果' },
      { value: 'spotlight', label: '聚光灯', icon: '💡', desc: '舞台聚光灯效果' }
    ] as const;

  const spotlightColors = [
      { value: 'white', label: '白色', color: '#ffffff' },
      { value: '#3b82f6', label: '蓝色', color: '#3b82f6' },
      { value: '#8b5cf6', label: '紫色', color: '#8b5cf6' },
      { value: '#ec4899', label: '粉色', color: '#ec4899' },
      { value: '#22c55e', label: '绿色', color: '#22c55e' },
      { value: '#f97316', label: '橙色', color: '#f97316' }
    ] as const;

  let settings = $state<NeoViewSettings | null>(null);

  onMount(() => {
      settings = settingsManager.getSettings();
      const unsubscribe = settingsManager.addListener((s: NeoViewSettings) => {
        settings = s;
      });
      return unsubscribe;
    });

  let backgroundMode = $derived(settings?.view.backgroundMode ?? 'solid');

  let isEffectEnabled = $derived(['ambient', 'aurora', 'spotlight'].includes(backgroundMode));

  let ambientStyle = $derived(settings?.view.ambient?.style ?? 'vibrant');

  let ambientSpeed = $derived(settings?.view.ambient?.speed ?? 8);

  let ambientBlur = $derived(settings?.view.ambient?.blur ?? 80);

  let ambientOpacity = $derived(settings?.view.ambient?.opacity ?? 0.8);

  let auroraShowRadialGradient = $derived(settings?.view.aurora?.showRadialGradient ?? true);

  let spotlightColor = $derived(settings?.view.spotlight?.color ?? 'white');

  function toggleEffect() {
      if (!settings) return;
      const newMode = isEffectEnabled ? 'solid' : 'ambient';
      settingsManager.updateNestedSettings('view', {
        backgroundMode: newMode
      });
    }

  function updateMode(mode: 'solid' | 'auto' | 'ambient' | 'aurora' | 'spotlight') {
      settingsManager.updateNestedSettings('view', {
        backgroundMode: mode
      });
    }

  function updateAmbient(
      updates: Partial<{
        style: 'gentle' | 'vibrant' | 'dynamic';
        speed: number;
        blur: number;
        opacity: number;
      }>
    ) {
      if (!settings) return;
      settingsManager.updateNestedSettings('view', {
        ambient: {
          style: settings.view.ambient?.style ?? 'vibrant',
          speed: settings.view.ambient?.speed ?? 8,
          blur: settings.view.ambient?.blur ?? 80,
          opacity: settings.view.ambient?.opacity ?? 0.8,
          ...updates
        }
      });
    }

  function updateAurora(showRadialGradient: boolean) {
      settingsManager.updateNestedSettings('view', {
        aurora: { showRadialGradient }
      });
    }

  function updateSpotlight(color: string) {
      settingsManager.updateNestedSettings('view', {
        spotlight: { color }
      });
    }

  function resetSettings() {
      settingsManager.updateNestedSettings('view', {
        backgroundMode: 'solid',
        ambient: {
          speed: 8,
          blur: 80,
          opacity: 0.8,
          style: 'vibrant'
        },
        aurora: {
          showRadialGradient: true
        },
        spotlight: {
          color: 'white'
        }
      });
    }
  return (
    <Fragment>

{settings ? (<Fragment>
	<div className="space-y-3 text-sm">
		{/*  标题栏  */}
		<div className="flex items-center justify-between">
			<label className="flex cursor-pointer items-center gap-2">
				<input type="checkbox" checked={isEffectEnabled} onChange={toggleEffect} className="border-border h-4 w-4 rounded" />
				<span>启用动态背景</span>
			</label>
			<button type="button" onClick={resetSettings} className="hover:bg-accent rounded p-1" title="重置设置">
				<RotateCcw className="h-4 w-4"></RotateCcw>
			</button>
		</div>

		{/*  背景模式选择  */}
		<div className="space-y-1">
			<span className="text-muted-foreground text-xs">背景模式</span>
			<div className="grid grid-cols-2 gap-1">
				{modeOptions.map((option) => (<Fragment>
					<button type="button" className={`flex items-center gap-1.5 rounded border px-2 py-1.5 text-left text-xs transition-colors ${backgroundMode ===
						option.value
							? 'bg-primary text-primary-foreground border-primary'
							: 'bg-background border-border hover:bg-accent'}`} onClick={() => updateMode(option.value)} title={option.desc}>
						<span>{option.icon}</span>
						<span>{option.label}</span>
					</button>
				</Fragment>))}
			</div>
			<p className="text-muted-foreground text-[10px]">
				{modeOptions.find((o) => o.value === backgroundMode)?.desc}
			</p>
		</div>

		{/*  流光溢彩设置  */}
		{backgroundMode === 'ambient' ? (<Fragment>
			<div className="bg-muted/20 space-y-2 rounded-lg border p-2">
				<span className="text-xs font-medium">✨ 流光溢彩设置</span>

				{/*  动画样式  */}
				<div className="space-y-1">
					<span className="text-muted-foreground text-xs">动画样式</span>
					<div className="grid grid-cols-3 gap-1">
						{ambientStyleOptions.map((option) => (<Fragment>
							<button type="button" className={`rounded border px-2 py-1 text-xs transition-colors ${ambientStyle ===
								option.value
									? 'bg-primary text-primary-foreground border-primary'
									: 'bg-background border-border hover:bg-accent'}`} onClick={() => updateAmbient({ style: option.value })} title={option.desc}>
								{option.label}
							</button>
						</Fragment>))}
					</div>
				</div>

				{/*  动画速度  */}
				<div className="space-y-1">
					<div className="flex justify-between text-xs">
						<span className="text-muted-foreground">动画速度</span>
						<span>{ambientSpeed}s</span>
					</div>
					<input type="range" min="2" max="20" step="1" value={ambientSpeed} onInput={(e) => updateAmbient({ speed: Number(e.currentTarget.value) })} className="accent-primary h-1 w-full" />
				</div>

				{/*  模糊程度  */}
				<div className="space-y-1">
					<div className="flex justify-between text-xs">
						<span className="text-muted-foreground">模糊程度</span>
						<span>{ambientBlur}px</span>
					</div>
					<input type="range" min="20" max="150" step="10" value={ambientBlur} onInput={(e) => updateAmbient({ blur: Number(e.currentTarget.value) })} className="accent-primary h-1 w-full" />
				</div>

				{/*  效果强度  */}
				<div className="space-y-1">
					<div className="flex justify-between text-xs">
						<span className="text-muted-foreground">效果强度</span>
						<span>{Math.round(ambientOpacity * 100)}%</span>
					</div>
					<input type="range" min="0.3" max="1" step="0.05" value={ambientOpacity} onInput={(e) => updateAmbient({ opacity: Number(e.currentTarget.value) })} className="accent-primary h-1 w-full" />
				</div>

				{/*  预览  */}
				<div className="relative mt-2 h-16 overflow-hidden rounded bg-black">
					<div className="ambient-preview absolute inset-0" style={`--preview-speed: ${ambientSpeed}s; --preview-blur: ${Math.min(
							ambientBlur / 4,
							20
						)}px; --preview-opacity: ${ambientOpacity};`}>
						<div className="preview-blob blob-1"></div>
						<div className="preview-blob blob-2"></div>
						<div className="preview-blob blob-3"></div>
					</div>
				</div>
			</div>
		</Fragment>) : null}

		{/*  极光设置  */}
		{backgroundMode === 'aurora' ? (<Fragment>
			<div className="bg-muted/20 space-y-2 rounded-lg border p-2">
				<span className="text-xs font-medium">🌌 极光设置</span>

				<label className="flex cursor-pointer items-center justify-between gap-2">
					<span className="text-xs">显示径向渐变遮罩</span>
					<input type="checkbox" checked={auroraShowRadialGradient} onChange={(e) => updateAurora(e.currentTarget.checked)} className="border-border h-4 w-4 rounded" />
				</label>
				<p className="text-muted-foreground text-[10px]">开启后极光会从角落渐隐，关闭则全屏显示</p>

				{/*  预览  */}
				<div className="relative mt-2 h-16 overflow-hidden rounded bg-zinc-900">
					<div className="aurora-preview absolute inset-0"></div>
				</div>
			</div>
		</Fragment>) : null}

		{/*  聚光灯设置  */}
		{backgroundMode === 'spotlight' ? (<Fragment>
			<div className="bg-muted/20 space-y-2 rounded-lg border p-2">
				<span className="text-xs font-medium">💡 聚光灯设置</span>

				<div className="space-y-1">
					<span className="text-muted-foreground text-xs">光束颜色</span>
					<div className="flex flex-wrap gap-1">
						{spotlightColors.map((option) => (<Fragment>
							<button type="button" className={`h-6 w-6 rounded-full border-2 transition-transform hover:scale-110 ${spotlightColor ===
								option.value
									? 'border-primary ring-primary/30 ring-2'
									: 'border-border'}`} style={`background-color: ${option.color};`} onClick={() => updateSpotlight(option.value)} title={option.label}></button>
						</Fragment>))}
					</div>
				</div>

				{/*  预览  */}
				<div className="relative mt-2 h-16 overflow-hidden rounded bg-zinc-900">
					<svg className="spotlight-preview" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3787 2842" fill="none">
						<g filter="url(#spotlight-preview-filter)">
							<ellipse cx="1924.71" cy="273.501" rx="1924.71" ry="273.501" transform="matrix(-0.822377 -0.568943 -0.568943 0.822377 3631.88 2291.09)" fill={spotlightColor} fill-opacity="0.21"></ellipse>
						</g>
						<defs>
							<filter id="spotlight-preview-filter" x="0.860352" y="0.838989" width="3785.16" height="2840.26" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
								<feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
								<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"></feBlend>
								<feGaussianBlur stdDeviation="50" result="effect1_foregroundBlur"></feGaussianBlur>
							</filter>
						</defs>
					</svg>
				</div>
			</div>
		</Fragment>) : null}
	</div>
</Fragment>) : (<Fragment>
	<div className="text-muted-foreground py-2 text-center text-sm">加载中...</div>
</Fragment>)}

</Fragment>
  )
}
