/**
 * @migrated-from src/lib/cards/info/BookInfoCard.svelte
 * @source-hash sha256:29f7489a66667bc7b5dec64584511b2b9c038909b045b024bc072ebb46910755
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { infoPanelStore, type ViewerBookInfo } from '$lib/stores/infoPanel.js';

export function BookInfoCard() {
  let bookInfo = $state<ViewerBookInfo | null>(null);

  $effect(() => {
      const unsubscribe = infoPanelStore.subscribe((state) => {
        bookInfo = state.bookInfo;
      });
      return unsubscribe;
    });

  function formatBookType(type?: string): string {
      if (!type) return '未知';
      switch (type.toLowerCase()) {
        case 'folder':
          return '文件夹';
        case 'archive':
          return '压缩包';
        case 'pdf':
          return 'PDF';
        case 'media':
          return '媒体';
        default:
          return type;
      }
    }
  return (
    <Fragment>

{bookInfo ? (<Fragment>
	<div className="space-y-2 text-sm">
		<div className="flex justify-between">
			<span className="text-muted-foreground">名称:</span>
			<span className={bookInfo.emmMetadata?.translatedTitle &&
				bookInfo.emmMetadata.translatedTitle !== bookInfo.name
					? 'border-primary/20 bg-primary/10 text-primary max-w-[200px] rounded border px-1.5 py-0.5 text-right text-xs break-words'
					: 'max-w-[200px] font-medium break-words'} title={bookInfo.emmMetadata?.translatedTitle || bookInfo.name}>
				{bookInfo.emmMetadata?.translatedTitle || bookInfo.name}
			</span>
		</div>
		{bookInfo.emmMetadata?.translatedTitle && bookInfo.emmMetadata.translatedTitle !== bookInfo.name ? (<Fragment>
			<div className="flex justify-between">
				<span className="text-muted-foreground">原名:</span>
				<span className="max-w-[200px] font-mono text-xs break-words" title={bookInfo.name}>
					{bookInfo.name}
				</span>
			</div>
		</Fragment>) : null}
		<div className="flex justify-between">
			<span className="text-muted-foreground">路径:</span>
			<span className="max-w-[200px] font-mono text-xs break-words" title={bookInfo.path}>
				{bookInfo.path}
			</span>
		</div>
		<div className="flex justify-between">
			<span className="text-muted-foreground">类型:</span>
			<span>{formatBookType(bookInfo.type)}</span>
		</div>
		<div className="flex justify-between">
			<span className="text-muted-foreground">页码:</span>
			<span>{bookInfo.currentPage} / {bookInfo.totalPages}</span>
		</div>
		<div className="flex justify-between">
			<span className="text-muted-foreground">进度:</span>
			<span>
				{bookInfo.totalPages > 0 ? (<Fragment>
					{(
						(Math.min(bookInfo.currentPage, bookInfo.totalPages) / bookInfo.totalPages) *
						100
					).toFixed(1)}%
				</Fragment>) : (<Fragment>
					—
				</Fragment>)}
			</span>
		</div>
	</div>
</Fragment>) : (<Fragment>
	<div className="text-muted-foreground py-2 text-center text-sm">暂无书籍信息</div>
</Fragment>)}</Fragment>
  )
}
