/**
 * @migrated-from src/lib/cards/info/InfoOverlayCard.svelte
 * @source-hash sha256:47bbb9b8824b6effc99211d400b5ad1520315cb91e2a6559e6dc3aaae4e844f1
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import * as Switch from '$lib/components/ui/switch';
import { Slider } from '$lib/components/ui/slider';
import { settingsManager } from '$lib/settings/settingsManager';

export function InfoOverlayCard() {
  let infoOverlayEnabled = $state(false);

  let infoOverlayOpacity = $state(0.85);

  let infoOverlayShowBorder = $state(false);

  let infoOverlayWidth = $state<number | undefined>(undefined);

  let infoOverlayHeight = $state<number | undefined>(undefined);

  $effect(() => {
      const syncFromSettings = () => {
        const s = settingsManager.getSettings();
        const overlay = s.view?.infoOverlay;
        infoOverlayEnabled = overlay?.enabled ?? false;
        infoOverlayOpacity = overlay?.opacity ?? 0.85;
        infoOverlayShowBorder = overlay?.showBorder ?? false;
        infoOverlayWidth = overlay?.width;
        infoOverlayHeight = overlay?.height;
      };

      syncFromSettings();
      const listener = () => syncFromSettings();
      settingsManager.addListener(listener);
      return () => settingsManager.removeListener(listener);
    });

  function updateInfoOverlay(partial: {
      enabled?: boolean;
      opacity?: number;
      showBorder?: boolean;
      width?: number;
      height?: number;
    }) {
      const current = settingsManager.getSettings();
      const prev = current.view?.infoOverlay ?? { enabled: false, opacity: 0.85, showBorder: false };
      const next = { ...prev };

      if (partial.enabled !== undefined) next.enabled = partial.enabled;
      if (partial.opacity !== undefined) {
        const clamped = Math.min(1, Math.max(0, partial.opacity));
        next.opacity = clamped;
      }
      if (partial.showBorder !== undefined) next.showBorder = partial.showBorder;
      if (partial.width !== undefined) {
        if (partial.width <= 0) delete (next as any).width;
        else (next as any).width = Math.max(120, Math.min(1600, partial.width));
      }
      if (partial.height !== undefined) {
        if (partial.height <= 0) delete (next as any).height;
        else (next as any).height = Math.max(32, Math.min(600, partial.height));
      }

      const prevWidth = (prev as any).width;
      const nextWidth = (next as any).width;
      const prevHeight = (prev as any).height;
      const nextHeight = (next as any).height;
      const unchanged =
        prev.enabled === next.enabled &&
        prev.opacity === next.opacity &&
        prev.showBorder === next.showBorder &&
        prevWidth === nextWidth &&
        prevHeight === nextHeight;

      if (unchanged) {
        return;
      }

      infoOverlayEnabled = next.enabled;
      infoOverlayOpacity = next.opacity;
      infoOverlayShowBorder = next.showBorder;
      infoOverlayWidth = (next as any).width;
      infoOverlayHeight = (next as any).height;

      settingsManager.updateNestedSettings('view', { infoOverlay: next });
    }
  return (
    <Fragment>

<div className="text-muted-foreground space-y-2 text-xs">
	<div className="flex items-center justify-between gap-2">
		<span>启用悬浮窗</span>
		<Switch.Root checked={infoOverlayEnabled} onCheckedChange={(v) => updateInfoOverlay({ enabled: v })} className="scale-75"></Switch.Root>
	</div>
	<div className="flex items-center justify-between gap-2">
		<span>透明度</span>
		<div className="flex items-center gap-2">
			<input type="number" min="0" max="100" step="5" className="border-input bg-background selection:bg-primary dark:bg-input/30 selection:text-primary-foreground ring-offset-background placeholder:text-muted-foreground h-7 w-20 rounded-md border px-2 text-xs shadow-xs transition-[color,box-shadow] outline-none disabled:cursor-not-allowed disabled:opacity-50" value={Math.round(infoOverlayOpacity * 100).toString()} onInput={(e) => {
					const v = parseFloat((e.currentTarget as HTMLInputElement).value);
					if (!Number.isNaN(v)) updateInfoOverlay({ opacity: v / 100 });
				}} />
			<span className="text-[11px]">{Math.round(infoOverlayOpacity * 100)}%</span>
		</div>
	</div>
	<div className="space-y-1">
		<div className="flex items-center justify-between gap-2">
			<span>宽度</span>
			<span className="text-muted-foreground text-[11px]">
				{infoOverlayWidth != null ? `${infoOverlayWidth} px` : '自动'}
			</span>
		</div>
		<Slider type="single" min={120} max={1600} step={20} value={infoOverlayWidth ?? 480} onValueChange={(v: number) => updateInfoOverlay({ width: v })} className="w-full"></Slider>
	</div>
	<div className="space-y-1">
		<div className="flex items-center justify-between gap-2">
			<span>高度</span>
			<span className="text-muted-foreground text-[11px]">
				{infoOverlayHeight != null ? `${infoOverlayHeight} px` : '自动'}
			</span>
		</div>
		<Slider type="single" min={32} max={600} step={8} value={infoOverlayHeight ?? 56} onValueChange={(v: number) => updateInfoOverlay({ height: v })} className="w-full"></Slider>
	</div>
	<div className="flex items-center justify-between gap-2">
		<span>显示边框</span>
		<Switch.Root checked={infoOverlayShowBorder} onCheckedChange={(v) => updateInfoOverlay({ showBorder: v })} className="scale-75"></Switch.Root>
	</div>
	<p className="text-[10px]">调节悬浮信息窗的背景透明度（0% - 100%，0% 为仅文字无底色）。</p>
</div></Fragment>
  )
}
