/**
 * @migrated-from src/lib/cards/monitor/components/GpuMonitor.svelte
 * @source-hash sha256:20f0396b77e255f837baced895e392f14652969757c3ee2c9dbcb345fe9415e4
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Cpu } from 'lucide-react';

export function GpuMonitor() {
  return (
    <Fragment>

<div className="bg-muted/50 rounded p-3">
	<div className="mb-3 flex items-center gap-2">
		<Cpu className="text-primary h-4 w-4"></Cpu>
		<span className="text-sm font-semibold">GPU</span>
	</div>

	<div className="text-muted-foreground py-4 text-center text-xs">
		GPU 监控功能开发中...
		<br />
		需要后端支持
	</div>
</div></Fragment>
  )
}
