import type { InteractionField, InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import type { CrashuAction, CrashuConflictPolicy, CrashuInput, CrashuMoveDirection, CrashuResult } from "./core.js"
export type CrashuInteractionValues = InteractionValues & { action: CrashuAction; sourcePaths: string; targetPath: string; targetNames: string; destinationPath: string; similarityThreshold: number; moveDirection: CrashuMoveDirection; conflictPolicy: CrashuConflictPolicy; pairsFileName: string; dryRun: boolean }
export function createCrashuInteractionSchema(defaults: Partial<CrashuInteractionValues> = {}, language: TerminalLanguage = "zh"): TerminalInteractionSchema<CrashuInput, CrashuResult> {
  const zh = language === "zh", initialValues = { action: "scan", sourcePaths: "", targetPath: "", targetNames: "", destinationPath: "", similarityThreshold: 0.65, moveDirection: "to_target", conflictPolicy: "skip", pairsFileName: "folder_pairs.json", dryRun: true, ...clean(defaults) } as CrashuInteractionValues
  const fields: InteractionField[] = [
    { id: "action", label: zh ? "命令" : "Command", kind: "select", role: "action", options: [{ value: "scan", label: zh ? "⌕ 扫描" : "⌕ Scan" }, { value: "plan", label: zh ? "⌁ 规划" : "⌁ Plan" }, { value: "move", label: zh ? "⇄ 移动" : "⇄ Move" }] },
    { id: "sourcePaths", label: zh ? "来源目录" : "Source directories", kind: "path-list", lines: 3 }, { id: "targetPath", label: zh ? "目标目录" : "Target directory", kind: "text" }, { id: "targetNames", label: zh ? "目标名称（可选）" : "Target names", kind: "text" }, { id: "destinationPath", label: zh ? "移动目标根目录" : "Move destination", kind: "text" },
    { id: "similarityThreshold", label: zh ? "相似度阈值" : "Similarity threshold", kind: "number", min: 0, max: 1, step: 0.05 },
    { id: "moveDirection", label: zh ? "移动方向" : "Move direction", kind: "select", options: [{ value: "to_target", label: zh ? "来源 → 目标" : "Source → target" }, { value: "to_source", label: zh ? "目标 → 来源" : "Target → source" }] },
    { id: "conflictPolicy", label: zh ? "冲突策略" : "Conflict policy", kind: "select", options: [{ value: "skip", label: zh ? "跳过" : "Skip" }, { value: "rename", label: zh ? "改名" : "Rename" }, { value: "overwrite", label: zh ? "覆盖" : "Overwrite" }] },
    { id: "pairsFileName", label: zh ? "配对记录文件" : "Pairs file", kind: "text" }, { id: "dryRun", label: zh ? "仅预演" : "Dry run", kind: "boolean", visibleWhen: (values) => values.action === "move" },
  ]
  return { id: "crashu", title: "CrashU", description: zh ? "目录相似度碰撞扫描与移动规划" : "Folder collision resolver", initialValues, fields, view: { sections: [{ id: "collision", title: zh ? "碰撞解析" : "Collision resolver", fieldIds: fields.map((field) => field.id) }], dashboard: { title: "CrashU", display: (values) => ({ primary: first(values.sourcePaths), secondary: String(values.targetPath), metrics: [] }) } },
    toInput: (values) => ({ action: values.action as CrashuAction, sourcePaths: splitLines(values.sourcePaths), targetPath: String(values.targetPath ?? ""), targetNames: splitNames(values.targetNames), destinationPath: String(values.destinationPath ?? ""), similarityThreshold: Number(values.similarityThreshold ?? 0.65), autoMove: values.action === "move", moveDirection: values.moveDirection as CrashuMoveDirection, conflictPolicy: values.conflictPolicy as CrashuConflictPolicy, pairsFileName: String(values.pairsFileName ?? "folder_pairs.json"), dryRun: values.dryRun !== false }),
    validate: (_values, input) => !input.sourcePaths?.length ? (zh ? "请至少输入一个来源目录。" : "Enter a source directory.") : !input.targetPath?.trim() && !input.targetNames?.length ? (zh ? "请输入目标目录或目标名称。" : "Enter a target directory or names.") : null,
    preview: (input) => [`${input.sourcePaths?.length ?? 0} ${zh ? "个来源" : "source(s)"}`, `${Math.round((input.similarityThreshold ?? 0) * 100)}% · ${input.moveDirection}`], isDangerous: (input) => input.action === "move" && input.dryRun === false,
    dangerPrompt: () => ({ title: zh ? "确认执行目录移动" : "Confirm folder moves", body: zh ? "匹配目录将按冲突策略移动，覆盖无法撤销。" : "Matched folders will be moved using the conflict policy.", confirmLabel: zh ? "确认移动" : "Move" }), result: (result) => ({ success: result.success, message: result.message, lines: result.data ? [`Scanned: ${result.data.totalScanned}`, `Matches: ${result.data.similarFound}`, `Moved: ${result.data.movedCount}`, `Errors: ${result.data.errorCount}`] : [] }) }
}
const clean = (value: Record<string, unknown>) => Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)); const splitLines = (value: unknown) => String(value ?? "").split(/\r?\n/).map((item) => item.trim()).filter(Boolean); const splitNames = (value: unknown) => String(value ?? "").split(/[,;\r\n]+/).map((item) => item.trim()).filter(Boolean); const first = (value: unknown) => splitLines(value)[0] ?? "CrashU"
