import { parseSync } from "oxc-parser"
import type { Node, Program } from "@oxc-project/types"
import { basename } from "node:path"
import { parse as parseSvelte } from "svelte/compiler"

import type { ComponentInventoryEntry, ReactScaffoldEntry } from "./types.js"

interface SvelteScriptNode {
  start: number
  content: { start: number; end: number }
}

interface SvelteAstShape {
  instance?: SvelteScriptNode | null
  module?: SvelteScriptNode | null
  fragment?: { nodes?: unknown[] }
}

interface ScriptParts {
  external: string[]
  local: string[]
  propsPattern: string | null
  propsType: string | null
  legacyProps: string[]
  unsupported: string[]
}

interface RenderContext {
  source: string
  unsupported: Set<string>
  usesFragment: boolean
}

export function generateReactScaffold(
  source: string,
  component: ComponentInventoryEntry,
): { scaffold: ReactScaffoldEntry | null; unsupported: string[] } {
  const ast = parseSvelte(source, { filename: component.file, modern: true }) as unknown as SvelteAstShape
  const script = extractScripts(source, ast, component)
  const context: RenderContext = { source, unsupported: new Set(script.unsupported), usesFragment: false }
  const markup = renderNodes(ast.fragment?.nodes ?? [], context, 2)
  context.usesFragment = true
  const unsupported = [...context.unsupported].sort()
  if (unsupported.length) return { scaffold: null, unsupported }

  const componentName = componentNameFor(component.file)
  const propsType = script.propsType ?? (script.legacyProps.length ? `${componentName}Props` : null)
  const generatedProps = script.legacyProps.length
    ? `export interface ${componentName}Props {\n${script.legacyProps.map((name) => `  ${name}?: unknown`).join("\n")}\n}\n\n`
    : ""
  const parameter = propsType ? `props: ${propsType}` : ""
  const destructure = script.propsPattern ? `  const ${script.propsPattern} = props\n` : ""
  const local = script.local.length ? `${script.local.map((statement) => indent(statement, 2)).join("\n\n")}\n` : ""
  const reactImport = context.usesFragment ? `import { Fragment } from "react"\n` : ""
  const featureIds = component.featureIds.join(",")
  const content = `/**\n` +
    ` * @migrated-from ${component.file}\n` +
    ` * @source-hash ${component.hash}\n` +
    ` * @features ${featureIds}\n` +
    ` * @migration-status scaffold\n` +
    ` * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.\n` +
    ` */\n` +
    `${reactImport}${script.external.join("\n")}\n\n` +
    `${generatedProps}` +
    `export function ${componentName}(${parameter}) {\n` +
    `${destructure}${local}` +
    `  return (\n    <Fragment>${markup}</Fragment>\n  )\n` +
    `}\n`
  return {
    scaffold: {
      sourceFile: component.file,
      outputFile: scaffoldPath(component.file),
      sourceHash: component.hash,
      featureIds: component.featureIds,
      content,
    },
    unsupported: [],
  }
}

function extractScripts(source: string, ast: SvelteAstShape, component: ComponentInventoryEntry): ScriptParts {
  const result: ScriptParts = { external: [], local: [], propsPattern: null, propsType: null, legacyProps: [], unsupported: [] }
  for (const [kind, node] of [["module", ast.module], ["instance", ast.instance]] as const) {
    if (!node) continue
    const content = source.slice(node.content.start, node.content.end)
    let program: Program
    try {
      program = parseSync(component.file, content, { lang: "ts", sourceType: "module", astType: "ts", preserveParens: true }).program
    } catch {
      result.unsupported.push(`${kind} script parse failure`)
      continue
    }
    for (const statement of program.body as unknown as Node[]) {
      if (statement.type === "ImportDeclaration") {
        const rewritten = rewriteImport(content, statement)
        if (rewritten === null) result.unsupported.push("Svelte runtime import")
        else result.external.push(rewritten)
        continue
      }
      if (isTypeDeclaration(statement)) {
        result.external.push(nodeText(content, statement))
        continue
      }
      if (kind === "module") {
        result.external.push(nodeText(content, statement))
        continue
      }
      if (statement.type === "VariableDeclaration") {
        const props = extractPropsDeclaration(content, statement)
        if (props) {
          result.propsPattern = props.pattern
          result.propsType = props.type
          continue
        }
      }
      if (statement.type === "ExportNamedDeclaration") {
        const legacy = extractLegacyPropDeclaration(content, statement)
        if (legacy) {
          result.legacyProps.push(...legacy.names)
          if (legacy.localStatement) result.local.push(legacy.localStatement)
          continue
        }
        result.unsupported.push("instance export")
        continue
      }
      result.local.push(nodeText(content, statement))
    }
  }
  if (component.props.length && !result.propsPattern && !result.legacyProps.length) result.unsupported.push("unresolved props declaration")
  result.external = [...new Set(result.external)]
  return result
}

function extractPropsDeclaration(content: string, statement: Node): { pattern: string; type: string } | null {
  const declarations = (statement as unknown as { declarations?: Node[] }).declarations ?? []
  if (declarations.length !== 1) return null
  const declaration = declarations[0]!
  const initializer = (declaration as unknown as { init?: Node | null }).init
  if (initializer?.type !== "CallExpression" || calleeName((initializer as unknown as { callee?: Node }).callee) !== "$props") return null
  const id = (declaration as unknown as { id?: Node }).id
  if (!id) return null
  const annotation = (id as unknown as { typeAnnotation?: Node | null }).typeAnnotation
  const patternEnd = annotation ? nodeStart(annotation) : nodeEnd(id)
  const pattern = content.slice(nodeStart(id), patternEnd).trim()
  const typeNode = (annotation as unknown as { typeAnnotation?: Node } | null)?.typeAnnotation
  return { pattern, type: typeNode ? nodeText(content, typeNode) : "Record<string, unknown>" }
}

function extractLegacyPropDeclaration(content: string, statement: Node): { names: string[]; localStatement: string | null } | null {
  const declaration = (statement as unknown as { declaration?: Node | null }).declaration
  if (declaration?.type !== "VariableDeclaration" || (declaration as unknown as { kind?: string }).kind !== "let") return null
  const names: string[] = []
  const local: string[] = []
  for (const variable of (declaration as unknown as { declarations?: Node[] }).declarations ?? []) {
    const id = (variable as unknown as { id?: Node }).id
    const name = id?.type === "Identifier" ? identifierName(id) : undefined
    if (!name) return null
    names.push(name)
    const initializer = (variable as unknown as { init?: Node | null }).init
    if (initializer) local.push(`const ${name} = props.${name} ?? ${nodeText(content, initializer)}`)
  }
  return { names, localStatement: local.length ? local.join("\n") : null }
}

function rewriteImport(content: string, statement: Node): string | null {
  const sourceNode = (statement as unknown as { source?: Node }).source
  const sourceValue = literalString(sourceNode)
  if (!sourceNode || !sourceValue) return nodeText(content, statement)
  if (sourceValue === "svelte" || sourceValue.startsWith("svelte/")) return null
  let replacement = sourceValue === "@lucide/svelte" ? "lucide-react" : sourceValue
  if (replacement.endsWith(".svelte")) replacement = `${replacement.slice(0, -".svelte".length)}.js`
  const statementStart = nodeStart(statement)
  const relativeStart = nodeStart(sourceNode) - statementStart
  const relativeEnd = nodeEnd(sourceNode) - statementStart
  const text = nodeText(content, statement)
  const quote = text[relativeStart] === "'" ? "'" : "\""
  return `${text.slice(0, relativeStart)}${quote}${replacement}${quote}${text.slice(relativeEnd)}`
}

function renderNodes(nodes: unknown[], context: RenderContext, depth: number): string {
  return nodes.map((node) => renderNode(node, context, depth)).filter(Boolean).join("")
}

function renderNode(value: unknown, context: RenderContext, depth: number): string {
  if (!value || typeof value !== "object") return ""
  const node = value as Record<string, unknown>
  const type = String(node.type ?? "")
  if (type === "Text") return escapeJsxText(String(node.raw ?? node.data ?? ""))
  if (type === "Comment") return `{/* ${String(node.data ?? "").replaceAll("*/", "* /")} */}`
  if (type === "ExpressionTag") return `{${expressionText(node.expression, context)}}`
  if (type === "RegularElement" || type === "Component" || type === "TitleElement") return renderElement(node, context, depth)
  if (type === "IfBlock") return renderIfBlock(node, context, depth)
  if (type === "EachBlock") return renderEachBlock(node, context, depth)
  if (type === "Fragment") return renderNodes((node.nodes as unknown[]) ?? [], context, depth)
  context.unsupported.add(`template node ${type || "unknown"}`)
  return `{/* TODO unsupported ${type || "node"} */}`
}

function renderElement(node: Record<string, unknown>, context: RenderContext, depth: number): string {
  const name = String(node.name ?? (node.type === "TitleElement" ? "title" : ""))
  if (!/^(?:[A-Za-z][\w.-]*|[A-Z_$][\w$]*(?:\.[A-Z_$][\w$]*)*)$/.test(name)) {
    context.unsupported.add(`element name ${name}`)
  }
  const attributes = ((node.attributes as unknown[]) ?? []).map((attribute) => renderAttribute(attribute, context)).filter(Boolean)
  const opening = `<${name}${attributes.length ? ` ${attributes.join(" ")}` : ""}`
  const fragment = node.fragment as Record<string, unknown> | undefined
  const children = (fragment?.nodes as unknown[]) ?? []
  if (!children.length && isVoidElement(name)) return `${opening} />`
  return `${opening}>${renderNodes(children, context, depth + 1)}</${name}>`
}

function renderAttribute(value: unknown, context: RenderContext): string {
  if (!value || typeof value !== "object") return ""
  const node = value as Record<string, unknown>
  const type = String(node.type ?? "")
  if (type === "SpreadAttribute") return `{...${expressionText(node.expression, context)}}`
  if (type === "OnDirective") {
    const event = reactEventName(String(node.name ?? ""))
    if (!node.expression) {
      context.unsupported.add(`shorthand event ${event}`)
      return `${event}={() => {}}`
    }
    return `${event}={${expressionText(node.expression, context)}}`
  }
  if (type !== "Attribute") {
    context.unsupported.add(`attribute ${type || "unknown"}`)
    return ""
  }
  const rawName = String(node.name ?? "")
  const name = reactAttributeName(rawName)
  if (node.value === true) return name
  const values = Array.isArray(node.value) ? node.value : node.value ? [node.value] : []
  if (values.length === 1 && isRecordType(values[0], "Text")) return `${name}=${JSON.stringify(String(values[0].data ?? values[0].raw ?? ""))}`
  if (values.length === 1 && isRecordType(values[0], "ExpressionTag")) return `${name}={${expressionText(values[0].expression, context)}}`
  const template = values.map((part) => {
    if (isRecordType(part, "Text")) return String(part.data ?? part.raw ?? "").replaceAll("`", "\\`").replaceAll("${", "\\${")
    if (isRecordType(part, "ExpressionTag")) return `\${${expressionText(part.expression, context)}}`
    context.unsupported.add(`attribute value ${String((part as Record<string, unknown>)?.type ?? "unknown")}`)
    return ""
  }).join("")
  return `${name}={\`${template}\`}`
}

function renderIfBlock(node: Record<string, unknown>, context: RenderContext, depth: number): string {
  const test = expressionText(node.test, context)
  const consequent = renderFragmentLike(node.consequent, context, depth + 1)
  const alternate = node.alternate ? renderFragmentLike(node.alternate, context, depth + 1) : "null"
  context.usesFragment = true
  return `{${test} ? (<Fragment>${consequent}</Fragment>) : ${node.alternate ? `(<Fragment>${alternate}</Fragment>)` : "null"}}`
}

function renderEachBlock(node: Record<string, unknown>, context: RenderContext, depth: number): string {
  const expression = expressionText(node.expression, context)
  const item = expressionText(node.context, context) || "item"
  const index = node.index ? `, ${String(node.index)}` : ""
  const body = renderFragmentLike(node.body, context, depth + 1)
  const key = node.key ? ` key={${expressionText(node.key, context)}}` : ""
  const fallback = node.fallback ? renderFragmentLike(node.fallback, context, depth + 1) : ""
  context.usesFragment = true
  const mapped = `${expression}.map((${item}${index}) => (<Fragment${key}>${body}</Fragment>))`
  return fallback ? `{${expression}.length ? ${mapped} : (<Fragment>${fallback}</Fragment>)}` : `{${mapped}}`
}

function renderFragmentLike(value: unknown, context: RenderContext, depth: number): string {
  if (!value || typeof value !== "object") return ""
  const record = value as Record<string, unknown>
  return renderNodes((record.nodes as unknown[]) ?? (record.children as unknown[]) ?? [], context, depth)
}

function expressionText(value: unknown, context: RenderContext): string {
  if (!value || typeof value !== "object") return ""
  const node = value as Node
  const start = nodeStart(node)
  const end = nodeEnd(node)
  if (end <= start) {
    context.unsupported.add("expression without source range")
    return "undefined"
  }
  return context.source.slice(start, end)
}

function componentNameFor(file: string): string {
  const name = basename(file, ".svelte").replace(/^\+/, "")
  const value = name.split(/[^A-Za-z0-9_$]+/).filter(Boolean).map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join("")
  return /^[A-Za-z_$]/.test(value) ? value : `Migrated${value}`
}

function scaffoldPath(file: string): string {
  return `${file.slice(0, -".svelte".length)}.tsx`
}

function isTypeDeclaration(node: Node): boolean {
  if (["TSInterfaceDeclaration", "TSTypeAliasDeclaration", "TSEnumDeclaration"].includes(node.type)) return true
  if (node.type !== "ExportNamedDeclaration") return false
  const declaration = (node as unknown as { declaration?: Node | null }).declaration
  return Boolean(declaration && ["TSInterfaceDeclaration", "TSTypeAliasDeclaration", "TSEnumDeclaration"].includes(declaration.type))
}

function calleeName(node: Node | undefined): string | undefined {
  return node?.type === "Identifier" ? identifierName(node) : undefined
}

function literalString(node: Node | undefined): string | undefined {
  if (node?.type !== "Literal") return undefined
  const value = (node as unknown as { value?: unknown }).value
  return typeof value === "string" ? value : undefined
}

function identifierName(node: Node | undefined): string | undefined {
  return node?.type === "Identifier" ? (node as unknown as { name?: string }).name : undefined
}

function nodeText(source: string, node: Node): string {
  return source.slice(nodeStart(node), nodeEnd(node)).trim()
}

function nodeStart(node: Node): number {
  return typeof (node as unknown as { start?: unknown }).start === "number" ? (node as unknown as { start: number }).start : 0
}

function nodeEnd(node: Node): number {
  return typeof (node as unknown as { end?: unknown }).end === "number" ? (node as unknown as { end: number }).end : nodeStart(node)
}

function reactEventName(name: string): string {
  const known: Record<string, string> = {
    auxclick: "AuxClick",
    dblclick: "DoubleClick",
    keydown: "KeyDown",
    keyup: "KeyUp",
    mousedown: "MouseDown",
    mouseenter: "MouseEnter",
    mouseleave: "MouseLeave",
    mousemove: "MouseMove",
    mouseup: "MouseUp",
    pointerdown: "PointerDown",
    pointermove: "PointerMove",
    pointerup: "PointerUp",
    touchend: "TouchEnd",
    touchmove: "TouchMove",
    touchstart: "TouchStart",
  }
  if (known[name]) return `on${known[name]}`
  return `on${name.slice(0, 1).toUpperCase()}${name.slice(1)}`
}

function reactAttributeName(name: string): string {
  if (name === "class") return "className"
  if (name === "for") return "htmlFor"
  if (name === "tabindex") return "tabIndex"
  if (/^on[a-z]/.test(name)) return reactEventName(name.slice(2))
  return name
}

function isVoidElement(name: string): boolean {
  return new Set(["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"]).has(name)
}

function escapeJsxText(value: string): string {
  return value.replaceAll("{", "&#123;").replaceAll("}", "&#125;")
}

function isRecordType(value: unknown, type: string): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && (value as Record<string, unknown>).type === type)
}

function indent(value: string, spaces: number): string {
  const prefix = " ".repeat(spaces)
  return value.split("\n").map((line) => `${prefix}${line.replaceAll("\t", "  ")}`).join("\n")
}
