#!/usr/bin/env node
import { defineCommand, nodeCliName, readStdinLines, runMain, writeJson, writeLine, runGuidedInteraction } from "@xiranite/cli-runtime"
import type { CliCommand, CliHost } from "@xiranite/cli-runtime"
import { resolveInteractionPreferences, type CliInteractionPreferencesSource, type TerminalInteractionDefinition } from "@xiranite/cli-runtime/interaction"
import type { TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import { runInteractionCli, runTerminalUi, type TerminalPreferenceController, type TerminalPreferenceValues } from "@xiranite/cli-runtime/terminal"
import { loadNodeConfigWithHints, updateNodeConfigFile } from "@xiranite/config"
import { runTransq, type TransqInput, type TransqResult } from "./core.js"
import { createNodeTransqRuntime } from "./platform.js"
import { createTransqInteractionSchema } from "./interaction.js"
import { help } from "./help.js"
const CLI_NAME=nodeCliName("transq")
interface Config extends CliInteractionPreferencesSource { preview?:boolean }
export const cli: CliCommand = { name: CLI_NAME, description: "Translation result queue organizer.", run: (args, host) => runProgram(args, host) }
export async function runProgram(args=process.argv.slice(2),host:CliHost=defaultHost()):Promise<void>{await runInteractionCli({args,host,cliName:CLI_NAME,loadContext:async()=>{const {config}=await loadNodeConfigWithHints<Config>("transq",{env:host.env,cwd:host.cwd,hintSink:{stderr:host.stderr},jsonMode:true});return {preferences:resolveInteractionPreferences(config),value:config??{}}},createDefinition:(d,l)=>({schema:createTransqInteractionSchema({preview:d.preview},l),run:(input,onEvent)=>runTransq(input,createNodeTransqRuntime(),onEvent)}),runPipe:(a,h)=>a.length?runMain(program(h),{rawArgs:a}):Promise.resolve(usage(h)),runGuide:runGuidedInteraction,runUi:runTerminalUi,loadScreen:async()=> (await import("./Tui.js")).TransqTui,createPreferences:(_d,v)=>prefs(host,v),reexecEntrypoint:process.argv[1],help})}
function program(host:CliHost){return defineCommand({meta:{name:CLI_NAME,description:"Translation result queue organizer."},subCommands:{status:cmd("status",host),plan:cmd("plan",host),run:cmd("run",host)}})}function cmd(action:"status"|"plan"|"run",host:CliHost){return defineCommand({meta:{name:action,description:`${action} translation queues.`},args:{paths:{type:"positional",required:false},preview:{type:"boolean"},live:{type:"boolean"},json:{type:"boolean"}},async run({args}){const paths=typeof args.paths==="string"?(args.paths==="-"?await readStdinLines():args.paths.split(/[;,\r\n]+/).filter(Boolean)):[];const result=await runTransq({action,paths,preview:action==="plan"||(!args.live&&(args.preview||true))},createNodeTransqRuntime());if(args.json)writeJson(host,result);else writeLine(host,result.message);if(!result.success)process.exitCode=1}})}function prefs(host:CliHost,current:TerminalPreferenceValues):TerminalPreferenceController{const options={env:host.env,cwd:host.cwd};return {nodeId:"transq",current,async save(v){await updateNodeConfigFile("transq", {cli:{theme:v.theme,default_mode:v.defaultMode,language:v.language}}, options)},async restore(){const {config}=await loadNodeConfigWithHints<Config>("transq",{...options,jsonMode:true});const p=resolveInteractionPreferences(config);return {theme:p.theme,defaultMode:p.mode,language:p.language??"zh"}}}}function usage(h:CliHost){writeLine(h,`${CLI_NAME} ui | gd | status | plan <path> | run <path> --live`)}function defaultHost():CliHost{return {cwd:process.cwd(),env:process.env,stdin:process.stdin,stdout:process.stdout,stderr:process.stderr}}if(process.argv[1]&&/\bcli\.[jt]s$/.test(process.argv[1].replace(/\\/g,"/")))await runProgram()
