/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import { ActionTabs, ClickTarget, ExecutionActions, ProgressBar, resolveTerminalTheme, TerminalPreferencesScreen, TerminalThemeProvider, terminalIcon, useAnimation, useTerminalChromeActions, useTerminalTheme, useTerminalUiSession, WorkbenchButton, WorkbenchField, WorkbenchPanel } from "@xiranite/cli-runtime/terminal/opentui"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { ClassfInput, ClassfResult } from "./core.js"

export function ClassfTui(props: TerminalUiScreenProps<ClassfInput, ClassfResult>) { const [previewTheme, setPreviewTheme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit"); return <TerminalThemeProvider theme={resolveTerminalTheme(previewTheme === "inherit" ? "nord" : previewTheme)}><ClassfWorkbench {...props} onThemePreview={setPreviewTheme} /></TerminalThemeProvider> }

function ClassfWorkbench({ definition, language, preferences, onExit, onThemePreview }: TerminalUiScreenProps<ClassfInput, ClassfResult> & { onThemePreview: (theme: string) => void }) {
  const theme = useTerminalTheme(), t = createTerminalTranslator(language), session = useTerminalUiSession(definition), [settings, setSettings] = useState(false), frame = useAnimation({ intervalMs: session.phase === "running" ? 110 : 620 })
  const fields = definition.schema.fields, action = fields.find((f) => f.id === "action")!, paths = fields.find((f) => f.id === "pathsText")!, target = fields.find((f) => f.id === "targetDir")!, transfer = fields.find((f) => f.id === "transferMode")!, classify = fields.find((f) => f.id === "classifyMode")!, existing = fields.find((f) => f.id === "existingPolicy")!, dryRun = fields.find((f) => f.id === "dryRun")!
  const sourceCount = String(session.values.pathsText ?? "").split(/\r?\n/).map((v) => v.trim()).filter(Boolean).length, rows = session.resultSummary?.table?.rows ?? []
  useTerminalChromeActions({ onReset: session.reset, onExit, resetLabel: `↺ ${t("reset")}`, exitLabel: `× ${language === "zh" ? "退出" : "Exit"}` })
  useKeyboard((key) => { if (key.name !== "escape") return; if (settings) setSettings(false); else if (session.confirming) session.dismissConfirmation(); else if (session.phase === "running" || session.phase === "paused") void session.cancel(); else onExit() })
  if (settings && preferences) return <TerminalPreferencesScreen controller={preferences} focusedId={session.focusedControlId} onFocus={session.focus} onPreviewTheme={onThemePreview} onBack={() => setSettings(false)} />
  if (session.confirming) return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="70%" height={9} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>{`${terminalIcon("danger")} ${language === "zh" ? "确认分类传输" : "Confirm transfer"}`}</b></text><text>{session.dangerPrompt?.body}</text><text fg={theme.colors.mutedForeground}>{session.preview.join(" · ")}</text><box flexDirection="row" gap={2}><WorkbenchButton id="confirm-execute" danger onClick={() => void session.confirmExecute()}>{`${terminalIcon("danger")} ${language === "zh" ? "确认执行" : "Run now"}`}</WorkbenchButton><WorkbenchButton id="confirm-dismiss" onClick={session.dismissConfirmation}>{`× ${language === "zh" ? "取消" : "Cancel"}`}</WorkbenchButton></box></box></box>
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden">
    <box height={4} flexShrink={0} borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("section")} CLASSF // TRANSFER CONTROL`}</b></text><text fg={theme.colors.mutedForeground}>{session.status || (language === "zh" ? "来源列表、分类计划与安全传输" : "Source list, classification plan and safe transfer")}</text></box><box flexDirection="column" alignItems="flex-end"><text fg={session.phase === "running" ? theme.colors.warning : theme.colors.primary}>{`${session.phase === "running" ? "TRANSFERRING" : "READY"} ${["◴", "◷", "◶", "◵"][frame % 4]}`}</text>{preferences ? <ClickTarget id="settings" onClick={() => setSettings(true)}>{`${terminalIcon("settings")} CONFIG`}</ClickTarget> : null}</box></box>
    <box height={3} marginTop={1} flexShrink={0} flexDirection="row" justifyContent="space-between"><ActionTabs id="field-action" options={[{ value: "plan", label: "⌕ 规划" }, { value: "classify", label: "▶ 分类" }]} value={String(session.values.action ?? "plan")} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)} /><text fg={theme.colors.mutedForeground}>{`${terminalIcon("path")} ${sourceCount}  ·  ${session.progress}%`}</text></box>
    <box flexDirection="row" flexGrow={1} minHeight={0} gap={1}><WorkbenchPanel title={`${terminalIcon("path")} ${language === "zh" ? "来源列表" : "Source list"}`} width="37%"><box flexDirection="column" flexGrow={1} minHeight={0}><WorkbenchField field={paths} value={session.values.pathsText} error={session.fieldErrors.pathsText} focused={session.focusedControlId === "pathsText"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("pathsText")} onChange={(value) => session.setField("pathsText", value)} /><scrollbox flexGrow={1}>{String(session.values.pathsText ?? "").split(/\r?\n/).map((v) => v.trim()).filter(Boolean).map((v, i) => <text key={`${v}-${i}`} fg={theme.colors.mutedForeground}>{`${i === 0 ? "▸" : "·"} ${v}`}</text>)}</scrollbox></box></WorkbenchPanel><WorkbenchPanel title={`${terminalIcon("section")} ${language === "zh" ? "分类计划" : "Classification plan"}`} flexGrow={1}><box flexDirection="column" flexGrow={1} minHeight={0}><box flexDirection="row" justifyContent="space-between"><text fg={theme.colors.mutedForeground}>{`${terminalIcon("logs")} PLAN / DESTINATION`}</text><text fg={session.dangerous ? theme.colors.error : theme.colors.success}>{session.dangerous ? "LIVE / ARMED" : "DRY-RUN / SAFE"}</text></box><scrollbox flexGrow={1} minHeight={4}>{rows.length ? rows.map((row, i) => <text key={`${row.sourceName}-${i}`} fg={row.status === "error" ? theme.colors.error : theme.colors.foreground}>{`${row.status === "moved" || row.status === "copied" ? terminalIcon("result") : "▸"} ${row.sourceName}  →  ${row.targetRelative}`}</text>) : session.preview.map((line, i) => <text key={`${line}-${i}`} fg={i ? theme.colors.mutedForeground : theme.colors.primary}>{`${i ? "·" : "$"} ${line}`}</text>)}</scrollbox><ProgressBar value={session.progress} label={session.status || "READY"} /></box></WorkbenchPanel></box>
    <box height={10} minHeight={10} flexShrink={0} marginTop={1} borderStyle="rounded" borderColor={session.dangerous ? theme.colors.error : theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" gap={2}><box width="70%" flexDirection="column"><box flexDirection="row" gap={1}><box width="34%"><WorkbenchField field={target} value={session.values.targetDir} error={session.fieldErrors.targetDir} focused={session.focusedControlId === "targetDir"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("targetDir")} onChange={(value) => session.setField("targetDir", value)} /></box><box width="22%"><WorkbenchField field={transfer} value={session.values.transferMode} error={session.fieldErrors.transferMode} focused={session.focusedControlId === "transferMode"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("transferMode")} onChange={(value) => session.setField("transferMode", value)} /></box><box width="22%"><WorkbenchField field={classify} value={session.values.classifyMode} error={session.fieldErrors.classifyMode} focused={session.focusedControlId === "classifyMode"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("classifyMode")} onChange={(value) => session.setField("classifyMode", value)} /></box><box width="22%"><WorkbenchField field={existing} value={session.values.existingPolicy} error={session.fieldErrors.existingPolicy} focused={session.focusedControlId === "existingPolicy"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("existingPolicy")} onChange={(value) => session.setField("existingPolicy", value)} /></box></box></box><box flexGrow={1} flexDirection="column"><box><WorkbenchField field={dryRun} value={session.values.dryRun} error={session.fieldErrors.dryRun} focused={session.focusedControlId === "dryRun"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("dryRun")} onChange={(value) => session.setField("dryRun", value)} /></box><box flexGrow={1} /><ExecutionActions session={session} executeLabel={`▶ ${language === "zh" ? "执行分类" : "Run classify"}`} confirmLabel={`${terminalIcon("danger")} ${language === "zh" ? "确认传输" : "Confirm"}`} /></box></box>
  </box>
}
