export type { ReaderBook, ViewSource } from "./domain/book/book.js"
export { def } from "./domain/definition.js"
export {
  DEFAULT_READER_LAYOUT,
  type FramePage,
  type FrameCropInsets,
  type FrameSnapshot,
  type PageMode,
  type ReaderGeneration,
  type ReaderLayout,
  type ReaderPagePart,
} from "./domain/frame/frame.js"
export {
  calculateReaderFrameSize,
  calculateReaderPageStretchScales,
  calculateReaderScale,
  DEFAULT_READER_PRESENTATION,
  effectiveReaderRotation,
  normalizeReaderManualScale,
  normalizeReaderRotation,
  rotatePresentationSize,
  rotateReaderPresentation,
  stepReaderManualScale,
  type PresentationSize,
  type ReaderFitMode,
  type ReaderAutoRotation,
  type ReaderOrientation,
  type ReaderWidePageStretch,
  type ReaderPresentation,
  type ReaderRotation,
} from "./domain/presentation/presentation.js"
export {
  activeReaderColorFilterPoints,
  applyReaderColorFilterPatch,
  DEFAULT_READER_COLOR_FILTER,
  isReaderColorFilterPresetId,
  normalizeReaderColorFilter,
  parseReaderColorFilterPatch,
  projectReaderColorFilterCss,
  projectReaderColorFilterTables,
  READER_COLOR_FILTER_PRESET_IDS,
  READER_COLOR_FILTER_PRESET_LABELS,
  READER_COLOR_FILTER_PRESETS,
  type ReaderColorFilterCssOptions,
  type ReaderColorFilterPatch,
  type ReaderColorFilterPresetId,
  type ReaderColorFilterSettings,
  type ReaderColorFilterTables,
  type ReaderColorPoint,
} from "./domain/color-filter/ReaderColorFilter.js"
export type { ReadingDirection, TailOverflowBehavior } from "./domain/navigation/navigation.js"
export {
  cloneReaderRadialMenuConfig,
  DEFAULT_READER_RADIAL_MENU_CONFIG,
  parseReaderRadialMenuConfig,
  parseReaderRadialMenuPatch,
  type NeoviewRadialMenuPatch,
  type ReaderRadialMenuConfig,
  type ReaderRadialMenuDefinition,
  type ReaderRadialMenuItem,
  type ReaderRadialMenuVariant,
} from "./application/config/ReaderRadialMenuConfig.js"
export {
  convertLegacyReaderInputBindings,
  type ReaderLegacyInputBindingConversion,
  type ReaderLegacyInputBindingReportEntry,
} from "./application/config/ReaderLegacyInputBindings.js"
export {
  cloneReaderInputBindings,
  DEFAULT_READER_INPUT_BINDINGS,
  matchingReaderInputBinding,
  LEGACY_READER_INPUT_ACTION_MAP,
  READER_INPUT_ACTION_CATEGORIES,
  READER_INPUT_ACTION_CATEGORY_LABELS,
  READER_INPUT_ACTION_LABELS,
  READER_INPUT_ACTION_METADATA,
  READER_INPUT_ACTIONS,
  readerInputActionFromLegacyId,
  READER_INPUT_CONTEXT_LABELS,
  READER_INPUT_CONTEXT_PRIORITY,
  READER_INPUT_CONTEXTS,
  READER_MOUSE_GESTURE_DIRECTIONS,
  READER_VIEW_AREAS,
  readerInputConflictKey,
  readerInputConflicts,
  readerInputDescriptorKey,
  readerViewAreaAtPoint,
  type ReaderInputAction,
  type ReaderInputActionDefinition,
  type ReaderInputActionCategory,
  type ReaderInputActionMetadata,
  type ReaderInputBinding,
  type ReaderInputBindingsConfig,
  type ReaderInputConflict,
  type ReaderInputContext,
  type ReaderInputDescriptor,
  type ReaderMouseGestureDirection,
  type ReaderViewArea,
} from "./domain/input/ReaderInputBindings.js"
export type {
  PageDimensions,
  PageId,
  PageMediaKind,
  ReaderPage,
  ReaderPageTimestamps,
  ReaderPageTimeSource,
} from "./domain/page/page.js"
export {
  ReaderSlideshow,
  type ReaderSlideshowConfig,
  type ReaderSlideshowOptions,
  type ReaderSlideshowPosition,
  type ReaderSlideshowSnapshot,
  type ReaderSlideshowState,
} from "./application/slideshow/ReaderSlideshow.js"
export {
  READER_CARD_MANIFEST,
  READER_PANEL_MANIFEST,
  readerCardCanMoveTo,
  readerPanelAcceptsCards,
  type ReaderCardId,
  type ReaderCardManifestEntry,
  type ReaderPanelId,
  type ReaderPanelManifestEntry,
  type ReaderPanelPosition,
} from "./application/config/ReaderLayoutManifest.js"
export {
  applyReaderSwitchToastPatch,
  DEFAULT_READER_SWITCH_TOAST,
  normalizeReaderSwitchToast,
  parseReaderSwitchToastPatch,
  renderReaderSwitchToastTemplate,
  READER_SWITCH_TOAST_OPACITY_MAX,
  READER_SWITCH_TOAST_OPACITY_MIN,
  READER_SWITCH_TOAST_POSITION_MAX,
  READER_SWITCH_TOAST_POSITION_MIN,
  type ReaderSwitchToastBookContext,
  type ReaderSwitchToastContext,
  type ReaderSwitchToastLegacyAliases,
  type ReaderSwitchToastPageContext,
  type ReaderSwitchToastPatch,
  type ReaderSwitchToastSettings,
} from "./application/switch-toast/ReaderSwitchToast.js"
export {
  formatReaderTimestamp,
  projectReaderTimeInformation,
  resolveReaderTimeInformation,
  type ReaderTimeInformationLanguage,
  type ReaderTimeInformationInput,
  type ReaderTimeInformationProjection,
} from "./domain/page/TimeInformationProjection.js"
export {
  projectReaderBookInformation,
  type ReaderBookInformationInput,
  type ReaderBookInformationLanguage,
  type ReaderBookInformationProjection,
} from "./domain/book/BookInformationProjection.js"
export {
  DEFAULT_READER_INFO_OVERLAY,
  READER_INFO_OVERLAY_HEIGHT_MAX,
  READER_INFO_OVERLAY_HEIGHT_MIN,
  READER_INFO_OVERLAY_OPACITY_MAX,
  READER_INFO_OVERLAY_OPACITY_MIN,
  READER_INFO_OVERLAY_WIDTH_MAX,
  READER_INFO_OVERLAY_WIDTH_MIN,
  applyReaderInfoOverlayPatch,
  normalizeReaderInfoOverlay,
  parseReaderInfoOverlayPatch,
  type ReaderInfoOverlayMutation,
  type ReaderInfoOverlayPatch,
  type ReaderInfoOverlaySettings,
} from "./application/info-overlay/ReaderInfoOverlay.js"
export {
  DEFAULT_READER_IMAGE_TRIM,
  READER_IMAGE_TRIM_MARGIN_MAX,
  READER_IMAGE_TRIM_MARGIN_MIN,
  READER_IMAGE_TRIM_MARGIN_STEP,
  READER_IMAGE_TRIM_TARGETS,
  READER_IMAGE_TRIM_THRESHOLD_MAX,
  READER_IMAGE_TRIM_THRESHOLD_MIN,
  READER_IMAGE_TRIM_THRESHOLD_STEP,
  applyReaderImageTrimPatch,
  isReaderImageTrimTarget,
  mergeReaderImageCropInsets,
  normalizeReaderImageTrim,
  parseReaderImageTrimPatch,
  projectReaderImageTrimPatch,
  readerImageCropTranslation,
  readerImageTrimClipPath,
  readerImageTrimEffectiveDimensions,
  readerImageTrimInsets,
  serializeReaderImageTrim,
  toReaderImageTrimJson,
  type ReaderImageCropInsets,
  type ReaderImageTrimDimensions,
  type ReaderImageTrimJson,
  type ReaderImageTrimMutation,
  type ReaderImageTrimPatch,
  type ReaderImageTrimSettings,
  type ReaderImageTrimTarget,
} from "./application/image-trim/ReaderImageTrim.js"
export {
  DEFAULT_READER_PAGE_TRANSITION,
  isReaderPageTransitionEasing,
  isReaderPageTransitionType,
  normalizeReaderPageTransition,
  parseReaderPageTransitionPatch,
  projectReaderPageTransitionCss,
  READER_PAGE_TRANSITION_EASING_CSS,
  READER_PAGE_TRANSITION_EASING_LABELS,
  READER_PAGE_TRANSITION_EASINGS,
  READER_PAGE_TRANSITION_TYPE_LABELS,
  READER_PAGE_TRANSITION_TYPES,
  type ReaderPageTransitionCssProjection,
  type ReaderPageTransitionCssState,
  type ReaderPageTransitionDirection,
  type ReaderPageTransitionEasing,
  type ReaderPageTransitionPatch,
  type ReaderPageTransitionSettings,
  type ReaderPageTransitionType,
} from "./domain/page-transition/ReaderPageTransition.js"
export {
  formatReaderPageTransition,
  readerPageTransitionSurfaceOptions,
  READER_PAGE_TRANSITION_DURATION_RANGE,
} from "./application/page-transition/ReaderPageTransitionPresentation.js"
export {
  SuperResolutionPreferencesWireSchema,
  parseSuperResolutionPreferences,
  type SuperResolutionCondition,
  type SuperResolutionConditionExpression,
  type SuperResolutionPreferences,
  type SuperResolutionPreferencesWire,
} from "./domain/super-resolution/super-resolution-preferences.js"
export {
  LegacySuperResolutionSettingsCodec,
  type DecodedLegacySuperResolutionSettings,
  type LegacySuperResolutionDisposition,
  type LegacySuperResolutionReportEntry,
} from "./migration/LegacySuperResolutionSettingsCodec.js"
export {
  DEFAULT_READER_ANIMATED_VIDEO_KEYWORDS,
  DEFAULT_READER_ANIMATED_VIDEO_MODE,
  matchesReaderAnimatedVideoKeyword,
  normalizeReaderAnimatedVideoKeywords,
  normalizeReaderAnimatedVideoMode,
  parseReaderAnimatedVideoModePatch,
  type ReaderAnimatedVideoModePatch,
  type ReaderAnimatedVideoModeSettings,
} from "./application/animated-video/ReaderAnimatedVideoMode.js"
