export type { ReaderBook, ViewSource } from "./domain/book/book.js"
export {
  DEFAULT_READER_LAYOUT,
  type FramePage,
  type FrameCropInsets,
  type FrameSnapshot,
  type PageMode,
  type ReaderGeneration,
  type ReaderLayout,
  type ReaderPagePart,
} from "./domain/frame/frame.js"
export {
  calculateReaderFrameSize,
  calculateReaderPageStretchScales,
  calculateReaderScale,
  DEFAULT_READER_PRESENTATION,
  effectiveReaderRotation,
  normalizeReaderManualScale,
  normalizeReaderRotation,
  rotatePresentationSize,
  rotateReaderPresentation,
  stepReaderManualScale,
  type PresentationSize,
  type ReaderFitMode,
  type ReaderAutoRotation,
  type ReaderOrientation,
  type ReaderWidePageStretch,
  type ReaderPresentation,
  type ReaderRotation,
} from "./domain/presentation/presentation.js"
export type { ReadingDirection, TailOverflowBehavior } from "./domain/navigation/navigation.js"
export {
  cloneReaderRadialMenuConfig,
  DEFAULT_READER_RADIAL_MENU_CONFIG,
  parseReaderRadialMenuConfig,
  parseReaderRadialMenuPatch,
  type NeoviewRadialMenuPatch,
  type ReaderRadialMenuConfig,
  type ReaderRadialMenuDefinition,
  type ReaderRadialMenuItem,
  type ReaderRadialMenuVariant,
} from "./application/config/ReaderRadialMenuConfig.js"
export {
  convertLegacyReaderInputBindings,
  type ReaderLegacyInputBindingConversion,
  type ReaderLegacyInputBindingReportEntry,
} from "./application/config/ReaderLegacyInputBindings.js"
export {
  cloneReaderInputBindings,
  DEFAULT_READER_INPUT_BINDINGS,
  matchingReaderInputBinding,
  LEGACY_READER_INPUT_ACTION_MAP,
  READER_INPUT_ACTION_CATEGORIES,
  READER_INPUT_ACTION_CATEGORY_LABELS,
  READER_INPUT_ACTION_LABELS,
  READER_INPUT_ACTION_METADATA,
  READER_INPUT_ACTIONS,
  readerInputActionFromLegacyId,
  READER_INPUT_CONTEXT_LABELS,
  READER_INPUT_CONTEXT_PRIORITY,
  READER_INPUT_CONTEXTS,
  READER_MOUSE_GESTURE_DIRECTIONS,
  READER_VIEW_AREAS,
  readerInputConflictKey,
  readerInputConflicts,
  readerInputDescriptorKey,
  readerViewAreaAtPoint,
  type ReaderInputAction,
  type ReaderInputActionDefinition,
  type ReaderInputActionCategory,
  type ReaderInputActionMetadata,
  type ReaderInputBinding,
  type ReaderInputBindingsConfig,
  type ReaderInputConflict,
  type ReaderInputContext,
  type ReaderInputDescriptor,
  type ReaderMouseGestureDirection,
  type ReaderViewArea,
} from "./domain/input/ReaderInputBindings.js"
export type {
  PageDimensions,
  PageId,
  PageMediaKind,
  ReaderPage,
  ReaderPageTimestamps,
  ReaderPageTimeSource,
} from "./domain/page/page.js"
export {
  ReaderSlideshow,
  type ReaderSlideshowConfig,
  type ReaderSlideshowOptions,
  type ReaderSlideshowPosition,
  type ReaderSlideshowSnapshot,
  type ReaderSlideshowState,
} from "./application/slideshow/ReaderSlideshow.js"
export {
  READER_CARD_MANIFEST,
  READER_PANEL_MANIFEST,
  readerCardCanMoveTo,
  readerPanelAcceptsCards,
  type ReaderCardId,
  type ReaderCardManifestEntry,
  type ReaderPanelId,
  type ReaderPanelManifestEntry,
  type ReaderPanelPosition,
} from "./application/config/ReaderLayoutManifest.js"
