/**
 * @migrated-from src/lib/cards/info/PreloadStatusCard.svelte
 * @source-hash sha256:1cceb9bccf3022428af0708c673885636bd29e410abc2e7de79368f2f27e2b76
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,preload-stream-scheduler,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { bookStore } from '$lib/stores/book/core.js';
import {
		formatMemorySize,
		getCacheStatus,
		getMemoryStats,
		type MemoryPoolStats
	} from '$lib/api/pageManager';
interface PageCacheStatus {
		page: number;
		cached: boolean;
		isCurrent: boolean;
	}

export function PreloadStatusCard() {
  const totalPages = $derived(bookStore.totalPages);

  const currentPageIndex = $derived(bookStore.currentPageIndex);

  let memoryStats = $state<MemoryPoolStats | null>(null);

  let nearbyPages = $state<PageCacheStatus[]>([]);

  let isRefreshing = $state(false);

  let errorMessage = $state<string | null>(null);

  let refreshToken = 0;

  function buildStatuses(startPage: number, statuses: boolean[]): PageCacheStatus[] {
      return statuses.map((cached, offset) => {
        const page = startPage + offset;
        return {
          page,
          cached,
          isCurrent: page === currentPageIndex
        };
      });
    }

  async function refreshPreloadStatus(): Promise<void> {
      const token = ++refreshToken;
      const total = totalPages;
      const current = currentPageIndex;

      if (total <= 0) {
        memoryStats = null;
        nearbyPages = [];
        errorMessage = null;
        return;
      }

      const behind = 3;
      const ahead = 5;
      const startPage = Math.max(0, current - behind);
      const endPage = Math.min(total - 1, current + ahead);
      const count = endPage - startPage + 1;

      isRefreshing = true;
      try {
        const [memory, statuses] = await Promise.all([
          getMemoryStats(),
          getCacheStatus(startPage, count)
        ]);

        if (token !== refreshToken) return;
        memoryStats = memory;
        nearbyPages = buildStatuses(startPage, statuses);
        errorMessage = null;
      } catch (err) {
        if (token !== refreshToken) return;
        errorMessage = String(err);
      } finally {
        if (token === refreshToken) {
          isRefreshing = false;
        }
      }
    }

  $effect(() => {
      currentPageIndex;
      totalPages;
      void refreshPreloadStatus();
    });

  onMount(() => {
      const timer = window.setInterval(() => {
        void refreshPreloadStatus();
      }, 2000);

      return () => {
        window.clearInterval(timer);
      };
    });
  return (
    <Fragment>

<div className="space-y-3 text-xs">
	<div className="grid grid-cols-2 gap-2">
		<div className="border-border/60 bg-muted/20 rounded border p-2">
			<div className="text-muted-foreground text-[10px]">当前页</div>
			<div className="mt-1 font-medium">{totalPages > 0 ? currentPageIndex + 1 : 0} / {totalPages}</div>
		</div>
		<div className="border-border/60 bg-muted/20 rounded border p-2">
			<div className="text-muted-foreground text-[10px]">内存池</div>
			<div className="mt-1 font-medium">
				{memoryStats ? (<Fragment>
					{memoryStats.entryCount} 项
				</Fragment>) : (<Fragment>
					--
				</Fragment>)}
			</div>
		</div>
	</div>

	{memoryStats ? (<Fragment>
		<div className="space-y-1.5">
			<div className="text-muted-foreground flex items-center justify-between text-[10px]">
				<span>{formatMemorySize(memoryStats.totalSize)} / {formatMemorySize(memoryStats.maxSize)}</span>
				<span>{memoryStats.usagePercent.toFixed(1)}%</span>
			</div>
			<div className="bg-muted h-1.5 overflow-hidden rounded">
				<div className="bg-primary h-full rounded transition-[width]" style={`width: ${Math.min(100, Math.max(0, memoryStats.usagePercent))}%`}></div>
			</div>
		</div>
	</Fragment>) : null}

	<div className="space-y-1.5">
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground text-[10px]">附近页缓存</span>
			<span className="text-muted-foreground text-[10px]">{isRefreshing ? '刷新中' : '已同步'}</span>
		</div>
		<div className="grid grid-cols-3 gap-1.5">
			{nearbyPages.map((item) => (<Fragment key={item.page}>
				<div className={[
						'rounded border px-2 py-1 text-center',
						item.isCurrent
							? 'border-primary bg-primary/10 text-primary'
							: item.cached
								? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-600'
								: 'border-border/60 bg-muted/20 text-muted-foreground'
					]}>
					<span className="block text-[10px]">P{item.page + 1}</span>
					<span className="block text-[9px]">{item.cached ? 'cached' : 'cold'}</span>
				</div>
			</Fragment>))}
		</div>
	</div>

	{errorMessage ? (<Fragment>
		<div className="border-destructive/40 bg-destructive/10 text-destructive rounded border p-2 text-[10px]">
			{errorMessage}
		</div>
	</Fragment>) : null}
</div></Fragment>
  )
}
