//! Generated by `scripts/audit-tui-theme-table.ts` from `packages/cli-runtime/src/tui/theme.tsx`.
//! Do not edit by hand: `bun run audit:tui-theme-table` fails when this file and the producer disagree, and
//! `bun run migrate:tui-theme-table` rewrites it. The producer's own meaning is preserved: the fallback theme is
//! `nord` (not the palette named `default`), and an unknown name resolves to the fallback instead of failing.

/// One palette entry: eight sRGB colours with their alpha byte, so this crate stays free of any terminal
/// dependency. A face that cannot draw alpha (ratatui cannot) must decide what to do with the last byte and
/// say so — the "cursor" theme is translucent on purpose.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Palette {
    pub primary: (u8, u8, u8, u8),
    pub foreground: (u8, u8, u8, u8),
    pub muted_foreground: (u8, u8, u8, u8),
    pub border: (u8, u8, u8, u8),
    pub focus_ring: (u8, u8, u8, u8),
    pub success: (u8, u8, u8, u8),
    pub warning: (u8, u8, u8, u8),
    pub error: (u8, u8, u8, u8),
}

/// Every theme the legacy TUI registers, in its own order.
#[must_use]
pub const fn theme_names() -> &'static [&'static str] {
    &["default", "nord", "dracula", "high-contrast", "high-contrast-light", "catppuccin", "catppuccin-frappe", "catppuccin-macchiato", "monokai", "one-dark", "onedarkpro", "solarized", "tokyo-night", "amoled", "aura", "ayu", "carbonfox", "cobalt2", "cursor", "everforest", "flexoki", "github", "gruvbox", "kanagawa", "lucent-orng", "material", "matrix", "mercury", "nightowl", "oc-2", "opencode", "orng", "osaka-jade", "palenight", "rosepine", "shadesofpurple", "synthwave84", "vercel", "vesper", "zenburn"]
}

/// The palette for a theme name, matched the way `resolveTerminalTheme` matches it.
#[must_use]
pub fn palette(name: &str) -> Option<Palette> {
    match name.trim().to_ascii_lowercase().as_str() {
        "default" => Some(Palette { primary: (124, 58, 237, 255), foreground: (255, 255, 255, 255), muted_foreground: (156, 163, 175, 255), border: (75, 85, 99, 255), focus_ring: (139, 92, 246, 255), success: (16, 185, 129, 255), warning: (245, 158, 11, 255), error: (239, 68, 68, 255) }),
        "nord" => Some(Palette { primary: (136, 192, 208, 255), foreground: (236, 239, 244, 255), muted_foreground: (76, 86, 106, 255), border: (76, 86, 106, 255), focus_ring: (136, 192, 208, 255), success: (163, 190, 140, 255), warning: (235, 203, 139, 255), error: (191, 97, 106, 255) }),
        "dracula" => Some(Palette { primary: (189, 147, 249, 255), foreground: (248, 248, 242, 255), muted_foreground: (98, 114, 164, 255), border: (98, 114, 164, 255), focus_ring: (189, 147, 249, 255), success: (80, 250, 123, 255), warning: (241, 250, 140, 255), error: (255, 85, 85, 255) }),
        "high-contrast" => Some(Palette { primary: (255, 255, 255, 255), foreground: (255, 255, 255, 255), muted_foreground: (204, 204, 204, 255), border: (255, 255, 255, 255), focus_ring: (255, 255, 0, 255), success: (0, 255, 0, 255), warning: (255, 255, 0, 255), error: (255, 68, 68, 255) }),
        "high-contrast-light" => Some(Palette { primary: (0, 0, 0, 255), foreground: (0, 0, 0, 255), muted_foreground: (68, 68, 68, 255), border: (0, 0, 0, 255), focus_ring: (0, 0, 204, 255), success: (0, 102, 0, 255), warning: (136, 68, 0, 255), error: (204, 0, 0, 255) }),
        "catppuccin" => Some(Palette { primary: (203, 166, 247, 255), foreground: (205, 214, 244, 255), muted_foreground: (108, 112, 134, 255), border: (69, 71, 90, 255), focus_ring: (203, 166, 247, 255), success: (166, 227, 161, 255), warning: (249, 226, 175, 255), error: (243, 139, 168, 255) }),
        "catppuccin-frappe" => Some(Palette { primary: (141, 164, 226, 255), foreground: (198, 208, 245, 255), muted_foreground: (148, 156, 184, 255), border: (148, 156, 184, 255), focus_ring: (202, 158, 230, 255), success: (166, 209, 137, 255), warning: (229, 200, 144, 255), error: (231, 130, 132, 255) }),
        "catppuccin-macchiato" => Some(Palette { primary: (138, 173, 244, 255), foreground: (202, 211, 245, 255), muted_foreground: (147, 154, 183, 255), border: (147, 154, 183, 255), focus_ring: (198, 160, 246, 255), success: (166, 218, 149, 255), warning: (238, 212, 159, 255), error: (237, 135, 150, 255) }),
        "monokai" => Some(Palette { primary: (166, 226, 46, 255), foreground: (248, 248, 242, 255), muted_foreground: (117, 113, 94, 255), border: (117, 113, 94, 255), focus_ring: (166, 226, 46, 255), success: (166, 226, 46, 255), warning: (230, 219, 116, 255), error: (249, 38, 114, 255) }),
        "one-dark" => Some(Palette { primary: (97, 175, 239, 255), foreground: (171, 178, 191, 255), muted_foreground: (92, 99, 112, 255), border: (75, 82, 99, 255), focus_ring: (97, 175, 239, 255), success: (152, 195, 121, 255), warning: (229, 192, 123, 255), error: (224, 108, 117, 255) }),
        "onedarkpro" => Some(Palette { primary: (97, 175, 239, 255), foreground: (171, 178, 191, 255), muted_foreground: (92, 99, 112, 255), border: (92, 99, 112, 255), focus_ring: (198, 120, 221, 255), success: (152, 195, 121, 255), warning: (229, 192, 123, 255), error: (224, 108, 117, 255) }),
        "solarized" => Some(Palette { primary: (38, 139, 210, 255), foreground: (131, 148, 150, 255), muted_foreground: (88, 110, 117, 255), border: (88, 110, 117, 255), focus_ring: (38, 139, 210, 255), success: (133, 153, 0, 255), warning: (181, 137, 0, 255), error: (220, 50, 47, 255) }),
        "tokyo-night" => Some(Palette { primary: (122, 162, 247, 255), foreground: (192, 202, 245, 255), muted_foreground: (86, 95, 137, 255), border: (59, 66, 97, 255), focus_ring: (122, 162, 247, 255), success: (158, 206, 106, 255), warning: (224, 175, 104, 255), error: (247, 118, 142, 255) }),
        "amoled" => Some(Palette { primary: (179, 136, 255, 255), foreground: (255, 255, 255, 255), muted_foreground: (136, 136, 136, 255), border: (85, 85, 85, 255), focus_ring: (179, 136, 255, 255), success: (0, 255, 136, 255), warning: (255, 234, 0, 255), error: (255, 23, 68, 255) }),
        "aura" => Some(Palette { primary: (162, 119, 255, 255), foreground: (237, 236, 238, 255), muted_foreground: (109, 106, 126, 255), border: (109, 106, 126, 255), focus_ring: (162, 119, 255, 255), success: (97, 255, 202, 255), warning: (255, 202, 133, 255), error: (255, 103, 103, 255) }),
        "ayu" => Some(Palette { primary: (63, 183, 227, 255), foreground: (214, 218, 224, 255), muted_foreground: (90, 102, 115, 255), border: (90, 102, 115, 255), focus_ring: (63, 183, 227, 255), success: (120, 208, 92, 255), warning: (228, 167, 92, 255), error: (245, 133, 114, 255) }),
        "carbonfox" => Some(Palette { primary: (51, 177, 255, 255), foreground: (242, 244, 248, 255), muted_foreground: (111, 111, 111, 255), border: (111, 111, 111, 255), focus_ring: (190, 149, 255, 255), success: (66, 190, 101, 255), warning: (241, 194, 27, 255), error: (255, 131, 137, 255) }),
        "cobalt2" => Some(Palette { primary: (0, 136, 255, 255), foreground: (255, 255, 255, 255), muted_foreground: (173, 183, 201, 255), border: (0, 136, 255, 255), focus_ring: (42, 255, 223, 255), success: (158, 255, 128, 255), warning: (255, 198, 0, 255), error: (255, 0, 136, 255) }),
        "cursor" => Some(Palette { primary: (136, 192, 208, 255), foreground: (228, 228, 228, 255), muted_foreground: (228, 228, 228, 94), border: (228, 228, 228, 94), focus_ring: (130, 210, 206, 255), success: (63, 162, 102, 255), warning: (241, 180, 103, 255), error: (227, 70, 113, 255) }),
        "everforest" => Some(Palette { primary: (167, 192, 128, 255), foreground: (211, 198, 170, 255), muted_foreground: (122, 132, 120, 255), border: (122, 132, 120, 255), focus_ring: (214, 153, 182, 255), success: (167, 192, 128, 255), warning: (230, 152, 117, 255), error: (230, 126, 128, 255) }),
        "flexoki" => Some(Palette { primary: (218, 112, 44, 255), foreground: (206, 205, 195, 255), muted_foreground: (111, 110, 105, 255), border: (111, 110, 105, 255), focus_ring: (135, 154, 57, 255), success: (135, 154, 57, 255), warning: (218, 112, 44, 255), error: (209, 77, 65, 255) }),
        "github" => Some(Palette { primary: (88, 166, 255, 255), foreground: (201, 209, 217, 255), muted_foreground: (139, 148, 158, 255), border: (48, 54, 61, 255), focus_ring: (88, 166, 255, 255), success: (63, 185, 80, 255), warning: (227, 179, 65, 255), error: (248, 81, 73, 255) }),
        "gruvbox" => Some(Palette { primary: (131, 165, 152, 255), foreground: (235, 219, 178, 255), muted_foreground: (146, 131, 116, 255), border: (146, 131, 116, 255), focus_ring: (251, 73, 52, 255), success: (184, 187, 38, 255), warning: (250, 189, 47, 255), error: (251, 73, 52, 255) }),
        "kanagawa" => Some(Palette { primary: (126, 156, 216, 255), foreground: (220, 215, 186, 255), muted_foreground: (114, 113, 105, 255), border: (114, 113, 105, 255), focus_ring: (149, 127, 187, 255), success: (152, 187, 108, 255), warning: (215, 166, 87, 255), error: (232, 36, 36, 255) }),
        "lucent-orng" => Some(Palette { primary: (236, 91, 43, 255), foreground: (238, 238, 238, 255), muted_foreground: (128, 128, 128, 255), border: (128, 128, 128, 255), focus_ring: (236, 91, 43, 255), success: (107, 161, 230, 255), warning: (236, 91, 43, 255), error: (224, 108, 117, 255) }),
        "material" => Some(Palette { primary: (130, 170, 255, 255), foreground: (238, 255, 255, 255), muted_foreground: (84, 110, 122, 255), border: (84, 110, 122, 255), focus_ring: (199, 146, 234, 255), success: (195, 232, 141, 255), warning: (255, 203, 107, 255), error: (240, 113, 120, 255) }),
        "matrix" => Some(Palette { primary: (46, 255, 106, 255), foreground: (98, 255, 148, 255), muted_foreground: (140, 163, 145, 255), border: (140, 163, 145, 255), focus_ring: (199, 112, 255, 255), success: (98, 255, 148, 255), warning: (230, 255, 87, 255), error: (255, 75, 75, 255) }),
        "mercury" => Some(Palette { primary: (141, 164, 245, 255), foreground: (221, 221, 229, 255), muted_foreground: (157, 157, 168, 255), border: (157, 157, 168, 255), focus_ring: (141, 164, 245, 255), success: (119, 197, 153, 255), warning: (252, 155, 111, 255), error: (252, 146, 180, 255) }),
        "nightowl" => Some(Palette { primary: (130, 170, 255, 255), foreground: (214, 222, 235, 255), muted_foreground: (99, 119, 119, 255), border: (99, 119, 119, 255), focus_ring: (199, 146, 234, 255), success: (197, 228, 120, 255), warning: (236, 196, 141, 255), error: (239, 83, 80, 255) }),
        "oc-2" => Some(Palette { primary: (250, 178, 131, 255), foreground: (241, 236, 232, 255), muted_foreground: (112, 112, 112, 255), border: (40, 40, 40, 255), focus_ring: (237, 178, 241, 255), success: (18, 201, 5, 255), warning: (252, 213, 58, 255), error: (252, 83, 58, 255) }),
        "opencode" => Some(Palette { primary: (250, 178, 131, 255), foreground: (238, 238, 238, 255), muted_foreground: (128, 128, 128, 255), border: (128, 128, 128, 255), focus_ring: (157, 124, 216, 255), success: (127, 216, 143, 255), warning: (245, 167, 66, 255), error: (224, 108, 117, 255) }),
        "orng" => Some(Palette { primary: (236, 91, 43, 255), foreground: (238, 238, 238, 255), muted_foreground: (128, 128, 128, 255), border: (128, 128, 128, 255), focus_ring: (236, 91, 43, 255), success: (107, 161, 230, 255), warning: (236, 91, 43, 255), error: (224, 108, 117, 255) }),
        "osaka-jade" => Some(Palette { primary: (45, 213, 183, 255), foreground: (193, 196, 151, 255), muted_foreground: (83, 104, 91, 255), border: (83, 104, 91, 255), focus_ring: (45, 213, 183, 255), success: (84, 158, 106, 255), warning: (229, 199, 54, 255), error: (255, 83, 69, 255) }),
        "palenight" => Some(Palette { primary: (130, 170, 255, 255), foreground: (166, 172, 205, 255), muted_foreground: (103, 110, 149, 255), border: (103, 110, 149, 255), focus_ring: (199, 146, 234, 255), success: (195, 232, 141, 255), warning: (255, 203, 107, 255), error: (240, 113, 120, 255) }),
        "rosepine" => Some(Palette { primary: (156, 207, 216, 255), foreground: (224, 222, 244, 255), muted_foreground: (110, 106, 134, 255), border: (110, 106, 134, 255), focus_ring: (49, 116, 143, 255), success: (49, 116, 143, 255), warning: (246, 193, 119, 255), error: (235, 111, 146, 255) }),
        "shadesofpurple" => Some(Palette { primary: (199, 146, 255, 255), foreground: (245, 240, 255, 255), muted_foreground: (179, 98, 255, 255), border: (179, 98, 255, 255), focus_ring: (199, 146, 255, 255), success: (123, 224, 176, 255), warning: (255, 213, 128, 255), error: (255, 122, 198, 255) }),
        "synthwave84" => Some(Palette { primary: (54, 249, 246, 255), foreground: (255, 255, 255, 255), muted_foreground: (132, 139, 189, 255), border: (132, 139, 189, 255), focus_ring: (255, 126, 219, 255), success: (114, 241, 184, 255), warning: (254, 222, 93, 255), error: (254, 68, 80, 255) }),
        "vercel" => Some(Palette { primary: (0, 112, 243, 255), foreground: (237, 237, 237, 255), muted_foreground: (135, 135, 135, 255), border: (69, 69, 69, 255), focus_ring: (247, 85, 144, 255), success: (70, 167, 88, 255), warning: (255, 178, 36, 255), error: (229, 72, 77, 255) }),
        "vesper" => Some(Palette { primary: (255, 199, 153, 255), foreground: (255, 255, 255, 255), muted_foreground: (139, 139, 139, 255), border: (139, 139, 139, 255), focus_ring: (160, 160, 160, 255), success: (153, 255, 228, 255), warning: (255, 199, 153, 255), error: (255, 128, 128, 255) }),
        "zenburn" => Some(Palette { primary: (140, 208, 211, 255), foreground: (220, 220, 204, 255), muted_foreground: (159, 159, 159, 255), border: (159, 159, 159, 255), focus_ring: (240, 223, 175, 255), success: (127, 159, 127, 255), warning: (240, 223, 175, 255), error: (204, 147, 147, 255) }),
        _ => None,
    }
}

/// The theme the screen falls back to, and the answer for a name it does not know.
#[must_use]
pub const fn fallback_theme() -> &'static str {
    "nord"
}

/// Resolve an optional theme name exactly like the TypeScript does: absent, empty or unknown → nord.
#[must_use]
pub fn resolve_theme_name(name: Option<&str>) -> &'static str {
    let requested = name.map(str::trim).filter(|value| !value.is_empty()).map(|value| value.to_ascii_lowercase());
    match requested.as_deref() {
        Some(looked_up) => theme_names().iter().find(|candidate| **candidate == looked_up).copied().unwrap_or_else(fallback_theme),
        None => fallback_theme(),
    }
}

#[cfg(test)]
mod tests {
    use super::{fallback_theme, palette, resolve_theme_name, theme_names};

    #[test]
    fn every_theme_in_the_table_has_a_palette() {
        for name in theme_names() {
            assert!(palette(name).is_some(), "{name} is listed but has no palette");
        }
        assert!(theme_names().len() >= 40, "the producer registered fewer themes than before: {}", theme_names().len());
    }

    #[test]
    fn matching_ignores_case_and_surrounding_space() {
        assert_eq!(palette("Nord"), palette("  nord "));
        assert!(palette("torak").is_none(), "an invented theme must not resolve to a palette");
        // The one translucent entry in the producer, kept as it was authored rather than flattened to opaque.
        let cursor = palette("cursor").expect("cursor theme");
        assert!(cursor.muted_foreground.3 < 255, "cursor's muted foreground carries alpha: {cursor:?}");
        assert_eq!(palette("nord").map(|entry| entry.primary), Some((136, 192, 208, 255)));
    }

    #[test]
    fn the_fallback_is_nord_and_an_unknown_name_falls_back_to_it() {
        assert_eq!(fallback_theme(), "nord");
        assert_eq!(resolve_theme_name(None), "nord");
        assert_eq!(resolve_theme_name(Some("not-a-theme")), "nord");
        assert_eq!(resolve_theme_name(Some("   ")), "nord");
        // The palette literally named "default" is a colour scheme, not the fallback theme: a port that reads the
        // first row as "the default" would recolour every screen.
        assert!(theme_names().contains(&"default"));
        assert_ne!(fallback_theme(), "default");
        assert_eq!(resolve_theme_name(Some(" Dracula ")), "dracula");
        assert_eq!(resolve_theme_name(Some("HIGH-CONTRAST")), "high-contrast");
    }
}
