/**
 * @migrated-from src/lib/components/panels/theme/ThemeModeTab.svelte
 * @source-hash sha256:9a77d89682bfa34ed06b2d72f822537712b7a32a91ae6e3643803fb0d0a4d9aa
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Sun, Moon, Monitor, Check } from 'lucide-react';
import { Label } from '$lib/components/ui/label';
import type { ThemeMode } from './themeStore';
interface Props {
		currentMode: ThemeMode;
		systemPrefersDark: boolean;
		onModeChange: (mode: ThemeMode) => void;
	}

export function ThemeModeTab(props: Props) {
  const { currentMode, systemPrefersDark, onModeChange } = props
  return (
    <Fragment>{/* 
  主题模式选择 Tab
  包含浅色/深色/跟随系统三种模式
 */}


<div className="space-y-4">
	{/*  主题模式选择  */}
	<div className="space-y-3">
		<Label className="text-sm font-semibold">主题模式</Label>
		<div className="grid grid-cols-3 gap-3">
			<button onClick={() => onModeChange('light')} className={`hover:bg-accent flex flex-col items-center gap-2 rounded-lg border p-4 transition-colors ${currentMode ===
				'light'
					? 'border-primary bg-primary/5'
					: ''}`}>
				<Sun className="h-6 w-6"></Sun>
				<span className="text-sm font-medium">浅色</span>
				{currentMode === 'light' ? (<Fragment>
					<Check className="text-primary h-4 w-4"></Check>
				</Fragment>) : null}
			</button>

			<button onClick={() => onModeChange('dark')} className={`hover:bg-accent flex flex-col items-center gap-2 rounded-lg border p-4 transition-colors ${currentMode ===
				'dark'
					? 'border-primary bg-primary/5'
					: ''}`}>
				<Moon className="h-6 w-6"></Moon>
				<span className="text-sm font-medium">深色</span>
				{currentMode === 'dark' ? (<Fragment>
					<Check className="text-primary h-4 w-4"></Check>
				</Fragment>) : null}
			</button>

			<button onClick={() => onModeChange('system')} className={`hover:bg-accent flex flex-col items-center gap-2 rounded-lg border p-4 transition-colors ${currentMode ===
				'system'
					? 'border-primary bg-primary/5'
					: ''}`}>
				<Monitor className="h-6 w-6"></Monitor>
				<span className="text-sm font-medium">跟随系统</span>
				{currentMode === 'system' ? (<Fragment>
					<Check className="text-primary h-4 w-4"></Check>
				</Fragment>) : null}
			</button>
		</div>
		{currentMode === 'system' ? (<Fragment>
			<p className="text-muted-foreground text-xs">
				当前系统偏好: {systemPrefersDark ? '深色' : '浅色'}
			</p>
		</Fragment>) : null}
	</div>

	{/*  颜色预览  */}
	<div className="space-y-3">
		<Label className="text-sm font-semibold">颜色预览</Label>
		<div className="grid grid-cols-2 gap-3">
			<div className="bg-primary text-primary-foreground rounded-lg border p-3">
				<p className="text-sm font-medium">Primary</p>
			</div>
			<div className="bg-secondary text-secondary-foreground rounded-lg border p-3">
				<p className="text-sm font-medium">Secondary</p>
			</div>
			<div className="bg-accent text-accent-foreground rounded-lg border p-3">
				<p className="text-sm font-medium">Accent</p>
			</div>
			<div className="bg-muted text-muted-foreground rounded-lg border p-3">
				<p className="text-sm font-medium">Muted</p>
			</div>
		</div>
	</div>

	{/*  提示信息  */}
	<div className="border-primary/20 bg-primary/5 rounded-lg border p-4">
		<p className="text-sm">
			<strong>💡 提示:</strong> 主题设置会自动保存，下次打开应用时会自动应用。
		</p>
	</div>
</div></Fragment>
  )
}
