/**
 * @migrated-from src/lib/components/layout/TopToolbar/HoverScrollPanel.svelte
 * @source-hash sha256:3e2646506cc0585fa406b6a1b96ab9f212f2c7c0230e4aafbea871c144f886b9
 * @features panels-toolbar-shell,zoom-rotate-magnifier
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Button } from '$lib/components/ui/button';
import * as Separator from '$lib/components/ui/separator';
import { settingsManager } from '$lib/settings/settingsManager';
import { bookStore } from '$lib/stores/book.js';
interface Props {
		expanded: boolean;
	}

export function HoverScrollPanel(props: Props) {
  const { expanded } = props
  let settings = $state(settingsManager.getSettings());

  settingsManager.addListener((newSettings) => {
      settings = newSettings;
    });

  let hoverScrollEnabled = $derived(settings.image.hoverScrollEnabled ?? true);

  let hoverScrollSpeed = $derived(settings.image.hoverScrollSpeed ?? 2.0);

  function toggleHoverScroll() {
      const next = !(settings.image.hoverScrollEnabled ?? true);
      settingsManager.updateNestedSettings('image', { hoverScrollEnabled: next });
    }

  function handleHoverScrollSpeedChange(value: number) {
      const clamped = Math.max(0.5, Math.min(value, 10));
      settingsManager.updateNestedSettings('image', { hoverScrollSpeed: clamped });
    }
  return (
    <Fragment>

{expanded && bookStore.currentBook ? (<Fragment>
	<div className="border-border/50 flex flex-wrap items-center justify-center gap-2 border-t pt-1">
		<span className="text-muted-foreground mr-2 text-xs">悬停滚动</span>

		{/*  开关按钮  */}
		<Button variant={hoverScrollEnabled ? 'default' : 'outline'} size="sm" className="h-7 px-3" onClick={toggleHoverScroll}>
			{hoverScrollEnabled ? '已启用' : '已禁用'}
		</Button>

		<Separator.Root orientation="vertical" className="mx-2 h-5"></Separator.Root>

		{/*  滚动倍率  */}
		<span className="text-muted-foreground text-xs">倍率</span>
		<div className="flex items-center gap-1">
			<input type="range" min="0.5" max="10" step="0.5" value={hoverScrollSpeed} onInput={(e) =>
					handleHoverScrollSpeedChange(parseFloat((e.target as HTMLInputElement).value))} className="bg-muted h-1 w-20 cursor-pointer appearance-none rounded-full" />
			<span className="w-10 text-center text-xs">{hoverScrollSpeed.toFixed(1)}x</span>
		</div>
	</div>
</Fragment>) : null}</Fragment>
  )
}
