/**
 * @migrated-from src/lib/cards/upscale/UpscaleCacheCard.svelte
 * @source-hash sha256:1bf602820ffb4e1dbba5e5243c88147d7389a0932ccced3418e162c529e0b37c
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute BindDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Trash2, FolderOpen, RefreshCw, Loader2, HardDrive } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import { cacheStats, formatFileSize } from '$lib/stores/upscale/upscalePanelStore.js';
import { pyo3UpscaleManager } from '$lib/stores/upscale/PyO3UpscaleManager.js';
import { FileSystemAPI } from '$lib/api';
import { confirm } from '$lib/stores/confirmDialog.js';
import { invoke } from '@tauri-apps/api/core';

export function UpscaleCacheCard() {
  let isRefreshing = $state(false);

  let isClearing = $state(false);

  let isClearingAll = $state(false);

  let cleanupDays = $state(30);

  async function refreshCacheStats() {
      isRefreshing = true;
      try {
        // 直接调用 Tauri 命令获取缓存统计
        const stats = await invoke<{ total_files: number; total_size: number; cache_dir: string }>(
          'get_pyo3_cache_stats'
        );
        if (stats) {
          cacheStats.value = {
            totalFiles: stats.total_files,
            totalSize: stats.total_size,
            cacheDir: stats.cache_dir
          };
        }
      } catch (err) {
        console.error('刷新缓存统计失败:', err);
        // 尝试使用 pyo3UpscaleManager 作为备选
        try {
          const stats = await pyo3UpscaleManager.getCacheStats();
          if (stats) {
            cacheStats.value = {
              totalFiles: stats.totalFiles,
              totalSize: stats.totalSize,
              cacheDir: stats.cacheDir
            };
          }
        } catch (e) {
          console.error('备选方案也失败:', e);
        }
      } finally {
        isRefreshing = false;
      }
    }

  async function clearOldCache() {
      const confirmed = await confirm({
        title: '清理过期缓存',
        description: `确定要清除 ${cleanupDays} 天前的超分缓存吗？`,
        confirmText: '清理',
        cancelText: '取消',
        variant: 'default'
      });
      if (!confirmed) return;

      isClearing = true;
      try {
        const removed = await pyo3UpscaleManager.cleanupCache(cleanupDays);
        console.log(`已清理 ${removed} 个过期缓存文件`);
        await refreshCacheStats();
      } catch (err) {
        console.error('清除缓存失败:', err);
      } finally {
        isClearing = false;
      }
    }

  async function clearAllCache() {
      const confirmed = await confirm({
        title: '清除全部缓存',
        description: '确定要清除所有超分缓存吗？此操作不可撤销。',
        confirmText: '全部清除',
        cancelText: '取消',
        variant: 'destructive'
      });
      if (!confirmed) return;

      isClearingAll = true;
      try {
        // 清除所有缓存（设置 maxAgeDays 为 0）
        await invoke('clear_all_pyo3_cache');
        await refreshCacheStats();
      } catch (err) {
        console.error('清除全部缓存失败:', err);
        // 回退方案：使用 cleanupCache(0)
        try {
          await pyo3UpscaleManager.cleanupCache(0);
          await refreshCacheStats();
        } catch (e) {
          console.error('回退清除也失败:', e);
        }
      } finally {
        isClearingAll = false;
      }
    }

  async function openCacheDir() {
      if (!cacheStats.value.cacheDir) return;
      try {
        await FileSystemAPI.showInFileManager(cacheStats.value.cacheDir);
      } catch (err) {
        console.error('打开缓存目录失败:', err);
      }
    }

  onMount(() => {
      refreshCacheStats();
    });
  return (
    <Fragment>

<div className="space-y-3 text-xs">
	{/*  缓存统计  */}
	<div className="space-y-2">
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground">缓存文件</span>
			<span>{cacheStats.value.totalFiles} 个</span>
		</div>
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground">占用空间</span>
			<span>{formatFileSize(cacheStats.value.totalSize)}</span>
		</div>
		{cacheStats.value.cacheDir ? (<Fragment>
			<p className="text-muted-foreground truncate text-[10px]" title={cacheStats.value.cacheDir}>
				{cacheStats.value.cacheDir}
			</p>
		</Fragment>) : null}
	</div>

	{/*  过期清理配置  */}
	<div className="flex items-center justify-between">
		<span className="text-muted-foreground">清理天数</span>
		<select className="bg-muted h-6 rounded border-0 px-2 text-xs">
			{[7, 14, 30, 60, 90].map((days) => (<Fragment>
				<option value={days}>{days} 天</option>
			</Fragment>))}
		</select>
	</div>

	{/*  操作按钮  */}
	<div className="flex gap-2">
		<Button variant="outline" size="sm" className="h-7 flex-1 text-xs" onClick={refreshCacheStats} disabled={isRefreshing}>
			{isRefreshing ? (<Fragment>
				<Loader2 className="mr-1 h-3 w-3 animate-spin"></Loader2>
			</Fragment>) : (<Fragment>
				<RefreshCw className="mr-1 h-3 w-3"></RefreshCw>
			</Fragment>)}
			刷新
		</Button>

		<Button variant="outline" size="sm" className="h-7 flex-1 text-xs" onClick={openCacheDir} disabled={!cacheStats.value.cacheDir}>
			<FolderOpen className="mr-1 h-3 w-3"></FolderOpen>
			打开
		</Button>
	</div>

	<div className="flex gap-2">
		<Button variant="outline" size="sm" className="h-7 flex-1 text-xs" onClick={clearOldCache} disabled={isClearing || cacheStats.value.totalFiles === 0}>
			{isClearing ? (<Fragment>
				<Loader2 className="mr-1 h-3 w-3 animate-spin"></Loader2>
			</Fragment>) : (<Fragment>
				<Trash2 className="mr-1 h-3 w-3"></Trash2>
			</Fragment>)}
			清理过期
		</Button>

		<Button variant="outline" size="sm" className="text-destructive hover:text-destructive h-7 flex-1 text-xs" onClick={clearAllCache} disabled={isClearingAll || cacheStats.value.totalFiles === 0}>
			{isClearingAll ? (<Fragment>
				<Loader2 className="mr-1 h-3 w-3 animate-spin"></Loader2>
			</Fragment>) : (<Fragment>
				<Trash2 className="mr-1 h-3 w-3"></Trash2>
			</Fragment>)}
			全部清除
		</Button>
	</div>
</div></Fragment>
  )
}
