/**
 * @migrated-from src/lib/cards/upscale/UpscaleModelCard.svelte
 * @source-hash sha256:53109f03db9f490133bf5da353cd93e78e021db115b34b98613101350cff13f9
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { open } from '@tauri-apps/plugin-dialog';
import FolderOpenIcon from '@lucide/svelte/icons/folder-open';
import RefreshCwIcon from '@lucide/svelte/icons/refresh-cw';
import { Button } from '$lib/components/ui/button';
import { Label } from '$lib/components/ui/label';
import { Switch } from '$lib/components/ui/switch';
import {
		DEFAULT_MANGA_JANAI_MODEL_DIR,
		GPU_OPTIONS,
		MODEL_LABELS,
		NOISE_LEVEL_OPTIONS,
		TILE_SIZE_OPTIONS,
		availableModels,
		gpuId,
		isPyO3Available,
		mangaJanaiModelDir,
		noiseLevel,
		saveSettings,
		scale,
		selectedModel,
		tileEnabled,
		tileSize
	} from '$lib/stores/upscale/upscalePanelStore.js';
import { pyo3UpscaleManager } from '$lib/stores/upscale/PyO3UpscaleManager.js';

export function UpscaleModelCard() {
  let isRefreshingModels = $state(false);

  let modelDirError = $state('');

  function getModelLabel(modelName: string): string {
      return MODEL_LABELS[modelName] || modelName.replace(/^MODEL_/, '').replace(/_/g, ' ');
    }

  function getModelScale(modelName: string): number | null {
      if (modelName.includes('UP1X')) return 1;
      if (modelName.includes('UP2X') || modelName.includes('_X2') || modelName.startsWith('2x_'))
        return 2;
      if (modelName.includes('UP3X') || modelName.includes('_X3') || modelName.startsWith('3x_'))
        return 3;
      if (modelName.includes('UP4X') || modelName.includes('_X4') || modelName.startsWith('4x_'))
        return 4;
      return null;
    }

  async function refreshMangaJanaiModels() {
      modelDirError = '';
      isRefreshingModels = true;
      try {
        const modelDir = mangaJanaiModelDir.value.trim() || DEFAULT_MANGA_JANAI_MODEL_DIR;
        mangaJanaiModelDir.value = modelDir;
        saveSettings();
        await pyo3UpscaleManager.setMangaJanaiModelDir(modelDir);
        availableModels.value = pyo3UpscaleManager.getAvailableModels();
      } catch (error) {
        console.error('Failed to refresh MangaJaNai models', error);
        modelDirError = error instanceof Error ? error.message : String(error);
      } finally {
        isRefreshingModels = false;
      }
    }

  async function selectMangaJanaiModelDir() {
      const selected = await open({
        directory: true,
        multiple: false,
        defaultPath: mangaJanaiModelDir.value || DEFAULT_MANGA_JANAI_MODEL_DIR
      });

      const path = Array.isArray(selected) ? selected[0] : selected;
      if (!path) return;

      mangaJanaiModelDir.value = path;
      await refreshMangaJanaiModels();
    }

  function handleModelChange(value: string) {
      selectedModel.value = value;

      const nextScale = getModelScale(value);
      if (nextScale) {
        scale.value = nextScale;
      }

      saveSettings();
    }
  return (
    <Fragment>

<div className="space-y-3 text-xs">
	{!isPyO3Available.value ? (<Fragment>
		<div className="text-muted-foreground py-4 text-center">
			<p>超分功能不可用</p>
			<p className="mt-1 text-[10px]">请检查 sr_vulkan / PyO3 模块是否可用</p>
		</div>
	</Fragment>) : (<Fragment>
		<div className="space-y-1">
			<Label className="text-xs">模型</Label>
			<select className="bg-muted h-7 w-full rounded border-0 px-2 text-xs" value={selectedModel.value} onChange={(e) => handleModelChange(e.currentTarget.value)}>
				{availableModels.value.map((model) => (<Fragment>
					<option value={model}>{getModelLabel(model)}</option>
				</Fragment>))}
			</select>
		</div>

		<div className="space-y-1">
			<div className="flex items-center justify-between gap-2">
				<Label className="text-muted-foreground text-[10px]">MangaJaNai 模型目录</Label>
				<Button variant="ghost" size="sm" className="h-6 px-2 text-[10px]" onClick={() => {
						mangaJanaiModelDir.value = DEFAULT_MANGA_JANAI_MODEL_DIR;
						void refreshMangaJanaiModels();
					}}>
					默认
				</Button>
			</div>
			<div className="flex gap-1">
				<input className="bg-muted h-7 min-w-0 flex-1 rounded border-0 px-2 text-[10px]" value={mangaJanaiModelDir.value} onChange={(e) => {
						mangaJanaiModelDir.value = e.currentTarget.value;
						saveSettings();
					}} onKeyDown={(e) => {
						if (e.key === 'Enter') void refreshMangaJanaiModels();
					}} />
				<Button variant="outline" size="icon" className="h-7 w-7" title="选择目录" onClick={selectMangaJanaiModelDir}>
					<FolderOpenIcon className="size-3.5"></FolderOpenIcon>
				</Button>
				<Button variant="outline" size="icon" className="h-7 w-7" title="刷新模型" loading={isRefreshingModels} onClick={refreshMangaJanaiModels}>
					<RefreshCwIcon className="size-3.5"></RefreshCwIcon>
				</Button>
			</div>
			{modelDirError ? (<Fragment>
				<p className="text-destructive text-[10px]">{modelDirError}</p>
			</Fragment>) : null}
		</div>

		<div className="grid grid-cols-2 gap-2">
			<div className="space-y-1">
				<Label className="text-muted-foreground text-[10px]">放大倍率</Label>
				<select className="bg-muted h-6 w-full rounded border-0 px-2 text-xs" value={scale.value} onChange={(e) => {
						scale.value = parseInt(e.currentTarget.value);
						saveSettings();
					}}>
					<option value={1}>1x</option>
					<option value={2}>2x</option>
					<option value={3}>3x</option>
					<option value={4}>4x</option>
				</select>
			</div>

			<div className="space-y-1">
				<div className="flex items-center justify-between gap-2">
					<Label className="text-muted-foreground text-[10px]">Tile Size</Label>
					<label className="text-muted-foreground flex items-center gap-1 text-[10px]">
						<Switch checked={tileEnabled.value} onClick={() => {
								tileEnabled.value = !tileEnabled.value;
								saveSettings();
							}}></Switch>
						<span>{tileEnabled.value ? 'On' : 'Off'}</span>
					</label>
				</div>
				<select className="bg-muted h-6 w-full rounded border-0 px-2 text-xs" value={tileSize.value} disabled={!tileEnabled.value} onChange={(e) => {
						tileSize.value = parseInt(e.currentTarget.value);
						saveSettings();
					}}>
					{TILE_SIZE_OPTIONS.map((opt) => (<Fragment>
						<option value={opt.value}>{opt.label}</option>
					</Fragment>))}
				</select>
			</div>

			<div className="space-y-1">
				<Label className="text-muted-foreground text-[10px]">降噪等级</Label>
				<select className="bg-muted h-6 w-full rounded border-0 px-2 text-xs" value={noiseLevel.value} onChange={(e) => {
						noiseLevel.value = parseInt(e.currentTarget.value);
						saveSettings();
					}}>
					{NOISE_LEVEL_OPTIONS.map((opt) => (<Fragment>
						<option value={opt.value}>{opt.label}</option>
					</Fragment>))}
				</select>
			</div>

			<div className="space-y-1">
				<Label className="text-muted-foreground text-[10px]">GPU</Label>
				<select className="bg-muted h-6 w-full rounded border-0 px-2 text-xs" value={gpuId.value} onChange={(e) => {
						gpuId.value = parseInt(e.currentTarget.value);
						saveSettings();
					}}>
					{GPU_OPTIONS.map((opt) => (<Fragment>
						<option value={opt.value}>{opt.label}</option>
					</Fragment>))}
				</select>
			</div>
		</div>

		<div className="text-muted-foreground border-t pt-2 text-[10px]">
			<p>当前: {getModelLabel(selectedModel.value)} @ {scale.value}x</p>
		</div>
	</Fragment>)}
</div></Fragment>
  )
}
