import type { InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import type { SmartZipAction, SmartZipInput, SmartZipResult } from "./core.js"

export type SmartZipInteractionValues = InteractionValues & { action: SmartZipAction; pathsText: string; iniPath: string; databasePath: string; smartZipExe: string; smartZipAhk: string; autohotkeyExe: string; recordRun: boolean; dryRun: boolean }
export function createSmartZipInteractionSchema(defaults: Partial<SmartZipInteractionValues> = {}, language: TerminalLanguage = "zh"): TerminalInteractionSchema<SmartZipInput, SmartZipResult> {
  const zh = language === "zh"; const initialValues: SmartZipInteractionValues = { action: "status", pathsText: "", iniPath: "", databasePath: "", smartZipExe: "", smartZipAhk: "", autohotkeyExe: "AutoHotkey.exe", recordRun: false, dryRun: true, ...defaults }
  return { id: "smartzip", title: "SmartZip", description: zh ? "归档提取、压缩、打开与配置工作流。" : "Archive extract, compress, open and configuration workflow.", initialValues,
    fields: [{ id: "action", label: zh ? "归档动作" : "Archive action", kind: "select", options: [{ value: "status", label: zh ? "状态" : "Status" }, { value: "extract", label: zh ? "提取" : "Extract" }, { value: "extract_codepage", label: zh ? "编码提取" : "Codepage extract" }, { value: "open", label: zh ? "打开" : "Open" }, { value: "archive", label: zh ? "压缩" : "Archive" }, { value: "settings", label: zh ? "设置" : "Settings" }] }, { id: "pathsText", label: zh ? "归档路径" : "Archive paths", kind: "path-list", lines: 6, visibleWhen: (values) => values.action !== "status" && values.action !== "settings" }, { id: "iniPath", label: "SmartZip.ini", kind: "text" }, { id: "databasePath", label: zh ? "运行记录" : "Run database", kind: "text", visibleWhen: (values) => values.recordRun === true }, { id: "recordRun", label: zh ? "记录运行" : "Record run", kind: "boolean" }, { id: "dryRun", label: zh ? "预演" : "Dry-run", kind: "boolean", visibleWhen: (values) => values.action !== "status" && values.action !== "settings" }, { id: "smartZipExe", label: "SmartZip.exe", kind: "text" }, { id: "smartZipAhk", label: "SmartZip.ahk", kind: "text" }, { id: "autohotkeyExe", label: "AutoHotkey.exe", kind: "text" }],
    toInput: (values) => ({ action: values.action as SmartZipAction, paths: String(values.pathsText ?? "").split(/\r?\n/).map((path) => path.trim()).filter(Boolean), iniPath: String(values.iniPath ?? "") || undefined, databasePath: String(values.databasePath ?? "") || undefined, smartZipExe: String(values.smartZipExe ?? "") || undefined, smartZipAhk: String(values.smartZipAhk ?? "") || undefined, autohotkeyExe: String(values.autohotkeyExe ?? "") || undefined, recordRun: values.recordRun === true, dryRun: values.dryRun !== false }),
    validate: (values, input) => input.action !== "status" && input.action !== "settings" && !input.paths?.length ? (zh ? "至少输入一个归档路径。" : "Enter at least one archive path.") : null,
    preview: (input) => [`${zh ? "动作" : "Action"}: ${input.action}`, `${zh ? "路径" : "Paths"}: ${input.paths?.length ?? 0}`, input.dryRun ? (zh ? "预演：不会启动 SmartZip。" : "Dry-run: SmartZip will not start.") : (zh ? "真实执行：将启动 SmartZip。" : "Live run: SmartZip will launch.")],
    isDangerous: (input) => input.action !== "status" && input.action !== "settings" && input.dryRun === false,
    result: (result) => ({ success: result.success, message: result.message, lines: result.data?.errors ?? [], table: { columns: [{ id: "path", label: zh ? "路径" : "Path", width: 44 }], rows: (result.data?.selectedPaths ?? []).map((path) => ({ path })), emptyMessage: result.message } }),
  }
}
