import { expect, test } from "@playwright/test"

test.use({ viewport: { width: 1920, height: 1080 } })

test("[neoview.page-transition.ui] [neoview.page-transition.ui-1920x1080] [neoview.page-transition.image-identity] keeps the animation switch interactive and stable", async ({ page }, testInfo) => {
  await page.route(/^https:\/\/fonts\.(?:googleapis|gstatic)\.com\//, (route) => route.abort())
  await page.goto("/tests/e2e/neoview/neoview-page-transition-harness.html", { waitUntil: "domcontentloaded" })
  await expect(page).toHaveTitle("NeoView Page Transition Harness")
  const image = page.locator('[data-reader-page-image="page-0"]')
  await expect(image).toBeVisible()
  await image.evaluate((element) => { (window as typeof window & { __originalPageTransitionImage?: Element }).__originalPageTransitionImage = element })
  const originalSource = await image.getAttribute("src")
  await page.getByRole("checkbox", { name: "启用翻页动画" }).click()
  await page.getByLabel("动画类型").selectOption("slide")
  const duration = page.getByRole("slider", { name: "动画时长" })
  await duration.focus()
  await duration.press("ArrowRight")
  await expect.poll(() => page.locator("html").getAttribute("data-page-transition-writes")).toBe("3")
  expect(await image.evaluate((element) => (window as typeof window & { __originalPageTransitionImage?: Element }).__originalPageTransitionImage === element)).toBe(true)
  expect(await image.getAttribute("src")).toBe(originalSource)
  await page.getByRole("button", { name: "下一页" }).click()
  const layer = page.locator("[data-reader-page-transition-layer]")
  await expect(layer).toHaveAttribute("data-reader-page-transition-direction", "next")
  await expect.poll(() => layer.getAttribute("data-reader-page-transition-direction")).toBeNull()
  await page.screenshot({ path: testInfo.outputPath("neoview-page-transition-1920x1080.png"), fullPage: false })
})
