import { expect, test } from "@playwright/test"

test("[neoview.history.ui-1920x1080] [neoview.history.search-sort-e2e] preserves the shared file view controls and server query boundary", async ({ page }, testInfo) => {
  const runtimeErrors: string[] = []
  page.on("console", (message) => { if (message.type() === "error") runtimeErrors.push(message.text()) })
  page.on("pageerror", (error) => runtimeErrors.push(error.message))
  await page.setViewportSize(testInfo.project.name === "chromium-card" ? { width: 420, height: 360 } : { width: 1920, height: 1080 })
  await page.route(/^https:\/\/fonts\.(?:googleapis|gstatic)\.com\//, (route) => route.abort())
  await page.goto("/tests/e2e/neoview/neoview-history-list-harness.html", { waitUntil: "domcontentloaded" })
  await expect(page).toHaveTitle("NeoView History List Harness")
  await expect(page.locator("vite-error-overlay")).toHaveCount(0)
  const card = page.getByTestId("history-card")
  await expect(card).toHaveAttribute("data-history-state", "ready")
  await expect(card.getByRole("listbox", { name: "阅读历史" })).toBeVisible()
  await expect(card.locator('[data-history-id]')).toHaveCount(3)
  await expect(card).toHaveAttribute("data-history-view-mode", "cover-grid")
  await expect(card.getByRole("button", { name: "视图：封面网格" })).toBeVisible()
  await card.getByRole("textbox", { name: "搜索历史记录视图" }).fill("beta")
  await expect(card.locator('[data-history-id]')).toHaveCount(1)
  await expect(card.locator('[data-history-id="history-2"]')).toBeVisible()
  await card.getByRole("button", { name: "排序：时间 · 降序" }).click()
  await page.getByRole("menuitemradio", { name: "名称" }).click()
  await expect(card.getByRole("button", { name: "排序：名称 · 降序" })).toBeVisible()
  await card.getByRole("button", { name: "视图：封面网格" }).click()
  await page.getByRole("menuitemradio", { name: "横幅" }).click()
  await expect(card).toHaveAttribute("data-history-view-mode", "mosaic-list")
  await expect(page.locator("[data-history-view-overrides]")).toHaveText(/mosaic-list/)
  await card.getByRole("button", { name: "视图：横幅" }).click()
  await page.getByRole("menuitem", { name: "跟随 File Card 视图" }).click()
  await expect(card).toHaveAttribute("data-history-view-mode", "cover-grid")
  await expect(page.locator("[data-history-view-overrides]")).toHaveText("{}")
  await card.getByRole("button", { name: "更多" }).click()
  await expect(page.getByText("项目尺寸", { exact: true })).toBeVisible()
  const thumbnailWidth = page.getByRole("slider", { name: "缩略图宽度" })
  await expect(thumbnailWidth).toHaveAttribute("aria-valuenow", "28")
  await thumbnailWidth.press("ArrowRight")
  await expect(page.locator("[data-history-view-overrides]")).toHaveText(/thumbnailWidthPercent.*29/)
  await page.getByRole("button", { name: "恢复继承的缩略图宽度" }).click()
  await expect(page.locator("[data-history-view-overrides]")).toHaveText("{}")
  await expect(thumbnailWidth).toHaveAttribute("aria-valuenow", "28")
  await page.screenshot({ path: testInfo.outputPath("neoview-history-list-1920x1080.png"), fullPage: false })
  expect(runtimeErrors).toEqual([])
})
