import { expect, test, type Page } from "@playwright/test"

const HARNESS = "/tests/e2e/neoview/neoview-swimlane-workspace-harness.html"

test("[neoview.swimlane.preview-resize-e2e] keeps an auto-revealed side lane open on its divider", async ({ page }, testInfo) => {
  await openHarness(page, { width: 1920, height: 1080 })
  await page.locator('[data-reader-breadcrumb-bar="true"]').getByRole("button", { name: "泳道模式" }).click()
  const workspace = page.locator('[data-neoview-workspace-mode="swimlane"]')
  const rightLane = page.locator('[data-reader-swimlane="right"]')
  await page.locator('[data-reader-swimlane-trigger="right"]').hover()
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "right")

  const divider = page.getByRole("separator", { name: "调整阅读器与右侧面板泳道宽度" })
  await divider.hover()
  await page.waitForTimeout(500)
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "right")
  await expect(divider).toBeVisible()

  const initialWidth = await rightLane.evaluate((lane) => lane.getBoundingClientRect().width)
  await dragHorizontally(page, divider, -40)
  await expect(rightLane).toHaveJSProperty("offsetWidth", initialWidth + 40)
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "right")
  await page.screenshot({ path: testInfo.outputPath("neoview-swimlane-preview-resize-1920x1080.png") })
})

test("[neoview.swimlane.preview-resize-anchor-e2e] keeps the left divider under the pointer after release", async ({ page }) => {
  await openHarness(page, { width: 1920, height: 1080 })
  await page.locator('[data-reader-breadcrumb-bar="true"]').getByRole("button", { name: "泳道模式" }).click()
  const workspace = page.locator('[data-neoview-workspace-mode="swimlane"]')
  await page.locator('[data-reader-swimlane-trigger="left"]').hover()
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "left")
  const divider = page.getByRole("separator", { name: "调整左侧面板与阅读器泳道宽度" })
  await divider.hover()
  const box = await divider.boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await page.mouse.down()
  await page.mouse.move(box!.x - 40, box!.y + box!.height / 2, { steps: 8 })
  const beforeRelease = await divider.evaluate((node) => node.getBoundingClientRect().x)
  await page.mouse.up()
  await page.waitForTimeout(300)
  const afterRelease = await divider.evaluate((node) => node.getBoundingClientRect().x)
  expect(Math.abs(afterRelease - beforeRelease)).toBeLessThanOrEqual(1)
})

test("[neoview.swimlane.width-profiles-e2e] restores widths by orientation and Reader fullscreen state", async ({ page }) => {
  await openHarness(page, { width: 1920, height: 1080 })
  await page.locator('[data-reader-breadcrumb-bar="true"]').getByRole("button", { name: "泳道模式" }).click()
  const workspace = page.locator('[data-neoview-workspace-mode="swimlane"]')
  const rightLane = page.locator('[data-reader-swimlane="right"]')
  await page.locator('[data-reader-swimlane-trigger="right"]').hover()
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "right")
  let divider = page.getByRole("separator", { name: "调整阅读器与右侧面板泳道宽度" })
  await dragHorizontally(page, divider, -40)
  await expect(rightLane).toHaveJSProperty("offsetWidth", 420)

  await page.setViewportSize({ width: 700, height: 1000 })
  await expect(rightLane).toHaveJSProperty("offsetWidth", 380)
  await page.setViewportSize({ width: 1920, height: 1080 })
  await expect(rightLane).toHaveJSProperty("offsetWidth", 420)

  await page.getByRole("button", { name: "阅读器更多设置" }).click()
  await page.getByRole("menuitem", { name: "退出全屏" }).click()
  await expect(rightLane).toHaveJSProperty("offsetWidth", 380)
  divider = page.getByRole("separator", { name: "调整阅读器与右侧面板泳道宽度" })
  await dragHorizontally(page, divider, -30)
  const landscapeNormalWidth = await rightLane.evaluate((lane) => lane.getBoundingClientRect().width)
  expect(landscapeNormalWidth).toBeGreaterThan(380)
  expect(landscapeNormalWidth).not.toBe(420)

  await page.getByRole("button", { name: "阅读器更多设置" }).click()
  await page.getByRole("menuitem", { name: "当前泳道全屏" }).click()
  await expect(rightLane).toHaveJSProperty("offsetWidth", 420)
})

test("[neoview.swimlane.workspace-e2e] keeps flat reveal, Reader focus and fused chrome", async ({ page }, testInfo) => {
  await openHarness(page, { width: 1920, height: 1080 })
  const breadcrumb = page.locator('[data-reader-breadcrumb-bar="true"]')
  await expect(page.locator('[data-neoview-workspace-mode="edges"]')).toBeVisible()
  await expect(breadcrumb.getByRole("button", { name: "泳道模式" })).toBeVisible()
  await expect(breadcrumb.locator("[data-window-caption-button]")).toHaveCount(3)

  await breadcrumb.getByRole("button", { name: "泳道模式" }).click()
  const workspace = page.locator('[data-neoview-workspace-mode="swimlane"]')
  const viewport = page.locator('[data-reader-swimlane-viewport="true"]')
  const readerLane = page.locator('[data-reader-swimlane="reader"]')
  await expect(workspace).toBeVisible()
  await expect(readerLane.locator('[data-reader-swimlane-header="reader"]')).toBeVisible()
  await expect(readerLane).toHaveJSProperty("offsetWidth", 1920)
  const readerViewFullscreen = readerLane.getByRole("button", { name: "Reader 视图全屏" })
  await expect(readerViewFullscreen.locator("svg.lucide-scan")).toBeVisible()
  await readerViewFullscreen.click()
  await expect(readerLane.locator('[data-reader-swimlane-header="reader"]')).toHaveCount(0)
  await expect(readerLane).toHaveAttribute("data-reader-view-fullscreen", "true")
  await expect(readerLane).toHaveCSS("border-top-width", "0px")
  await expect(readerLane).toHaveCSS("border-right-width", "0px")
  await expect(readerLane).toHaveCSS("border-bottom-width", "0px")
  await expect(readerLane).toHaveCSS("border-left-width", "0px")
  await expect(readerLane).toHaveCSS("box-shadow", "none")
  await expect.poll(() => page.evaluate(() => document.fullscreenElement)).toBeNull()
  const exitReaderViewFullscreen = breadcrumb.getByRole("button", { name: "退出 Reader 视图全屏" })
  await expect(exitReaderViewFullscreen.locator("svg.lucide-scan")).toBeVisible()
  await exitReaderViewFullscreen.click()
  await expect(readerLane.locator('[data-reader-swimlane-header="reader"]')).toBeVisible()
  await expect(readerLane).not.toHaveAttribute("data-reader-view-fullscreen", "true")

  await page.locator('[data-reader-swimlane-trigger="right"]').hover()
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "right")
  await expect.poll(() => viewport.evaluate((node) => node.scrollLeft)).toBeGreaterThan(0)
  await page.getByRole("button", { name: "书籍信息" }).click()
  await expect(page.locator('[data-reader-swimlane="right"]')).toHaveAttribute("data-reader-swimlane-active", "true")
  await expect(readerLane).toHaveJSProperty("offsetWidth", 1920)
  await expect(page.locator('[data-reader-swimlane="right"]')).toHaveJSProperty("offsetWidth", 380)
  await expect(readerLane.locator('[data-reader-swimlane-header="reader"]')).toBeVisible()
  const rightEdgeBeforeResize = await page.locator('[data-reader-swimlane="right"]').evaluate((lane) => lane.getBoundingClientRect().right)
  await dragHorizontally(page, page.getByRole("separator", { name: "调整阅读器与右侧面板泳道宽度" }), -40)
  await expect(page.locator('[data-reader-swimlane="right"]')).toHaveJSProperty("offsetWidth", 420)
  const rightEdgeAfterResize = await page.locator('[data-reader-swimlane="right"]').evaluate((lane) => lane.getBoundingClientRect().right)
  expect(rightEdgeAfterResize).toBeCloseTo(rightEdgeBeforeResize, 0)

  const readerAction = page.getByRole("button", { name: /Reader 操作/ })
  const beforeClick = await readerAction.getAttribute("data-reader-action-count")
  await readerAction.click()
  await expect(readerLane).toHaveAttribute("data-reader-swimlane-active", "true")
  await expect(readerAction).toHaveAttribute("data-reader-action-count", beforeClick ?? "0")

  await page.locator('[data-reader-swimlane-trigger="right"]').hover()
  await page.getByRole("button", { name: "书籍信息" }).click()
  await readerLane.hover()
  await page.waitForTimeout(700)
  await expect(readerLane).toHaveAttribute("data-reader-swimlane-active", "true")

  const topTrigger = page.locator('[data-reader-edge-trigger="top"]')
  const bottomTrigger = page.locator('[data-reader-edge-trigger="bottom"]')
  await topTrigger.hover()
  await expect(page.locator('[data-reader-edge="top"]')).toHaveAttribute("data-reader-edge-visible", "true")
  await readerLane.hover()
  await page.waitForTimeout(400)
  await bottomTrigger.hover()
  await expect(page.locator('[data-reader-edge="bottom"]')).toHaveAttribute("data-reader-edge-visible", "true")

  await page.locator('[data-reader-swimlane-trigger="left"]').hover()
  await expect(workspace).toHaveAttribute("data-reader-swimlane-preview", "left")
  await page.getByRole("button", { name: "文件夹" }).click()
  await expect(page.locator('[data-reader-swimlane="left"]')).toHaveAttribute("data-reader-swimlane-active", "true")
  await dragHorizontally(page, page.getByRole("separator", { name: "调整左侧面板与阅读器泳道宽度" }), 40)
  await expect(page.locator('[data-reader-swimlane="left"]')).toHaveJSProperty("offsetWidth", 380)
  await page.screenshot({ path: testInfo.outputPath("neoview-swimlane-focus-1920x1080.png") })
})

test("[neoview.swimlane.drag-e2e] freezes Reader width and docks the panel bar", async ({ page }, testInfo) => {
  await openOrdinarySwimlane(page)
  const readerLane = page.locator('[data-reader-swimlane="reader"]')
  const rightLane = page.locator('[data-reader-swimlane="right"]')
  const windowDragHeaders = page.locator('[data-reader-window-drag-region="true"]')
  const windowChromeOwner = page.locator('[data-reader-window-controls-owner]')
  const rightBar = page.locator('[data-reader-panel-bar="right"]')
  const rightHandle = rightBar.getByRole("button", { name: "拖动或设置面板操作栏" })
  await expect(windowDragHeaders).toHaveCount(3)
  await expect.poll(() => windowDragHeaders.evaluateAll((headers) => headers.every((header) => (
    getComputedStyle(header).getPropertyValue("--wails-draggable").trim() === "drag"
  )))).toBe(true)
  await expect(windowChromeOwner).toHaveCount(1)
  await expect(windowChromeOwner).toHaveAttribute("data-reader-window-controls-owner", "right")
  await expect(page.getByTestId("floating-window-integrated-controls")).toHaveCount(0)
  const chrome = windowChromeOwner.locator('[data-reader-swimlane-window-chrome="true"]')
  const compactWindowControls = windowChromeOwner.getByTestId("floating-window-integrated-controls")
  await expect(compactWindowControls).toHaveAttribute("data-window-caption-density", "compact")
  await expect(chrome).toHaveAttribute("data-reader-window-controls-expanded", "false")
  await expect(compactWindowControls.locator('[data-window-caption-button]:visible')).toHaveCount(1)
  await expect(compactWindowControls.locator('[data-window-control-action="close"]')).toBeVisible()
  await chrome.hover()
  await expect(chrome).toHaveAttribute("data-reader-window-controls-expanded", "true")
  await expect(compactWindowControls.locator('[data-window-caption-button]:visible')).toHaveCount(3)
  await expect.poll(() => compactWindowControls.locator('[data-window-caption-button]:visible').evaluateAll((buttons) => buttons.every((button) => {
    const box = button.getBoundingClientRect()
    return box.width === 32 && box.height <= 28
  }))).toBe(true)
  await compactWindowControls.locator('[data-window-control-action="minimize"]').hover()
  await page.waitForTimeout(250)
  await expect(chrome).toHaveAttribute("data-reader-window-controls-expanded", "true")
  await rightHandle.hover()
  await expect(chrome).toHaveAttribute("data-reader-window-controls-expanded", "false")
  await expect.poll(() => rightHandle.evaluate((handle) => (
    getComputedStyle(handle).getPropertyValue("--wails-draggable").trim()
  ))).toBe("no-drag")
  const rightLaneBox = await rightLane.boundingBox()
  const rightHandleBox = await rightHandle.boundingBox()
  expect(rightLaneBox).not.toBeNull()
  expect(rightHandleBox).not.toBeNull()

  await page.mouse.move(rightHandleBox!.x + rightHandleBox!.width / 2, rightHandleBox!.y + rightHandleBox!.height / 2)
  await page.mouse.down()
  await page.mouse.move(rightLaneBox!.x + rightLaneBox!.width / 2, rightLaneBox!.y + rightLaneBox!.height - 8, { steps: 6 })
  await page.mouse.up()
  await expect(rightBar).toHaveAttribute("data-reader-panel-bar-dock", "bottom")
  await expect(rightBar).toHaveClass(/flex-row/)

  const separator = page.getByRole("separator", { name: "调整阅读器与右侧面板泳道宽度" })
  const box = await separator.boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + 120)
  await page.mouse.down()
  await page.mouse.move(box!.x + 100, box!.y + 120, { steps: 4 })
  await page.mouse.up()
  const releasedWidth = await readerLane.evaluate((node) => node.getBoundingClientRect().width)
  await page.mouse.move(box!.x + 220, box!.y + 120)
  await page.waitForTimeout(80)
  expect(await readerLane.evaluate((node) => node.getBoundingClientRect().width)).toBeCloseTo(releasedWidth, 0)

  await page.getByRole("button", { name: "右侧面板更多设置" }).click()
  await page.getByRole("menuitemcheckbox", { name: "使用顶部窗口标题栏" }).click()
  const windowTitlebar = page.locator('[data-reader-window-titlebar="true"]')
  await expect(windowTitlebar).toBeVisible()
  await expect.poll(() => windowTitlebar.evaluate((node) => node.getBoundingClientRect().height)).toBe(28)
  await expect.poll(() => windowTitlebar.evaluate((node) => getComputedStyle(node).getPropertyValue("--wails-draggable").trim())).toBe("drag")
  await expect.poll(() => windowTitlebar.locator('[data-reader-window-titlebar-control-slot="true"]').evaluate((node) => getComputedStyle(node).getPropertyValue("--wails-draggable").trim())).toBe("drag")
  await page.getByRole("button", { name: "右侧面板更多设置" }).click()
  await page.getByRole("menuitem", { name: "展开窗口按钮" }).click()
  await expect(windowTitlebar.locator('[data-reader-window-controls-pinned="true"]')).toBeVisible()
  const navigator = page.locator('[data-reader-lane-navigator="true"]')
  await openNavigatorMenu(navigator)
  await page.getByRole("menuitem", { name: "固定到窗口标题栏" }).click()
  await expect(windowTitlebar.locator('[data-reader-lane-navigator="true"]')).toBeVisible()
  await openNavigatorMenu(navigator)
  await page.getByRole("menuitem", { name: "固定到 Reader 标题栏" }).click()
  await expect(page.locator('[data-reader-lane-navigator-title-slot="true"] [data-reader-lane-navigator="true"]')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath("neoview-swimlane-shared-divider-1920x1080.png") })
})

test("[neoview.swimlane.portrait-e2e] adds lanes, fits proportions and stays bounded in portrait", async ({ page }, testInfo) => {
  await openOrdinarySwimlane(page)
  const breadcrumb = page.locator('[data-reader-breadcrumb-bar="true"]')
  const readerLane = page.locator('[data-reader-swimlane="reader"]')
  const navigator = page.locator('[data-reader-lane-navigator="true"]')

  await openNavigatorMenu(navigator)
  await page.getByRole("menuitem", { name: "添加泳道" }).click()
  await page.getByRole("textbox", { name: "泳道名称" }).fill("资料")
  await page.getByRole("button", { name: "确认添加泳道" }).click()
  await expect(page.locator("[data-reader-swimlane]")).toHaveCount(4)
  await expect(navigator.getByRole("button", { name: "定位资料泳道" })).toBeVisible()

  const widthsBeforeFit = await laneWidths(page)
  await openNavigatorMenu(navigator)
  await page.getByRole("menuitem", { name: "按当前比例填满视口" }).click()
  await expect.poll(async () => (await laneWidths(page)).reduce((sum, width) => sum + width, 0)).toBeCloseTo(1920, 0)
  const fittedWidths = await laneWidths(page)
  const factors = fittedWidths.map((width, index) => width / widthsBeforeFit[index]!)
  expect(Math.max(...factors) - Math.min(...factors)).toBeLessThan(0.01)

  await openNavigatorMenu(navigator)
  await page.getByRole("menuitemcheckbox", { name: "Reader 独占时显示" }).click()
  await page.getByRole("button", { name: "阅读器更多设置" }).click()
  await page.getByRole("menuitem", { name: "当前泳道全屏" }).click()
  await expect(navigator).toBeVisible()
  await page.getByRole("button", { name: "阅读器更多设置" }).click()
  await page.getByRole("menuitem", { name: "退出全屏" }).click()

  await page.setViewportSize({ width: 600, height: 900 })
  await expect.poll(() => readerLane.evaluate((node) => node.getBoundingClientRect().width)).toBeLessThanOrEqual(600)
  await openNavigatorMenu(navigator)
  await page.getByRole("menuitem", { name: "按当前比例填满视口" }).click()
  await expect.poll(async () => (await laneWidths(page)).reduce((sum, width) => sum + width, 0)).toBeCloseTo(600, 0)
  const navigatorBox = await navigator.boundingBox()
  expect(navigatorBox).not.toBeNull()
  expect(navigatorBox!.x).toBeGreaterThanOrEqual(0)
  expect(navigatorBox!.x + navigatorBox!.width).toBeLessThanOrEqual(600)
  await page.screenshot({ path: testInfo.outputPath("neoview-swimlane-portrait-600x900.png") })

  await page.getByRole("button", { name: "阅读器更多设置" }).click()
  await page.getByRole("menuitem", { name: "当前泳道全屏" }).click()
  await expect(readerLane).toHaveJSProperty("offsetWidth", 600)
  await breadcrumb.getByRole("button", { name: "四边栏模式" }).click()
  await expect(page.locator('[data-neoview-workspace-mode="edges"]')).toBeVisible()
})

async function openHarness(page: Page, viewport: { width: number; height: number }) {
  test.setTimeout(45_000)
  await page.setViewportSize(viewport)
  await page.goto(HARNESS, { waitUntil: "domcontentloaded" })
  await expect(page).toHaveTitle("NeoView Swimlane Workspace Harness")
}

async function openOrdinarySwimlane(page: Page) {
  await openHarness(page, { width: 1920, height: 1080 })
  const breadcrumb = page.locator('[data-reader-breadcrumb-bar="true"]')
  await breadcrumb.getByRole("button", { name: "泳道模式" }).click()
  await page.getByRole("button", { name: "阅读器更多设置" }).click()
  await page.getByRole("menuitem", { name: "退出全屏" }).click()
  await expect(page.locator('[data-reader-swimlane-header="reader"]')).toBeVisible()
}

async function laneWidths(page: Page): Promise<number[]> {
  return await page.locator("[data-reader-swimlane]").evaluateAll((lanes) => lanes.map((lane) => lane.getBoundingClientRect().width))
}

async function dragHorizontally(page: Page, handle: import("@playwright/test").Locator, deltaX: number) {
  const box = await handle.boundingBox()
  expect(box).not.toBeNull()
  const x = box!.x + box!.width / 2
  const y = box!.y + Math.min(120, box!.height / 2)
  await page.mouse.move(x, y)
  await page.mouse.down()
  await page.mouse.move(x + deltaX, y, { steps: 4 })
  await page.mouse.up()
}

async function openNavigatorMenu(navigator: import("@playwright/test").Locator) {
  await navigator.getByRole("button", { name: "拖动或设置泳道切换栏" }).click({ button: "right" })
}
