import { expect, test } from "@playwright/test"

test("[neoview.bookmark.ui-1920x1080] [neoview.bookmark.search-sort-e2e] preserves shared file views and searches before paging", async ({ page }, testInfo) => {
  const runtimeErrors: string[] = []
  page.on("console", (message) => { if (message.type() === "error") runtimeErrors.push(message.text()) })
  page.on("pageerror", (error) => runtimeErrors.push(error.message))
  await page.setViewportSize(testInfo.project.name === "chromium-card" ? { width: 420, height: 360 } : { width: 1920, height: 1080 })
  await page.route(/^https:\/\/fonts\.(?:googleapis|gstatic)\.com\//, (route) => route.abort())
  await page.goto("/tests/e2e/neoview/neoview-bookmark-list-harness.html", { waitUntil: "domcontentloaded" })
  await expect(page).toHaveTitle("NeoView Bookmark List Harness")
  await expect(page.locator("vite-error-overlay")).toHaveCount(0)
  const card = page.getByTestId("bookmark-card")
  await expect(card).toHaveAttribute("data-bookmark-state", "ready")
  await expect(card.locator('[aria-label="书签列表"]')).toBeVisible()
  await expect(card.locator('[data-neoview-library-list^="bookmarks:all:"]')).toBeVisible()
  await expect(card.locator('[data-bookmark-id]')).toHaveCount(3)
  await expect(card).toHaveAttribute("data-bookmark-view-mode", "cover-grid")
  await expect(card.getByRole("button", { name: "视图：封面网格" })).toBeVisible()
  await card.getByRole("textbox", { name: "搜索书签视图" }).fill("series")
  await expect(card.locator('[data-bookmark-id]')).toHaveCount(1)
  await expect(card.locator('[data-bookmark-id="bookmark-3"]')).toBeVisible()
  await card.getByRole("button", { name: "排序：时间 · 降序" }).click()
  await page.getByRole("menuitemradio", { name: "路径" }).click()
  await expect(card.getByRole("button", { name: "排序：路径 · 降序" })).toBeVisible()
  await card.getByRole("button", { name: "视图：封面网格" }).click()
  await expect(page.getByRole("menuitem", { name: "跟随 File Card 视图" })).toBeVisible()
  await page.keyboard.press("Escape")
  await card.getByRole("button", { name: "更多" }).click()
  await expect(page.getByText("项目尺寸", { exact: true })).toBeVisible()
  await expect(page.locator("#root")).not.toHaveAttribute("aria-hidden", "true")
  await expect(page.getByRole("slider", { name: "缩略图宽度" })).toHaveAttribute("aria-valuenow", "28")
  await expect(page.locator("[data-bookmark-view-overrides]")).toHaveText("{}")
  await page.screenshot({ path: testInfo.outputPath("neoview-bookmark-list-1920x1080.png"), fullPage: false })
  expect(runtimeErrors).toEqual([])
})
