/**
 * @migrated-from src/lib/cards/bookmark/BookmarkListCard.svelte
 * @source-hash sha256:b3a57872754ed639fbf37e45996432da3a4c454cb1ce44b8264ff5fdd074c36f
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { FileListPanel } from '$lib/cards/shared';
import { VIRTUAL_PATHS } from '$lib/components/panels/folderPanel/stores/folderTabStore';

export function BookmarkListCard() {
  return (
    <Fragment>

{/*  使用共享的文件列表面板  */}
<FileListPanel initialPath={VIRTUAL_PATHS.BOOKMARK} mode="bookmark"></FileListPanel></Fragment>
  )
}
