import type { InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { RepackuAction, RepackuInput, RepackuResult } from "./core.js"

export type RepackuInteractionValues = InteractionValues & { action: RepackuAction; pathsText: string; configPath: string; types: string; outputPath: string; deleteAfter: boolean; dryRun: boolean; minCount: number; galleryMarker: string }

export function createRepackuInteractionSchema(defaults: Partial<RepackuInteractionValues> = {}, language = "zh"): TerminalInteractionSchema<RepackuInput, RepackuResult> {
  const zh = language === "zh", initialValues: RepackuInteractionValues = { action: "full", pathsText: "", configPath: "", types: "image", outputPath: "", deleteAfter: false, dryRun: true, minCount: 2, galleryMarker: "画集", ...defaults }
  return { id: "repacku", title: "RepackU", description: zh ? "分析目录树并生成安全的重打包计划。" : "Analyze folder trees and create safe repacking plans.", initialValues,
    fields: [{ id: "action", label: zh ? "工作流" : "Workflow", kind: "select", options: [{ value: "analyze", label: zh ? "分析" : "Analyze" }, { value: "compress", label: zh ? "压缩" : "Compress" }, { value: "full", label: zh ? "完整流程" : "Full flow" }, { value: "single-pack", label: zh ? "单层打包" : "Single pack" }, { value: "gallery-pack", label: zh ? "画集打包" : "Gallery pack" }] }, { id: "pathsText", label: zh ? "文件夹路径" : "Folder paths", kind: "path-list", lines: 5 }, { id: "types", label: zh ? "目标类型" : "Target types", kind: "text" }, { id: "minCount", label: zh ? "最少文件数" : "Minimum files", kind: "number", min: 1, max: 9999 }, { id: "outputPath", label: zh ? "配置输出" : "Config output", kind: "text" }, { id: "configPath", label: zh ? "配置路径" : "Config path", kind: "text" }, { id: "galleryMarker", label: zh ? "画集标记" : "Gallery marker", kind: "text" }, { id: "deleteAfter", label: zh ? "成功后删除源文件" : "Delete sources", kind: "boolean" }, { id: "dryRun", label: zh ? "预演" : "Dry-run", kind: "boolean" }],
    toInput: v => ({ action: v.action as RepackuAction, paths: String(v.pathsText ?? "").split(/[\r\n;]+/).map(x => x.trim()).filter(Boolean), configPath: String(v.configPath || "") || undefined, types: String(v.types || "") || undefined, outputPath: String(v.outputPath || "") || undefined, deleteAfter: v.deleteAfter === true, dryRun: v.dryRun !== false, minCount: Number(v.minCount) || 2, galleryMarker: String(v.galleryMarker || "") || undefined }),
    validate: (_v, i) => i.action === "compress" ? (i.configPath || i.paths?.length ? null : (zh ? "压缩需要配置路径或文件夹路径。" : "Compress needs a config or folder.")) : (i.paths?.length ? null : (zh ? "至少输入一个文件夹路径。" : "Enter a folder path.")),
    preview: i => [`${zh ? "流程" : "Workflow"}: ${i.action}`, `${zh ? "路径" : "Paths"}: ${i.paths?.length ?? 0}`, i.dryRun ? (zh ? "预演：不写入归档。" : "Dry-run: no archives written.") : (zh ? "真实执行：会写入归档。" : "Live: archives will be written.")], isDangerous: i => i.dryRun === false || i.deleteAfter === true,
    result: r => ({ success: r.success, message: r.message, lines: r.data?.errors ?? [], table: { columns: [{ id: "sourcePath", label: zh ? "源路径" : "Source", width: 42 }, { id: "targetPath", label: zh ? "目标归档" : "Archive", width: 42 }], rows: (r.data?.operations ?? []).map(x => ({ sourcePath: x.sourcePath, targetPath: x.targetPath })), emptyMessage: r.message } }) }
}
