/**
 * @migrated-from src/lib/cards/settings/DataSettingsCard.svelte
 * @source-hash sha256:a019057db504300a28d10586463994f516eda675975c973051799a68b1d410dc
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import DataSettingsPanel from '$lib/components/panels/DataSettingsPanel.js';

export function DataSettingsCard() {
  return (
    <Fragment>

<div className="settings-card-wrapper">
	<DataSettingsPanel></DataSettingsPanel>
</div>

</Fragment>
  )
}
