#!/usr/bin/env node
import { hasPipedInput, nodeCliName, readStdinLines, runGuidedInteraction, writeError, writeJson, writeLine, type CliCommand, type CliHost } from "@xiranite/cli-runtime"
import { resolveInteractionPreferences, type CliInteractionPreferencesSource, type TerminalInteractionDefinition } from "@xiranite/cli-runtime/interaction"
import { resolveTerminalLanguage, type TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import { runInteractionCli, runTerminalUi, type TerminalPreferenceController, type TerminalPreferenceValues } from "@xiranite/cli-runtime/terminal"
import { loadNodeConfigWithHints, loadXiraniteConfig, saveXiraniteConfig, updateNodeConfig } from "@xiranite/config"
import { runXlchemy, type XlchemyAction, type XlchemyExistingPolicy, type XlchemyFormat, type XlchemyInput, type XlchemyResult } from "./core.js"
import { help } from "./help.js"
import { createXlchemyInteractionSchema } from "./interaction.js"
import { createNodeXlchemyRuntime } from "./platform.js"

interface XlchemyNodeConfig { format?: XlchemyFormat; quality?: number; effort?: number; threads?: number; lossless?: boolean; output_dir?: string; existing_policy?: XlchemyExistingPolicy; preserve_metadata?: boolean; preserve_structure?: boolean; preserve_timestamps?: boolean; recursive?: boolean }
interface XlchemyCliConfig extends CliInteractionPreferencesSource, XlchemyNodeConfig {}
const CLI_NAME = nodeCliName("xlchemy")
export const cli: CliCommand = { name: CLI_NAME, description: "Plan and run native image transcoding batches.", run: (args, host) => runProgram(args, host) }

export async function runProgram(args = process.argv.slice(2), host: CliHost = defaultHost()): Promise<void> {
  await runInteractionCli({ args, host, cliName: CLI_NAME, loadContext: async () => { const { config } = await loadNodeConfigWithHints<XlchemyCliConfig>("xlchemy", { env: host.env, cwd: host.cwd, hintSink: { stderr: host.stderr }, jsonMode: true }); return { preferences: resolveInteractionPreferences(config), value: config ?? {} } }, createDefinition: (defaults, language) => definition(defaults, language), runPipe, runGuide: runGuidedInteraction, runUi: runTerminalUi, loadScreen: async () => (await import("./Tui.js")).XlchemyTui, createPreferences: (_defaults, values) => preferences(host, values), reexecEntrypoint: process.argv[1], help })
}
function definition(defaults: XlchemyNodeConfig, language: TerminalLanguage): TerminalInteractionDefinition<XlchemyInput, XlchemyResult> { return { schema: createXlchemyInteractionSchema({ format: defaults.format, quality: defaults.quality, effort: defaults.effort, threads: defaults.threads, lossless: defaults.lossless, outputDir: defaults.output_dir, existingPolicy: defaults.existing_policy, preserveMetadata: defaults.preserve_metadata, preserveStructure: defaults.preserve_structure, preserveTimestamps: defaults.preserve_timestamps, recursive: defaults.recursive }, language), run: (input, onEvent) => runXlchemy(input, createNodeXlchemyRuntime(), onEvent) } }
async function runPipe(args: string[], host: CliHost) { const json = args.includes("--json"), action: XlchemyAction = args.includes("convert") ? "convert" : "plan"; const { config } = await loadNodeConfigWithHints<XlchemyNodeConfig>("xlchemy", { env: host.env, cwd: host.cwd, hintSink: { stderr: host.stderr }, jsonMode: json }); let paths = positional(args); if (paths.includes("-") || (!paths.length && hasPipedInput(host.stdin))) paths = paths.filter((path) => path !== "-").concat(await readStdinLines(host.stdin)); const input: XlchemyInput = { action, paths, format: (value(args, "--format") as XlchemyFormat | undefined) ?? config?.format ?? "JPEG XL", lossless: args.includes("--lossless") || config?.lossless === true, quality: numberValue(args, "--quality") ?? config?.quality ?? 90, effort: numberValue(args, "--effort") ?? config?.effort ?? 7, threads: numberValue(args, "--threads") ?? config?.threads ?? 4, outputMode: value(args, "--output") ? "directory" : "source", outputDir: value(args, "--output") ?? config?.output_dir, existingPolicy: (value(args, "--existing") as XlchemyExistingPolicy | undefined) ?? config?.existing_policy ?? "skip", overwrite: args.includes("--overwrite"), preserveMetadata: !args.includes("--strip-metadata") && config?.preserve_metadata !== false, preserveStructure: !args.includes("--flat") && config?.preserve_structure !== false, preserveTimestamps: args.includes("--timestamps") || config?.preserve_timestamps === true, recursive: !args.includes("--no-recursive") && config?.recursive !== false, deleteOriginal: args.includes("--delete-original") }; const result = await runXlchemy(input, createNodeXlchemyRuntime()); if (json) writeJson(host, result); else { writeLine(host, result.message); for (const file of result.data?.files ?? []) writeLine(host, `${file.status}\t${file.sourcePath}\t->\t${file.outputPath}`) } if (!result.success) process.exitCode = 1 }
function preferences(host: CliHost, current: TerminalPreferenceValues): TerminalPreferenceController { const options = { env: host.env, cwd: host.cwd }; return { nodeId: "xlchemy", current, async save(values) { const { config, path } = await loadXiraniteConfig(options); await saveXiraniteConfig(updateNodeConfig(config, "xlchemy", { cli: { theme: values.theme, default_mode: values.defaultMode, language: values.language } }), { ...options, configPath: path }) }, async restore() { const { config } = await loadNodeConfigWithHints<XlchemyCliConfig>("xlchemy", { ...options, jsonMode: true }); const prefs = resolveInteractionPreferences(config); return { theme: prefs.theme, defaultMode: prefs.mode, language: prefs.language ?? resolveTerminalLanguage(undefined, host.env) } } } }
function defaultHost(): CliHost { return { cwd: process.cwd(), env: process.env, stdin: process.stdin, stdout: process.stdout, stderr: process.stderr } }
function positional(args: string[]) { const commands = new Set(["plan", "convert"]), options = new Set(["--format", "--quality", "--effort", "--threads", "--output", "--existing"]); return args.filter((arg, index) => !arg.startsWith("--") && !commands.has(arg) && !options.has(args[index - 1] ?? "")) }
function value(args: string[], flag: string) { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : undefined }
function numberValue(args: string[], flag: string) { const raw = value(args, flag); return raw === undefined ? undefined : Number(raw) }
if (process.argv[1] && /\bcli\.[jt]s$/.test(process.argv[1].replace(/\\/g, "/"))) await runProgram().catch((error) => { writeError(defaultHost(), error instanceof Error ? error.message : String(error)); process.exitCode = 1 })
