import { describe, expect, test } from "vitest"

import { isAnimatedAvif, isAnimatedPng } from "./container-animation.js"

const ANIMATED_APNG = "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAAAAAAAAQCEeRdzAAAACGFjVEwAAAACAAAAAPONk3AAAAAaZmNUTAAAAAAAAAAEAAAABAAAAAAAAAAAAAEACgAAV3ID4QAAABNJREFUeJxj/MfAyAADLHAWXg4ANGsBDWoZhKIAAAAaZmNUTAAAAAEAAAAEAAAABAAAAAAAAAAAAAEACgAAzAHpNQAAABdmZEFUAAAAAnicY2Rk+McAAyxwFl4OADJxAQ1IRkV5AAAAAElFTkSuQmCC"
const ANIMATED_AVIF = "AAAAKGZ0eXBhdmlzAAAAAG1pZjFhdmlmbWlhZm1zZjFpc29tYXZpcwAAAmNtb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAABkAAAAFAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAB73RyYWsAAABcdGtoZAAAAAcAAAAAAAAAAAAAAAEAAAAAAAAAFAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAABAAAAAQAAAAAAYttZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAABkAAAAFFXLAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAFCbWluZgAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAQJzdGJsAAAAgnN0c2QAAAAAAAAAAQAAAHJhdjAxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAQABABIAAAASAAAAAAAAAABBEFWSUYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAADGF2MUOBDQwAAAAAEGNjc3QAAAAAQAAAAAAAABhzdHRzAAAAAAAAAAEAAAACAAAACgAAABxzdHNjAAAAAAAAAAEAAAABAAAAAgAAAAEAAAAcc3RzegAAAAAAAAAAAAAAAgAAAC8AAAAmAAAAFHN0Y28AAAAAAAAAAQAAA5kAAAAUc3RzcwAAAAAAAAABAAAAAQAAABR2bWhkAAAAAQAAAAAAAAAAAAAA1m1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAHBpY3QAAAAAAAAAAAAAAAAAAAAAImlsb2MAAAAAREAAAQABAAAAAANpAAEAAAAAAAAAKAAAACNpaW5mAAAAAAABAAAAFWluZmUCAAAAAAEAAGF2MDEAAAAADnBpdG0AAAAAAAEAAABWaXBycAAAADhpcGNvAAAADGF2MUOBAAwAAAAAFGlzcGUAAAAAAAAABAAAAAQAAAAQcGl4aQAAAAADCAgIAAAAFmlwbWEAAAAAAAAAAQABA4ECAwAAADBtZGF0EgAKCBgEfaICGg0IMhoZR4eGIYeeeeaAAACQQMkcYUuL0Y9RRU6koAAAAF1tZGF0EgAKDAAAAACPm18yAhoNCDIdEACWPj4zSAAPCAAAAABIVwOj+8SpchOM3DO0gSASADIiMAPAgAAABso8PDEMAANAAABAAJBA6G35qd/8Tzxo0KjOsA=="

describe("xlchemy container animation parsers", () => {
  test("detects APNG by its acTL chunk", () => {
    expect(isAnimatedPng(Buffer.from(ANIMATED_APNG, "base64"))).toBe(true)
    expect(isAnimatedPng(staticPng())).toBe(false)
  })

  test("detects animated AVIF by its sequence brand", () => {
    expect(isAnimatedAvif(Buffer.from(ANIMATED_AVIF, "base64"))).toBe(true)
    expect(isAnimatedAvif(staticAvif())).toBe(false)
  })
})

function staticPng(): Uint8Array {
  return Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64")
}

function staticAvif(): Uint8Array {
  const bytes = Buffer.alloc(20)
  bytes.writeUInt32BE(20, 0)
  bytes.write("ftypavif", 4, "ascii")
  bytes.writeUInt32BE(0, 12)
  bytes.write("mif1", 16, "ascii")
  return bytes
}
