/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import { ActionTabs, ClickTarget, ExecutionActions, ProgressBar, resolveTerminalTheme, TerminalPreferencesScreen, TerminalThemeProvider, terminalIcon, useTerminalChromeActions, useTerminalTheme, useTerminalUiSession, WorkbenchField, WorkbenchPanel } from "@xiranite/cli-runtime/terminal/opentui"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { XlchemyInput, XlchemyResult } from "./core.js"

export function XlchemyTui(props: TerminalUiScreenProps<XlchemyInput, XlchemyResult>) { const [previewTheme, setPreviewTheme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit"); return <TerminalThemeProvider theme={resolveTerminalTheme(previewTheme === "inherit" ? "nord" : previewTheme)}><Workbench {...props} onThemePreview={setPreviewTheme} /></TerminalThemeProvider> }

function Workbench({ definition, language, preferences, onExit, onThemePreview }: TerminalUiScreenProps<XlchemyInput, XlchemyResult> & { onThemePreview: (theme: string) => void }) {
  const theme = useTerminalTheme(), t = createTerminalTranslator(language), session = useTerminalUiSession(definition), [settings, setSettings] = useState(false)
  const field = (id: string) => definition.schema.fields.find((item) => item.id === id)!
  const paths = String(session.values.pathsText ?? "").split(/\r?\n/).map((value) => value.trim()).filter(Boolean), rows = session.resultSummary?.table?.rows ?? []
  useTerminalChromeActions({ onReset: session.reset, onExit, resetLabel: `↺ ${t("reset")}`, exitLabel: `× ${language === "zh" ? "退出" : "Exit"}` })
  useKeyboard((key) => { if (key.name !== "escape") return; if (settings) setSettings(false); else if (session.confirming) session.dismissConfirmation(); else if (session.phase === "running" || session.phase === "paused") void session.cancel(); else onExit() })
  if (settings && preferences) return <TerminalPreferencesScreen controller={preferences} focusedId={session.focusedControlId} onFocus={session.focus} onPreviewTheme={onThemePreview} onBack={() => setSettings(false)} />
  if (session.confirming) return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="70%" height={9} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>{`${terminalIcon("danger")} ${session.dangerPrompt?.title}`}</b></text><text>{session.dangerPrompt?.body}</text><ExecutionActions session={session} executeLabel="" confirmLabel={language === "zh" ? "确认转换" : "Convert"} /></box></box>
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden">
    <box height={4} flexShrink={0} borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("section")} XLCHEMY // IMAGE TRANSCODE`}</b></text><text fg={theme.colors.mutedForeground}>{session.status || (language === "zh" ? "输入队列、格式校准与批次转换" : "Input queue, format calibration, and batch conversion")}</text></box>{preferences ? <ClickTarget id="settings" onClick={() => setSettings(true)}>{`${terminalIcon("settings")} CONFIG`}</ClickTarget> : null}</box>
    <box height={3} marginTop={1} flexShrink={0} flexDirection="row" justifyContent="space-between"><ActionTabs id="field-action" options={[{ value: "plan", label: "⌕ PLAN" }, { value: "convert", label: "▶ CONVERT" }]} value={String(session.values.action ?? "plan")} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)} /><text fg={theme.colors.mutedForeground}>{`${paths.length} FILES · ${session.progress}%`}</text></box>
    <box flexDirection="row" flexGrow={1} minHeight={0} gap={1}><WorkbenchPanel title={`${terminalIcon("path")} ${language === "zh" ? "输入队列" : "Input queue"}`} width="34%"><WorkbenchField field={field("pathsText")} value={session.values.pathsText} error={session.fieldErrors.pathsText} focused={session.focusedControlId === "pathsText"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("pathsText")} onChange={(value) => session.setField("pathsText", value)} /><scrollbox flexGrow={1}>{paths.map((path, index) => <text key={`${path}-${index}`} fg={theme.colors.mutedForeground}>{`${index === 0 ? "▸" : "·"} ${path}`}</text>)}</scrollbox></WorkbenchPanel><WorkbenchPanel title={`${terminalIcon("section")} ${language === "zh" ? "格式与输出" : "Format and output"}`} width="34%"><scrollbox flexGrow={1}><box flexDirection="column" gap={1}>{["format", "lossless", "quality", "effort", "threads", "intelligentEffort", "jxlModular", "jxlVerify", "outputMode", "outputDir", "existingPolicy", "keepIfLarger", "copyIfLarger", "metadataMode", "downscaleEnabled", "downscaleMode", "downscaleWidth", "downscaleHeight"].map((id) => <WorkbenchField key={id} field={field(id)} value={session.values[id]} error={session.fieldErrors[id]} focused={session.focusedControlId === id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(id)} onChange={(value) => session.setField(id, value)} />)}</box></scrollbox></WorkbenchPanel><WorkbenchPanel title={`${terminalIcon("result")} ${language === "zh" ? "批次结果" : "Batch results"}`} flexGrow={1}><scrollbox flexGrow={1}>{rows.length ? rows.map((row, index) => <text key={`${row.source}-${index}`} fg={row.status === "error" ? theme.colors.error : theme.colors.foreground}>{`${row.status} ${row.source} → ${row.output}`}</text>) : session.preview.map((line, index) => <text key={`${line}-${index}`} fg={index ? theme.colors.mutedForeground : theme.colors.primary}>{line}</text>)}</scrollbox><ProgressBar value={session.progress} label={session.status || "READY"} /></WorkbenchPanel></box>
    <box height={8} flexShrink={0} marginTop={1} borderStyle="rounded" borderColor={session.dangerous ? theme.colors.error : theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" gap={1}><box width="72%" flexDirection="row" gap={1}>{["preserveMetadata", "preserveStructure", "preserveTimestamps", "recursive", "deleteOriginal"].map((id) => <box key={id} width="20%"><WorkbenchField field={field(id)} value={session.values[id]} error={session.fieldErrors[id]} focused={session.focusedControlId === id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(id)} onChange={(value) => session.setField(id, value)} /></box>)}</box><box flexGrow={1} flexDirection="column"><box flexGrow={1} /><ExecutionActions session={session} executeLabel={`▶ ${language === "zh" ? "执行批次" : "Run batch"}`} confirmLabel={`${terminalIcon("danger")} ${language === "zh" ? "确认" : "Confirm"}`} /></box></box>
  </box>
}
