/**
 * @migrated-from src/lib/cards/properties/EmmConfigCard.svelte
 * @source-hash sha256:31aa9e3785d5fbac55a4a07944820b5912c398f644811044026247877dee38a4
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import EmmConfig from '$lib/components/panels/emm/EmmConfigCard.js';

export function EmmConfigCard() {
  return (
    <Fragment>

<EmmConfig></EmmConfig></Fragment>
  )
}
