/**
 * @migrated-from src/lib/cards/properties/FileListTagDisplayCard.svelte
 * @source-hash sha256:372ef11a089413c212e2cfde37e77d7787dd2a4abe9e1ff42a42ca79ab776e33
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import FileListTagDisplay from '$lib/components/panels/emm/FileListTagDisplayCard.js';

export function FileListTagDisplayCard() {
  return (
    <Fragment>

<FileListTagDisplay></FileListTagDisplay></Fragment>
  )
}
