/**
 * @migrated-from src/lib/components/layout/TopToolbar/SlideshowPanel.svelte
 * @source-hash sha256:eb7a063ad1252600384269d05fe9a67c8af75568dd31cf48f66ed912d5a9f326
 * @features panels-toolbar-shell,slideshow,zoom-rotate-magnifier
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported attribute BindDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Button } from '$lib/components/ui/button';
import * as Separator from '$lib/components/ui/separator';
import * as Tooltip from '$lib/components/ui/tooltip';
import { Play, Pause } from 'lucide-react';
import { slideshowStore } from '$lib/stores/slideshow.js';
import { bookStore } from '$lib/stores/book.js';
interface Props {
		expanded: boolean;
	}

export function SlideshowPanel(props: Props) {
  const { expanded } = props
  let slideshowInterval = $state(slideshowStore.interval);

  function handleSlideshowIntervalChange() {
      slideshowStore.setInterval(slideshowInterval);
    }

  function startSlideshow() {
      window.dispatchEvent(
        new CustomEvent('neoview-viewer-action', {
          detail: { action: 'slideshowToggle' }
        })
      );
    }
  return (
    <Fragment>

{expanded && bookStore.currentBook ? (<Fragment>
	<div className="border-border/50 flex flex-wrap items-center justify-center gap-2 border-t pt-1">
		<span className="text-muted-foreground mr-2 text-xs">幻灯片</span>

		{/*  播放/暂停按钮  */}
		<Button variant={slideshowStore.isPlaying ? 'default' : 'outline'} size="sm" className="h-7 px-3" onClick={startSlideshow}>
			{slideshowStore.isPlaying ? (<Fragment>
				<Pause className="mr-1 h-3 w-3"></Pause>
				暂停
			</Fragment>) : (<Fragment>
				<Play className="mr-1 h-3 w-3"></Play>
				开始
			</Fragment>)}
		</Button>

		<Separator.Root orientation="vertical" className="mx-2 h-5"></Separator.Root>

		{/*  间隔时间  */}
		<span className="text-muted-foreground text-xs">间隔</span>
		<div className="flex items-center gap-1">
			<input type="range" min="1" max="30" step="1" onInput={handleSlideshowIntervalChange} className="bg-muted h-1 w-20 cursor-pointer appearance-none rounded-full" />
			<span className="w-8 text-center text-xs">{slideshowInterval}s</span>
		</div>

		{/*  快速设置  */}
		<div className="bg-muted/60 inline-flex items-center gap-0.5 rounded-full p-0.5 shadow-inner">
			{[3, 5, 10, 15].map((sec) => (<Fragment>
				<Button variant={slideshowInterval === sec ? 'default' : 'ghost'} size="sm" className="h-6 w-8 rounded-full px-1 text-xs" onClick={() => {
						slideshowInterval = sec;
						slideshowStore.setInterval(sec);
					}}>
					{sec}s
				</Button>
			</Fragment>))}
		</div>

		<Separator.Root orientation="vertical" className="mx-2 h-5"></Separator.Root>

		{/*  循环模式  */}
		<Tooltip.Root>
			<Tooltip.Trigger>
				<Button variant={slideshowStore.loop ? 'default' : 'ghost'} size="icon" className="h-7 w-7" onClick={() => slideshowStore.setLoop(!slideshowStore.loop)}>
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"></path><path d="M3 11v-1a4 4 0 0 1 4-4h14"></path><path d="m7 22-4-4 4-4"></path><path d="M21 13v1a4 4 0 0 1-4 4H3"></path></svg>
				</Button>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>循环播放{slideshowStore.loop ? '（开）' : '（关）'}</p>
			</Tooltip.Content>
		</Tooltip.Root>

		{/*  随机模式  */}
		<Tooltip.Root>
			<Tooltip.Trigger>
				<Button variant={slideshowStore.random ? 'default' : 'ghost'} size="icon" className="h-7 w-7" onClick={() => slideshowStore.setRandom(!slideshowStore.random)}>
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h1.4c1.3 0 2.5-.6 3.3-1.7l6.1-8.6c.7-1.1 2-1.7 3.3-1.7H22"></path><path d="m18 2 4 4-4 4"></path><path d="M2 6h1.9c1.5 0 2.9.9 3.6 2.2"></path><path d="M22 18h-5.9c-1.3 0-2.6-.7-3.3-1.8l-.5-.8"></path><path d="m18 14 4 4-4 4"></path></svg>
				</Button>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>随机播放{slideshowStore.random ? '（开）' : '（关）'}</p>
			</Tooltip.Content>
		</Tooltip.Root>

		{/*  进度显示  */}
		{slideshowStore.isPlaying ? (<Fragment>
			<Separator.Root orientation="vertical" className="mx-2 h-5"></Separator.Root>
			<div className="flex items-center gap-1">
				<div className="relative h-6 w-6">
					<svg className="h-6 w-6 -rotate-90 transform" viewBox="0 0 36 36">
						<circle cx="18" cy="18" r="15" fill="none" stroke="currentColor" stroke-opacity="0.2" stroke-width="3"></circle>
						<circle cx="18" cy="18" r="15" fill="none" stroke="currentColor" stroke-width="3" stroke-dasharray="94.2" stroke-dashoffset={94.2 - (slideshowStore.progress / 100) * 94.2} stroke-linecap="round" className="text-primary transition-all duration-200"></circle>
					</svg>
				</div>
				<span className="text-xs">{Math.ceil(slideshowStore.remainingTime)}s</span>
			</div>
		</Fragment>) : null}
	</div>
</Fragment>) : null}</Fragment>
  )
}
