import { useEffect, useRef, useState } from "react"
import type { CzkawkaBuiltinFilterPreset, CzkawkaFilterState, CzkawkaFilterStats, CzkawkaFormatCategory, CzkawkaMarkFilter, CzkawkaPathMatchMode, CzkawkaSizeUnit, CzkawkaStoredFilterPreset, CzkawkaTextField, CzkawkaTool } from "@xiranite/node-czkawka/filters"
import { applyCzkawkaBuiltinFilterPreset, countActiveCzkawkaFilters, createDefaultCzkawkaFilterState, CZKAWKA_NO_EXTENSION, parseCzkawkaFilterPresets, serializeCzkawkaFilterPresets, supportsResolutionFilter, supportsSimilarityFilter } from "@xiranite/node-czkawka/filters"
import { Filter, RotateCcw, Save, Trash2, Upload } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { useNodeI18n } from "@/nodes/shared/useNodeI18n"

type Translate = (key: string, fallback: string, vars?: Record<string, unknown>) => string

export interface CzkawkaFilterPanelProps {
  tool: CzkawkaTool
  state: CzkawkaFilterState
  stats: CzkawkaFilterStats
  pathPatternError?: string
  textPatternError?: string
  presets: CzkawkaStoredFilterPreset[]
  onChange: (state: CzkawkaFilterState) => void
  onPresetsChange: (presets: CzkawkaStoredFilterPreset[]) => void
}

export function CzkawkaFilterPanel(props: CzkawkaFilterPanelProps) {
  "use no memo"
  const { t } = useNodeI18n("czkawka")
  const active = countActiveCzkawkaFilters(props.state)
  const [open, setOpen] = useState(false)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const [selectedPreset, setSelectedPreset] = useState("none")
  const [presetName, setPresetName] = useState("")
  const [transferText, setTransferText] = useState("")
  const [presetError, setPresetError] = useState("")
  const patch = <K extends keyof CzkawkaFilterState>(key: K, value: CzkawkaFilterState[K]) => props.onChange({ ...props.state, [key]: value })

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const surface = triggerRef.current?.closest('[data-testid="czkawka-surface"]')
      if (!open && surface && !surface.contains(document.activeElement)) return
      if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLocaleLowerCase() === "f") { event.preventDefault(); setOpen((value) => !value); return }
      if ((event.ctrlKey || event.metaKey) && event.key.toLocaleLowerCase() === "f") { event.preventDefault(); setOpen(true); return }
      if ((event.ctrlKey || event.metaKey) && event.key.toLocaleLowerCase() === "r") { event.preventDefault(); props.onChange({ ...props.state }); return }
      if (event.key === "Escape") { event.preventDefault(); props.onChange(createDefaultCzkawkaFilterState()); setOpen(false) }
    }
    window.addEventListener("keydown", handleKeyDown)
    return () => window.removeEventListener("keydown", handleKeyDown)
  }, [open, props.onChange, props.state])

  function choosePreset(value: string) {
    setSelectedPreset(value)
    if (isBuiltinPreset(value)) props.onChange(applyCzkawkaBuiltinFilterPreset(value))
    else { const preset = props.presets.find((item) => item.id === value); if (preset) props.onChange(preset.state) }
  }

  function savePreset() {
    const name = presetName.trim()
    if (!name) { setPresetError(t("filter.enterPresetName", "请输入预设名称。")); return }
    const existing = props.presets.find((item) => item.name === name)
    const preset = { id: existing?.id ?? `filter-${Date.now()}`, name, state: props.state }
    props.onPresetsChange(existing ? props.presets.map((item) => item.id === existing.id ? preset : item) : [...props.presets, preset])
    setSelectedPreset(preset.id)
    setPresetName("")
    setPresetError("")
  }

  function importPresets() {
    try { const imported = parseCzkawkaFilterPresets(transferText); props.onPresetsChange(imported); setPresetError("") }
    catch (error) { setPresetError(error instanceof Error ? error.message : String(error)) }
  }

  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button ref={triggerRef} aria-label={t("filter.open", "打开多维筛选")} size="sm" variant={active ? "secondary" : "outline"}><Filter />{t("filter.filter", "筛选")}{active ? <Badge variant="default">{active}</Badge> : null}</Button></PopoverTrigger><PopoverContent align="end" className="w-[min(94vw,520px)] p-0"><div className="flex items-center justify-between border-b px-3 py-2"><div><div className="text-sm font-semibold">{t("filter.title", "多维筛选")}</div><div className="text-[11px] text-muted-foreground">{t("filter.stats", "{{filtered}}/{{total}} 文件 · {{filteredGroups}}/{{totalGroups}} 组 · {{bytes}}", { filtered: props.stats.filteredItems, total: props.stats.totalItems, filteredGroups: props.stats.filteredGroups, totalGroups: props.stats.totalGroups, bytes: formatBytes(props.stats.filteredBytes) })}</div></div><Button size="xs" variant="ghost" onClick={() => props.onChange(createDefaultCzkawkaFilterState())}><RotateCcw />{t("filter.reset", "重置")}</Button></div><ScrollArea className="h-[min(68vh,620px)]"><div className="grid gap-3 p-3">
    <FilterSection label={t("filter.presets.title", "筛选预设")}><div className="grid grid-cols-[1fr_auto] gap-2"><Select value={selectedPreset} onValueChange={choosePreset}><SelectTrigger aria-label={t("filter.presets.title", "筛选预设")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">{t("filter.presets.none", "无预设")}</SelectItem><SelectItem value="large-files">{t("filter.presets.large", "大文件（≥100 MB）")}</SelectItem><SelectItem value="small-files">{t("filter.presets.small", "小文件（≤1 MB）")}</SelectItem><SelectItem value="recently-modified">{t("filter.presets.recent", "最近 30 天")}</SelectItem><SelectItem value="old-files">{t("filter.presets.old", "一年以前")}</SelectItem>{props.presets.map((preset) => <SelectItem key={preset.id} value={preset.id}>{preset.name}</SelectItem>)}</SelectContent></Select><Button aria-label={t("filter.presets.delete", "删除当前预设")} disabled={isBuiltinPreset(selectedPreset)} size="icon-sm" variant="outline" onClick={() => { props.onPresetsChange(props.presets.filter((item) => item.id !== selectedPreset)); setSelectedPreset("none") }}><Trash2 /></Button></div><div className="flex gap-2"><Input aria-label={t("filter.presets.newName", "新预设名称")} placeholder={t("filter.presets.name", "预设名称")} value={presetName} onChange={(event) => setPresetName(event.currentTarget.value)} /><Button size="sm" variant="outline" onClick={savePreset}><Save />{t("filter.presets.save", "保存")}</Button></div><div className="flex gap-2"><Button size="xs" variant="ghost" onClick={() => { setTransferText(serializeCzkawkaFilterPresets(props.presets)); setPresetError("") }}>{t("filter.presets.export", "导出 JSON")}</Button><Button size="xs" variant="ghost" onClick={importPresets}><Upload />{t("filter.presets.import", "导入 JSON")}</Button></div>{transferText ? <Textarea aria-label={t("filter.presets.json", "预设 JSON")} className="min-h-24 font-mono text-[10px]" value={transferText} onChange={(event) => setTransferText(event.currentTarget.value)} /> : null}{presetError ? <div role="alert" className="text-xs text-destructive">{presetError}</div> : null}</FilterSection>
    <FilterSection label={t("filter.text.title", "快速文本")}><Enabled checked={props.state.text.enabled} label={t("filter.text.enabled", "启用文本筛选")} onChange={(enabled) => patch("text", { ...props.state.text, enabled })} /><Input aria-label={t("filter.text.pattern", "快速文本模式")} placeholder={t("filter.text.placeholder", "名称、路径和媒体字段")} value={props.state.text.pattern} onChange={(event) => patch("text", { ...props.state.text, enabled: Boolean(event.currentTarget.value), pattern: event.currentTarget.value })} /><div className="flex flex-wrap gap-1">{(["name", "path", "metadata", "detail"] as CzkawkaTextField[]).map((field) => { const label = textFieldLabel(field, t); return <Button key={field} aria-label={t("filter.text.fieldLabel", "{{field}}字段", { field: label })} aria-pressed={props.state.text.fields.includes(field)} size="xs" variant={props.state.text.fields.includes(field) ? "secondary" : "outline"} onClick={() => patch("text", { ...props.state.text, fields: toggleValue(props.state.text.fields, field) })}>{label}</Button> })}</div><div className="grid grid-cols-2 gap-2"><Enabled checked={props.state.text.regex} label={t("filter.regex", "正则表达式")} onChange={(regex) => patch("text", { ...props.state.text, regex })} /><Enabled checked={props.state.text.caseSensitive} label={t("filter.caseSensitive", "区分大小写")} onChange={(caseSensitive) => patch("text", { ...props.state.text, caseSensitive })} /></div>{props.textPatternError ? <div role="alert" className="text-xs text-destructive">{t("filter.invalidRegex", "正则无效：{{error}}", { error: props.textPatternError })}</div> : null}</FilterSection>
    <FilterSection label={t("filter.mark.title", "标记状态")}><Select value={props.state.mark} onValueChange={(value) => patch("mark", value as CzkawkaMarkFilter)}><SelectTrigger aria-label={t("filter.mark.title", "标记状态")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t("filter.mark.all", "全部")}</SelectItem><SelectItem value="selected">{t("filter.mark.selected", "已选")}</SelectItem><SelectItem value="unselected">{t("filter.mark.unselected", "未选")}</SelectItem><SelectItem value="group-some-selected">{t("filter.mark.some", "组内部分已选")}</SelectItem><SelectItem value="group-all-selected">{t("filter.mark.allSelected", "组内全部已选")}</SelectItem><SelectItem value="group-none-selected">{t("filter.mark.noneSelected", "组内均未选")}</SelectItem><SelectItem value="reference">{t("filter.mark.reference", "仅参考项")}</SelectItem></SelectContent></Select></FilterSection>
    <div className="grid grid-cols-2 gap-2"><RangeSection t={t} label={t("filter.groupCount", "组内数量")} value={props.state.groupCount} onChange={(value) => patch("groupCount", value)} /><SizeRangeSection t={t} label={t("filter.groupSize", "组总体积")} value={props.state.groupSize} onChange={(value) => patch("groupSize", value)} /></div>
    <SizeRangeSection t={t} label={t("filter.fileSize", "文件大小")} value={props.state.fileSize} onChange={(value) => patch("fileSize", value)} />
    <FilterSection label={t("filter.extension.title", "扩展名")}><Enabled checked={props.state.extension.enabled} label={t("filter.extension.enabled", "启用扩展名筛选")} onChange={(enabled) => patch("extension", { ...props.state.extension, enabled })} /><div className="grid grid-cols-[120px_1fr] gap-2"><Select value={props.state.extension.mode} onValueChange={(mode) => patch("extension", { ...props.state.extension, mode: mode as "include" | "exclude" })}><SelectTrigger aria-label={t("filter.extension.mode", "扩展名模式")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="include">{t("filter.extension.include", "仅包含")}</SelectItem><SelectItem value="exclude">{t("filter.extension.exclude", "排除")}</SelectItem></SelectContent></Select><Input aria-label={t("filter.extension.list", "扩展名列表")} placeholder="jpg, png, avif" value={props.state.extension.extensions.join(", ")} onChange={(event) => patch("extension", { ...props.state.extension, extensions: tokens(event.currentTarget.value) })} /></div><div className="flex flex-wrap gap-1">{props.stats.categories.map((item) => <Button key={item.category} aria-pressed={!props.state.extension.excludedCategories.includes(item.category)} size="xs" variant={props.state.extension.excludedCategories.includes(item.category) ? "outline" : "secondary"} onClick={() => toggleCategory(props, item.category)}>{categoryLabel(item.category, t)} <span className="opacity-70">{item.filteredCount}/{item.totalCount}</span></Button>)}</div><div className="flex flex-wrap gap-1">{props.stats.extensions.slice(0, 10).map((item) => <Button key={item.extension} size="xs" variant={props.state.extension.extensions.includes(item.extension) ? "default" : "outline"} onClick={() => toggleExtension(props, item.extension)}>{item.extension === CZKAWKA_NO_EXTENSION ? t("filter.extension.noExtension", "无扩展名") : item.extension} <span className="opacity-70">{item.filteredCount}/{item.totalCount}</span></Button>)}</div></FilterSection>
    <FilterSection label={t("filter.date.title", "修改日期")}><Enabled checked={props.state.modifiedDate.enabled} label={t("filter.date.enabled", "启用日期筛选")} onChange={(enabled) => patch("modifiedDate", { ...props.state.modifiedDate, enabled })} /><Select value={props.state.modifiedDate.preset} onValueChange={(preset) => patch("modifiedDate", { ...props.state.modifiedDate, preset: preset as CzkawkaFilterState["modifiedDate"]["preset"] })}><SelectTrigger aria-label={t("filter.date.range", "日期范围")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="today">{t("filter.date.today", "今天")}</SelectItem><SelectItem value="last-7-days">{t("filter.date.last7", "最近 7 天")}</SelectItem><SelectItem value="last-30-days">{t("filter.date.last30", "最近 30 天")}</SelectItem><SelectItem value="last-year">{t("filter.date.lastYear", "最近一年")}</SelectItem><SelectItem value="custom">{t("filter.date.custom", "自定义")}</SelectItem></SelectContent></Select>{props.state.modifiedDate.preset === "custom" ? <div className="grid grid-cols-2 gap-2"><Input aria-label={t("filter.date.start", "开始日期")} type="date" value={dateInput(props.state.modifiedDate.start)} onChange={(event) => patch("modifiedDate", { ...props.state.modifiedDate, start: dateTimestamp(event.currentTarget.value) })} /><Input aria-label={t("filter.date.end", "结束日期")} type="date" value={dateInput(props.state.modifiedDate.end)} onChange={(event) => patch("modifiedDate", { ...props.state.modifiedDate, end: endOfDateTimestamp(event.currentTarget.value) })} /></div> : null}</FilterSection>
    <FilterSection label={t("filter.path.title", "路径")}><Enabled checked={props.state.path.enabled} label={t("filter.path.enabled", "启用路径筛选")} onChange={(enabled) => patch("path", { ...props.state.path, enabled })} /><div className="grid grid-cols-[130px_1fr] gap-2"><Select value={props.state.path.mode} onValueChange={(mode) => patch("path", { ...props.state.path, mode: mode as CzkawkaPathMatchMode })}><SelectTrigger aria-label={t("filter.path.mode", "路径匹配模式")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="contains">{t("filter.path.contains", "包含")}</SelectItem><SelectItem value="not-contains">{t("filter.path.notContains", "不包含")}</SelectItem><SelectItem value="starts-with">{t("filter.path.startsWith", "开头是")}</SelectItem><SelectItem value="ends-with">{t("filter.path.endsWith", "结尾是")}</SelectItem><SelectItem value="regex">{t("filter.regex", "正则表达式")}</SelectItem></SelectContent></Select><Input aria-label={t("filter.path.pattern", "路径模式")} value={props.state.path.pattern} onChange={(event) => patch("path", { ...props.state.path, pattern: event.currentTarget.value })} /></div><Enabled checked={props.state.path.caseSensitive} label={t("filter.caseSensitive", "区分大小写")} onChange={(caseSensitive) => patch("path", { ...props.state.path, caseSensitive })} />{props.pathPatternError ? <div role="alert" className="text-xs text-destructive">{t("filter.invalidRegex", "正则无效：{{error}}", { error: props.pathPatternError })}</div> : null}</FilterSection>
    {supportsSimilarityFilter(props.tool) ? <RangeSection t={t} label={t("filter.similarity", "相似度（%）")} value={props.state.similarity} onChange={(value) => patch("similarity", value)} /> : null}
    {supportsResolutionFilter(props.tool) ? <FilterSection label={t("filter.resolution.title", "分辨率 / 宽高比")}><Enabled checked={props.state.resolution.enabled} label={t("filter.resolution.enabled", "启用分辨率筛选")} onChange={(enabled) => patch("resolution", { ...props.state.resolution, enabled })} /><div className="grid grid-cols-2 gap-2"><NumberInput label={t("filter.resolution.minWidth", "最小宽度")} value={props.state.resolution.minWidth} onChange={(minWidth) => patch("resolution", { ...props.state.resolution, minWidth })} /><NumberInput label={t("filter.resolution.minHeight", "最小高度")} value={props.state.resolution.minHeight} onChange={(minHeight) => patch("resolution", { ...props.state.resolution, minHeight })} /><NumberInput label={t("filter.resolution.maxWidth", "最大宽度")} value={props.state.resolution.maxWidth} onChange={(maxWidth) => patch("resolution", { ...props.state.resolution, maxWidth })} /><NumberInput label={t("filter.resolution.maxHeight", "最大高度")} value={props.state.resolution.maxHeight} onChange={(maxHeight) => patch("resolution", { ...props.state.resolution, maxHeight })} /></div><Select value={props.state.resolution.aspectRatio} onValueChange={(aspectRatio) => patch("resolution", { ...props.state.resolution, aspectRatio: aspectRatio as CzkawkaFilterState["resolution"]["aspectRatio"] })}><SelectTrigger aria-label={t("filter.resolution.aspectRatio", "宽高比")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="any">{t("filter.resolution.any", "任意宽高比")}</SelectItem><SelectItem value="16:9">16:9</SelectItem><SelectItem value="4:3">4:3</SelectItem><SelectItem value="1:1">1:1</SelectItem></SelectContent></Select></FilterSection> : null}
    <Enabled checked={props.state.showAllInFilteredGroups} label={t("filter.showWholeGroup", "命中组显示全部文件")} onChange={(showAllInFilteredGroups) => patch("showAllInFilteredGroups", showAllInFilteredGroups)} /><div className="text-[10px] text-muted-foreground">{t("filter.shortcuts", "快捷键：Ctrl/Cmd+F 打开 · Ctrl/Cmd+Shift+F 切换 · Ctrl/Cmd+R 刷新 · Esc 重置")}</div>
  </div></ScrollArea></PopoverContent></Popover>
}

function FilterSection({ label, children }: { label: string; children: React.ReactNode }) { return <section className="grid gap-2 rounded-md border p-2"><div className="text-xs font-semibold">{label}</div>{children}</section> }
function Enabled({ checked, label, onChange }: { checked: boolean; label: string; onChange: (checked: boolean) => void }) { return <label className="flex items-center justify-between gap-2 text-xs"><span>{label}</span><Switch aria-label={label} checked={checked} size="sm" onCheckedChange={onChange} /></label> }
function NumberInput({ label, value, onChange }: { label: string; value?: number; onChange: (value?: number) => void }) { return <label className="grid gap-1 text-[11px] text-muted-foreground"><span>{label}</span><Input aria-label={label} type="number" min={0} value={value ?? ""} onChange={(event) => onChange(optionalNumber(event.currentTarget.value))} /></label> }
function RangeSection({ label, value, onChange, t }: { label: string; value: CzkawkaFilterState["groupCount"]; onChange: (value: CzkawkaFilterState["groupCount"]) => void; t: Translate }) { return <FilterSection label={label}><Enabled checked={value.enabled} label={t("filter.range.enabled", "{{label}}筛选", { label })} onChange={(enabled) => onChange({ ...value, enabled })} /><div className="grid grid-cols-2 gap-2"><NumberInput label={t("filter.range.minimum", "{{label}}最小", { label })} value={value.min} onChange={(min) => onChange({ ...value, min })} /><NumberInput label={t("filter.range.maximum", "{{label}}最大", { label })} value={value.max} onChange={(max) => onChange({ ...value, max })} /></div></FilterSection> }
function SizeRangeSection({ label, value, onChange, t }: { label: string; value: CzkawkaFilterState["fileSize"]; onChange: (value: CzkawkaFilterState["fileSize"]) => void; t: Translate }) { return <FilterSection label={label}><Enabled checked={value.enabled} label={t("filter.range.enabled", "{{label}}筛选", { label })} onChange={(enabled) => onChange({ ...value, enabled })} /><div className="grid grid-cols-[1fr_1fr_86px] gap-2"><NumberInput label={t("filter.range.minimum", "{{label}}最小", { label })} value={value.min} onChange={(min) => onChange({ ...value, min })} /><NumberInput label={t("filter.range.maximum", "{{label}}最大", { label })} value={value.max} onChange={(max) => onChange({ ...value, max })} /><label className="grid gap-1 text-[11px] text-muted-foreground"><span>{t("filter.range.unit", "单位")}</span><Select value={value.unit ?? "B"} onValueChange={(unit) => onChange({ ...value, unit: unit as CzkawkaSizeUnit })}><SelectTrigger aria-label={t("filter.range.unitLabel", "{{label}}单位", { label })}><SelectValue /></SelectTrigger><SelectContent>{["B", "KB", "MB", "GB", "TB"].map((unit) => <SelectItem key={unit} value={unit}>{unit}</SelectItem>)}</SelectContent></Select></label></div></FilterSection> }

function toggleExtension(props: CzkawkaFilterPanelProps, extension: string) { const current = props.state.extension.extensions; props.onChange({ ...props.state, extension: { ...props.state.extension, enabled: true, extensions: current.includes(extension) ? current.filter((item) => item !== extension) : [...current, extension] } }) }
function toggleCategory(props: CzkawkaFilterPanelProps, category: CzkawkaFormatCategory) { const current = props.state.extension.excludedCategories; props.onChange({ ...props.state, extension: { ...props.state.extension, enabled: true, excludedCategories: current.includes(category) ? current.filter((item) => item !== category) : [...current, category] } }) }
function categoryLabel(category: CzkawkaFormatCategory, t: Translate): string { return t(`filter.categories.${category}`, ({ images: "图片", videos: "视频", audio: "音频", documents: "文档", archives: "压缩包", folders: "文件夹", other: "其他" })[category]) }
function textFieldLabel(field: CzkawkaTextField, t: Translate): string { return t(`filter.text.fields.${field}`, ({ name: "名称", path: "路径", metadata: "媒体元数据", detail: "详情" })[field]) }
function toggleValue<T>(values: T[], value: T): T[] { return values.includes(value) ? values.filter((item) => item !== value) : [...values, value] }
function tokens(value: string): string[] { return [...new Set(value.split(/[\s,;]+/).map((item) => item.trim().replace(/^\./, "").toLocaleLowerCase()).filter(Boolean))] }
function optionalNumber(value: string): number | undefined { const number = Number(value); return value === "" || !Number.isFinite(number) ? undefined : number }
function dateInput(value: number | undefined): string { return value ? new Date(value).toISOString().slice(0, 10) : "" }
function dateTimestamp(value: string): number | undefined { return value ? new Date(`${value}T00:00:00`).getTime() : undefined }
function endOfDateTimestamp(value: string): number | undefined { return value ? new Date(`${value}T23:59:59.999`).getTime() : undefined }
function formatBytes(bytes: number): string { if (bytes < 1024) return `${bytes} B`; const units = ["KB", "MB", "GB", "TB"]; let value = bytes / 1024; let unit = units[0]!; for (let index = 1; index < units.length && value >= 1024; index += 1) { value /= 1024; unit = units[index]! } return `${value.toFixed(value >= 10 ? 1 : 2)} ${unit}` }
function isBuiltinPreset(value: string): value is CzkawkaBuiltinFilterPreset { return ["none", "large-files", "small-files", "recently-modified", "old-files"].includes(value) }
