import type { CzkawkaCardState } from "./types"

export const CZKAWKA_NODE_CONFIG_KEYS = [
  "tool",
  "includedDirectoriesText",
  "includedDirectoriesReferencedText",
  "excludedDirectoriesText",
  "excludedItemsText",
  "allowedExtensions",
  "excludedExtensions",
  "minimumFileSize",
  "maximumFileSize",
  "recursive",
  "useCache",
  "saveAlsoAsJson",
  "deleteOutdatedCacheByTool",
  "cacheFolderPath",
  "configFolderPath",
  "duplicateMinimalHashCacheSizeKiB",
  "duplicateMinimalPrehashCacheSizeKiB",
  "threadCount",
  "checkMethod",
  "hashType",
  "caseSensitiveNames",
  "ignoreHardLinks",
  "usePrehash",
  "duplicateMinimumGroupSize",
  "numberOfFiles",
  "biggestFirst",
  "similarity",
  "similarImagesHashSize",
  "similarImagesHashAlgorithm",
  "similarImagesResizeAlgorithm",
  "similarImagesIgnoreSameSize",
  "similarImagesIgnoreSameResolution",
  "similarImagesGeometricInvariance",
  "similarImagesFolderThreshold",
  "similarImagesViewMode",
  "similarVideosIgnoreSameSize",
  "similarVideosIgnoreSameResolution",
  "similarVideosSkipForward",
  "similarVideosHashDuration",
  "similarVideosLetterboxCrop",
  "similarVideosWindowCount",
  "similarVideosDurationTolerancePct",
  "similarVideosMinMatchingWindows",
  "similarVideosSubclipMinMatch",
  "similarVideosCheckAudioContent",
  "musicCheckType",
  "musicApproximateComparison",
  "musicCompareTitle",
  "musicCompareArtist",
  "musicCompareBitrate",
  "musicCompareGenre",
  "musicCompareYear",
  "musicCompareLength",
  "musicMaximumDifference",
  "musicMinimumFragmentDuration",
  "musicCompareFingerprintsOnlyWithSimilarTitles",
  "brokenAudio",
  "brokenPdf",
  "brokenArchive",
  "brokenImage",
  "brokenVideoFfprobe",
  "brokenVideoFfmpeg",
  "brokenFont",
  "brokenMarkup",
  "emptyFilesSearchZeroByteContent",
  "emptyFilesSearchNonPrintableContent",
  "temporaryFileExtensions",
  "videoOptimizerMode",
  "videoOptimizerExcludedCodecs",
  "videoOptimizerBlackPixelThreshold",
  "videoOptimizerBlackBarMinPercentage",
  "videoOptimizerMaxSamples",
  "videoOptimizerMinCropSize",
  "videoOptimizerTargetCodec",
  "videoOptimizerQuality",
  "videoOptimizerFailIfNotSmaller",
  "videoOptimizerLimitVideoSize",
  "videoOptimizerMaximumWidth",
  "videoOptimizerMaximumHeight",
  "videoOptimizerNoiseReduction",
  "videoOptimizerNoiseReductionStrength",
  "videoOptimizerCropTranscode",
  "filterPresets",
  "selectionAssistantConfig",
  "previewPanelEnabledByTool",
  "thumbnailEnabledByTool",
  "referencePathKeywords",
  "reversePathDisplay",
  "tableWrapText",
  "imageComparisonMode",
  "imageComparisonColorCoding",
  "scanPresets",
  "activeScanPresetId",
  "sortBy",
  "descending",
  "dryRun",
  "destinationDirectory",
  "deleteMode",
  "copyMode",
  "preserveStructure",
  "conflictPolicy",
  "organizeSubfolderTemplate",
  "organizeSkipSingleFileFolders",
  "outputPath",
  "exportScope",
] as const satisfies readonly (keyof CzkawkaCardState)[]

export type CzkawkaNodeConfig = Pick<CzkawkaCardState, (typeof CZKAWKA_NODE_CONFIG_KEYS)[number]>

/** Keeps reusable Czkawka defaults in TOML and leaves workspace/session state in SQLite. */
export function pickCzkawkaNodeConfig(value: unknown): Partial<CzkawkaNodeConfig> {
  if (!isRecord(value)) return {}

  const config: Partial<CzkawkaNodeConfig> = {}
  for (const key of CZKAWKA_NODE_CONFIG_KEYS) {
    if (Object.prototype.hasOwnProperty.call(value, key)) {
      config[key] = value[key] as CzkawkaNodeConfig[typeof key]
    }
  }
  return config
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}
