import type { CzkawkaSimilarFolderStat } from "@xiranite/node-czkawka/similar-folders"
import { Copy, ExternalLink, FolderOpen, FolderSearch2 } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { LocalMediaPreview } from "@/nodes/shared/LocalMediaPreview"

export function CzkawkaSimilarFoldersView({ folders, filterText, getFileUrl, onCopyText, onOpenPath, onRevealPath }: { folders: CzkawkaSimilarFolderStat[]; filterText: string; getFileUrl?: (path: string) => string; onCopyText?: (text: string) => Promise<void>; onOpenPath?: (path: string) => Promise<void>; onRevealPath?: (path: string) => Promise<void> }) {
  const needle = filterText.trim().toLocaleLowerCase()
  const visible = needle ? folders.filter((folder) => folder.path.toLocaleLowerCase().includes(needle)) : folders
  return <section data-testid="czkawka-similar-folders" className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden rounded-md border bg-card"><div className="flex items-center justify-between gap-2 border-b px-2 py-1.5"><div className="flex min-w-0 items-center gap-2 text-xs font-semibold"><FolderSearch2 className="size-3.5 text-primary" /><span>相似文件夹</span><Badge variant="outline">{visible.length}</Badge></div><span className="truncate text-[10px] text-muted-foreground">按图片数量、体积和涉及分组汇总</span></div><ScrollArea className="min-h-0 flex-1"><div className="grid gap-px bg-border">{visible.map((folder) => <div key={folder.path} className="grid min-w-0 grid-cols-[44px_minmax(0,1fr)_auto] items-center gap-2 bg-card p-2"><LocalMediaPreview path={folder.previewPath ?? folder.path} getFileUrl={getFileUrl} className="grid size-10 place-items-center overflow-hidden rounded-sm border bg-muted/30 object-cover" fallback={<FolderSearch2 className="size-4 text-muted-foreground" />} /><div className="min-w-0"><div className="truncate font-mono text-xs" title={folder.path}>{folder.path}</div><div className="mt-1 flex flex-wrap gap-1"><Badge variant="secondary">{folder.count} 张</Badge><Badge variant="outline">{folder.groupCount} 组</Badge><Badge variant="outline">{formatBytes(folder.bytes)}</Badge></div></div><div className="flex items-center gap-0.5"><Button aria-label={`复制文件夹路径 ${folder.path}`} disabled={!onCopyText} size="icon-xs" variant="ghost" onClick={() => void onCopyText?.(folder.path)}><Copy /></Button><Button aria-label={`打开文件夹 ${folder.path}`} disabled={!onOpenPath} size="icon-xs" variant="ghost" onClick={() => void onOpenPath?.(folder.path)}><ExternalLink /></Button><Button aria-label={`定位文件夹 ${folder.path}`} disabled={!onRevealPath} size="icon-xs" variant="ghost" onClick={() => void onRevealPath?.(folder.path)}><FolderOpen /></Button></div></div>)}{visible.length ? null : <div className="bg-card p-6 text-center text-xs text-muted-foreground">当前阈值和筛选条件下没有相似文件夹。</div>}</div></ScrollArea></section>
}

function formatBytes(bytes: number): string { if (bytes < 1024) return `${bytes} B`; const units = ["KB", "MB", "GB", "TB"]; let value = bytes / 1024, unit = units[0]!; for (let index = 1; index < units.length && value >= 1024; index += 1) { value /= 1024; unit = units[index]! } return `${value.toFixed(value >= 10 ? 1 : 2)} ${unit}` }
