import type { NodeRunEvent, NodeRunResult } from "@xiranite/contract"

export type LinkuAction = "info" | "create" | "move_link" | "list" | "recover"
export type LinkuPathKind = "file" | "dir" | "missing" | "other"

export interface LinkuInput {
  action?: LinkuAction
  path?: string
  target?: string
  configPath?: string
}

export interface LinkRecord {
  link: string
  target: string
  type: string
  createdAt: string
}

export interface LinkPathInfo {
  path: string
  exists: boolean
  kind: LinkuPathKind
  isSymlink: boolean
  linkTarget?: string
  targetExists?: boolean
  sizeMb?: number
  fileCount?: number
}

export interface LinkuData {
  pathInfo?: LinkPathInfo
  links: LinkRecord[]
  created: boolean
  recoveredCount: number
  failedCount: number
}

export interface LinkuRuntime {
  pathInfo: (path: string) => Promise<LinkPathInfo>
  createSymlink: (source: string, link: string) => Promise<void>
  movePath: (source: string, target: string) => Promise<void>
  readConfig: (path?: string) => Promise<string | null>
  writeConfig: (content: string, path?: string) => Promise<void>
}

export type LinkuResult = NodeRunResult<LinkuData>

export function normalizeLinkuInput(input: LinkuInput): Required<LinkuInput> {
  return {
    action: input.action ?? "info",
    path: normalizePath(input.path),
    target: normalizePath(input.target),
    configPath: normalizePath(input.configPath),
  }
}

export function normalizePath(path?: string): string {
  return (path ?? "").trim().replace(/^["']|["']$/g, "")
}

export function resolveMoveTarget(sourceInfo: LinkPathInfo, targetInput: string): { target: string; error?: string } {
  const target = normalizePath(targetInput)
  if (!target) return { target, error: "Target path is required." }
  if (sourceInfo.kind === "dir" && sourceInfo.exists && sourceInfo.path === target) {
    return { target, error: "Target must be different from source." }
  }
  return { target }
}

export function parseLinkRecords(content: string | null): LinkRecord[] {
  if (!content) return []
  const records: LinkRecord[] = []
  let current: Partial<LinkRecord> | null = null

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith("#")) continue
    if (line === "[[links]]") {
      current = {}
      records.push(current as LinkRecord)
      continue
    }
    if (!current || !line.includes("=")) continue
    const [rawKey, ...rawValueParts] = line.split("=")
    const key = rawKey.trim()
    const value = unquoteTomlString(rawValueParts.join("=").trim())
    if (key === "link") current.link = value
    else if (key === "target") current.target = value
    else if (key === "type") current.type = value
    else if (key === "created_at") current.createdAt = value
    else if (key === "createdAt") current.createdAt = value
  }

  return records.filter((record) => record.link && record.target).map((record) => ({
    link: record.link,
    target: record.target,
    type: record.type ?? "",
    createdAt: record.createdAt ?? "",
  }))
}

export function dumpLinkRecords(records: LinkRecord[]): string {
  const lines = ["# linku config generated by xiranite", "config_version = 1", ""]
  for (const record of records) {
    lines.push("[[links]]")
    lines.push(`link = "${escapeTomlString(record.link)}"`)
    lines.push(`target = "${escapeTomlString(record.target)}"`)
    lines.push(`type = "${escapeTomlString(record.type)}"`)
    lines.push(`created_at = "${escapeTomlString(record.createdAt)}"`)
    lines.push("")
  }
  return `${lines.join("\n").trimEnd()}\n`
}

export function upsertLinkRecord(records: LinkRecord[], next: LinkRecord): LinkRecord[] {
  const key = next.link.toLowerCase()
  let replaced = false
  const updated = records.map((record) => {
    if (record.link.toLowerCase() !== key) return record
    replaced = true
    return next
  })
  return replaced ? updated : [...updated, next]
}

export async function runLinku(
  input: LinkuInput,
  runtime: LinkuRuntime,
  onEvent: (event: NodeRunEvent) => void = () => {},
): Promise<LinkuResult> {
  const normalized = normalizeLinkuInput(input)
  if (normalized.action === "info") {
    if (!normalized.path) return failure("Path is required.")
    const pathInfo = await runtime.pathInfo(normalized.path)
    return success("Path info loaded.", { pathInfo, links: [], created: false, recoveredCount: 0, failedCount: 0 })
  }

  if (normalized.action === "list") {
    const links = parseLinkRecords(await runtime.readConfig(normalized.configPath))
    return success(`Found ${links.length} link record(s).`, { links, created: false, recoveredCount: 0, failedCount: 0 })
  }

  if (normalized.action === "create") {
    if (!normalized.path || !normalized.target) return failure("Source and link paths are required.")
    const sourceInfo = await runtime.pathInfo(normalized.path)
    if (!sourceInfo.exists) return failure(`Source path does not exist: ${normalized.path}`)
    const linkInfo = await runtime.pathInfo(normalized.target)
    if (linkInfo.exists || linkInfo.isSymlink) return failure(`Link path already exists: ${normalized.target}`)
    await runtime.createSymlink(normalized.path, normalized.target)
    await recordLink(runtime, normalized.configPath, normalized.target, normalized.path, sourceInfo.kind)
    return success(`Symlink created: ${normalized.target} -> ${normalized.path}`, { links: [], created: true, recoveredCount: 0, failedCount: 0 })
  }

  if (normalized.action === "move_link") {
    if (!normalized.path || !normalized.target) return failure("Source and target paths are required.")
    const sourceInfo = await runtime.pathInfo(normalized.path)
    if (!sourceInfo.exists) return failure(`Source path does not exist: ${normalized.path}`)
    const planned = resolveMoveTarget(sourceInfo, normalized.target)
    if (planned.error) return failure(planned.error)
    onEvent({ type: "progress", progress: 40, message: `Moving ${normalized.path}` })
    await runtime.movePath(normalized.path, planned.target)
    onEvent({ type: "progress", progress: 75, message: "Creating symlink" })
    await runtime.createSymlink(planned.target, normalized.path)
    await recordLink(runtime, normalized.configPath, normalized.path, planned.target, sourceInfo.kind)
    return success(`Moved and linked: ${normalized.path} -> ${planned.target}`, { links: [], created: true, recoveredCount: 0, failedCount: 0 })
  }

  const links = parseLinkRecords(await runtime.readConfig(normalized.configPath))
  let recoveredCount = 0
  let failedCount = 0
  for (const link of links) {
    const linkInfo = await runtime.pathInfo(link.link)
    const targetInfo = await runtime.pathInfo(link.target)
    if (!targetInfo.exists) {
      failedCount += 1
      continue
    }
    if (linkInfo.isSymlink && linkInfo.linkTarget?.toLowerCase() === link.target.toLowerCase()) continue
    try {
      await runtime.createSymlink(link.target, link.link)
      recoveredCount += 1
    } catch {
      failedCount += 1
    }
  }
  return success(`Recovery completed: ${recoveredCount} recovered, ${failedCount} failed.`, { links, created: false, recoveredCount, failedCount })
}

async function recordLink(runtime: LinkuRuntime, configPath: string, link: string, target: string, kind: string) {
  const records = parseLinkRecords(await runtime.readConfig(configPath))
  const next = upsertLinkRecord(records, {
    link,
    target,
    type: kind === "dir" ? "directory" : kind === "file" ? "file" : kind,
    createdAt: new Date().toISOString(),
  })
  await runtime.writeConfig(dumpLinkRecords(next), configPath)
}

function success(message: string, data: Partial<LinkuData>): LinkuResult {
  return {
    success: true,
    message,
    data: { links: [], created: false, recoveredCount: 0, failedCount: 0, ...data },
  }
}

function failure(message: string): LinkuResult {
  return {
    success: false,
    message,
    data: { links: [], created: false, recoveredCount: 0, failedCount: 0 },
  }
}

function escapeTomlString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

function unquoteTomlString(value: string): string {
  const trimmed = value.trim()
  const unquoted = trimmed.startsWith('"') && trimmed.endsWith('"') ? trimmed.slice(1, -1) : trimmed
  return unquoted.replace(/\\"/g, '"').replace(/\\\\/g, "\\")
}
