/**
 * @migrated-from src/lib/cards/folder/FolderMainCard.svelte
 * @source-hash sha256:d93869d9290513ffd008d0041f24bd040646e69bb5f10bcd683a6f29c843fc4b
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { FileListPanel } from '$lib/cards/shared';
interface Props {
		initialPath?: string;
	}

export function FolderMainCard(props: Props) {
  const { initialPath } = props
  return (
    <Fragment>

{/*  使用共享的文件列表面板  */}
<FileListPanel initialPath={initialPath} mode="folder"></FileListPanel></Fragment>
  )
}
