/**
 * @migrated-from src/lib/cards/PanelContainer.svelte
 * @source-hash sha256:8c2dc923d863fd8e7c233964b27ccdef496ad68c3097003fe212e597b0c089a8
 * @features card-windows-tabs
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported template node RenderTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { cardConfigStore, type PanelId } from '$lib/stores/cardConfig.js';
import CardRenderer from './CardRenderer.js';
interface Props {
		panelId: PanelId;
		title: string;
		subtitle?: string;
		headerIcon?: any;
		children?: import('svelte').Snippet;
	}

export function PanelContainer(props: Props) {
  const { panelId, title, subtitle, headerIcon: HeaderIcon, children } = props
  const visibleCards = $derived(cardConfigStore.getPanelCards(panelId).filter((c) => c.visible));
  return (
    <Fragment>

<div className="flex h-full flex-col">
	{/*  面板头部  */}
	<header className="flex items-center justify-between px-4 py-3">
		<div className="flex items-center gap-2">
			{HeaderIcon ? (<Fragment>
				<HeaderIcon className="h-5 w-5"></HeaderIcon>
			</Fragment>) : null}
			<div>
				<p className="text-sm font-semibold">{title}</p>
				{subtitle ? (<Fragment>
					<p className="text-muted-foreground text-xs">{subtitle}</p>
				</Fragment>) : null}
			</div>
		</div>
		{children ? (<Fragment>
			{/* TODO unsupported RenderTag */}
		</Fragment>) : null}
	</header>

	{/*  渐变过渡  */}
	<div className="to-background h-4 bg-linear-to-b from-transparent"></div>

	{/*  可滚动内容区  */}
	<div className="bg-background flex-1 overflow-y-auto px-3 py-2">
		<div className="flex flex-col gap-3">
			{visibleCards.map((card) => (<Fragment key={card.id}>
				<CardRenderer cardId={card.id} panelId={panelId}></CardRenderer>
			</Fragment>))}
		</div>
	</div>
</div></Fragment>
  )
}
