/**
 * @migrated-from src/lib/components/panels/ThemePreview.svelte
 * @source-hash sha256:cd585e6484a617bb969ac2c90084d4850b2249a81ce9b8d7ddc868fe538285f4
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Card } from '$lib/components/ui/card';
import { Button } from '$lib/components/ui/button';
import { Input } from '$lib/components/ui/input';
import { Badge } from '$lib/components/ui/badge';
import { Separator } from '$lib/components/ui/separator';

export function ThemePreview() {
  return (
    <Fragment>

<div className="bg-background space-y-6 p-6">
	<div className="space-y-2">
		<h2 className="text-foreground text-3xl font-bold">主题预览</h2>
		<p className="text-muted-foreground">查看当前主题的所有颜色和组件样式</p>
	</div>

	<Separator></Separator>

	{/*  颜色卡片  */}
	<div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
		{/*  Primary  */}
		<Card className="bg-primary text-primary-foreground p-6">
			<h3 className="mb-2 text-lg font-semibold">Primary</h3>
			<p className="text-sm opacity-90">主色调,用于主要操作和强调</p>
			<div className="mt-4 flex gap-2">
				<Button variant="secondary" size="sm">按钮</Button>
				<Badge>标签</Badge>
			</div>
		</Card>

		{/*  Secondary  */}
		<Card className="bg-secondary text-secondary-foreground p-6">
			<h3 className="mb-2 text-lg font-semibold">Secondary</h3>
			<p className="text-sm opacity-90">次要色,用于辅助元素</p>
			<div className="mt-4 flex gap-2">
				<Button variant="outline" size="sm">按钮</Button>
				<Badge variant="secondary">标签</Badge>
			</div>
		</Card>

		{/*  Accent  */}
		<Card className="bg-accent text-accent-foreground p-6">
			<h3 className="mb-2 text-lg font-semibold">Accent</h3>
			<p className="text-sm opacity-90">强调色,用于突出显示</p>
			<div className="mt-4 flex gap-2">
				<Button variant="ghost" size="sm">按钮</Button>
				<Badge variant="outline">标签</Badge>
			</div>
		</Card>

		{/*  Muted  */}
		<Card className="bg-muted text-muted-foreground p-6">
			<h3 className="mb-2 text-lg font-semibold">Muted</h3>
			<p className="text-sm opacity-90">柔和色,用于背景和禁用状态</p>
			<div className="mt-4">
				<Input placeholder="输入框示例" disabled></Input>
			</div>
		</Card>

		{/*  Card  */}
		<Card className="bg-card text-card-foreground border p-6">
			<h3 className="mb-2 text-lg font-semibold">Card</h3>
			<p className="text-muted-foreground text-sm">卡片背景,用于内容容器</p>
			<div className="mt-4">
				<Input placeholder="输入框示例"></Input>
			</div>
		</Card>

		{/*  Destructive  */}
		<Card className="bg-destructive text-primary-foreground p-6">
			<h3 className="mb-2 text-lg font-semibold">Destructive</h3>
			<p className="text-sm opacity-90">破坏性操作,如删除、警告</p>
			<div className="mt-4">
				<Button variant="destructive" size="sm">删除</Button>
			</div>
		</Card>
	</div>

	<Separator></Separator>

	{/*  按钮变体  */}
	<div className="space-y-4">
		<h3 className="text-xl font-semibold">按钮变体</h3>
		<div className="flex flex-wrap gap-3">
			<Button variant="default">Default</Button>
			<Button variant="secondary">Secondary</Button>
			<Button variant="outline">Outline</Button>
			<Button variant="ghost">Ghost</Button>
			<Button variant="link">Link</Button>
			<Button variant="destructive">Destructive</Button>
		</div>
	</div>

	<Separator></Separator>

	{/*  表单元素  */}
	<div className="space-y-4">
		<h3 className="text-xl font-semibold">表单元素</h3>
		<div className="grid max-w-2xl grid-cols-1 gap-4 md:grid-cols-2">
			<div className="space-y-2">
				<label className="text-sm font-medium" htmlFor="theme-preview-input-normal">普通输入框</label>
				<Input id="theme-preview-input-normal" placeholder="请输入内容..."></Input>
			</div>
			<div className="space-y-2">
				<label className="text-sm font-medium" htmlFor="theme-preview-input-disabled">禁用输入框</label>
				<Input id="theme-preview-input-disabled" placeholder="禁用状态" disabled></Input>
			</div>
		</div>
	</div>

	<Separator></Separator>

	{/*  文字样式  */}
	<div className="space-y-4">
		<h3 className="text-xl font-semibold">文字样式</h3>
		<div className="space-y-2">
			<p className="text-foreground">这是前景色文字 (foreground)</p>
			<p className="text-muted-foreground">这是柔和色文字 (muted-foreground)</p>
			<p className="text-primary">这是主色调文字 (primary)</p>
			<p className="text-secondary-foreground">这是次要色文字 (secondary-foreground)</p>
			<p className="text-accent-foreground">这是强调色文字 (accent-foreground)</p>
		</div>
	</div>

	<Separator></Separator>

	{/*  边框和圆角  */}
	<div className="space-y-4">
		<h3 className="text-xl font-semibold">边框和圆角</h3>
		<div className="grid grid-cols-2 gap-4 md:grid-cols-4">
			<div className="rounded-sm border p-4 text-center">
				<p className="text-sm">rounded-sm</p>
			</div>
			<div className="rounded-md border p-4 text-center">
				<p className="text-sm">rounded-md</p>
			</div>
			<div className="rounded-lg border p-4 text-center">
				<p className="text-sm">rounded-lg</p>
			</div>
			<div className="rounded-xl border p-4 text-center">
				<p className="text-sm">rounded-xl</p>
			</div>
		</div>
	</div>

	<Separator></Separator>

	{/*  阴影  */}
	<div className="space-y-4">
		<h3 className="text-xl font-semibold">阴影效果</h3>
		<div className="grid grid-cols-2 gap-4 md:grid-cols-4">
			<div className="bg-card rounded-lg p-4 text-center shadow-sm">
				<p className="text-sm">shadow-sm</p>
			</div>
			<div className="bg-card rounded-lg p-4 text-center shadow">
				<p className="text-sm">shadow</p>
			</div>
			<div className="bg-card rounded-lg p-4 text-center shadow-md">
				<p className="text-sm">shadow-md</p>
			</div>
			<div className="bg-card rounded-lg p-4 text-center shadow-lg">
				<p className="text-sm">shadow-lg</p>
			</div>
		</div>
	</div>
</div></Fragment>
  )
}
