//! The embedded bundles are the shipping path, so they are tested as product, not as fixtures.
//!
//! `crates/xiranite-quickjs-executor/bundles/` is generated by `scripts/embed-node-bundles.ts` from
//! `artifacts/node-bundles/manifest.json`, and a registration site reads it with
//! `include_str!("../bundles/<id>.js")` (ADR-0074 §6: the host binary carries every linked node). These
//! tests fail in the ways that matter here: a bundle that no longer evaluates, an index that drifted from
//! the files beside it, and — the one every pin in this crate owes — a green run that would also happen if
//! nothing ran at all.

mod support;

use std::path::PathBuf;

use support::Harness;

use xiranite_node_registry::BuiltInNode;
use xiranite_quickjs_executor::{JsNode, JsNodeSpec};
use xiranite_node_registry::NodeDescriptor;

/// The real `linedup` bundle, exactly as a shipping host binary would embed it.
static LINEDUP_BUNDLE: &str = include_str!("../bundles/linedup.js");

static LINEDUP_SPEC: JsNodeSpec = JsNodeSpec::pure(
    NodeDescriptor::new("linedup", "0.1.0", 1).budget(8 * 1024 * 1024, 1),
    LINEDUP_BUNDLE,
    "filterLines",
    "linedup completed",
);

static LINEDUP_NODE: JsNode = JsNode::new(&LINEDUP_SPEC);

/// A node that only throws while its module body evaluates.
static BROKEN_BUNDLE: &str = r#"
throw new Error("the bundle is broken on purpose");
export function run(input) { return input; }
"#;

static BROKEN_SPEC: JsNodeSpec = JsNodeSpec::pure(
    NodeDescriptor::new("quickjs-embed-test.broken", "0.1.0", 1).budget(1024 * 1024, 1),
    BROKEN_BUNDLE,
    "run",
    "unreachable",
);

static BROKEN_NODE: JsNode = JsNode::new(&BROKEN_SPEC);

fn index_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bundles/index.json")
}

/// The product claim: the node's own TypeScript, bundled and run inside the host, answers the same numbers
/// the same code answers under Bun. Those five values were measured against `bun -e` importing
/// `packages/nodes/linedup/src/core.ts` with the identical request document.
#[test]
fn the_embedded_linedup_bundle_answers_the_numbers_bun_answers() {
    let harness = Harness::new("embedded-linedup", "linedup");
    let mut host = harness.host();
    let request = r#"{"sourceLines":["alpha","beta","gamma","beta"],"filterLines":["beta"],"caseSensitive":false,"sort":true}"#;

    let document = LINEDUP_NODE
        .run(request, &mut host)
        .expect("the embedded linedup bundle runs");
    let value: serde_json::Value = serde_json::from_str(&document).expect("the document is JSON");

    assert_eq!(value["success"], true, "{value}");
    assert_eq!(value["message"], "linedup completed", "{value}");
    assert_eq!(value["data"]["filteredLines"][0], "alpha", "{value}");
    assert_eq!(value["data"]["filteredLines"][1], "gamma", "{value}");
    assert_eq!(value["data"]["filteredLines"][2], serde_json::Value::Null, "two lines kept: {value}");
    assert_eq!(value["data"]["removedLines"][0], "beta", "{value}");
    assert_eq!(value["data"]["keptCount"], 2, "{value}");
    assert_eq!(value["data"]["removedCount"], 1, "{value}");
    // How this could pass while nothing ran: `data` would be an empty object and every field above would be
    // `null`. The filtering happens inside the JavaScript, so a green `keptCount` is proof the bundle evaluated.
    // How it could pass while the *wrong* code ran: `sort` and `caseSensitive` are honoured by the node's own
    // logic, and a bundle that skipped them would reorder these lines or keep the `beta`.
}

/// The index and the files beside it must describe each other: a registration site that `include_str!`s a
/// bundle the index does not list is a node shipped without a record of which export names it answers.
#[test]
fn the_index_lists_exactly_the_bundles_on_disk() {
    let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("bundles");
    let text = std::fs::read_to_string(index_path())
        .unwrap_or_else(|error| panic!("{} could not be read: {error}", index_path().display()));
    let index: serde_json::Value = serde_json::from_str(&text).expect("index.json is JSON");
    let entries = index["nodes"]
        .as_array()
        .unwrap_or_else(|| panic!("index.json has no nodes array: {text}"));
    assert!(
        !entries.is_empty(),
        "an empty embedded set means the host binary carries no scripted node at all"
    );

    let mut listed: Vec<String> = Vec::new();
    for entry in entries {
        let file = entry["file"]
            .as_str()
            .unwrap_or_else(|| panic!("an index entry has no file name: {entry}"));
        let run = entry["run"]
            .as_str()
            .unwrap_or_else(|| panic!("{file} has no run export name: {entry}"));
        let path = directory.join(file);
        let source = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{file} is listed in the index but missing: {error}"));
        assert!(
            source.contains(&format!("function {run}")) || source.contains(&format!("{run},")) || source.contains(&format!(" {run} ")),
            "{file} does not appear to define its advertised run export {run:?}"
        );
        listed.push(file.to_string());
    }

    let on_disk: Vec<String> = std::fs::read_dir(&directory)
        .expect("bundles/ is readable")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().to_string())
        .filter(|name| name.ends_with(".js"))
        .collect();
    for name in &on_disk {
        assert!(
            listed.contains(name),
            "{name} sits in bundles/ but the index does not list it: {listed:?}"
        );
    }
}

/// The pin's own negative control: a bundle that fails while its module body evaluates must surface as an
/// engine-level failure, not as a document. Without this, the first test could read green for a bundle that
/// never got as far as its `run` export.
#[test]
fn a_bundle_that_throws_at_module_level_is_reported_as_a_failure() {
    let harness = Harness::new("embedded-broken", "quickjs-embed-test.broken");
    let mut host = harness.host();
    let error = BROKEN_NODE
        .run(r#"{"path":"/work"}"#, &mut host)
        .expect_err("a module-level throw cannot produce a result document");
    assert!(
        error.message.contains("the bundle") && error.message.contains("rejected while evaluating"),
        "the failure must say the bundle rejected, got {:?}",
        error.message
    );
    assert!(
        error.message.contains("the bundle is broken on purpose"),
        "the engine's own message must reach the operator, got {:?}",
        error.message
    );
}
