/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { ActionTabs, ClickTarget, ExecutionActions, ProgressBar, TerminalThemeProvider, WorkbenchField, WorkbenchPanel, resolveTerminalTheme, terminalIcon, useAnimation, useTerminalChromeActions, useTerminalTheme, useTerminalUiSession } from "@xiranite/cli-runtime/terminal/opentui"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { BandiaInput, BandiaItemResult, BandiaResult } from "./core.js"

export function BandiaTui(props: TerminalUiScreenProps<BandiaInput, BandiaResult>) { const [theme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit"); return <TerminalThemeProvider theme={resolveTerminalTheme(theme === "inherit" ? "nord" : theme)}><BandiaWorkbench {...props}/></TerminalThemeProvider> }
function BandiaWorkbench({ definition, language, onExit }: TerminalUiScreenProps<BandiaInput, BandiaResult>) {
  const theme = useTerminalTheme(), t = createTerminalTranslator(language), session = useTerminalUiSession(definition), frame = useAnimation({ intervalMs: session.phase === "running" ? 90 : 500 })
  const data = session.result?.data, action = String(session.values.action ?? "extract"), results = data?.results ?? [], mappings = data?.pathMappings ?? []
  useTerminalChromeActions({ onReset: session.reset, onExit })
  useKeyboard((key) => { if (key.name === "escape") { if (session.confirming) session.dismissConfirmation(); else onExit() } })
  if (session.confirming) return <Confirm onConfirm={() => void session.confirmExecute()} onDismiss={session.dismissConfirmation}/>
  const field = (id: string) => definition.schema.fields.find((item) => item.id === id)!
  const Field = ({ id, width }: { id: string; width?: `${number}%` }) => session.fields.some((item) => item.id === id) ? <box width={width} flexGrow={width ? 0 : 1}><WorkbenchField field={field(id)} value={session.values[id]} error={session.fieldErrors[id]} focused={session.focusedControlId === id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(id)} onChange={(value) => session.setField(id, value)}/></box> : null
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden">
    <box height={4} flexShrink={0} borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("status")} BANDIA // ARCHIVE PIPELINE`}</b></text><text fg={theme.colors.mutedForeground}>归档输入、命令编排与路径映射输出</text></box><text fg={session.phase === "running" ? theme.colors.warning : theme.colors.success}>{`${session.phase === "running" ? "PROCESSING" : "PIPELINE READY"} ${["◐", "◓", "◑", "◒"][frame % 4]}`}</text></box>
    <box height={3} flexShrink={0} marginTop={1} flexDirection="row" justifyContent="space-between"><ActionTabs id="field-action" options={field("action").options ?? []} value={action} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)}/><text fg={theme.colors.mutedForeground}>{`⌕ ${results.length} · ✓ ${results.filter((item) => item.success).length} · ⚠ ${data?.failedCount ?? 0}`}</text></box>
    <box height={7} flexShrink={0} flexDirection="row" gap={1}>{action === "repack" ? <Field id="mappingText" width="46%"/> : <Field id="paths" width="46%"/>}{action === "extract" ? <><Field id="extractMode"/><Field id="overwriteMode"/></> : action === "compress" || action === "repack" ? <><Field id="compressFormat"/><Field id="outputDir"/></> : <Field id="efuOutputPath" width="24%"/>}<box flexGrow={1} flexDirection="column" borderStyle="rounded" borderColor={session.dangerous ? theme.colors.error : theme.colors.border} paddingLeft={1}><text fg={session.dangerous ? theme.colors.error : theme.colors.mutedForeground}>{session.dangerous ? "⚠ LIVE FILESYSTEM" : "◇ DRY RUN"}</text><box flexGrow={1}/><ExecutionActions session={session} executeLabel={actionLabel(action)} confirmLabel="⚠ 确认执行"/></box></box>
    <box flexGrow={1} minHeight={0} marginTop={1} flexDirection="row" gap={1}><WorkbenchPanel title="输入队列" description="归档或源目录路径" width="29%"><scrollbox flexGrow={1}>{String(session.values.paths ?? "").split(/\r?\n/).filter(Boolean).map((path, index) => <text key={`${path}-${index}`}>{`▣ ${path}`}</text>)}{!String(session.values.paths ?? "").trim() ? <text fg={theme.colors.mutedForeground}>粘贴路径后显示队列。</text> : null}</scrollbox></WorkbenchPanel><WorkbenchPanel title="命令舱" description="任务、并发与安全状态" width="33%"><box flexDirection="column" alignItems="center"><ascii-font text={session.phase === "running" ? String(session.progress).padStart(3, "0") : "RDY"} font="tiny" color={[theme.colors.primary, theme.colors.focusRing]}/><text fg={theme.colors.primary}><b>{actionLabel(action)}</b></text><text fg={theme.colors.mutedForeground}>{session.preview[0] ?? "准备执行"}</text></box><ProgressBar value={session.progress} label={session.status || "READY"}/><scrollbox flexGrow={1}>{session.logs.map((line, index) => <text key={`${line}-${index}`} fg={theme.colors.mutedForeground}>{`${String(index + 1).padStart(2, "0")} ${line}`}</text>)}</scrollbox></WorkbenchPanel><WorkbenchPanel title={`映射输出 · ${mappings.length}`} description="结果、映射与失败项" flexGrow={1}><scrollbox flexGrow={1}>{results.length ? results.map((item, index) => <ResultRow key={`${item.sourcePath}-${index}`} item={item}/>) : mappings.length ? mappings.map((item, index) => <box key={`${item.archivePath}-${index}`} flexDirection="column"><text fg={theme.colors.primary}>{`▣ ${item.archivePath}`}</text><text fg={theme.colors.success}>{`↳ ${item.extractedPath}`}</text></box>) : <text fg={theme.colors.mutedForeground}>执行后显示路径映射和每项结果。</text>}</scrollbox></WorkbenchPanel></box>
  </box>
}
function ResultRow({ item }: { item: BandiaItemResult }) { const theme = useTerminalTheme(); return <box flexDirection="column" borderStyle="single" borderColor={item.success ? theme.colors.border : theme.colors.error} paddingLeft={1}><text fg={item.success ? theme.colors.success : theme.colors.error}><b>{`${item.success ? "✓" : "⚠"} ${item.sourcePath}`}</b></text><text fg={theme.colors.mutedForeground}>{`↳ ${item.outputPath ?? item.archivePath ?? item.error ?? "—"}`}</text></box> }
function Confirm({ onConfirm, onDismiss }: { onConfirm: () => void; onDismiss: () => void }) { const theme = useTerminalTheme(); return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="64%" height={10} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>⚠ 确认真实归档操作</b></text><text>归档、解压与可能的源文件删除会真实写入磁盘。</text><text fg={theme.colors.mutedForeground}>请先检查输入队列和映射输出。</text><box flexGrow={1}/><box flexDirection="row" gap={2}><ClickTarget id="confirm-execute" bordered onClick={onConfirm}>确认执行</ClickTarget><ClickTarget id="confirm-dismiss" onClick={onDismiss}>返回</ClickTarget></box></box></box> }
function actionLabel(action: string) { return action === "extract" ? "⇩ 解压归档" : action === "compress" ? "▣ 压缩归档" : action === "repack" ? "↻ 重打包" : "⇧ 导出 EFU" }
