/**
 * @migrated-from src/lib/cards/pageList/PageListCard.svelte
 * @source-hash sha256:d579024de54c968191a47c40661a8c539fb556e82e537a4be3054ddfb712aaf3
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute BindDirective; template node KeyBlock
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Button } from '$lib/components/ui/button';
import { Input } from '$lib/components/ui/input';
import { Slider } from '$lib/components/ui/slider';
import { Search, Grid3x3, List, Image as ImageIcon, Navigation, Sparkles } from 'lucide-react';
import { bookStore } from '$lib/stores/book.js';
import {
		unifiedThumbnailStore,
		generateThumbKey,
		type ThumbnailSource,
		type ThumbnailEntry
	} from '$lib/stores/unifiedThumbnailStore.js';
import { upscaleStore } from '$lib/stackview/stores/upscaleStore.js';
import { settingsManager } from '$lib/settings/settingsManager';
import { FileSystemAPI } from '$lib/api';
import { deleteArchiveEntry } from '$lib/api/archive';
import { showErrorToast, showSuccessToast } from '$lib/utils/toast';
import type { Page } from '$lib/types';
import PageContextMenu from './PageContextMenu.js';
import PageIndexBadge from './PageIndexBadge.js';
type ViewMode = 'list' | 'grid' | 'thumb';
interface PageItem {
		index: number;
		name: string;
		path: string;
		innerPath?: string;
	}

export function PageListCard() {
  let items = $state<PageItem[]>([]);

  let searchQuery = $state('');

  let viewMode = $state<ViewMode>('list');

  let scrollContainer: HTMLDivElement | undefined;

  let prefetching = $state(false);

  let prefetchDone = $state(false);

  let prefetchError = $state<string | null>(null);

  let followProgress = $state(settingsManager.getSettings().panels?.pageListFollowProgress ?? true);

  settingsManager.addListener((newSettings) => {
      followProgress = newSettings.panels?.pageListFollowProgress ?? true;
    });

  function toggleFollowProgress() {
      const newValue = !followProgress;
      settingsManager.updateNestedSettings('panels', {
        pageListFollowProgress: newValue
      });
      followProgress = newValue;
    }

  let contextMenu = $state<{
      visible: boolean;
      x: number;
      y: number;
      item: PageItem | null;
    }>({
      visible: false,
      x: 0,
      y: 0,
      item: null
    });

  function handleContextMenu(event: MouseEvent, item: PageItem) {
      event.preventDefault();
      contextMenu = {
        visible: true,
        x: event.clientX,
        y: event.clientY,
        item
      };
    }

  function closeContextMenu() {
      contextMenu = { ...contextMenu, visible: false, item: null };
    }

  const filteredItems = $derived(
      searchQuery.trim()
        ? items.filter((item) => {
            const q = searchQuery.toLowerCase();
            return item.name.toLowerCase().includes(q) || (item.index + 1).toString().includes(q);
          })
        : items
    );

  const currentPageIndex = $derived(bookStore.currentPageIndex);

  const upscaleEnabled = $derived(upscaleStore.enabled);

  const upscaleStoreVersion = $derived(upscaleStore.version);

  function isPageUpscaled(pageIndex: number): boolean {
      void upscaleStoreVersion;
      return upscaleStore.isPageUpscaled(pageIndex);
    }

  let previewIndex = $state<number | null>(null);

  const displayIndex = $derived(
      followProgress ? currentPageIndex : (previewIndex ?? currentPageIndex)
    );

  $effect(() => {
      const idx = followProgress ? currentPageIndex : previewIndex;
      if (idx === null || idx < 0 || !scrollContainer) return;
      requestAnimationFrame(() => {
        const el = scrollContainer?.querySelector(`[data-page-index="${idx}"]`) as HTMLElement | null;
        if (el) {
          el.scrollIntoView({ block: 'center', behavior: 'smooth' });
        }
      });
    });

  $effect(() => {
      const book = bookStore.currentBook;
      if (book?.pages) {
        items = book.pages.map((page: Page, index: number) => ({
          index,
          name: page.name || `第 ${index + 1} 页`,
          path: page.path || '',
          innerPath: page.innerPath
        }));
        prefetchDone = false;
        prefetchError = null;
      } else {
        items = [];
      }
    });

  onMount(() => {
      // unifiedThumbnailStore uses SvelteMap (reactive), no manual subscription needed
    });

  onDestroy(() => {
      // No manual cleanup needed for unifiedThumbnailStore
    });

  function getPageThumbnailSource(
      pageIndex: number
    ): { source: ThumbnailSource; page: Page } | null {
      const book = bookStore.currentBook;
      const page = book?.pages?.[pageIndex];
      if (!book || !page) return null;

      const source: ThumbnailSource =
        book.type === 'archive' || book.type === 'epub'
          ? {
              kind: 'archiveEntry',
              archivePath: book.path,
              innerPath: page.innerPath ?? page.path,
              entryIndex: page.entryIndex,
              fileSize: page.size
            }
          : {
              kind: 'bookPage',
              bookPath: book.path,
              pageIndex,
              pagePath: page.path,
              fileSize: page.size
            };
      return { source, page };
    }

  function getThumbnail(pageIndex: number): ThumbnailEntry | null {
      const result = getPageThumbnailSource(pageIndex);
      if (!result) return null;
      const key = generateThumbKey(result.source, 256);
      return unifiedThumbnailStore.getEntry(key);
    }

  function goToPage(index: number) {
      bookStore.goToPage(index);
    }

  async function handleDeletePage(item: PageItem) {
      const book = bookStore.currentBook;
      const page = book?.pages?.[item.index];
      if (!book || !page) return;

      try {
        const nextIndex = Math.max(0, Math.min(item.index, book.pages.length - 2));

        if (book.type === 'archive') {
          const innerPath = page.innerPath ?? item.innerPath ?? page.path ?? item.path;
          if (!innerPath) {
            throw new Error('压缩包内路径为空');
          }

          await FileSystemAPI.releaseResourcesForPath(book.path);
          await deleteArchiveEntry(book.path, innerPath);
          await bookStore.openBook(book.path, { initialPage: nextIndex });
          showSuccessToast('删除成功', item.name);
          return;
        }

        const targetPath = page.path || item.path;
        await FileSystemAPI.releaseResourcesForPath(targetPath);
        await FileSystemAPI.moveToTrashAsync(targetPath);
        FileSystemAPI.recordTrashDeletion([targetPath]);
        if (book.path && book.path !== targetPath) {
          await bookStore.openBook(book.path, { initialPage: nextIndex });
        }
        showSuccessToast('删除成功', item.name);
      } catch (err) {
        showErrorToast('删除失败', err instanceof Error ? err.message : String(err));
      }
    }

  async function requestThumbnail(pageIndex: number) {
      const result = getPageThumbnailSource(pageIndex);
      if (!result) return;
      const { source } = result;
      const key = generateThumbKey(source, 256);
      if (unifiedThumbnailStore.hasThumbnail(key)) return;
      if (unifiedThumbnailStore.isLoading(key)) return;

      await unifiedThumbnailStore.requestThumbnails(
        [{ key, source, maxSize: 256 }],
        `pageList-${bookStore.currentBook!.path}`,
        'visible'
      );
    }

  function requestFilteredThumbnails() {
      const book = bookStore.currentBook;
      if (!book?.pages?.length || viewMode === 'list') return;

      const requests: { key: string; source: ThumbnailSource; maxSize: number }[] = [];
      for (const item of filteredItems) {
        const result = getPageThumbnailSource(item.index);
        if (!result) continue;
        const key = generateThumbKey(result.source, 256);
        if (unifiedThumbnailStore.hasThumbnail(key)) continue;
        if (unifiedThumbnailStore.isLoading(key)) continue;
        requests.push({ key, source: result.source, maxSize: 256 });
      }

      if (requests.length === 0) return;
      unifiedThumbnailStore.requestThumbnails(requests, `pageList-${book.path}`, 'visible');
    }

  $effect(() => {
      // 读取依赖以建立响应式追踪
      const _items = filteredItems;
      const _mode = viewMode;
      if (_mode === 'list') return;
      queueMicrotask(() => requestFilteredThumbnails());
    });

  async function prefetchAllThumbnails() {
      const book = bookStore.currentBook;
      if (!book?.pages?.length) return;
      if (prefetching) return;

      prefetching = true;
      prefetchError = null;

      try {
        const items = book.pages.map((page, pageIndex) => {
          const source: ThumbnailSource =
            book.type === 'archive' || book.type === 'epub'
              ? {
                  kind: 'archiveEntry',
                  archivePath: book.path,
                  innerPath: page.innerPath ?? page.path,
                  entryIndex: page.entryIndex,
                  fileSize: page.size
                }
              : {
                  kind: 'bookPage',
                  bookPath: book.path,
                  pageIndex,
                  pagePath: page.path,
                  fileSize: page.size
                };
          return { key: generateThumbKey(source, 256), source, maxSize: 256 };
        });
        await unifiedThumbnailStore.requestThumbnails(items, `pageList-${book.path}`, 'background');
        prefetchDone = true;
      } catch (err) {
        prefetchError = err instanceof Error ? err.message : String(err);
      } finally {
        prefetching = false;
      }
    }
  return (
    <Fragment>

<div className="flex h-full flex-col space-y-2">
	{/*  搜索和视图切换  */}
	<div className="flex items-center gap-2">
		<div className="relative flex-1">
			<Search className="text-muted-foreground absolute top-1/2 left-2 h-3 w-3 -translate-y-1/2"></Search>
			<Input type="text" placeholder="搜索页面..." className="h-7 pl-7 text-xs"></Input>
		</div>
		{/*  跟随进度开关  */}
		<Button variant={followProgress ? 'default' : 'ghost'} size="sm" className="h-7 w-7 p-0" onClick={toggleFollowProgress} title={followProgress ? '跟随进度：开' : '跟随进度：关'}>
			<Navigation className="h-3 w-3"></Navigation>
		</Button>
		<div className="flex gap-0.5">
			<Button variant={viewMode === 'list' ? 'default' : 'ghost'} size="sm" className="h-7 w-7 p-0" onClick={() => (viewMode = 'list')}>
				<List className="h-3 w-3"></List>
			</Button>
			<Button variant={viewMode === 'grid' ? 'default' : 'ghost'} size="sm" className="h-7 w-7 p-0" onClick={() => (viewMode = 'grid')}>
				<Grid3x3 className="h-3 w-3"></Grid3x3>
			</Button>
			<Button variant={viewMode === 'thumb' ? 'default' : 'ghost'} size="sm" className="h-7 w-7 p-0" onClick={() => (viewMode = 'thumb')}>
				<ImageIcon className="h-3 w-3"></ImageIcon>
			</Button>
		</div>
		<Button variant="secondary" size="sm" className="h-7 px-2" disabled={prefetching || items.length === 0} onClick={() => void prefetchAllThumbnails()}>
			<Sparkles className="h-3 w-3"></Sparkles>
		</Button>
	</div>

	{/*  页面统计  */}
	<div className="text-muted-foreground text-[10px]">
		共 {items.length} 页 {searchQuery ? `(显示 ${filteredItems.length})` : ''}
	</div>
	{prefetching ? (<Fragment>
		<div className="text-muted-foreground text-[10px]">正在预加载全部缩略图...</div>
	</Fragment>) : (<Fragment>{prefetchDone ? (<Fragment>
		<div className="text-muted-foreground text-[10px]">全部缩略图已预加载</div>
	</Fragment>) : (<Fragment>{prefetchError ? (<Fragment>
		<div className="text-destructive text-[10px]">预加载失败: {prefetchError}</div>
	</Fragment>) : null}</Fragment>)}</Fragment>)}

	{/*  页面列表  */}
	<div className="min-h-0 flex-1 overflow-y-auto">
		{/* TODO unsupported KeyBlock */}
	</div>

	{/*  底部固定 Slider  */}
	{items.length > 1 ? (<Fragment>
		<div className="border-border flex shrink-0 items-center gap-2 border-t pt-2">
			<span className="text-muted-foreground w-6 text-right font-mono text-[10px]">{displayIndex + 1}</span>
			<Slider type="single" value={displayIndex} min={0} max={items.length - 1} step={1} className="flex-1" onValueChange={(v: number) => {
					if (followProgress) {
						// 跟随模式：直接翻页
						if (v !== currentPageIndex) {
							goToPage(v);
						}
					} else {
						// 预览模式：只更新预览位置，不翻页
						previewIndex = v;
					}
				}}></Slider>
			<span className="text-muted-foreground w-6 font-mono text-[10px]">{items.length}</span>
		</div>
	</Fragment>) : null}
</div>

{/*  右键菜单  */}
<PageContextMenu item={contextMenu.item} x={contextMenu.x} y={contextMenu.y} visible={contextMenu.visible} onClose={closeContextMenu} onGoToPage={goToPage} onDelete={handleDeletePage}></PageContextMenu>

</Fragment>
  )
}
