// @vitest-environment happy-dom
import { afterEach, describe, expect, test, vi } from "vitest"
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import type { NodeFilePickerOptions, NodeHostApi, NodeRunEvent, NodeRunResult } from "@xiranite/contract"
import type { VertData, VertInput } from "@xiranite/node-vert/core"
import { NODE_SURFACE_TEST_MODES, NODE_SURFACE_TEST_SPECS } from "@/nodes/shared/nodeSurfaceTestUtils"
import { Component } from "./Component"
import type { VertCardState } from "./types"

const surface = vi.hoisted(() => ({ height: 420, width: 720 }))
vi.mock("@/nodes/shared/useNodeSurface", async (original) => { const actual = await original<typeof import("@/nodes/shared/useNodeSurface")>(); return { ...actual, useNodeSurface: () => ({ ref: { current: null }, width: surface.width, height: surface.height, mode: actual.resolveNodeSurfaceMode(surface), density: actual.resolveNodeSurfaceDensity(actual.resolveNodeSurfaceMode(surface)) }) } })
afterEach(() => { cleanup(); vi.clearAllMocks(); Object.assign(surface, NODE_SURFACE_TEST_SPECS.regular) })

describe("VERT workspace GUI", () => {
  test.each(NODE_SURFACE_TEST_MODES)("renders the %s surface", (mode) => { Object.assign(surface, NODE_SURFACE_TEST_SPECS[mode]); render(<Component compId="vert-1" host={createHost({ pathsText: "D:/images/demo.png" })} />); expect(screen.getByText(/VERT/)).toBeTruthy(); const view = mode === "collapsed" ? "collapsed" : mode === "compact" || mode === "portrait" ? "compact" : "full"; expect(screen.getByTestId(`vert-${view}-view`)).toBeTruthy() })
  test("plans native CLI conversion from the full VERT surface", async () => { const host = createHost({ pathsText: "D:/images/demo.png", targetFormat: "webp", engine: "auto" }); render(<Component compId="vert-1" host={host} />); await userEvent.setup().click(screen.getByRole("button", { name: "预演方案" })); await waitFor(() => expect(host.runCalls).toHaveLength(1)); expect(host.runCalls[0]).toEqual(expect.objectContaining({ nodeId: "vert", input: expect.objectContaining({ action: "plan", targetFormat: "webp", engine: "auto" }) })) })
  test("accepts a non-image browser file dropped without File.path", async () => { const host = createHost({ engine: "wasm" }); render(<Component compId="vert-1" host={host} />); const file = new File(["audio"], "voice.flac", { type: "audio/flac" }); fireEvent.drop(screen.getByTestId("vert-upload-dropzone"), { dataTransfer: { files: [file] } }); await waitFor(() => expect(screen.getByText("voice.flac")).toBeTruthy()); expect(screen.getByText(".flac · 音频")).toBeTruthy() })
  test("opens a universal native picker instead of the shared image-only default", async () => { const host = createHost({}); render(<Component compId="vert-1" host={host} />); await userEvent.setup().click(screen.getByRole("button", { name: "选择任意文件" })); expect(host.pickerOptions?.title).toBe("选择要转换的文件"); expect(host.pickerOptions?.filters?.map((filter) => filter.pattern).join(";")).toContain("*.flac"); expect(host.pickerOptions?.filters?.map((filter) => filter.pattern).join(";")).toContain("*.mp4"); expect(host.pickerOptions?.filters?.map((filter) => filter.pattern).join(";")).toContain("*.epub") })
  test("keeps preview available for a genuine browser Wasm drop", async () => { const host = createHost({ engine: "wasm", targetFormat: "mp3" }); render(<Component compId="vert-1" host={host} />); fireEvent.drop(screen.getByTestId("vert-upload-dropzone"), { dataTransfer: { files: [new File(["audio"], "voice.flac", { type: "audio/flac" })] } }); const preview = await screen.findByRole("button", { name: "预演方案" }); expect(preview).not.toBeDisabled(); await userEvent.setup().click(preview); await waitFor(() => expect(host.stateValue.result?.commands[0]?.command).toBe("wasm:ffmpeg")); expect(host.runCalls).toHaveLength(0) })
})

type TestHost = NodeHostApi<VertCardState, Partial<VertCardState>> & { stateValue: VertCardState; runCalls: Array<{ nodeId: string; input: VertInput }>; pickerOptions?: NodeFilePickerOptions }
function createHost(initial: VertCardState): TestHost { const host = { stateValue: { ...initial }, runCalls: [], pickerOptions: undefined, contract: { name: "xiranite.node-host", version: "1", supportedCapabilities: ["contract", "state", "runner", "localFiles"], hasCapability: () => true }, env: { theme: "light", platform: "web" }, state: { getData: () => host.stateValue, patchData: (patch: Partial<VertCardState>) => { host.stateValue = { ...host.stateValue, ...patch } } }, runner: { run: async <TInput, TData>(nodeId: string, input: TInput, onEvent?: (event: NodeRunEvent) => void): Promise<NodeRunResult<TData>> => { host.runCalls.push({ nodeId, input: input as VertInput }); onEvent?.({ type: "progress", progress: 100, message: "Plan ready." }); return { success: true, message: "Planned 1 conversion.", data: result as TData } } }, localFiles: { pickFiles: async (options?: NodeFilePickerOptions) => { host.pickerOptions = options; return ["D:/images/demo.png"] } }, getData: <T,>() => host.stateValue as T, patchData: (_id: string, patch: Partial<VertCardState>) => host.state.patchData(patch), listComponents: () => [], updateComponent: () => undefined } satisfies TestHost; return host }
const result: VertData = { capabilities: { wasm: true, magick: "magick" }, commands: [{ converter: "magick", command: "magick", args: ["demo.png", "demo.webp"], inputPath: "D:/images/demo.png", outputPath: "D:/images/demo.webp" }], commandResults: [], selectedPaths: ["D:/images/demo.png"], outputPaths: ["D:/images/demo.webp"], errors: [], wasmFallbackRequired: false }
