/**
 * @migrated-from src/lib/components/layout/LeftSidebar.svelte
 * @source-hash sha256:3c2fce2245cdca6b6224995c39adc4b6199ddd2c4b714e90a7a7f79767404b46
 * @features panels-toolbar-shell,startup-window-cli-lifecycle,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute BindDirective; attribute ClassDirective; template node ConstTag; template node SnippetBlock
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import {
		Pin,
		PinOff,
		GripVertical,
		GripHorizontal,
		MousePointer2,
		ArrowDownRight
	} from 'lucide-react';
import MagicCard from '$lib/components/ui/MagicCard.js';
import {
		activePanel,
		setActivePanelTab,
		leftSidebarWidth,
		leftSidebarPinned,
		leftSidebarLockState,
		leftSidebarOpen,
		sidebarLeftPanels,
		sidebarConfigStore,
		leftSidebarVerticalAlign,
		leftSidebarHorizontalPos,
		leftSidebarHeight,
		leftSidebarCustomHeight,
		enableBlankAreaCollapse,
		blankAreaCollapseMode,
		showDragHandle,
		type PanelId,
		type PanelTabType
	} from '$lib/stores';
import * as Sidebar from '$lib/components/ui/sidebar';
import { PANEL_COMPONENTS } from '$lib/components/panels';
import { Button } from '$lib/components/ui/button';
import HoverWrapper from './HoverWrapper.js';
import { appState, type StateSelector } from '$lib/core/state/appState';
import { settingsManager } from '$lib/settings/settingsManager';
import Icon from '$lib/components/ui/Icon.js';
interface Props {
		onResize?: (width: number) => void;
	}

export function LeftSidebar(props: Props) {
  const { onResize } = props
  let isVisible = $state($leftSidebarOpen);

  let localSidebarOpen = $state($leftSidebarOpen);

  let settings = $state(settingsManager.getSettings());

  let autoHideTiming = $derived(
      settings.panels?.autoHideTiming ?? { showDelaySec: 0, hideDelaySec: 0 }
    );

  let leftPanels = $derived($sidebarLeftPanels);

  let activePanelId = $state<PanelId>('folder');

  const panelComponents = PANEL_COMPONENTS;

  function createAppStateStore<T>(selector: StateSelector<T>) {
      const initial = selector(appState.getSnapshot());
      return readable(initial, (set) => appState.subscribe(selector, (value) => set(value)));
    }

  const viewerState = createAppStateStore((state) => state.viewer);

  const bookState = createAppStateStore((state) => state.book);

  const sidebarBookSummary = $derived(
      $bookState.totalPages > 0
        ? `第 ${$bookState.currentPageIndex + 1}/${$bookState.totalPages} 页`
        : '未打开书籍'
    );

  const sidebarWindowSummary = $derived(
      !$viewerState.pageWindow || $viewerState.pageWindow.stale
        ? '窗口初始化中'
        : `窗口中心 ${$viewerState.pageWindow.center + 1} · 前 ${$viewerState.pageWindow.forward.length} / 后 ${$viewerState.pageWindow.backward.length}`
    );

  let isResizing = $state(false);

  let startX = 0;

  let startWidth = 0;

  function handleMouseDown(e: MouseEvent) {
      isResizing = true;
      startX = e.clientX;
      startWidth = $leftSidebarWidth;
      e.preventDefault();
    }

  function handleMouseMove(e: MouseEvent) {
      if (!isResizing) return;

      const delta = e.clientX - startX;
      const newWidth = Math.max(200, Math.min(600, startWidth + delta));

      leftSidebarWidth.set(newWidth);
      onResize?.(newWidth);
    }

  function handleMouseUp() {
      isResizing = false;
    }

  let isDragging = $state(false);

  let dragStartX = 0;

  let dragStartY = 0;

  let initialXPos = 0;

  let initialYPos = 0;

  function handleDragStart(e: PointerEvent) {
      if ($leftSidebarHeight === 'full') return; // 全高模式不允许拖拽
      isDragging = true;
      dragStartX = e.clientX;
      dragStartY = e.clientY;
      initialXPos = $leftSidebarHorizontalPos;
      initialYPos = $leftSidebarVerticalAlign;
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
      e.preventDefault();
    }

  function handleDragMove(e: PointerEvent) {
      if (!isDragging) return;

      const deltaX = e.clientX - dragStartX;
      const deltaY = e.clientY - dragStartY;

      // 转换为百分比 (屏幕宽度/高度的比例)
      const xDeltaPercent = (deltaX / window.innerWidth) * 200; // 放大系数让拖拽更敏感
      const yDeltaPercent = (deltaY / window.innerHeight) * 200;

      const newXPos = Math.max(0, Math.min(100, initialXPos + xDeltaPercent));
      const newYPos = Math.max(0, Math.min(100, initialYPos + yDeltaPercent));

      sidebarConfigStore.setLeftSidebarHorizontalPos(newXPos);
      sidebarConfigStore.setLeftSidebarVerticalAlign(newYPos);
    }

  function handleDragEnd(e: PointerEvent) {
      if (isDragging) {
        isDragging = false;
        (e.target as HTMLElement).releasePointerCapture(e.pointerId);
      }
    }

  let isCornerResizing = $state(false);

  let cornerStartX = 0;

  let cornerStartY = 0;

  let cornerStartWidth = 0;

  let cornerStartHeight = 0;

  function handleCornerResizeStart(e: PointerEvent) {
      isCornerResizing = true;
      cornerStartX = e.clientX;
      cornerStartY = e.clientY;
      cornerStartWidth = $leftSidebarWidth;
      cornerStartHeight = $leftSidebarHeight === 'full' ? 100 : $leftSidebarCustomHeight;

      // 如果是全高模式开始缩放，先切换到自定义模式
      if ($leftSidebarHeight === 'full') {
        sidebarConfigStore.setLeftSidebarHeight('custom');
        sidebarConfigStore.setLeftSidebarCustomHeight(100);
      }

      (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
      e.preventDefault();
      e.stopPropagation();
    }

  function handleCornerResizeMove(e: PointerEvent) {
      if (!isCornerResizing) return;

      // 宽度调整
      const deltaX = e.clientX - cornerStartX;
      const newWidth = Math.max(200, Math.min(600, cornerStartWidth + deltaX));
      leftSidebarWidth.set(newWidth);
      onResize?.(newWidth);

      // 高度调整
      const deltaY = e.clientY - cornerStartY;
      const deltaHeightPercent = (deltaY / window.innerHeight) * 100;
      const newHeight = Math.max(10, Math.min(100, cornerStartHeight + deltaHeightPercent));

      if (newHeight >= 99.5) {
        sidebarConfigStore.setLeftSidebarHeight('full');
        sidebarConfigStore.setLeftSidebarCustomHeight(100);
      } else {
        sidebarConfigStore.setLeftSidebarHeight('custom');
        sidebarConfigStore.setLeftSidebarCustomHeight(newHeight);
      }
    }

  function handleCornerResizeEnd(e: PointerEvent) {
      if (isCornerResizing) {
        isCornerResizing = false;
        (e.currentTarget as HTMLElement).releasePointerCapture(e.pointerId);
      }
    }

  function togglePin() {
      leftSidebarPinned.set(!$leftSidebarPinned);
    }

  function handlePinContextMenu(e: MouseEvent) {
      e.preventDefault();
      collapseSidebar();
    }

  function collapseSidebar() {
      leftSidebarPinned.set(false);
      localSidebarOpen = false;
      leftSidebarOpen.set(false);
    }

  function isInteractiveElement(target: EventTarget | null): boolean {
      if (!(target instanceof HTMLElement)) return false;
      // 空白收回按钮本身放行，不当作交互元素过滤
      if (target.closest('[data-blank-collapse="true"]')) return false;
      return Boolean(
        target.closest(
          'button,a,input,textarea,select,label,[role="button"],[role="switch"],[data-sidebar="menu-button"]'
        )
      );
    }

  function handleBlankAreaClick(e: MouseEvent) {
      if (!$enableBlankAreaCollapse || $blankAreaCollapseMode !== 'single') return;
      if (isInteractiveElement(e.target)) return;
      collapseSidebar();
    }

  function handleBlankAreaDoubleClick(e: MouseEvent) {
      if (!$enableBlankAreaCollapse || $blankAreaCollapseMode !== 'double') return;
      if (isInteractiveElement(e.target)) return;
      collapseSidebar();
    }

  function handleVisibilityChange(visible: boolean) {
      // 锁定隐藏时，不响应悬停
      if ($leftSidebarLockState === false) return;
      if (!$leftSidebarPinned && $leftSidebarLockState !== true) {
        localSidebarOpen = visible;
        leftSidebarOpen.set(visible);
      }
    }

  function handleTabChange(panelId: PanelId) {
      activePanelId = panelId;

      // 设置活动面板
      setActivePanelTab(panelId as PanelTabType);

      // 确保侧边栏打开
      localSidebarOpen = true;
      leftSidebarOpen.set(true);
    }

  $effect(() => {
      const currentActive = leftPanels.find((p) => p.id === $activePanel);
      if (currentActive && currentActive.id !== activePanelId) {
        activePanelId = currentActive.id;
      }
    });

  $effect(() => {
      // 锁定隐藏时，强制关闭
      if ($leftSidebarLockState === false) {
        localSidebarOpen = false;
        leftSidebarOpen.set(false);
        return;
      }
      // 锁定显示或钉住时，强制打开
      if ($leftSidebarPinned || $leftSidebarLockState === true) {
        localSidebarOpen = true;
        leftSidebarOpen.set(true);
      }
    });

  settingsManager.addListener((next) => {
      settings = next;
    });

  $effect(() => {
      localSidebarOpen = $leftSidebarOpen;
    });

  $effect(() => {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);

      return () => {
        document.removeEventListener('mousemove', handleMouseMove);
        document.removeEventListener('mouseup', handleMouseUp);
      };
    });
  return (
    <Fragment>

<HoverWrapper pinned={$leftSidebarPinned} onVisibilityChange={handleVisibilityChange} hideDelay={autoHideTiming.hideDelaySec * 1000} showDelay={autoHideTiming.showDelaySec * 1000} side="left">
	<div className="relative flex h-full" style={`--sidebar-width: ${$leftSidebarWidth}px; width: ${$leftSidebarWidth}px;`}>
		<div className="flex min-h-0 flex-1">
			<Sidebar.Provider onOpenChange={(v) => {
					localSidebarOpen = v;
					leftSidebarOpen.set(v);
				}} style={`--sidebar-width: ${$leftSidebarWidth}px;`}>
				<Sidebar.Root side="left" collapsible="offcanvas" className="overflow-hidden [&>[data-sidebar=sidebar]]:flex-row">
					{/*  一级菜单 - 图标模式  */}
					<MagicCard className="h-full !w-[calc(var(--sidebar-width-icon)_+_1px)]" gradientSize={80} gradientOpacity={0.4}>
						<Sidebar.Root collapsible="none" className="h-full !w-[calc(var(--sidebar-width-icon)_+_1px)]" style="width: calc(var(--sidebar-width-icon) + 1px);">
							<Sidebar.Header className="flex flex-col gap-2 px-1.5 py-2">
								<div className="flex flex-col gap-1">
									<Button variant={$leftSidebarPinned ? 'default' : 'ghost'} size="icon" className="h-9 w-9" onClick={togglePin} onContextmenu={handlePinContextMenu}>
										{$leftSidebarPinned ? (<Fragment>
											<PinOff className="h-4 w-4"></PinOff>
										</Fragment>) : (<Fragment>
											<Pin className="h-4 w-4"></Pin>
										</Fragment>)}
									</Button>
									{/*  拖拽移动按钮  */}
									{$showDragHandle && $leftSidebarHeight !== 'full' ? (<Fragment>
										<button type="button" className={`flex h-9 w-9 cursor-move items-center justify-center rounded-md transition-colors
											${isDragging
												? 'bg-primary text-primary-foreground'
												: 'hover:bg-accent text-muted-foreground hover:text-foreground'}`} onPointerDown={handleDragStart} onPointerMove={handleDragMove} onPointerUp={handleDragEnd} onPointercancel={handleDragEnd} title="拖拽移动侧边栏">
											<MousePointer2 className="h-4 w-4"></MousePointer2>
										</button>
									</Fragment>) : null}
								</div>
							</Sidebar.Header>

							<Sidebar.Content>
								<Sidebar.Group>
									<Sidebar.GroupContent className="flex h-full min-h-0 flex-col px-0">
										<Sidebar.Menu>
											{leftPanels.map((panel) => (<Fragment key={panel.id}>
												<Sidebar.MenuItem>
													<Sidebar.MenuButton tooltipContentProps={{
															hidden: false
														}} onClick={() => handleTabChange(panel.id)} isActive={$activePanel === panel.id} className="px-2">
														{/* TODO unsupported SnippetBlock */}
														<Icon name={panel.id} fallback={panel.icon} className="h-4 w-4"></Icon>
														<span>{panel.title}</span>
													</Sidebar.MenuButton>
												</Sidebar.MenuItem>
											</Fragment>))}
										</Sidebar.Menu>
										<button type="button" className="min-h-0 w-full flex-1 bg-transparent" data-blank-collapse="true" onClick={handleBlankAreaClick} onDoubleClick={handleBlankAreaDoubleClick} aria-label="收回左侧边栏"></button>
									</Sidebar.GroupContent>
								</Sidebar.Group>
							</Sidebar.Content>
						</Sidebar.Root>
					</MagicCard>

					{/*  二级菜单 - 内容面板  */}
					<Sidebar.Root collapsible="none" className="flex flex-1" style="width: calc(var(--sidebar-width) - var(--sidebar-width-icon) - 1px);">
						<Sidebar.Content className="h-full">
							<Sidebar.Group className="h-full flex-1 p-0">
								<Sidebar.GroupContent className="h-full">
									{/*  使用 content-visibility: hidden 保持布局信息，避免切换时重新计算尺寸  */}
									{leftPanels.map((panel) => (<Fragment key={panel.id}>
										{/* TODO unsupported ConstTag */}
										{PanelComponent ? (<Fragment>
											<div className="panel-content-wrapper">
												<PanelComponent></PanelComponent>
											</div>
										</Fragment>) : null}
									</Fragment>))}
								</Sidebar.GroupContent>
							</Sidebar.Group>
						</Sidebar.Content>
					</Sidebar.Root>
					{/*  拖拽手柄  */}
					<button type="button" className="hover:bg-accent text-muted-foreground absolute top-1/2 right-0 z-50 -translate-y-1/2 cursor-ew-resize rounded-l-md p-1 opacity-0 transition-all hover:opacity-100" onMouseDown={handleMouseDown} onContextmenu={handlePinContextMenu} aria-label="调整侧边栏宽度">
						<GripVertical className="h-4 w-4"></GripVertical>
					</button>

					{/*  边角缩放手柄 (右下角)  */}
					{$leftSidebarHeight !== 'full' ? (<Fragment>
						<button type="button" className={`text-muted-foreground/30 hover:text-primary absolute right-0 bottom-0 z-[60] cursor-nwse-resize p-1 transition-colors
							${isCornerResizing ? 'text-primary' : ''}`} onPointerDown={handleCornerResizeStart} onPointerMove={handleCornerResizeMove} onPointerUp={handleCornerResizeEnd} onPointercancel={handleCornerResizeEnd} aria-label="同时调整侧边栏宽高">
							<ArrowDownRight className="h-4 w-4"></ArrowDownRight>
						</button>
					</Fragment>) : null}
				</Sidebar.Root>
			</Sidebar.Provider>
		</div>
	</div>
</HoverWrapper>

</Fragment>
  )
}
