import type { InteractionField, InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { TerminalLanguage } from "@xiranite/cli-runtime/i18n"
import type { ArcThumbInput, ArcThumbResult } from "./core.js"

export function createArcThumbInteractionSchema(defaults: Partial<InteractionValues> = {}, language: TerminalLanguage = "zh"): TerminalInteractionSchema<ArcThumbInput, ArcThumbResult> {
  const zh = language === "zh"
  const fields: InteractionField[] = [
    { id: "action", label: zh ? "操作" : "Action", kind: "select", role: "action", options: [{ value: "inspect", label: zh ? "检查归档" : "Inspect archive" }, { value: "render", label: zh ? "渲染封面" : "Render covers" }, { value: "system-thumbnail", label: zh ? "读取 Shell 缓存" : "Read Shell cache" }] },
    { id: "paths", label: zh ? "归档、电子书或文件" : "Archives, ebooks, or files", kind: "path-list", lines: 5 },
    { id: "maxDimension", label: zh ? "最大边长" : "Maximum dimension", kind: "number" },
    { id: "format", label: zh ? "输出格式" : "Format", kind: "select", options: [{ value: "webp", label: "WebP" }, { value: "png", label: "PNG" }, { value: "jpeg", label: "JPEG" }] },
    { id: "quality", label: zh ? "质量" : "Quality", kind: "number" },
    { id: "sortOrder", label: zh ? "排序" : "Ordering", kind: "select", options: [{ value: "natural", label: zh ? "自然排序" : "Natural" }, { value: "alphabetical", label: zh ? "字母排序" : "Alphabetical" }], visibleWhen: (values) => values.action !== "system-thumbnail" },
    { id: "coverMode", label: zh ? "封面选择" : "Cover selection", kind: "select", options: [{ value: "prefer", label: zh ? "优先封面" : "Prefer cover" }, { value: "ignore", label: zh ? "首张图片" : "First image" }, { value: "only", label: zh ? "仅封面" : "Cover only" }], visibleWhen: (values) => values.action !== "system-thumbnail" },
    { id: "outputDir", label: zh ? "输出目录" : "Output directory", kind: "text", visibleWhen: (values) => values.action === "render" },
    { id: "write", label: zh ? "写入文件" : "Write files", kind: "boolean", visibleWhen: (values) => values.action === "render" },
    { id: "overwrite", label: zh ? "覆盖现有文件" : "Overwrite", kind: "boolean", visibleWhen: (values) => values.action === "render" },
  ]
  return { id: "arcthumb", title: "ArcThumb XR", description: zh ? "原生归档、电子书与 Shell 缩略图" : "Native archive, ebook, and Shell thumbnails", initialValues: { action: "inspect", paths: "", maxDimension: 512, format: "webp", quality: 85, sortOrder: "natural", coverMode: "prefer", outputDir: "", write: false, overwrite: false, ...defaults }, fields, view: { sections: [{ id: "thumbnail", title: "ArcThumb XR", fieldIds: fields.map((field) => field.id) }], dashboard: { title: "ArcThumb XR", display: (values) => ({ primary: String(values.action), secondary: values.write === true ? "Write" : "Inspect", metrics: [] }) } }, toInput: (values) => ({ action: values.action === "render" || values.action === "system-thumbnail" ? values.action : "inspect", paths: String(values.paths ?? "").split(/[\r\n;]+/).map((value) => value.trim()).filter(Boolean), maxDimension: Number(values.maxDimension), format: values.format === "png" || values.format === "jpeg" ? values.format : "webp", quality: Number(values.quality), sortOrder: values.sortOrder === "alphabetical" ? "alphabetical" : "natural", coverMode: values.coverMode === "ignore" || values.coverMode === "only" ? values.coverMode : "prefer", outputDir: String(values.outputDir ?? ""), write: values.write === true, overwrite: values.overwrite === true }), validate: (_values, input) => input.paths?.length ? null : zh ? "至少输入一个路径。" : "Enter at least one path.", preview: (input) => [`${zh ? "输入" : "Inputs"}: ${input.paths?.length ?? 0}`, input.action === "system-thumbnail" ? (zh ? "仅读取 Windows 已缓存的缩略图" : "Reads cached Windows thumbnails only") : input.write ? (zh ? "将写入缩略图文件" : "Will write thumbnail files") : (zh ? "仅检查和预览" : "Inspect only")], isDangerous: (input) => input.write === true, dangerPrompt: () => ({ title: zh ? "确认写入缩略图？" : "Write thumbnails?", body: zh ? "将按当前覆盖策略写出原生编码的封面缩略图。" : "Native encoded cover thumbnails will be written using the selected overwrite policy.", confirmLabel: zh ? "确认写入" : "Write" }), result: (result) => ({ success: result.success, message: result.message, lines: result.data ? [`Ready: ${result.data.readyCount}`, `Written: ${result.data.writtenCount}`, `Errors: ${result.data.errorCount}`] : [] }) }
}
