/**
 * @migrated-from src/lib/components/viewer/VideoPlayer/MoreMenu.svelte
 * @source-hash sha256:6dc2c3de7607c9e555bece44b3b086dadbe3a6b720a637a885c1db7361679566
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { MoreVertical, Camera, RotateCcw, Sun } from 'lucide-react';
interface Props {
		showMoreMenu: boolean;
		abLoop: { a: number | null; b: number | null };
		abLoopActive: boolean;
		showFilterPanel: boolean;
		brightness: number;
		contrast: number;
		saturate: number;
		videoWidth: number;
		videoHeight: number;
		duration: number;
		formatTime: (seconds: number) => string;
		onToggleMenu: (e: MouseEvent) => void;
		onCaptureScreenshot: () => void;
		onSetLoopPointA: () => void;
		onSetLoopPointB: () => void;
		onClearAbLoop: () => void;
		onToggleFilterPanel: () => void;
		onResetFilters: () => void;
		onBrightnessChange: (value: number) => void;
		onContrastChange: (value: number) => void;
		onSaturateChange: (value: number) => void;
	}

export function MoreMenu(props: Props) {
  const {
		showMoreMenu,
		abLoop,
		abLoopActive,
		showFilterPanel,
		brightness,
		contrast,
		saturate,
		videoWidth,
		videoHeight,
		duration,
		formatTime,
		onToggleMenu,
		onCaptureScreenshot,
		onSetLoopPointA,
		onSetLoopPointB,
		onClearAbLoop,
		onToggleFilterPanel,
		onResetFilters,
		onBrightnessChange,
		onContrastChange,
		onSaturateChange
	} = props
  return (
    <Fragment>

<div className="relative">
	<button className={`control-btn rounded-full p-2 transition-colors hover:bg-white/20 ${showMoreMenu ||
		abLoopActive
			? 'bg-white/20'
			: ''}`} onClick={onToggleMenu} title="更多功能" aria-label="更多功能">
		<MoreVertical className="text-primary h-5 w-5"></MoreVertical>
	</button>

	{showMoreMenu ? (<Fragment>
		<div className="absolute bottom-full left-0 mb-2 w-48 rounded-lg bg-black/95 p-2 shadow-lg backdrop-blur-sm" role="menu" tabIndex="-1" onClick={(e) => e.stopPropagation()} onMouseDown={(e) => e.stopPropagation()} onKeyDown={(e) => e.stopPropagation()}>
			{/*  截图  */}
			<button className="flex w-full items-center gap-2 rounded px-3 py-2 text-sm text-white hover:bg-white/10" onClick={onCaptureScreenshot}>
				<Camera className="h-4 w-4"></Camera>
				截图
			</button>

			{/*  AB循环  */}
			<div className="mt-2 border-t border-white/10 pt-2">
				<div className="px-3 py-1 text-xs text-white/50">AB循环</div>
				<div className="flex items-center gap-1 px-3 py-1">
					<button className={`rounded px-3 py-1 text-xs transition-colors ${abLoop.a !== null
							? 'bg-primary text-white'
							: 'bg-white/10 text-white hover:bg-white/20'}`} onClick={onSetLoopPointA}>
						A{abLoop.a !== null ? `: ${formatTime(abLoop.a)}` : ''}
					</button>
					<button className={`rounded px-3 py-1 text-xs transition-colors ${abLoop.b !== null
							? 'bg-primary text-white'
							: 'bg-white/10 text-white hover:bg-white/20'}`} onClick={onSetLoopPointB} disabled={abLoop.a === null}>
						B{abLoop.b !== null ? `: ${formatTime(abLoop.b)}` : ''}
					</button>
					{abLoopActive ? (<Fragment>
						<button className="rounded bg-white/10 p-1 text-xs text-white hover:bg-white/20" onClick={onClearAbLoop} title="清除">
							<RotateCcw className="h-3 w-3"></RotateCcw>
						</button>
					</Fragment>) : null}
				</div>
			</div>

			{/*  滤镜  */}
			<div className="mt-2 border-t border-white/10 pt-2">
				<button className="flex w-full items-center justify-between gap-2 rounded px-3 py-2 text-sm text-white hover:bg-white/10" onClick={onToggleFilterPanel}>
					<span className="flex items-center gap-2">
						<Sun className="h-4 w-4"></Sun>
						视频滤镜
					</span>
					{brightness !== 100 || contrast !== 100 || saturate !== 100 ? (<Fragment>
						<span className="text-primary text-xs">已调整</span>
					</Fragment>) : null}
				</button>

				{showFilterPanel ? (<Fragment>
					<div className="space-y-2 px-3 py-2">
						<div>
							<div className="mb-1 flex justify-between text-xs text-white/70">
								<span>亮度</span><span>{brightness}%</span>
							</div>
							<input type="range" min="0" max="200" step="5" value={brightness} onInput={(e) =>
									onBrightnessChange(parseFloat((e.target as HTMLInputElement).value))} className="h-1 w-full cursor-pointer appearance-none rounded bg-white/20" />
						</div>
						<div>
							<div className="mb-1 flex justify-between text-xs text-white/70">
								<span>对比度</span><span>{contrast}%</span>
							</div>
							<input type="range" min="0" max="200" step="5" value={contrast} onInput={(e) => onContrastChange(parseFloat((e.target as HTMLInputElement).value))} className="h-1 w-full cursor-pointer appearance-none rounded bg-white/20" />
						</div>
						<div>
							<div className="mb-1 flex justify-between text-xs text-white/70">
								<span>饱和度</span><span>{saturate}%</span>
							</div>
							<input type="range" min="0" max="200" step="5" value={saturate} onInput={(e) => onSaturateChange(parseFloat((e.target as HTMLInputElement).value))} className="h-1 w-full cursor-pointer appearance-none rounded bg-white/20" />
						</div>
						<button className="w-full rounded bg-white/10 px-2 py-1 text-xs text-white hover:bg-white/20" onClick={onResetFilters}>
							重置滤镜
						</button>
					</div>
				</Fragment>) : null}
			</div>

			{/*  视频信息  */}
			<div className="mt-2 border-t border-white/10 pt-2">
				<div className="px-3 py-1 text-xs text-white/50">视频信息</div>
				<div className="space-y-1 px-3 py-1 text-xs text-white/80">
					{videoWidth > 0 ? (<Fragment>
						<div className="flex justify-between">
							<span>分辨率</span>
							<span>{videoWidth}×{videoHeight}</span>
						</div>
						<div className="flex justify-between">
							<span>时长</span>
							<span>{formatTime(duration)}</span>
						</div>
					</Fragment>) : null}
				</div>
			</div>
		</div>
	</Fragment>) : null}
</div></Fragment>
  )
}
