/**
 * @migrated-from src/lib/components/viewer/VideoPlayer/VolumePanel.svelte
 * @source-hash sha256:abeb5b39ec27d5f7f998e27a7af776f554215fdc7501242424bbf997daa00551
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Volume2, VolumeX } from 'lucide-react';
interface Props {
		volume: number;
		isMuted: boolean;
		showVolumePanel: boolean;
		onToggleMute: () => void;
		onVolumeChange: (e: Event) => void;
		onTogglePanel: (e: MouseEvent) => void;
	}

export function VolumePanel(props: Props) {
  const { volume, isMuted, showVolumePanel, onToggleMute, onVolumeChange, onTogglePanel } = props
  return (
    <Fragment>

<div className="relative">
	<button className={`control-btn flex items-center gap-1 rounded-full px-2 py-1.5 transition-colors hover:bg-white/20 ${showVolumePanel
			? 'bg-white/20'
			: ''}`} onClick={onTogglePanel} aria-label="音量控制" title="点击展开音量调节">
		{isMuted || volume === 0 ? (<Fragment>
			<VolumeX className="text-primary h-4 w-4"></VolumeX>
		</Fragment>) : (<Fragment>
			<Volume2 className="text-primary h-4 w-4"></Volume2>
		</Fragment>)}
		<span className="text-primary text-xs">{Math.round(volume * 100)}%</span>
	</button>
	{showVolumePanel ? (<Fragment>
		<div className="absolute right-0 bottom-full mb-2 rounded-lg bg-black/95 p-3 shadow-lg" style="min-width: 140px;" role="dialog" tabIndex="-1" onClick={(e) => e.stopPropagation()} onMouseDown={(e) => e.stopPropagation()} onKeyDown={(e) => e.stopPropagation()}>
			<div className="flex items-center gap-2">
				<button onClick={onToggleMute} className="shrink-0 rounded p-1 hover:bg-white/20">
					{isMuted || volume === 0 ? (<Fragment>
						<VolumeX className="h-4 w-4 text-white"></VolumeX>
					</Fragment>) : (<Fragment>
						<Volume2 className="h-4 w-4 text-white"></Volume2>
					</Fragment>)}
				</button>
				<input type="range" min="0" max="1" step="0.05" value={volume} onInput={onVolumeChange} className="h-1 w-20 cursor-pointer appearance-none rounded bg-white/20" />
			</div>
		</div>
	</Fragment>) : null}
</div></Fragment>
  )
}
