/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState, type ReactNode } from "react"
import { ActionTabs, ClickTarget as ClickTargetBase, ProgressBar, resolveTerminalTheme, TerminalPreferencesScreen, TerminalThemeProvider, terminalIcon, useAnimation, useTerminalTheme, useTerminalUiSession, WorkbenchButton, WorkbenchField, WorkbenchPanel } from "@xiranite/cli-runtime/terminal/opentui"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { TimeuInput, TimeuResult } from "./core.js"

const ClickTarget = ClickTargetBase as unknown as (props: { id?: string; children: ReactNode; focused?: boolean; selected?: boolean; disabled?: boolean; onClick: () => void }) => ReactNode

export function TimeuTui(props: TerminalUiScreenProps<TimeuInput, TimeuResult>) { const [previewTheme, setPreviewTheme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit"); return <TerminalThemeProvider theme={resolveTerminalTheme(previewTheme === "inherit" ? "nord" : previewTheme)}><TimeuWorkbench {...props} onThemePreview={setPreviewTheme} /></TerminalThemeProvider> }
function TimeuWorkbench({ definition, language, preferences, onExit, onThemePreview }: TerminalUiScreenProps<TimeuInput, TimeuResult> & { onThemePreview: (theme: string) => void }) {
  const theme = useTerminalTheme(); const t = createTerminalTranslator(language); const session = useTerminalUiSession(definition); const [settings, setSettings] = useState(false); const frame = useAnimation({ intervalMs: session.phase === "running" ? 120 : 540 }); const action = String(session.values.action ?? "scan"); const fields = definition.schema.fields; const pathField = fields.find((field) => field.id === "listText")!; const recordField = fields.find((field) => field.id === "recordPath")!; const boolFields = fields.filter((field) => ["recursive", "includeDirectories", "dryRun"].includes(field.id)); const controls = ["action", "listText", "recordPath", ...boolFields.map((field) => field.id), "execute", "settings", "tab-status", "tab-logs", "reset", "exit"]
  useKeyboard((key) => { if (key.name === "escape") { if (settings) setSettings(false); else if (session.confirming) session.dismissConfirmation(); else if (session.phase === "running") session.cancel(); else onExit(); return }; if (key.name === "tab") session.moveFocus(controls, key.shift ? -1 : 1); if (key.name === "q" && session.phase !== "running") onExit() })
  if (settings && preferences) return <TerminalPreferencesScreen controller={preferences} focusedId={session.focusedControlId} onFocus={session.focus} onPreviewTheme={onThemePreview} onBack={() => setSettings(false)} />
  if (session.confirming) return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="68%" height={9} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>⚠ 确认写入时间戳</b></text><text>{session.dangerPrompt?.body}</text><text fg={theme.colors.mutedForeground}>{session.preview.join(" · ")}</text><box flexDirection="row" gap={2}><WorkbenchButton id="confirm-execute" danger onClick={() => void session.confirmExecute()}>⚠ 确认执行</WorkbenchButton><WorkbenchButton id="confirm-dismiss" onClick={session.dismissConfirmation}>× 取消</WorkbenchButton></box></box></box>
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden"><box height={4} flexShrink={0} flexDirection="row" justifyContent="space-between" borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1}><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("status")} TIMEU // TIMESTAMP VAULT`}</b></text><text fg={theme.colors.mutedForeground}>{language === "zh" ? "路径队列、时间记录与安全恢复闸门" : "Path queue, timestamp records and guarded restore"}</text></box><box flexDirection="column" alignItems="flex-end"><text fg={session.phase === "running" ? theme.colors.warning : theme.colors.mutedForeground}>{`${session.phase === "running" ? "◌ WORKING" : "● READY"} ${["⠁", "⠂", "⠄", "⡀", "⢀", "⠠"][frame % 6]}`}</text>{preferences ? <ClickTarget id="settings" focused={session.focusedControlId === "settings"} onClick={() => { session.focus("pref-theme"); setSettings(true) }}>{`${terminalIcon("settings")} ${language === "zh" ? "设置" : "settings"}`}</ClickTarget> : null}</box></box>
    <box flexDirection="row" flexGrow={1} minHeight={0} gap={1} marginTop={1}><WorkbenchPanel title={language === "zh" ? "路径队列" : "Path queue"} description={language === "zh" ? "每行一个文件或目录" : "One file or directory per line"} width="34%"><box flexDirection="column" flexGrow={1} minHeight={0}><WorkbenchField field={pathField} value={session.values.listText} error={session.fieldErrors.listText} focused={session.focusedControlId === "listText"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("listText")} onChange={(value) => session.setField("listText", value)} /><WorkbenchField field={recordField} value={session.values.recordPath} error={session.fieldErrors.recordPath} focused={session.focusedControlId === "recordPath"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("recordPath")} onChange={(value) => session.setField("recordPath", value)} /><box flexGrow={1} /></box></WorkbenchPanel>
      <WorkbenchPanel title={language === "zh" ? "时间记录" : "Timestamp records"} description={language === "zh" ? "扫描结果与备份/恢复计划" : "Scan result and backup/restore plan"} flexGrow={1}><box flexDirection="column" flexGrow={1} minHeight={0}><ActionTabs id="field-action" options={[{ value: "scan", label: "⌕ 检查" }, { value: "backup", label: "▣ 备份" }, { value: "restore", label: "↺ 恢复" }]} value={action} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)} /><scrollbox id="timeu-plan" flexGrow={1} minHeight={4} marginTop={1} scrollbarOptions={{ trackOptions: { foregroundColor: theme.colors.primary, backgroundColor: theme.colors.border } }}>{session.resultSummary?.table ? <>{session.resultSummary.table.rows.map((row, index) => <text key={`${row.path}-${index}`} fg={row.status === "error" ? theme.colors.error : row.status === "success" ? theme.colors.success : theme.colors.mutedForeground}>{`${row.status === "success" ? "✓" : row.status === "error" ? "!" : "·"} ${row.operation}  ${row.path}`}</text>)}</> : <text fg={theme.colors.mutedForeground}>{language === "zh" ? "执行后显示当前时间、记录时间及恢复计划。" : "Current, recorded and restore-plan timestamps appear after a run."}</text>}</scrollbox><ProgressBar value={session.progress} label={session.status || (language === "zh" ? "等待路径" : "Waiting for paths")} /></box></WorkbenchPanel>
      <WorkbenchPanel title={language === "zh" ? "执行闸门" : "Execution gate"} description={language === "zh" ? "预演、递归和写入保护" : "Dry-run, recursion and write protection"} width="28%"><box flexDirection="column" gap={1} flexGrow={1}>{boolFields.map((field) => <WorkbenchField key={field.id} field={field} value={session.values[field.id]} error={session.fieldErrors[field.id]} focused={session.focusedControlId === field.id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(field.id)} onChange={(value) => session.setField(field.id, value)} />)}<box flexGrow={1} /><WorkbenchButton id="execute" danger={session.dangerous} focused={session.focusedControlId === "execute"} onClick={() => session.phase === "running" ? session.cancel() : void session.requestExecute()}>{session.phase === "running" ? "■ 停止" : session.dangerous ? "⚠ 确认后执行" : "▶ 生成计划"}</WorkbenchButton><ClickTarget id="tab-status" selected={session.resultTab === "status"} onClick={() => session.selectResultTab("status")}>◉ 状态</ClickTarget><ClickTarget id="tab-logs" selected={session.resultTab === "logs"} onClick={() => session.selectResultTab("logs")}>▤ 日志 ({session.logs.length})</ClickTarget></box></WorkbenchPanel></box>
    <box height={2} flexShrink={0} marginTop={1} flexDirection="row" justifyContent="space-between"><box flexDirection="row"><ClickTarget id="reset" onClick={session.reset}>↺ {t("reset")}</ClickTarget><ClickTarget id="exit" onClick={onExit}>× {language === "zh" ? "退出" : "Exit"}</ClickTarget></box><text fg={theme.colors.mutedForeground}>{language === "zh" ? "Unicode 图标 · 可编辑路径队列 · 鼠标优先" : "Unicode icons · editable queue · mouse-first"}</text></box></box>
}
