// Generated by scripts/generate-node-registries.ts. Do not edit by hand.

import type { NodeSpec } from "./node-runner.js"

export const generatedNodeSpecs: Record<string, NodeSpec> = {
  bandia: {
    loadCore: () => import("@xiranite/node-bandia/core"),
    run: "runBandia",
    loadPlatform: () => import("@xiranite/node-bandia/platform"),
    createRuntime: "createNodeBandiaRuntime",
  },
  cleanf: {
    loadCore: () => import("@xiranite/node-cleanf/core"),
    run: "runCleanf",
    loadPlatform: () => import("@xiranite/node-cleanf/platform"),
    createRuntime: "createNodeCleanfRuntime",
  },
  crashu: {
    loadCore: () => import("@xiranite/node-crashu/core"),
    run: "runCrashu",
    loadPlatform: () => import("@xiranite/node-crashu/platform"),
    createRuntime: "createNodeCrashuRuntime",
  },
  dissolvef: {
    loadCore: () => import("@xiranite/node-dissolvef/core"),
    run: "runDissolvef",
    loadPlatform: () => import("@xiranite/node-dissolvef/platform"),
    createRuntime: "createNodeDissolvefRuntime",
  },
  encodeb: {
    loadCore: () => import("@xiranite/node-encodeb/core"),
    run: "runEncodeb",
    loadPlatform: () => import("@xiranite/node-encodeb/platform"),
    createRuntime: "createNodeEncodebRuntime",
  },
  enginev: {
    loadCore: () => import("@xiranite/node-enginev/core"),
    run: "runEngineV",
    loadPlatform: () => import("@xiranite/node-enginev/platform"),
    createRuntime: "createNodeEngineVRuntime",
  },
  findz: {
    loadCore: () => import("@xiranite/node-findz/core"),
    run: "runFindz",
    loadPlatform: () => import("@xiranite/node-findz/platform"),
    createRuntime: "createNodeFindzRuntime",
  },
  formatv: {
    loadCore: () => import("@xiranite/node-formatv/core"),
    run: "runFormatv",
    loadPlatform: () => import("@xiranite/node-formatv/platform"),
    createRuntime: "createNodeFormatvRuntime",
  },
  kavvka: {
    loadCore: () => import("@xiranite/node-kavvka/core"),
    run: "runKavvka",
    loadPlatform: () => import("@xiranite/node-kavvka/platform"),
    createRuntime: "createNodeKavvkaRuntime",
  },
  lata: {
    loadCore: () => import("@xiranite/node-lata/core"),
    run: "runLata",
    loadPlatform: () => import("@xiranite/node-lata/platform"),
    createRuntime: "createNodeLataRuntime",
  },
  linedup: {
    loadCore: () => import("@xiranite/node-linedup/core"),
    run: "filterLines",
    message: "Filtered lines.",
  },
  linku: {
    loadCore: () => import("@xiranite/node-linku/core"),
    run: "runLinku",
    loadPlatform: () => import("@xiranite/node-linku/platform"),
    createRuntime: "createNodeLinkuRuntime",
  },
  lorat: {
    loadCore: () => import("@xiranite/node-lorat/core"),
    run: "runLorat",
    loadPlatform: () => import("@xiranite/node-lorat/platform"),
    createRuntime: "createNodeLoratRuntime",
  },
  marku: {
    loadCore: () => import("@xiranite/node-marku/core"),
    run: "runMarku",
    loadPlatform: () => import("@xiranite/node-marku/platform"),
    createRuntime: "createNodeMarkuRuntime",
  },
  migratef: {
    loadCore: () => import("@xiranite/node-migratef/core"),
    run: "runMigratef",
    loadPlatform: () => import("@xiranite/node-migratef/platform"),
    createRuntime: "createNodeMigratefRuntime",
  },
  movea: {
    loadCore: () => import("@xiranite/node-movea/core"),
    run: "runMovea",
    loadPlatform: () => import("@xiranite/node-movea/platform"),
    createRuntime: "createNodeMoveaRuntime",
  },
  mvz: {
    loadCore: () => import("@xiranite/node-mvz/core"),
    run: "runMvz",
    loadPlatform: () => import("@xiranite/node-mvz/platform"),
    createRuntime: "createNodeMvzRuntime",
  },
  owithu: {
    loadCore: () => import("@xiranite/node-owithu/core"),
    run: "runOwithu",
    loadPlatform: () => import("@xiranite/node-owithu/platform"),
    createRuntime: "createNodeOwithuRuntime",
  },
  rawfilter: {
    loadCore: () => import("@xiranite/node-rawfilter/core"),
    run: "runRawfilter",
    loadPlatform: () => import("@xiranite/node-rawfilter/platform"),
    createRuntime: "createNodeRawfilterRuntime",
  },
  recycleu: {
    loadCore: () => import("@xiranite/node-recycleu/core"),
    run: "runRecycleu",
    loadPlatform: () => import("@xiranite/node-recycleu/platform"),
    createRuntime: "createNodeRecycleuRuntime",
  },
  repacku: {
    loadCore: () => import("@xiranite/node-repacku/core"),
    run: "runRepacku",
    loadPlatform: () => import("@xiranite/node-repacku/platform"),
    createRuntime: "createNodeRepackuRuntime",
  },
  scoolp: {
    loadCore: () => import("@xiranite/node-scoolp/core"),
    run: "runScoolp",
    loadPlatform: () => import("@xiranite/node-scoolp/platform"),
    createRuntime: "createNodeScoolpRuntime",
  },
  seriex: {
    loadCore: () => import("@xiranite/node-seriex/core"),
    run: "runSeriex",
    loadPlatform: () => import("@xiranite/node-seriex/platform"),
    createRuntime: "createNodeSeriexRuntime",
  },
  sleept: {
    loadCore: () => import("@xiranite/node-sleept/core"),
    run: "runSleept",
    loadPlatform: () => import("@xiranite/node-sleept/platform"),
    createRuntime: "createNodeSleeptRuntime",
  },
  trename: {
    loadCore: () => import("@xiranite/node-trename/core"),
    run: "runTrename",
    loadPlatform: () => import("@xiranite/node-trename/platform"),
    createRuntime: "createNodeTrenameRuntime",
  },
}

export const generatedNodeIds = Object.keys(generatedNodeSpecs).sort()
