import type { InteractionValues, TerminalInteractionSchema } from "@xiranite/cli-runtime/interaction"
import type { EngineVAction, EngineVExportFormat, EngineVInput, EngineVResult, EngineVSortField, EngineVSortOrder } from "./core.js"
import { DEFAULT_TEMPLATE, DEFAULT_WORKSHOP_PATH } from "./core.js"

export type EngineVInteractionValues = InteractionValues & { action: EngineVAction; workshopPath: string; titleFilter: string; ratingFilter: string; typeFilter: string; tagsText: string; idsText: string; template: string; maxWorkers: number; dryRun: boolean; permanent: boolean; copyMode: boolean; targetPath: string; exportFormat: EngineVExportFormat; exportPath: string; sortField: EngineVSortField; sortOrder: EngineVSortOrder; imageBackend: string; galleryColumns: number }

export function createEngineVInteractionSchema(defaults: Partial<EngineVInteractionValues> = {}, language: "zh" | "en" = "zh"): TerminalInteractionSchema<EngineVInput, EngineVResult> {
  const zh = language === "zh", text = (a: string, b: string) => zh ? a : b
  const initialValues: EngineVInteractionValues = { action: "scan", workshopPath: DEFAULT_WORKSHOP_PATH, titleFilter: "", ratingFilter: "", typeFilter: "", tagsText: "", idsText: "", template: DEFAULT_TEMPLATE, maxWorkers: 4, dryRun: true, permanent: false, copyMode: false, targetPath: "", exportFormat: "json", exportPath: "", sortField: "none", sortOrder: "desc", imageBackend: "auto", galleryColumns: 0, ...defaults }
  return {
    id: "enginev", title: "EngineV", description: text("扫描、筛选并管理 Wallpaper Engine 工坊图库。", "Scan, filter and manage a Wallpaper Engine workshop gallery."), initialValues,
    fields: [
      { id: "action", label: text("工作流", "Workflow"), kind: "select", role: "action", options: [{ value: "scan", label: text("扫描", "Scan") }, { value: "filter", label: text("筛选", "Filter") }, { value: "rename", label: text("重命名", "Rename") }, { value: "delete", label: text("删除", "Delete") }, { value: "export", label: text("导出", "Export") }] },
      { id: "workshopPath", label: text("工坊目录", "Workshop path"), kind: "text" },
      { id: "titleFilter", label: text("标题筛选", "Title filter"), kind: "text" }, { id: "ratingFilter", label: text("内容分级", "Content rating"), kind: "text" }, { id: "typeFilter", label: text("壁纸类型", "Wallpaper type"), kind: "text" }, { id: "tagsText", label: text("标签", "Tags"), kind: "text" },
      { id: "idsText", label: text("已选工坊 ID", "Selected workshop IDs"), kind: "text" }, { id: "template", label: text("命名模板", "Rename template"), kind: "text" },
      { id: "maxWorkers", label: text("并发数", "Workers"), kind: "number", min: 1, max: 32 }, { id: "dryRun", label: text("预演", "Dry-run"), kind: "boolean" }, { id: "permanent", label: text("永久删除", "Permanent delete"), kind: "boolean" }, { id: "copyMode", label: text("复制模式", "Copy mode"), kind: "boolean" }, { id: "targetPath", label: text("复制目标", "Copy target"), kind: "text" },
      { id: "exportFormat", label: text("导出格式", "Export format"), kind: "select", options: [{ value: "json", label: "JSON" }, { value: "paths", label: text("路径", "Paths") }] }, { id: "exportPath", label: text("导出路径", "Export path"), kind: "text" },
      { id: "sortField", label: text("排序字段", "Sort field"), kind: "select", options: ["none", "size", "title", "createdTime", "modifiedTime"].map((value) => ({ value, label: value })) }, { id: "sortOrder", label: text("排序方向", "Sort order"), kind: "select", options: [{ value: "desc", label: text("降序", "Descending") }, { value: "asc", label: text("升序", "Ascending") }] },
      { id: "imageBackend", label: text("图片后端", "Image backend"), kind: "select", options: [{ value: "auto", label: text("自动（SIXEL 优先）", "Auto (SIXEL first)") }, { value: "sixel", label: "SIXEL" }, { value: "kitty", label: "Kitty" }, { value: "half-block", label: text("真彩半块", "TrueColor half-block") }] },
      { id: "galleryColumns", label: text("列数（0 自动）", "Columns (0 auto)"), kind: "number", min: 0, max: 6 },
    ],
    toInput: (values) => ({ action: String(values.action ?? "scan") as EngineVAction, workshopPath: String(values.workshopPath ?? "").trim(), maxWorkers: Number(values.maxWorkers) || 4, filters: { title: String(values.titleFilter ?? "").trim() || undefined, contentRating: String(values.ratingFilter ?? "").trim() || undefined, type: String(values.typeFilter ?? "").trim() || undefined, tags: String(values.tagsText ?? "").split(",").map((v) => v.trim()).filter(Boolean) }, ids: String(values.idsText ?? "").split(/[\s,;]+/).filter(Boolean), template: String(values.template ?? DEFAULT_TEMPLATE), dryRun: values.dryRun !== false, permanent: values.permanent === true, copyMode: values.copyMode === true, targetPath: String(values.targetPath ?? "").trim() || undefined, exportFormat: String(values.exportFormat ?? "json") as EngineVExportFormat, exportPath: String(values.exportPath ?? "").trim() || undefined, sortField: String(values.sortField ?? "none") as EngineVSortField, sortOrder: String(values.sortOrder ?? "desc") as EngineVSortOrder }),
    validate: (_values, input) => input.workshopPath ? null : text("请选择工坊目录。", "Select a workshop directory."),
    preview: (input) => [`${text("工作流", "Workflow")}: ${input.action}`, `${text("目录", "Path")}: ${input.workshopPath}`, input.dryRun !== false ? text("预演：不会修改工坊文件。", "Dry-run: workshop files stay unchanged.") : text("真实执行：会修改工坊文件。", "Live: workshop files may change.")],
    isDangerous: (input) => (input.action === "rename" || input.action === "delete") && input.dryRun === false,
    dangerPrompt: (input) => ({ title: text("确认工坊操作", "Confirm workshop operation"), body: input.action === "delete" && input.permanent ? text("选中的工坊目录将被永久删除。", "Selected workshop folders will be permanently deleted.") : text("选中的工坊目录将被修改。", "Selected workshop folders will be modified."), confirmLabel: text("确认执行", "Run now") }),
    result: (result) => ({ success: result.success, message: result.message, lines: result.data?.errors ?? [], table: { columns: [{ id: "workshopId", label: "ID", width: 12 }, { id: "title", label: text("标题", "Title"), width: 34 }, { id: "wallpaperType", label: text("类型", "Type"), width: 12 }], rows: (result.data?.filteredWallpapers?.length ? result.data.filteredWallpapers : result.data?.wallpapers ?? []).map((item) => ({ workshopId: item.workshopId, title: item.title || item.folderName, wallpaperType: item.wallpaperType })), emptyMessage: result.message } }),
  }
}
