/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { ActionTabs, ClickTarget, ExecutionActions, ProgressBar, TerminalThemeProvider, WorkbenchField, WorkbenchPanel, resolveTerminalTheme, terminalIcon, useAnimation, useTerminalChromeActions, useTerminalTheme, useTerminalUiSession } from "@xiranite/cli-runtime/terminal/opentui"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { KavvkaInput, KavvkaMoveRecord, KavvkaProcessResult, KavvkaResult } from "./core.js"

export function KavvkaTui(props: TerminalUiScreenProps<KavvkaInput, KavvkaResult>) { const [theme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit"); return <TerminalThemeProvider theme={resolveTerminalTheme(theme === "inherit" ? "nord" : theme)}><KavvkaWorkbench {...props}/></TerminalThemeProvider> }

function KavvkaWorkbench({ definition, language, onExit }: TerminalUiScreenProps<KavvkaInput, KavvkaResult>) {
  const theme = useTerminalTheme(), t = createTerminalTranslator(language), session = useTerminalUiSession(definition), frame = useAnimation({ intervalMs: session.phase === "running" ? 110 : 560 })
  const action = String(session.values.action ?? "scan"), data = session.result?.data, scans = data?.scanResults ?? [], plans = data?.processResults ?? []
  useTerminalChromeActions({ onReset: session.reset, onExit })
  useKeyboard((key) => { if (key.name === "escape") { if (session.confirming) session.dismissConfirmation(); else onExit() } })
  if (session.confirming) return <Confirm onConfirm={() => void session.confirmExecute()} onDismiss={session.dismissConfirmation}/>
  const field = (id: string) => definition.schema.fields.find((item) => item.id === id)!
  const Field = ({ id, width }: { id: string; width?: `${number}%` }) => session.fields.some((item) => item.id === id) ? <box width={width} flexGrow={width ? 0 : 1}><WorkbenchField field={field(id)} value={session.values[id]} error={session.fieldErrors[id]} focused={session.focusedControlId === id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(id)} onChange={(value) => session.setField(id, value)}/></box> : null
  const scan = action === "scan"
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden">
    <box height={4} flexShrink={0} borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("status")} KAVVKA // PATH LAB`}</b></text><text fg={theme.colors.mutedForeground}>扫描画集候选 · 预演 #compare 路径 · 安全整理同级目录</text></box><text fg={session.phase === "running" ? theme.colors.warning : theme.colors.success}>{`${session.phase === "running" ? "SCAN" : "READY"} ${["·", "•", "●", "•"][frame % 4]}`}</text></box>
    <box height={3} flexShrink={0} marginTop={1} flexDirection="row" justifyContent="space-between"><ActionTabs id="field-action" options={field("action").options ?? []} value={action} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)}/><text fg={theme.colors.mutedForeground}>{`⌕ ${scans.length} · ↳ ${plans.length} · ! ${data?.errorCount ?? 0}`}</text></box>
    <box height={scan ? 8 : 7} flexShrink={0} flexDirection="row" gap={1}><Field id={scan ? "scanRoots" : "paths"} width={scan ? "36%" : "40%"}/>{scan ? <><Field id="keywordText" width="25%"/><Field id="scanDepth" width="14%"/></> : <><box width="20%" flexDirection="column" gap={1}><Field id="dryRun"/><Field id="force"/></box><box width="20%"><Field id="strictArtist"/></box></>}<box width={scan ? "21%" : "20%"} flexDirection="column" borderStyle="rounded" borderColor={session.dangerous ? theme.colors.error : theme.colors.border} paddingLeft={1}><text fg={session.dangerous ? theme.colors.error : theme.colors.mutedForeground}>{session.dangerous ? "! LIVE MOVE" : "◌ SAFE PLAN"}</text><box flexGrow={1}/><ExecutionActions session={session} executeLabel={scan ? "⌕ 扫描候选" : action === "plan" ? "◌ 生成路径计划" : "↳ 开始整理"} confirmLabel="! 确认移动"/></box></box>
    <box flexGrow={1} minHeight={0} marginTop={1} flexDirection="row" gap={1}><WorkbenchPanel title={scan ? "扫描范围" : "源目录队列"} description={scan ? "按关键词寻找可比较的画集目录" : "将同级目录移入画师的 #compare"} width="28%"><scrollbox flexGrow={1}>{String(session.values[scan ? "scanRoots" : "paths"] ?? "").split(/\r?\n/).filter(Boolean).map((path, index) => <text key={`${path}-${index}`}>{`▹ ${path}`}</text>)}<text fg={theme.colors.mutedForeground}>{session.preview[1] ?? "等待输入"}</text></scrollbox></WorkbenchPanel><WorkbenchPanel title={scan ? `候选目录 · ${scans.length}` : `移动计划 · ${plans.length}`} description={scan ? "匹配到的画集与所属扫描根目录" : "源目录、画师目录及 #compare 映射"} width="37%"><scrollbox flexGrow={1}>{scan ? scans.length ? scans.map((item, index) => <box key={`${item.path}-${index}`} flexDirection="column"><text fg={theme.colors.primary}>{`⌕ ${item.name}`}</text><text fg={theme.colors.mutedForeground}>{`  ${item.path}`}</text></box>) : <text fg={theme.colors.mutedForeground}>扫描后在这里列出候选目录。</text> : plans.length ? plans.map((item, index) => <Plan key={`${item.path}-${index}`} item={item}/>) : <text fg={theme.colors.mutedForeground}>预演后显示画师目录与 Czkawka include 路径。</text>}</scrollbox></WorkbenchPanel><WorkbenchPanel title="执行记录" description="进度、警告和最终 Czkawka 路径" flexGrow={1}><box flexDirection="column" alignItems="center"><ascii-font text={session.phase === "running" ? String(session.progress).padStart(3, "0") : scan ? "SCAN" : action === "plan" ? "PLAN" : "MOVE"} font="tiny" color={[theme.colors.primary, theme.colors.focusRing]}/><text fg={theme.colors.primary}>{session.status || "READY"}</text></box><ProgressBar value={session.progress} label={session.preview[0] ?? "准备就绪"}/><scrollbox flexGrow={1}>{data?.allCombinedPaths.map((path, index) => <text key={`${path}-${index}`} fg={theme.colors.success}>{`✓ ${path}`}</text>)}{session.logs.map((line, index) => <text key={`${line}-${index}`} fg={theme.colors.mutedForeground}>{`${String(index + 1).padStart(2, "0")} ${line}`}</text>)}{data?.errors.map((error, index) => <text key={`${error}-${index}`} fg={theme.colors.error}>{`! ${error}`}</text>)}</scrollbox></WorkbenchPanel></box>
  </box>
}

function Plan({ item }: { item: KavvkaProcessResult }) { const theme = useTerminalTheme(); return <box flexDirection="column" borderStyle="single" borderColor={item.success ? theme.colors.border : theme.colors.error} paddingLeft={1}><text fg={item.success ? theme.colors.primary : theme.colors.error}><b>{`${item.success ? "↳" : "!"} ${item.path}`}</b></text>{item.success ? <><text fg={theme.colors.mutedForeground}>{`artist: ${item.artistFolder}`}</text><text fg={theme.colors.success}>{`compare: ${item.compareFolder}`}</text>{item.movedFolders.map((move, index) => <Move key={`${move.source}-${index}`} move={move}/>)}</> : <text fg={theme.colors.error}>{item.error ?? "Invalid source"}</text>}</box> }
function Move({ move }: { move: KavvkaMoveRecord }) { const theme = useTerminalTheme(); return <text fg={move.success ? theme.colors.success : theme.colors.mutedForeground}>{`${move.success ? "✓" : "◌"} ${move.source} → ${move.target}`}</text> }
function Confirm({ onConfirm, onDismiss }: { onConfirm: () => void; onDismiss: () => void }) { const theme = useTerminalTheme(); return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="64%" height={10} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>! 确认移动同级目录</b></text><text>真实执行会将源目录的同级目录移动到画师目录下的 #compare。</text><text fg={theme.colors.mutedForeground}>请返回核对中间的移动计划和右侧 Czkawka 路径。</text><box flexGrow={1}/><box flexDirection="row" gap={2}><ClickTarget id="confirm-execute" bordered onClick={onConfirm}>确认移动</ClickTarget><ClickTarget id="confirm-dismiss" onClick={onDismiss}>返回检查</ClickTarget></box></box></box> }
