//! The nodes whose one implementation is TypeScript, registered for the host that runs them.
//!
//! ADR-0074 §1 allows exactly two executors behind one protocol: a native Rust crate and the host's
//! QuickJS executor. ADR-0074 §6 adds the distribution rule — the shipping binary carries every linked
//! node — which for the scripted side means `include_str!` of the bundle the TypeScript build produced.
//! This crate is where that embedding is declared, so a host binary links one thing instead of growing a
//! hand-written crate per node.
//!
//! ## Where the numbers come from
//!
//! [`registration`] is generated by `bun scripts/embed-node-bundles.ts` from three sources that already
//! exist in this repository: `bundles/index.json` (which node answers which export names),
//! `packages/runtime/src/node-runner.generated.ts` (the message a pure node's envelope carries), and
//! `docs/xiranite-target-node-manifest.json` plus the node's wasm-era `plugins/<id>/manifest.toml`
//! (version, memory ceiling, what the node was measured to need from the host). Nothing here is typed by
//! hand, which is the point: the same table used to be a per-node `register_node!` ceremony.
//!
//! ## Why most nodes are not registered yet, and why that is visible
//!
//! [`UNREGISTERED_BUNDLES`] lists every embedded bundle this crate deliberately does not serve, each with
//! the reason. The reason is the same for nearly all of them: **the policy a `NodeDescriptor` must carry is
//! not authored anywhere in this tree for the QuickJS path.** Root roles, per-node read versus write,
//! external program names and host-service names were stated by the wasm manifests, which survive for a few
//! nodes only, while `audit:node-feasibility` measures `platform.ts` — the half that moves *into* the host
//! under ADR-0074. Registering those nodes would mean inventing their grants, and an invented grant is a
//! wider permission than any measurement supports.
//!
//! So the work that closes this gap is data, not code: author the per-node policy in one place the
//! generator can read, re-run `bun scripts/embed-node-bundles.ts`, and the node appears here. The gate is
//! `--check`, which fails when the table and the bundles disagree.

mod registration;

pub use registration::{SCRIPTED_LINKED_NODES, SCRIPTED_NODE_IDS, UNREGISTERED_BUNDLES};

/// The number of embedded bundles this crate serves.
#[must_use]
pub fn registered_count() -> usize {
    SCRIPTED_NODE_IDS.len()
}

/// The number of embedded bundles it refuses to serve until their policy exists.
#[must_use]
pub fn unregistered_count() -> usize {
    UNREGISTERED_BUNDLES.len()
}
