//! The nodes whose one implementation is TypeScript, registered for the host that runs them.
//!
//! ADR-0074 §1 allows exactly two executors behind one protocol: a native Rust crate and the host's
//! QuickJS executor. ADR-0074 §6 adds the distribution rule — the shipping binary carries every linked
//! node — which for the scripted side means `include_str!` of the bundle the TypeScript build produced.
//! This crate is where that embedding is declared, so a host binary links one thing instead of growing a
//! hand-written crate per node.
//!
//! ## Where the numbers come from
//!
//! [`registration`] is generated by `bun scripts/embed-node-bundles.ts` from three sources that already
//! exist in this repository: `bundles/index.json` (which node answers which export names),
//! `packages/runtime/src/node-runner.generated.ts` (the message a pure node's envelope carries), and
//! `docs/xiranite-target-node-manifest.json` plus the node's wasm-era `plugins/<id>/manifest.toml`
//! (version, memory ceiling, what the node was measured to need from the host). Nothing here is typed by
//! hand, which is the point: the same table used to be a per-node `register_node!` ceremony.
//!
//! ## What is registered, what is refused, and which question is left
//!
//! The grants come from `bun scripts/derive-scripted-policy.ts --requirements` →
//! `artifacts/node-scripted-requirements.json`, which reads the tiers `audit:node-feasibility` already
//! proves per node and translates only the parts that need no invented name: a `workspace` root and its
//! read/write level (proved by a write call site in that node's `platform.ts`), and the recursive-walk
//! flag. So the table is no longer "one node, because nothing else has policy"; it is the nodes whose
//! policy is *derivable*, and 15 of the 24 embedded bundles are that today.
//!
//! [`UNREGISTERED_BUNDLES`] carries the remaining 9, each with the specific name still missing — an
//! external program for `proc.exec`, a host service for `service.invoke`, or a network host. No source in
//! this tree can state those, and an invented grant is a wider permission than any measurement supports,
//! so those nodes stay unregistered and the missing answer is one sentence per node, not a code change.
//! A row whose read/write level rests only on the analyzer's reason text says so in `accessSource`; a
//! node with no `plugins/<id>/manifest.toml` gets no `.budget()` call rather than a made-up number.
//!
//! The gate is `--check`, which fails when the table and the bundles disagree, and
//! `tests/every_generated_node_is_served.rs`, which fails when the table loses an id between its two halves.

mod registration;

// The whole generated surface, because a host binary names each runnable by path through `link_nodes!` and
// needs the anchor statics, not only the tables.
pub use registration::*;

use xiranite_node_registry::NodeRegistry;

/// The number of embedded bundles this crate serves.
#[must_use]
pub fn registered_count() -> usize {
    SCRIPTED_NODE_IDS.len()
}

/// The number of embedded bundles it refuses to serve until their policy exists.
#[must_use]
pub fn unregistered_count() -> usize {
    UNREGISTERED_BUNDLES.len()
}

/// Assembles a registry from the generated table alone — no `link_nodes!` anchor, no inventory.
///
/// This is the assembly shape AGENTS.md now asks for: the per-node `register_node!`/`link_nodes!` ceremony
/// and `NodeRegistry::builtin()` are retired, and a host should get its scripted nodes from one data table.
/// `crates/xiranite-builtin-host` today hand-writes one module per linked node and spells the pair list out
/// in `built_in_registry()`; both halves of that are this function's input, so a host that links this crate
/// reports exactly the node set `--check` verified instead of a set someone maintained by hand.
///
/// # Errors
///
/// [`NodeRegistry::from_registrations`]'s `DuplicateId` — which here would mean the generator emitted one
/// id twice, a build-time disagreement rather than a runtime condition.
pub fn scripted_registry() -> Result<NodeRegistry, xiranite_node_registry::RegistryError> {
    NodeRegistry::from_registrations(
        SCRIPTED_REGISTRATIONS.iter().map(|(descriptor, _node)| *descriptor),
        SCRIPTED_REGISTRATIONS.iter().map(|(_descriptor, node)| *node),
    )
}
