// @generated by scripts/embed-node-bundles.ts — do not edit; rerun the script instead.
//! Generated by `bun scripts/embed-node-bundles.ts`; edit the manifest or the script, not this file.

use xiranite_node_registry::{BuiltInNode, NodeDescriptor, NodeLink, RootAccess, RootRequirement, ProcessGrant};
use xiranite_quickjs_executor::{JsNode, JsNodeSpec};

/// classq: bundled TypeScript, run by the host's QuickJS executor.
static CLASSQ_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/classq.js");
static CLASSQ_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("classq", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    CLASSQ_BUNDLE,
    "runClassq",
    "createNodeClassqRuntime",
);
static CLASSQ_NODE: JsNode = JsNode::new(&CLASSQ_SPEC);
pub static CLASSQ_RUNNABLE: &'static dyn BuiltInNode = &CLASSQ_NODE;

xiranite_node_registry::register_node!(CLASSQ_SPEC.descriptor);
xiranite_node_registry::register_node!(CLASSQ_RUNNABLE);

/// dissolvef: bundled TypeScript, run by the host's QuickJS executor.
static DISSOLVEF_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/dissolvef.js");
static DISSOLVEF_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("dissolvef", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    DISSOLVEF_BUNDLE,
    "runDissolvef",
    "createNodeDissolvefRuntime",
);
static DISSOLVEF_NODE: JsNode = JsNode::new(&DISSOLVEF_SPEC);
pub static DISSOLVEF_RUNNABLE: &'static dyn BuiltInNode = &DISSOLVEF_NODE;

xiranite_node_registry::register_node!(DISSOLVEF_SPEC.descriptor);
xiranite_node_registry::register_node!(DISSOLVEF_RUNNABLE);

/// kisaki: bundled TypeScript, run by the host's QuickJS executor.
static KISAKI_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/kisaki.js");
static KISAKI_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("kisaki", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).with_processes(&[ProcessGrant { program: "explorer.exe", confirm_before_run: false }, ProcessGrant { program: "open", confirm_before_run: false }, ProcessGrant { program: "rundll32.exe", confirm_before_run: true }, ProcessGrant { program: "xdg-open", confirm_before_run: false }]).with_services(&["czkawka", "trash"]).budget(33554432, 1),
    KISAKI_BUNDLE,
    "runKisaki",
    "createNodeKisakiRuntime",
);
static KISAKI_NODE: JsNode = JsNode::new(&KISAKI_SPEC);
pub static KISAKI_RUNNABLE: &'static dyn BuiltInNode = &KISAKI_NODE;

xiranite_node_registry::register_node!(KISAKI_SPEC.descriptor);
xiranite_node_registry::register_node!(KISAKI_RUNNABLE);

/// linedup: bundled TypeScript, run by the host's QuickJS executor.
static LINEDUP_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/linedup.js");
static LINEDUP_SPEC: JsNodeSpec = JsNodeSpec::pure(
    NodeDescriptor::new("linedup", "0.1.0", 1).budget(16777216, 1),
    LINEDUP_BUNDLE,
    "filterLines",
    "Filtered lines.",
);
static LINEDUP_NODE: JsNode = JsNode::new(&LINEDUP_SPEC);
pub static LINEDUP_RUNNABLE: &'static dyn BuiltInNode = &LINEDUP_NODE;

xiranite_node_registry::register_node!(LINEDUP_SPEC.descriptor);
xiranite_node_registry::register_node!(LINEDUP_RUNNABLE);

/// logx: bundled TypeScript, run by the host's QuickJS executor.
static LOGX_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/logx.js");
static LOGX_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("logx", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadOnly }]).budget(67108864, 1),
    LOGX_BUNDLE,
    "runLogx",
    "createNodeLogxRuntime",
);
static LOGX_NODE: JsNode = JsNode::new(&LOGX_SPEC);
pub static LOGX_RUNNABLE: &'static dyn BuiltInNode = &LOGX_NODE;

xiranite_node_registry::register_node!(LOGX_SPEC.descriptor);
xiranite_node_registry::register_node!(LOGX_RUNNABLE);

/// nameu: bundled TypeScript, run by the host's QuickJS executor.
static NAMEU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/nameu.js");
static NAMEU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("nameu", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).budget(33554432, 1),
    NAMEU_BUNDLE,
    "runNameu",
    "createNodeNameuRuntime",
);
static NAMEU_NODE: JsNode = JsNode::new(&NAMEU_SPEC);
pub static NAMEU_RUNNABLE: &'static dyn BuiltInNode = &NAMEU_NODE;

xiranite_node_registry::register_node!(NAMEU_SPEC.descriptor);
xiranite_node_registry::register_node!(NAMEU_RUNNABLE);

/// samea: bundled TypeScript, run by the host's QuickJS executor.
static SAMEA_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/samea.js");
static SAMEA_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("samea", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    SAMEA_BUNDLE,
    "runSamea",
    "createNodeSameaRuntime",
);
static SAMEA_NODE: JsNode = JsNode::new(&SAMEA_SPEC);
pub static SAMEA_RUNNABLE: &'static dyn BuiltInNode = &SAMEA_NODE;

xiranite_node_registry::register_node!(SAMEA_SPEC.descriptor);
xiranite_node_registry::register_node!(SAMEA_RUNNABLE);

/// sleept: bundled TypeScript, run by the host's QuickJS executor.
static SLEEPT_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/sleept.js");
static SLEEPT_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("sleept", "0.1.0", 1).with_services(&["os", "power"]).budget(16777216, 1).run_deadline_ms(86400000),
    SLEEPT_BUNDLE,
    "runSleept",
    "createNodeSleeptRuntime",
);
static SLEEPT_NODE: JsNode = JsNode::new(&SLEEPT_SPEC);
pub static SLEEPT_RUNNABLE: &'static dyn BuiltInNode = &SLEEPT_NODE;

xiranite_node_registry::register_node!(SLEEPT_SPEC.descriptor);
xiranite_node_registry::register_node!(SLEEPT_RUNNABLE);

/// timeu: bundled TypeScript, run by the host's QuickJS executor.
static TIMEU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/timeu.js");
static TIMEU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("timeu", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    TIMEU_BUNDLE,
    "runTimeu",
    "createNodeTimeuRuntime",
);
static TIMEU_NODE: JsNode = JsNode::new(&TIMEU_SPEC);
pub static TIMEU_RUNNABLE: &'static dyn BuiltInNode = &TIMEU_NODE;

xiranite_node_registry::register_node!(TIMEU_SPEC.descriptor);
xiranite_node_registry::register_node!(TIMEU_RUNNABLE);

/// Every scripted node this crate anchors. A host binary spreads this into its own `link_nodes!` list.
/// Both halves of every registered node, in one table, so a host can assemble its registry without
/// naming one static per node. That is the shape AGENTS.md asks for now that the per-node
/// `register_node!`/`link_nodes!` ceremony is retired: one data table in, one `NodeRegistry` out.
pub const SCRIPTED_REGISTRATIONS: &[(&NodeDescriptor, &dyn BuiltInNode)] = &[
    (&CLASSQ_SPEC.descriptor, CLASSQ_RUNNABLE),
    (&DISSOLVEF_SPEC.descriptor, DISSOLVEF_RUNNABLE),
    (&KISAKI_SPEC.descriptor, KISAKI_RUNNABLE),
    (&LINEDUP_SPEC.descriptor, LINEDUP_RUNNABLE),
    (&LOGX_SPEC.descriptor, LOGX_RUNNABLE),
    (&NAMEU_SPEC.descriptor, NAMEU_RUNNABLE),
    (&SAMEA_SPEC.descriptor, SAMEA_RUNNABLE),
    (&SLEEPT_SPEC.descriptor, SLEEPT_RUNNABLE),
    (&TIMEU_SPEC.descriptor, TIMEU_RUNNABLE),
];

/// The anchors a host binary spreads into its own `link_nodes!`, kept for the inventory path.
pub const SCRIPTED_LINKED_NODES: &[NodeLink] = &[
    NodeLink::new(CLASSQ_RUNNABLE),
    NodeLink::new(DISSOLVEF_RUNNABLE),
    NodeLink::new(KISAKI_RUNNABLE),
    NodeLink::new(LINEDUP_RUNNABLE),
    NodeLink::new(LOGX_RUNNABLE),
    NodeLink::new(NAMEU_RUNNABLE),
    NodeLink::new(SAMEA_RUNNABLE),
    NodeLink::new(SLEEPT_RUNNABLE),
    NodeLink::new(TIMEU_RUNNABLE),
];

/// The ids this crate can serve today, in the order the index listed them.
pub const SCRIPTED_NODE_IDS: &[&str] = &["classq", "dissolvef", "kisaki", "linedup", "logx", "nameu", "samea", "sleept", "timeu"];

/// Embedded bundles that are built but deliberately not registered, each with the reason. A host that
/// reports "migration done" while this list is non-empty is lying about the missing policy, not the code.
pub const UNREGISTERED_BUNDLES: &[(&str, &str)] = &[
    ("bitv", "platform node whose grants name nothing yet — external-process: external-process: proc.exec(command) unresolved: exec is called at packages/nodes/bitv/src/platform.ts:46 with ffprobePath | manifest call sites awaiting a name: command at packages/nodes/bitv/src/platform.ts:294"),
    ("classf", "platform node whose grants name nothing yet — os-native: os-native: runClassf (clipboard), createNodeClassfRuntime (clipboard), readClipboardPaths (clipboard)"),
    ("crashu", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("encodeb", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("findz", "platform node whose grants name nothing yet — no-host-free-answer: no-host-free-answer: @parcel/watcher, @xiranite/findz-native; os-native: os-native: @parcel/watcher"),
    ("formatv", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("gifu", "platform node whose grants name nothing yet — external-process: external-process: proc.stop, proc.start(command) unresolved: runCommand is called at packages/nodes/gifu/src/platform.ts:35 with command, proc.wait | manifest call sites awaiting a name: handle at packages/nodes/gifu/src/platform.ts:66; command at packages/nodes/gifu/src/platform.ts:378; started.handle at packages/nodes/gifu/src/platform.ts:381"),
    ("linku", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("marku", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("migratef", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("mvz", "platform node whose grants name nothing yet — external-process: external-process: proc.exec(command) unresolved: runCommand is called at packages/nodes/mvz/src/platform.ts:73 with locator | manifest call sites awaiting a name: command at packages/nodes/mvz/src/platform.ts:80"),
    ("rawfilter", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("recycleu", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
    ("repacku", "platform node whose grants name nothing yet — external-process: external-process: proc.exec(command) unresolved: runCommand is called at packages/nodes/repacku/src/platform.ts:209 with locator | manifest call sites awaiting a name: command at packages/nodes/repacku/src/platform.ts:252"),
    ("trename", "no byte ceiling in any source: the executor refuses max_live_bytes = 0, and this file does not invent one — set maxLiveBytes in docs/xiranite-target-node-manifest.json with a \"maxLiveBytes: <source>\" evidence line"),
];
