// @generated by scripts/embed-node-bundles.ts — do not edit; rerun the script instead.
//! Generated by `bun scripts/embed-node-bundles.ts`; edit the manifest or the script, not this file.

use xiranite_node_registry::{BuiltInNode, NodeDescriptor, NodeLink, RootAccess, RootRequirement, ProcessGrant};
use xiranite_quickjs_executor::{JsNode, JsNodeSpec};

/// classq: bundled TypeScript, run by the host's QuickJS executor.
static CLASSQ_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/classq.js");
static CLASSQ_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("classq", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    CLASSQ_BUNDLE,
    "runClassq",
    "createNodeClassqRuntime",
);
static CLASSQ_NODE: JsNode = JsNode::new(&CLASSQ_SPEC);
pub static CLASSQ_RUNNABLE: &'static dyn BuiltInNode = &CLASSQ_NODE;

xiranite_node_registry::register_node!(CLASSQ_SPEC.descriptor);
xiranite_node_registry::register_node!(CLASSQ_RUNNABLE);

/// crashu: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/crashu/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static CRASHU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/crashu.js");
static CRASHU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("crashu", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]),
    CRASHU_BUNDLE,
    "runCrashu",
    "createNodeCrashuRuntime",
);
static CRASHU_NODE: JsNode = JsNode::new(&CRASHU_SPEC);
pub static CRASHU_RUNNABLE: &'static dyn BuiltInNode = &CRASHU_NODE;

xiranite_node_registry::register_node!(CRASHU_SPEC.descriptor);
xiranite_node_registry::register_node!(CRASHU_RUNNABLE);

/// dissolvef: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/dissolvef/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static DISSOLVEF_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/dissolvef.js");
static DISSOLVEF_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("dissolvef", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    DISSOLVEF_BUNDLE,
    "runDissolvef",
    "createNodeDissolvefRuntime",
);
static DISSOLVEF_NODE: JsNode = JsNode::new(&DISSOLVEF_SPEC);
pub static DISSOLVEF_RUNNABLE: &'static dyn BuiltInNode = &DISSOLVEF_NODE;

xiranite_node_registry::register_node!(DISSOLVEF_SPEC.descriptor);
xiranite_node_registry::register_node!(DISSOLVEF_RUNNABLE);

/// encodeb: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/encodeb/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static ENCODEB_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/encodeb.js");
static ENCODEB_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("encodeb", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    ENCODEB_BUNDLE,
    "runEncodeb",
    "createNodeEncodebRuntime",
);
static ENCODEB_NODE: JsNode = JsNode::new(&ENCODEB_SPEC);
pub static ENCODEB_RUNNABLE: &'static dyn BuiltInNode = &ENCODEB_NODE;

xiranite_node_registry::register_node!(ENCODEB_SPEC.descriptor);
xiranite_node_registry::register_node!(ENCODEB_RUNNABLE);

/// formatv: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/formatv/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static FORMATV_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/formatv.js");
static FORMATV_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("formatv", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    FORMATV_BUNDLE,
    "runFormatv",
    "createNodeFormatvRuntime",
);
static FORMATV_NODE: JsNode = JsNode::new(&FORMATV_SPEC);
pub static FORMATV_RUNNABLE: &'static dyn BuiltInNode = &FORMATV_NODE;

xiranite_node_registry::register_node!(FORMATV_SPEC.descriptor);
xiranite_node_registry::register_node!(FORMATV_RUNNABLE);

/// gifu: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/gifu/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static GIFU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/gifu.js");
static GIFU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("gifu", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).with_processes(&[ProcessGrant { program: "7z", confirm_before_run: false }, ProcessGrant { program: "7zz", confirm_before_run: false }, ProcessGrant { program: "7za", confirm_before_run: false }, ProcessGrant { program: "7z.exe", confirm_before_run: false }, ProcessGrant { program: "7zz.exe", confirm_before_run: false }, ProcessGrant { program: "7za.exe", confirm_before_run: false }, ProcessGrant { program: "ffmpeg", confirm_before_run: false }, ProcessGrant { program: "ffmpeg.exe", confirm_before_run: false }, ProcessGrant { program: "ffprobe", confirm_before_run: false }, ProcessGrant { program: "ffprobe.exe", confirm_before_run: false }]),
    GIFU_BUNDLE,
    "runGifu",
    "createNodeGifuRuntime",
);
static GIFU_NODE: JsNode = JsNode::new(&GIFU_SPEC);
pub static GIFU_RUNNABLE: &'static dyn BuiltInNode = &GIFU_NODE;

xiranite_node_registry::register_node!(GIFU_SPEC.descriptor);
xiranite_node_registry::register_node!(GIFU_RUNNABLE);

/// linedup: bundled TypeScript, run by the host's QuickJS executor.
static LINEDUP_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/linedup.js");
static LINEDUP_SPEC: JsNodeSpec = JsNodeSpec::pure(
    NodeDescriptor::new("linedup", "0.1.0", 1).budget(16777216, 1),
    LINEDUP_BUNDLE,
    "filterLines",
    "Filtered lines.",
);
static LINEDUP_NODE: JsNode = JsNode::new(&LINEDUP_SPEC);
pub static LINEDUP_RUNNABLE: &'static dyn BuiltInNode = &LINEDUP_NODE;

xiranite_node_registry::register_node!(LINEDUP_SPEC.descriptor);
xiranite_node_registry::register_node!(LINEDUP_RUNNABLE);

/// linku: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/linku/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static LINKU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/linku.js");
static LINKU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("linku", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    LINKU_BUNDLE,
    "runLinku",
    "createNodeLinkuRuntime",
);
static LINKU_NODE: JsNode = JsNode::new(&LINKU_SPEC);
pub static LINKU_RUNNABLE: &'static dyn BuiltInNode = &LINKU_NODE;

xiranite_node_registry::register_node!(LINKU_SPEC.descriptor);
xiranite_node_registry::register_node!(LINKU_RUNNABLE);

/// logx: bundled TypeScript, run by the host's QuickJS executor.
static LOGX_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/logx.js");
static LOGX_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("logx", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadOnly }]).budget(67108864, 1),
    LOGX_BUNDLE,
    "runLogx",
    "createNodeLogxRuntime",
);
static LOGX_NODE: JsNode = JsNode::new(&LOGX_SPEC);
pub static LOGX_RUNNABLE: &'static dyn BuiltInNode = &LOGX_NODE;

xiranite_node_registry::register_node!(LOGX_SPEC.descriptor);
xiranite_node_registry::register_node!(LOGX_RUNNABLE);

/// marku: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/marku/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static MARKU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/marku.js");
static MARKU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("marku", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    MARKU_BUNDLE,
    "runMarku",
    "createNodeMarkuRuntime",
);
static MARKU_NODE: JsNode = JsNode::new(&MARKU_SPEC);
pub static MARKU_RUNNABLE: &'static dyn BuiltInNode = &MARKU_NODE;

xiranite_node_registry::register_node!(MARKU_SPEC.descriptor);
xiranite_node_registry::register_node!(MARKU_RUNNABLE);

/// migratef: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/migratef/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static MIGRATEF_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/migratef.js");
static MIGRATEF_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("migratef", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    MIGRATEF_BUNDLE,
    "runMigratef",
    "createNodeMigratefRuntime",
);
static MIGRATEF_NODE: JsNode = JsNode::new(&MIGRATEF_SPEC);
pub static MIGRATEF_RUNNABLE: &'static dyn BuiltInNode = &MIGRATEF_NODE;

xiranite_node_registry::register_node!(MIGRATEF_SPEC.descriptor);
xiranite_node_registry::register_node!(MIGRATEF_RUNNABLE);

/// nameu: bundled TypeScript, run by the host's QuickJS executor.
static NAMEU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/nameu.js");
static NAMEU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("nameu", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).budget(33554432, 1),
    NAMEU_BUNDLE,
    "runNameu",
    "createNodeNameuRuntime",
);
static NAMEU_NODE: JsNode = JsNode::new(&NAMEU_SPEC);
pub static NAMEU_RUNNABLE: &'static dyn BuiltInNode = &NAMEU_NODE;

xiranite_node_registry::register_node!(NAMEU_SPEC.descriptor);
xiranite_node_registry::register_node!(NAMEU_RUNNABLE);

/// rawfilter: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/rawfilter/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static RAWFILTER_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/rawfilter.js");
static RAWFILTER_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("rawfilter", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]),
    RAWFILTER_BUNDLE,
    "runRawfilter",
    "createNodeRawfilterRuntime",
);
static RAWFILTER_NODE: JsNode = JsNode::new(&RAWFILTER_SPEC);
pub static RAWFILTER_RUNNABLE: &'static dyn BuiltInNode = &RAWFILTER_NODE;

xiranite_node_registry::register_node!(RAWFILTER_SPEC.descriptor);
xiranite_node_registry::register_node!(RAWFILTER_RUNNABLE);

/// samea: bundled TypeScript, run by the host's QuickJS executor.
static SAMEA_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/samea.js");
static SAMEA_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("samea", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    SAMEA_BUNDLE,
    "runSamea",
    "createNodeSameaRuntime",
);
static SAMEA_NODE: JsNode = JsNode::new(&SAMEA_SPEC);
pub static SAMEA_RUNNABLE: &'static dyn BuiltInNode = &SAMEA_NODE;

xiranite_node_registry::register_node!(SAMEA_SPEC.descriptor);
xiranite_node_registry::register_node!(SAMEA_RUNNABLE);

/// timeu: bundled TypeScript, run by the host's QuickJS executor.
static TIMEU_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/timeu.js");
static TIMEU_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("timeu", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true).budget(16777216, 1),
    TIMEU_BUNDLE,
    "runTimeu",
    "createNodeTimeuRuntime",
);
static TIMEU_NODE: JsNode = JsNode::new(&TIMEU_SPEC);
pub static TIMEU_RUNNABLE: &'static dyn BuiltInNode = &TIMEU_NODE;

xiranite_node_registry::register_node!(TIMEU_SPEC.descriptor);
xiranite_node_registry::register_node!(TIMEU_RUNNABLE);

/// trename: bundled TypeScript, run by the host's QuickJS executor. — no memory ceiling authored in `plugins/trename/manifest.toml`, so none is invented; the grants come from `accessSource` in the requirements artifact
static TRENAME_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/trename.js");
static TRENAME_SPEC: JsNodeSpec = JsNodeSpec::platform(
    NodeDescriptor::new("trename", "0.1.0", 1).with_roots(&[RootRequirement { role: "workspace", access: RootAccess::ReadWrite }]).walk_tree(true),
    TRENAME_BUNDLE,
    "runTrename",
    "createNodeTrenameRuntime",
);
static TRENAME_NODE: JsNode = JsNode::new(&TRENAME_SPEC);
pub static TRENAME_RUNNABLE: &'static dyn BuiltInNode = &TRENAME_NODE;

xiranite_node_registry::register_node!(TRENAME_SPEC.descriptor);
xiranite_node_registry::register_node!(TRENAME_RUNNABLE);

/// Every scripted node this crate anchors. A host binary spreads this into its own `link_nodes!` list.
/// Both halves of every registered node, in one table, so a host can assemble its registry without
/// naming one static per node. That is the shape AGENTS.md asks for now that the per-node
/// `register_node!`/`link_nodes!` ceremony is retired: one data table in, one `NodeRegistry` out.
pub const SCRIPTED_REGISTRATIONS: &[(&NodeDescriptor, &dyn BuiltInNode)] = &[
    (&CLASSQ_SPEC.descriptor, CLASSQ_RUNNABLE),
    (&CRASHU_SPEC.descriptor, CRASHU_RUNNABLE),
    (&DISSOLVEF_SPEC.descriptor, DISSOLVEF_RUNNABLE),
    (&ENCODEB_SPEC.descriptor, ENCODEB_RUNNABLE),
    (&FORMATV_SPEC.descriptor, FORMATV_RUNNABLE),
    (&GIFU_SPEC.descriptor, GIFU_RUNNABLE),
    (&LINEDUP_SPEC.descriptor, LINEDUP_RUNNABLE),
    (&LINKU_SPEC.descriptor, LINKU_RUNNABLE),
    (&LOGX_SPEC.descriptor, LOGX_RUNNABLE),
    (&MARKU_SPEC.descriptor, MARKU_RUNNABLE),
    (&MIGRATEF_SPEC.descriptor, MIGRATEF_RUNNABLE),
    (&NAMEU_SPEC.descriptor, NAMEU_RUNNABLE),
    (&RAWFILTER_SPEC.descriptor, RAWFILTER_RUNNABLE),
    (&SAMEA_SPEC.descriptor, SAMEA_RUNNABLE),
    (&TIMEU_SPEC.descriptor, TIMEU_RUNNABLE),
    (&TRENAME_SPEC.descriptor, TRENAME_RUNNABLE),
];

/// The anchors a host binary spreads into its own `link_nodes!`, kept for the inventory path.
pub const SCRIPTED_LINKED_NODES: &[NodeLink] = &[
    NodeLink::new(CLASSQ_RUNNABLE),
    NodeLink::new(CRASHU_RUNNABLE),
    NodeLink::new(DISSOLVEF_RUNNABLE),
    NodeLink::new(ENCODEB_RUNNABLE),
    NodeLink::new(FORMATV_RUNNABLE),
    NodeLink::new(GIFU_RUNNABLE),
    NodeLink::new(LINEDUP_RUNNABLE),
    NodeLink::new(LINKU_RUNNABLE),
    NodeLink::new(LOGX_RUNNABLE),
    NodeLink::new(MARKU_RUNNABLE),
    NodeLink::new(MIGRATEF_RUNNABLE),
    NodeLink::new(NAMEU_RUNNABLE),
    NodeLink::new(RAWFILTER_RUNNABLE),
    NodeLink::new(SAMEA_RUNNABLE),
    NodeLink::new(TIMEU_RUNNABLE),
    NodeLink::new(TRENAME_RUNNABLE),
];

/// The ids this crate can serve today, in the order the index listed them.
pub const SCRIPTED_NODE_IDS: &[&str] = &["classq", "crashu", "dissolvef", "encodeb", "formatv", "gifu", "linedup", "linku", "logx", "marku", "migratef", "nameu", "rawfilter", "samea", "timeu", "trename"];

/// Embedded bundles that are built but deliberately not registered, each with the reason. A host that
/// reports "migration done" while this list is non-empty is lying about the missing policy, not the code.
pub const UNREGISTERED_BUNDLES: &[(&str, &str)] = &[
    ("bitv", "platform node whose grants name nothing yet — external-process: external-process: execFile, node:child_process"),
    ("classf", "platform node whose grants name nothing yet — os-native: os-native: runClassf (clipboard), createNodeClassfRuntime (clipboard), readClipboardPaths (clipboard)"),
    ("findz", "platform node whose grants name nothing yet — no-host-free-answer: no-host-free-answer: @parcel/watcher, @xiranite/findz-native; os-native: os-native: @parcel/watcher"),
    ("kisaki", "platform node whose grants name nothing yet — os-native: os-native: @xiranite/czkawka-native, @xiranite/file-operations; external-process: external-process: execFileAsync, node:child_process"),
    ("mvz", "platform node whose grants name nothing yet — external-process: external-process: execFile, node:child_process"),
    ("recycleu", "platform node whose grants name nothing yet — external-process: external-process: execFileAsync, node:child_process"),
    ("repacku", "platform node whose grants name nothing yet — external-process: external-process: execFile, node:child_process"),
    ("sleept", "platform node whose grants name nothing yet — external-process: external-process: execFileAsync, node:child_process"),
];
