/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import { ActionTabs, ClickTarget, ExecutionActions, ProgressBar, resolveTerminalTheme, TerminalPreferencesScreen, TerminalThemeProvider, terminalIcon, useTerminalChromeActions, useTerminalTheme, useTerminalUiSession, WorkbenchField, WorkbenchPanel } from "@xiranite/cli-runtime/terminal/opentui"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { XlchemyInput, XlchemyResult } from "./core.js"

export function XlchemyTui(props: TerminalUiScreenProps<XlchemyInput, XlchemyResult>) {
  const [previewTheme, setPreviewTheme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit")
  return <TerminalThemeProvider theme={resolveTerminalTheme(previewTheme === "inherit" ? "nord" : previewTheme)}><Workbench {...props} onThemePreview={setPreviewTheme} /></TerminalThemeProvider>
}

function Workbench({ definition, language, preferences, onExit, onThemePreview }: TerminalUiScreenProps<XlchemyInput, XlchemyResult> & { onThemePreview: (theme: string) => void }) {
  const theme = useTerminalTheme(), t = createTerminalTranslator(language), session = useTerminalUiSession(definition)
  const [settings, setSettings] = useState(false), [sectionId, setSectionId] = useState("input")
  const paths = String(session.values.pathsText ?? "").split(/\r?\n/).map((value) => value.trim()).filter(Boolean)
  const rows = session.resultSummary?.table?.rows ?? [], sections = definition.schema.view?.sections ?? []
  const section = sections.find((item) => item.id === sectionId) ?? sections[0]
  const sectionFields = (section?.fieldIds ?? []).flatMap((id) => { const item = definition.schema.fields.find((field) => field.id === id); return item && id !== "action" && id !== "pathsText" && (item.visibleWhen?.(session.values) ?? true) ? [item] : [] })
  const pathField = definition.schema.fields.find((item) => item.id === "pathsText")!
  useTerminalChromeActions({ onReset: session.reset, onExit, resetLabel: `↺ ${t("reset")}`, exitLabel: `× ${language === "zh" ? "退出" : "Exit"}` })
  useKeyboard((key) => { if (key.name !== "escape") return; if (settings) setSettings(false); else if (session.confirming) session.dismissConfirmation(); else if (session.phase === "running" || session.phase === "paused") void session.cancel(); else onExit() })
  if (settings && preferences) return <TerminalPreferencesScreen controller={preferences} focusedId={session.focusedControlId} onFocus={session.focus} onPreviewTheme={onThemePreview} onBack={() => setSettings(false)} />
  if (session.confirming) return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="70%" height={9} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>{`${terminalIcon("danger")} ${session.dangerPrompt?.title}`}</b></text><text>{session.dangerPrompt?.body}</text><ExecutionActions session={session} executeLabel="" confirmLabel={language === "zh" ? "确认转换" : "Convert"} /></box></box>
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden">
    <box height={4} flexShrink={0} borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("section")} XLCHEMY // IMAGE TRANSCODE`}</b></text><text fg={theme.colors.mutedForeground}>{session.status || (language === "zh" ? "完整转换、文件、缩小、元数据与高级能力" : "Complete conversion, file, resize, metadata, and advanced capabilities")}</text></box>{preferences ? <ClickTarget id="settings" onClick={() => setSettings(true)}>{`${terminalIcon("settings")} CONFIG`}</ClickTarget> : null}</box>
    <box height={3} marginTop={1} flexShrink={0} flexDirection="row" justifyContent="space-between"><ActionTabs id="field-action" options={[{ value: "plan", label: "⌕ PLAN" }, { value: "convert", label: "▶ CONVERT" }, { value: "diagnose", label: "◇ DIAGNOSE" }]} value={String(session.values.action ?? "plan")} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)} /><text fg={theme.colors.mutedForeground}>{`${paths.length} FILES · ${session.progress}%`}</text></box>
    <box flexDirection="row" flexGrow={1} minHeight={0} gap={1}>
      <WorkbenchPanel title={`${terminalIcon("path")} ${language === "zh" ? "本地输入队列" : "Local input queue"}`} width="30%"><WorkbenchField field={pathField} value={session.values.pathsText} error={session.fieldErrors.pathsText} focused={session.focusedControlId === "pathsText"} disabled={session.phase === "running"} t={t} onFocus={() => session.focus("pathsText")} onChange={(value) => session.setField("pathsText", value)} /><scrollbox flexGrow={1}>{paths.map((path, index) => <text key={`${path}-${index}`} fg={theme.colors.mutedForeground}>{`${index === 0 ? "▸" : "·"} ${path}`}</text>)}</scrollbox></WorkbenchPanel>
      <WorkbenchPanel title={`${terminalIcon("section")} ${section?.title ?? "Configuration"}`} width="42%"><ActionTabs id="xlchemy-section" options={sections.map((item) => ({ value: item.id, label: item.title }))} value={sectionId} focused={session.focusedControlId === "xlchemy-section"} disabled={session.phase === "running"} onFocus={() => session.focus("xlchemy-section")} onChange={(value) => setSectionId(String(value))} /><scrollbox flexGrow={1} marginTop={1}><box flexDirection="column" gap={1}>{sectionFields.map((item) => <WorkbenchField key={item.id} field={item} value={session.values[item.id]} error={session.fieldErrors[item.id]} focused={session.focusedControlId === item.id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(item.id)} onChange={(value) => session.setField(item.id, value)} />)}</box></scrollbox></WorkbenchPanel>
      <WorkbenchPanel title={`${terminalIcon("result")} ${language === "zh" ? "批次结果" : "Batch results"}`} flexGrow={1}><scrollbox flexGrow={1}>{rows.length ? rows.map((row, index) => <text key={`${row.source}-${index}`} fg={row.status === "error" ? theme.colors.error : theme.colors.foreground}>{`${row.status} ${row.source} → ${row.output}`}</text>) : session.preview.map((line, index) => <text key={`${line}-${index}`} fg={index ? theme.colors.mutedForeground : theme.colors.primary}>{line}</text>)}</scrollbox><ProgressBar value={session.progress} label={session.status || "READY"} /></WorkbenchPanel>
    </box>
    <box height={5} flexShrink={0} marginTop={1} borderStyle="rounded" borderColor={session.dangerous ? theme.colors.error : theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.mutedForeground}>{language === "zh" ? "所有 GUI 转换参数均可在上方四个配置页访问" : "All GUI conversion parameters are available in the four configuration pages"}</text><text fg={theme.colors.mutedForeground}>{session.status || "READY"}</text></box><ExecutionActions session={session} executeLabel={`▶ ${language === "zh" ? "执行批次" : "Run batch"}`} confirmLabel={`${terminalIcon("danger")} ${language === "zh" ? "确认" : "Confirm"}`} /></box>
  </box>
}
