/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { ActionTabs, ClickTarget, ExecutionActions, ProgressBar, TerminalThemeProvider, WorkbenchField, WorkbenchPanel, resolveTerminalTheme, terminalIcon, useAnimation, useTerminalChromeActions, useTerminalTheme, useTerminalUiSession } from "@xiranite/cli-runtime/terminal/opentui"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { ClassqInput, ClassqPlanItem, ClassqResult } from "./core.js"

export function ClassqTui(props: TerminalUiScreenProps<ClassqInput, ClassqResult>) { const [theme] = useState(props.theme ?? props.preferences?.current.theme ?? "inherit"); return <TerminalThemeProvider theme={resolveTerminalTheme(theme === "inherit" ? "nord" : theme)}><ClassqWorkbench {...props}/></TerminalThemeProvider> }
function ClassqWorkbench({ definition, language, onExit }: TerminalUiScreenProps<ClassqInput, ClassqResult>) {
  const theme = useTerminalTheme(), t = createTerminalTranslator(language), session = useTerminalUiSession(definition), pulse = useAnimation({ intervalMs: session.phase === "running" ? 100 : 500 })
  const [selected, setSelected] = useState(0), data = session.result?.data, items = data?.items ?? [], action = String(session.values.action ?? "plan")
  useTerminalChromeActions({ onReset: session.reset, onExit })
  useKeyboard((key) => { if (key.name === "escape") { if (session.confirming) session.dismissConfirmation(); else onExit() }; if (key.name === "up") setSelected((value) => Math.max(0, value - 1)); if (key.name === "down") setSelected((value) => Math.min(Math.max(0, items.length - 1), value + 1)) })
  if (session.confirming) return <Confirm onConfirm={() => void session.confirmExecute()} onDismiss={session.dismissConfirmation}/>
  const field = (id: string) => definition.schema.fields.find((item) => item.id === id)!
  const Field = ({ id, width }: { id: string; width?: `${number}%` }) => session.fields.some((item) => item.id === id) ? <box width={width} flexGrow={width ? 0 : 1}><WorkbenchField field={field(id)} value={session.values[id]} error={session.fieldErrors[id]} focused={session.focusedControlId === id} disabled={session.phase === "running"} t={t} onFocus={() => session.focus(id)} onChange={(value) => session.setField(id, value)}/></box> : null
  return <box width="100%" height="100%" flexDirection="column" paddingLeft={1} paddingRight={1} overflow="hidden">
    <box height={4} flexShrink={0} borderStyle="single" borderColor={theme.colors.border} paddingLeft={1} paddingRight={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={theme.colors.primary}><b>{`${terminalIcon("status")} CLASSQ // ROUTING TOPOLOGY`}</b></text><text fg={theme.colors.mutedForeground}>关键词命中目录与同级 wait 归档路由</text></box><text fg={session.phase === "running" ? theme.colors.warning : theme.colors.success}>{`${session.phase === "running" ? "ROUTING" : "READY"} ${["◐", "◓", "◑", "◒"][pulse % 4]}`}</text></box>
    <box height={3} flexShrink={0} marginTop={1} flexDirection="row" justifyContent="space-between"><ActionTabs id="field-action" options={field("action").options ?? []} value={action} focused={session.focusedControlId === "action"} disabled={session.phase === "running"} onFocus={() => session.focus("action")} onChange={(value) => session.setField("action", value)}/><text fg={theme.colors.mutedForeground}>{`⌕ ${data?.keywordCount ?? 0} · ✓ ${data?.readyCount ?? 0} · ⚠ ${data?.conflictCount ?? 0}`}</text></box>
    <box height={7} flexShrink={0} flexDirection="row" gap={1}><Field id="paths" width="38%"/><Field id="keyword" width="14%"/><Field id="waitKeyword" width="14%"/>{action === "classify" ? <><Field id="transferMode"/><Field id="dryRun"/></> : null}<box flexGrow={1} flexDirection="column" borderStyle="rounded" borderColor={session.dangerous ? theme.colors.error : theme.colors.border} paddingLeft={1}><text fg={session.dangerous ? theme.colors.error : theme.colors.mutedForeground}>{session.dangerous ? "⚠ LIVE ROUTING" : "◇ DRY RUN"}</text><box flexGrow={1}/><ExecutionActions session={session} executeLabel={action === "classify" ? "↳ 分类路由" : "⌕ 扫描计划"} confirmLabel="⚠ 确认分类"/></box></box>
    <box flexGrow={1} minHeight={0} marginTop={1} flexDirection="row" gap={1}><WorkbenchPanel title="目录路由图" description="关键词目录和 wait 接收目录" width="42%"><scrollbox flexGrow={1}>{items.length ? <Topology items={items}/> : <text fg={theme.colors.mutedForeground}>输入根目录并扫描后显示路由拓扑。</text>}</scrollbox></WorkbenchPanel><WorkbenchPanel title={`分类计划 · ${items.length}`} description="红色冲突项不会执行" flexGrow={1}><scrollbox flexGrow={1}>{items.length ? items.map((item, index) => <PlanRow key={`${item.sourcePath}-${index}`} item={item} selected={selected === index} onClick={() => setSelected(index)}/>) : <text fg={theme.colors.mutedForeground}>扫描结果将在这里按目标路径列出。</text>}</scrollbox><ProgressBar value={session.progress} label={session.status || "READY"}/></WorkbenchPanel></box>
  </box>
}
function Topology({ items }: { items: ClassqPlanItem[] }) { const theme = useTerminalTheme(); return <box flexDirection="column">{items.filter((item) => item.stage === "keyword").map((item) => <box key={item.sourcePath} flexDirection="column" marginBottom={1}><text fg={theme.colors.primary}><b>{`▣ ${item.sourceName}`}</b></text><text fg={theme.colors.mutedForeground}>{`  └─ ${item.parentPath}`}</text>{items.filter((candidate) => candidate.parentPath === item.parentPath && candidate.stage === "wait").map((candidate) => <text key={candidate.sourcePath} fg={candidate.status === "conflict" ? theme.colors.error : theme.colors.success}>{`     ├─ ${candidate.sourceName}  →  ${candidate.targetRelative}`}</text>)}<text fg={theme.colors.primary}>{`     └─ ◉ ${item.targetPath}`}</text></box>)}</box> }
function PlanRow({ item, selected, onClick }: { item: ClassqPlanItem; selected: boolean; onClick: () => void }) { const theme = useTerminalTheme(), conflict = item.status === "conflict" || item.status === "error"; return <box flexDirection="column" borderStyle="single" borderColor={selected ? theme.colors.focusRing : conflict ? theme.colors.error : theme.colors.border} paddingLeft={1} paddingRight={1} onMouseDown={onClick}><box flexDirection="row" justifyContent="space-between"><text fg={conflict ? theme.colors.error : item.status === "ready" ? theme.colors.success : theme.colors.primary}><b>{`${conflict ? "⚠" : item.kind === "folder" ? "▣" : "•"} ${item.sourceName}`}</b></text><text fg={theme.colors.mutedForeground}>{item.status}</text></box><text fg={theme.colors.mutedForeground}>{`↳ ${item.targetRelative}${item.reason ? ` · ${item.reason}` : ""}`}</text></box> }
function Confirm({ onConfirm, onDismiss }: { onConfirm: () => void; onDismiss: () => void }) { const theme = useTerminalTheme(); return <box width="100%" height="100%" alignItems="center" justifyContent="center"><box width="64%" height={10} flexDirection="column" borderStyle="double" borderColor={theme.colors.error} paddingLeft={2} paddingRight={2}><text fg={theme.colors.error}><b>⚠ 确认真实分类</b></text><text>所有就绪项将按当前移动或复制规则执行。</text><text fg={theme.colors.mutedForeground}>请先检查路由拓扑和冲突项。</text><box flexGrow={1}/><box flexDirection="row" gap={2}><ClickTarget id="confirm-execute" bordered onClick={onConfirm}>确认分类</ClickTarget><ClickTarget id="confirm-dismiss" onClick={onDismiss}>返回</ClickTarget></box></box></box> }
