/**
 * @migrated-from src/lib/cards/upscale/UpscaleStatusCard.svelte
 * @source-hash sha256:096fc57a59abffe9daf6d1fbe64624482db714adfcd2d6a432ceb822afa6a6ae
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported template node ConstTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Loader2, Check, X, SkipForward, ImageOff } from 'lucide-react';
import { upscaleStore, type UpscaleStatus } from '$lib/stackview/stores/upscaleStore.js';
import { bookStore } from '$lib/stores/book.js';
import { registerBookPath, getArchiveImageUrl } from '$lib/api/imageProtocol';
import { selectedModel, scale } from '$lib/stores/upscale/upscalePanelStore.js';
interface StatusInfo {
		label: string;
		color: string;
		icon: typeof Check;
		description: string;
	}

export function UpscaleStatusCard() {
  let currentPageIndex = $derived(upscaleStore.currentPageIndex);

  let pageFullStatus = $derived(upscaleStore.getPageFullStatus(currentPageIndex));

  let pageStatus = $derived(pageFullStatus?.status ?? null);

  let hasUpscaled = $derived(upscaleStore.isPageUpscaled(currentPageIndex));

  let useUpscaled = $state(true);

  let showPreview = $state(false);

  let showZoomCompare = $state(false);

  let floatWindow = $state({
      width: 400,
      height: 450,
      x: 0, // 由 CSS right 控制，这里不用
      y: 0
    });

  let resizing = $state<string | null>(null);

  let startPos = { x: 0, y: 0, width: 0, height: 0 };

  function startResize(e: MouseEvent, direction: string) {
      e.preventDefault();
      resizing = direction;
      startPos = {
        x: e.clientX,
        y: e.clientY,
        width: floatWindow.width,
        height: floatWindow.height
      };
      window.addEventListener('mousemove', onResize);
      window.addEventListener('mouseup', stopResize);
    }

  function onResize(e: MouseEvent) {
      if (!resizing) return;

      const dx = e.clientX - startPos.x;
      const dy = e.clientY - startPos.y;

      let newWidth = startPos.width;
      let newHeight = startPos.height;

      // 根据方向调整
      if (resizing.includes('e')) newWidth = Math.max(200, startPos.width + dx);
      if (resizing.includes('w')) newWidth = Math.max(200, startPos.width - dx);
      if (resizing.includes('s')) newHeight = Math.max(200, startPos.height + dy);
      if (resizing.includes('n')) newHeight = Math.max(200, startPos.height - dy);

      floatWindow.width = newWidth;
      floatWindow.height = newHeight;
    }

  function stopResize() {
      resizing = null;
      window.removeEventListener('mousemove', onResize);
      window.removeEventListener('mouseup', stopResize);
    }

  let bookHash = $state<string>('');

  $effect(() => {
      const book = bookStore.currentBook;
      if (book) {
        registerBookPath(book.path).then((h) => {
          bookHash = h;
        });
      }
    });

  let originalUrl = $derived(bookHash ? getArchiveImageUrl(bookHash, currentPageIndex) : null);

  let upscaledUrl = $derived(upscaleStore.getPageUpscaleUrl(currentPageIndex));

  let displayUrl = $derived(useUpscaled && upscaledUrl ? upscaledUrl : originalUrl);

  let originalDimensions = $derived.by(() => {
      const book = bookStore.currentBook;
      const page = book?.pages?.[currentPageIndex];
      if (!page?.width || !page?.height) return null;
      return { width: page.width, height: page.height };
    });

  let actualModelName = $derived(pageFullStatus?.modelName ?? selectedModel.value);

  let actualScale = $derived(pageFullStatus?.scale ?? scale.value);

  function getStatusInfo(status: UpscaleStatus | null): StatusInfo {
      switch (status) {
        case 'pending':
          return {
            label: '等待中',
            color: 'text-muted-foreground',
            icon: Loader2,
            description: '排队等待超分'
          };
        case 'processing':
          return {
            label: '超分中',
            color: 'text-blue-500',
            icon: Loader2,
            description: '正在进行超分处理'
          };
        case 'completed':
          return { label: '已完成', color: 'text-green-500', icon: Check, description: '超分完成' };
        case 'skipped':
          return {
            label: '已跳过',
            color: 'text-yellow-500',
            icon: SkipForward,
            description: '不符合条件，已跳过'
          };
        case 'failed':
          return { label: '失败', color: 'text-red-500', icon: X, description: '超分处理失败' };
        case 'cancelled':
          return {
            label: '已取消',
            color: 'text-muted-foreground',
            icon: X,
            description: '任务已取消'
          };
        default:
          return {
            label: '未超分',
            color: 'text-muted-foreground',
            icon: ImageOff,
            description: '尚未进行超分'
          };
      }
    }

  let statusInfo = $derived(getStatusInfo(pageStatus));

  let upscaledDimensions = $derived.by(() => {
      // 优先使用后端返回的实际尺寸
      if (pageFullStatus?.upscaledSize) {
        return {
          width: pageFullStatus.upscaledSize[0],
          height: pageFullStatus.upscaledSize[1]
        };
      }
      // 否则根据原图尺寸和倍率计算
      if (!originalDimensions || !hasUpscaled) return null;
      const s = actualScale || 2;
      return {
        width: originalDimensions.width * s,
        height: originalDimensions.height * s
      };
    });
  return (
    <Fragment>

<div className="space-y-3 text-xs">
	{/*  页面信息  */}
	<div className="flex items-center justify-between">
		<span className="text-muted-foreground">当前页面</span>
		<span className="font-mono">{currentPageIndex + 1}</span>
	</div>

	{/*  超分状态  */}
	<div className="bg-muted/50 space-y-2 rounded-lg p-2">
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground">状态</span>
			<span className={`flex items-center gap-1.5 ${statusInfo.color}`}>
				{pageStatus === 'processing' ? (<Fragment>
					<Loader2 className="h-3.5 w-3.5 animate-spin"></Loader2>
				</Fragment>) : (<Fragment>
					{/* TODO unsupported ConstTag */}
					<Icon className="h-3.5 w-3.5"></Icon>
				</Fragment>)}
				<span className="font-medium">{statusInfo.label}</span>
			</span>
		</div>
		<p className="text-muted-foreground text-[10px]">{statusInfo.description}</p>
	</div>

	{/*  模型信息  */}
	{upscaleStore.enabled ? (<Fragment>
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground">模型</span>
			<span className="max-w-30 truncate font-mono text-[10px]" title={actualModelName}>
				{actualModelName}
				{pageFullStatus?.modelName ? (<Fragment>
					<span className="ml-1 text-green-500">✓</span>
				</Fragment>) : null}
			</span>
		</div>
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground">放大倍率</span>
			<span className="font-mono">
				{actualScale}x
				{pageFullStatus?.scale ? (<Fragment>
					<span className="ml-1 text-green-500">✓</span>
				</Fragment>) : null}
			</span>
		</div>
	</Fragment>) : null}

	{/*  尺寸信息  */}
	{originalDimensions && originalDimensions.width > 0 ? (<Fragment>
		<div className="space-y-1">
			<div className="flex items-center justify-between">
				<span className="text-muted-foreground">原图尺寸</span>
				<span className="font-mono">{originalDimensions.width}×{originalDimensions.height}</span>
			</div>
			{hasUpscaled && upscaledDimensions ? (<Fragment>
				<div className="flex items-center justify-between text-green-500">
					<span>超分尺寸</span>
					<span className="font-mono">{upscaledDimensions.width}×{upscaledDimensions.height}</span>
				</div>
			</Fragment>) : null}
		</div>
	</Fragment>) : null}

	{/*  预览开关  */}
	<div className="flex items-center justify-between">
		<span className="text-muted-foreground">显示预览</span>
		<button className={`relative h-4 w-8 rounded-full transition-colors ${showPreview
				? 'bg-primary'
				: 'bg-muted'}`} onClick={() => (showPreview = !showPreview)} aria-label="切换预览显示">
			<span className={`absolute top-0.5 left-0.5 h-3 w-3 rounded-full bg-white transition-transform ${showPreview
					? 'translate-x-4'
					: ''}`}></span>
		</button>
	</div>

	{/*  预览图和对比切换  */}
	{showPreview && displayUrl ? (<Fragment>
		<div className="space-y-2">
			{/*  点击切换原图/超分图  */}
			<button className="border-border/50 hover:border-primary/50 w-full overflow-hidden rounded-lg border transition-colors" onClick={() => {
					if (hasUpscaled) useUpscaled = !useUpscaled;
				}} disabled={!hasUpscaled} aria-label="切换原图/超分图对比">
				<img src={displayUrl} alt={useUpscaled && hasUpscaled ? '超分图' : '原图'} className="bg-muted/30 h-auto max-h-50 w-full object-contain" />
			</button>
			{/*  当前显示状态  */}
			<div className="flex items-center justify-center gap-2 text-[10px]">
				{hasUpscaled ? (<Fragment>
					<span className={useUpscaled ? 'font-medium text-green-500' : 'text-muted-foreground'}>
						{useUpscaled ? '🔍 超分图' : '📷 原图'}
					</span>
					<span className="text-muted-foreground">（点击图片切换）</span>
				</Fragment>) : (<Fragment>
					<span className="text-muted-foreground">📷 原图</span>
				</Fragment>)}
			</div>
		</div>
	</Fragment>) : (<Fragment>{showPreview && !displayUrl ? (<Fragment>
		<div className="text-muted-foreground bg-muted/30 rounded-lg p-4 text-center">暂无图片</div>
	</Fragment>) : null}</Fragment>)}

	{/*  放大对比开关（仅在有超分图时显示）  */}
	{hasUpscaled ? (<Fragment>
		<div className="flex items-center justify-between">
			<span className="text-muted-foreground">放大对比</span>
			<button className={`relative h-4 w-8 rounded-full transition-colors ${showZoomCompare
					? 'bg-primary'
					: 'bg-muted'}`} onClick={() => (showZoomCompare = !showZoomCompare)} aria-label="切换放大对比面板">
				<span className={`absolute top-0.5 left-0.5 h-3 w-3 rounded-full bg-white transition-transform ${showZoomCompare
						? 'translate-x-4'
						: ''}`}></span>
			</button>
		</div>
	</Fragment>) : null}

	{/*  处理状态提示  */}
	{pageStatus === 'processing' ? (<Fragment>
		<div className="flex items-center justify-center gap-2 py-2 text-blue-500">
			<Loader2 className="h-4 w-4 animate-spin"></Loader2>
			<span>正在超分处理...</span>
		</div>
	</Fragment>) : (<Fragment>{!upscaleStore.enabled ? (<Fragment>
		<p className="text-muted-foreground py-2 text-center">超分功能未启用</p>
	</Fragment>) : null}</Fragment>)}

	{/*  服务统计  */}
	{upscaleStore.enabled ? (<Fragment>
		<div className="border-border/50 text-muted-foreground space-y-1 border-t pt-2 text-[10px]">
			<div className="flex justify-between">
				<span>队列</span>
				<span>{upscaleStore.stats.pendingTasks} 等待 / {upscaleStore.stats.processingTasks} 处理中</span>
			</div>
			<div className="flex justify-between">
				<span>统计</span>
				<span className="space-x-2">
					<span className="text-green-500">{upscaleStore.stats.completedCount} 完成</span>
					<span className="text-yellow-500">{upscaleStore.stats.skippedCount} 跳过</span>
					{upscaleStore.stats.failedCount > 0 ? (<Fragment>
						<span className="text-red-500">{upscaleStore.stats.failedCount} 失败</span>
					</Fragment>) : null}
				</span>
			</div>
		</div>
	</Fragment>) : null}
</div>

{/*  可调整大小的浮窗对比  */}
{showZoomCompare && hasUpscaled && originalUrl && upscaledUrl ? (<Fragment>
	<div className="bg-background/95 border-border fixed z-50 overflow-hidden rounded-lg border shadow-2xl backdrop-blur-sm" style={`right: 16px; top: 50%; transform: translateY(-50%); width: ${floatWindow.width}px; height: ${floatWindow.height}px;`}>
		{/*  调整大小手柄  */}
		{/*  四边  */}
		<button type="button" className="hover:bg-primary/30 absolute top-0 right-2 left-2 h-1 cursor-n-resize" aria-label="向上调整大小" onMouseDown={(e) => startResize(e, 'n')}></button>
		<button type="button" className="hover:bg-primary/30 absolute right-2 bottom-0 left-2 h-1 cursor-s-resize" aria-label="向下调整大小" onMouseDown={(e) => startResize(e, 's')}></button>
		<button type="button" className="hover:bg-primary/30 absolute top-2 bottom-2 left-0 w-1 cursor-w-resize" aria-label="向左调整大小" onMouseDown={(e) => startResize(e, 'w')}></button>
		<button type="button" className="hover:bg-primary/30 absolute top-2 right-0 bottom-2 w-1 cursor-e-resize" aria-label="向右调整大小" onMouseDown={(e) => startResize(e, 'e')}></button>
		{/*  四角  */}
		<button type="button" className="hover:bg-primary/30 absolute top-0 left-0 h-3 w-3 cursor-nw-resize" aria-label="左上角调整大小" onMouseDown={(e) => startResize(e, 'nw')}></button>
		<button type="button" className="hover:bg-primary/30 absolute top-0 right-0 h-3 w-3 cursor-ne-resize" aria-label="右上角调整大小" onMouseDown={(e) => startResize(e, 'ne')}></button>
		<button type="button" className="hover:bg-primary/30 absolute bottom-0 left-0 h-3 w-3 cursor-sw-resize" aria-label="左下角调整大小" onMouseDown={(e) => startResize(e, 'sw')}></button>
		<button type="button" className="hover:bg-primary/30 absolute right-0 bottom-0 h-3 w-3 cursor-se-resize" aria-label="右下角调整大小" onMouseDown={(e) => startResize(e, 'se')}></button>

		{/*  标题栏  */}
		<div className="border-border/50 bg-muted/30 flex items-center justify-between border-b px-3 py-2">
			<span className="flex items-center gap-1.5 text-xs font-medium">
				{useUpscaled ? (<Fragment>
					<span className="text-green-500">🔍 超分图</span>
				</Fragment>) : (<Fragment>
					<span>📷 原图</span>
				</Fragment>)}
			</span>
			<button className="hover:bg-muted flex h-5 w-5 items-center justify-center rounded" onClick={() => (showZoomCompare = false)} aria-label="关闭对比浮窗">
				<X className="h-3.5 w-3.5"></X>
			</button>
		</div>

		{/*  可点击切换的图片  */}
		<button className="bg-muted/20 hover:bg-muted/40 flex h-[calc(100%-60px)] w-full cursor-pointer items-center justify-center transition-colors" onClick={() => (useUpscaled = !useUpscaled)} aria-label="点击切换原图/超分图">
			<img src={useUpscaled ? upscaledUrl : originalUrl} alt={useUpscaled ? '超分图' : '原图'} className="max-h-full max-w-full object-contain" />
		</button>

		{/*  底部信息  */}
		<div className="bg-background/80 border-border/50 absolute right-0 bottom-0 left-0 flex items-center justify-between border-t px-3 py-1.5 text-[10px]">
			<span className="text-muted-foreground">
				{useUpscaled && upscaledDimensions
					? `${upscaledDimensions.width}×${upscaledDimensions.height}`
					: originalDimensions
						? `${originalDimensions.width}×${originalDimensions.height}`
						: ''}
			</span>
			<span className="text-muted-foreground">点击切换 | 拖拽边缘调整</span>
		</div>
	</div>
</Fragment>) : null}</Fragment>
  )
}
