/**
 * @migrated-from src/lib/cards/upscale/UpscaleControlCard.svelte
 * @source-hash sha256:714c9bb823a2c30d7aa244e31df8d29a818e84cbff24f5ce4ede885e127ec76c
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Switch } from '$lib/components/ui/switch';
import { Label } from '$lib/components/ui/label';
import {
		autoUpscaleEnabled,
		showPanelPreview,
		saveSettings
	} from '$lib/stores/upscale/upscalePanelStore.js';
import { upscaleStore } from '$lib/stackview/stores/upscaleStore.js';
import { showInfoToast } from '$lib/utils/toast';

export function UpscaleControlCard() {
  function handleAutoUpscaleChange(checked: boolean) {
      autoUpscaleEnabled.value = checked;
      saveSettings();
      // 同步到后端
      upscaleStore.setEnabled(checked);
      showInfoToast(checked ? '自动超分已开启' : '自动超分已关闭');
    }

  function handlePreviewChange(checked: boolean) {
      showPanelPreview.value = checked;
      saveSettings();
      showInfoToast(checked ? '侧边预览已开启' : '侧边预览已关闭');
    }
  return (
    <Fragment>

<div className="space-y-3 text-xs">
	{/*  自动超分开关（全局主开关）  */}
	<div className="flex items-center justify-between">
		<Label className="text-xs font-medium">自动超分</Label>
		<Switch checked={autoUpscaleEnabled.value} onCheckedChange={handleAutoUpscaleChange} className="scale-90"></Switch>
	</div>
	<p className="text-muted-foreground -mt-1 text-[10px]">切换图片时自动执行超分（全局主开关）</p>

	{/*  侧边预览开关  */}
</div></Fragment>
  )
}
