/**
 * @migrated-from src/lib/cards/settings/ImageSettingsCard.svelte
 * @source-hash sha256:32cf697b364ddd8a953b6e1509005a9e11172e64b78e974dc88e4d7b7d92684d
 * @features settings-import-export-backup
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import ImageSettingsPanel from '$lib/components/panels/ImageSettingsPanel.js';
import ViewerSettingsPanel from '$lib/components/dialogs/ViewerSettingsPanel.js';

export function ImageSettingsCard() {
  return (
    <Fragment>

<div className="settings-card-wrapper space-y-4">
	<ImageSettingsPanel></ImageSettingsPanel>
	<ViewerSettingsPanel></ViewerSettingsPanel>
</div>

</Fragment>
  )
}
