/**
 * @migrated-from src/lib/components/panels/file/components/FileItemListView.svelte
 * @source-hash sha256:3093eb47ad2aeaf0db4ca9f3423c88e71412ad5d778b561402b05d0f9e2e9171
 * @features file-browser-navigation
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported attribute BindDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import {
		Folder,
		File,
		Image,
		FileArchive,
		Check,
		Star,
		FolderOpen,
		Package,
		Video,
		Eye,
		BookOpen,
		PanelRight,
		X,
		HardDrive,
		Clock,
		Play,
		Images
	} from 'lucide-react';
import type { FsItem } from '$lib/types';
import * as Tooltip from '$lib/components/ui/tooltip';
import FolderRatingBadge from './FolderRatingBadge.js';
import TagChip from '$lib/components/ui/TagChip.js';
import MetadataBadge from '$lib/components/ui/MetadataBadge.js';
import type { EMMTranslationDict } from '$lib/api/emm';
import {
		hoverPreviewEnabled,
		hoverPreviewDelayMs
	} from '$lib/stores/hoverPreviewSettings.js';
import FileTypeIcon from '$lib/components/ui/FileTypeIcon.js';
import FolderPreviewGrid from './FolderPreviewGrid.js';
import {
		formatDuration,
		formatRelativeTime,
		formatBytes,
		formatSize,
		getFolderSizeDisplay
	} from '$lib/utils/formatters';
interface Props {
		item: FsItem;
		thumbnail?: string;
		folderThumbnails?: string[];
		folderPreviewGridEnabled?: boolean;
		folderPreviewLoading?: boolean;
		folderPreviewExpectedCount?: number;
		/** 视图模式: list=列表, content=内容, banner=横幅, thumbnail=缩略图 */
		viewMode?: 'list' | 'content' | 'banner' | 'thumbnail';
		isSelected?: boolean;
		isChecked?: boolean;
		isCheckMode?: boolean;
		isDeleteMode?: boolean;
		showReadMark?: boolean;
		showSizeAndModified?: boolean;
		currentPage?: number;
		totalPages?: number;
		videoPosition?: number;
		videoDuration?: number;
		timestamp?: number;
		thumbnailSize?: number;
		// 文件夹总大小（异步加载）
		folderTotalSize?: number | null;
		folderSizeLoading?: boolean;
		// 计算状态
		isBookmarked: boolean;
		isArchive: boolean;
		isReadCompleted: boolean;
		emmMetadata: {
			translatedTitle?: string;
			tags?: Record<string, string[]>;
			rating?: number;
		} | null;
		// 穿透模式：内部压缩包信息列表（支持多个）
		penetrateInfoList?: Array<{
			originalName: string;
			translatedTitle?: string | null;
			isAiTranslated: boolean;
		}>;
		// 穿透模式：纯媒体文件夹（只包含图片/视频/文本，点击直接作为 book 打开）
		isPureMediaFolder?: boolean;
		folderAverageRating: number | null;
		folderManualRating: number | null;
		displayTags: () => {
			tag: string;
			display: string;
			isCollect: boolean;
			color?: string;
			isMixedVariant?: boolean;
			isManual?: boolean;
		}[];
		getEffectiveRating: () => number | null;
		// 预览相关
		showPreview: boolean;
		previewLoading: boolean;
		previewItems: FsItem[];
		previewIconElement?: HTMLElement | null;
		// 事件
		onClick?: () => void;
		onDoubleClick?: () => void;
		onContextMenu?: (e: MouseEvent) => void;
		onToggleSelection?: () => void;
		onDelete?: () => void;
		onOpenAsBook?: () => void;
		onOpenInNewTab?: () => void;
		onSetRating: (rating: number | null) => void;
		onPreviewEnter: () => void;
		onPreviewLeave: () => void;
	}

export function FileItemListView(props: Props) {
  const {
		item,
		thumbnail,
		folderThumbnails = [],
		folderPreviewGridEnabled = false,
		folderPreviewLoading = false,
		folderPreviewExpectedCount = 0,
		viewMode = 'list',
		isSelected = false,
		isChecked = false,
		isCheckMode = false,
		isDeleteMode = false,
		showReadMark = false,
		showSizeAndModified = false,
		currentPage,
		totalPages,
		videoPosition,
		videoDuration,
		timestamp,
		thumbnailSize = 48,
		folderTotalSize = null,
		folderSizeLoading = false,
		isBookmarked,
		isArchive,
		isReadCompleted,
		emmMetadata,
		penetrateInfoList = [],
		isPureMediaFolder = false,
		folderAverageRating,
		folderManualRating,
		displayTags,
		getEffectiveRating,
		showPreview,
		previewLoading,
		previewItems,
		previewIconElement = $bindable(),
		onClick,
		onDoubleClick,
		onContextMenu,
		onToggleSelection,
		onDelete,
		onOpenAsBook,
		onOpenInNewTab,
		onSetRating,
		onPreviewEnter,
		onPreviewLeave
	} = props
  const isGridLayout = $derived(viewMode === 'banner' || viewMode === 'thumbnail');

  const showFolderPreviewGrid = $derived(
      item.isDir && folderPreviewGridEnabled && (folderPreviewLoading || folderThumbnails.length > 0)
    );

  const containerClass = $derived(
      isGridLayout
        ? `border-border group/item relative flex flex-col cursor-pointer rounded-md border overflow-hidden transition-colors ${isSelected ? 'bg-accent text-accent-foreground border-accent' : 'hover:bg-accent/40'}`
        : `border-border group/item relative flex min-h-16 cursor-pointer items-center gap-3 rounded-md border p-2 transition-colors ${isSelected ? 'bg-accent text-accent-foreground border-accent' : 'hover:bg-accent/40'}`
    );
  return (
    <Fragment>

<div className={containerClass} onClick={(e) => {
		e.stopPropagation();
		onClick?.();
	}} onDoubleClick={(e) => {
		e.stopPropagation();
		onDoubleClick?.();
	}} onContextmenu={onContextMenu} role="button" tabIndex="0" onKeyDown={(e) => {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			onClick?.();
		}
	}}>
	{/*  勾选框（勾选模式）- 正方形图标，扩大透明点击区域  */}
	{isCheckMode ? (<Fragment>
		<button className="group/checkbox focus-visible:ring-ring flex shrink-0 items-center self-stretch px-2 transition-all focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none" onClick={(e) => {
				e.stopPropagation();
				onToggleSelection?.();
			}} aria-label={isChecked ? '取消选择' : '选择'}>
			<div className={`flex h-5 w-5 items-center justify-center rounded-md border-2 transition-all duration-200 ${isChecked
					? 'border-primary bg-primary text-primary-foreground shadow-md'
					: 'border-input bg-background hover:border-primary hover:bg-accent'}`}>
				{isChecked ? (<Fragment>
					<Check className="animate-in zoom-in-50 h-3.5 w-3.5 duration-200"></Check>
				</Fragment>) : null}
			</div>
		</button>
	</Fragment>) : null}

	{/*  删除按钮（删除模式）- 正方形图标，扩大透明点击区域  */}
	{isDeleteMode ? (<Fragment>
		<button className="group/delete focus-visible:ring-destructive flex shrink-0 items-center self-stretch px-2 transition-all focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none" onClick={(e) => {
				e.stopPropagation();
				onDelete?.();
			}} title="删除" aria-label="删除">
			<div className="bg-destructive text-destructive-foreground hover:bg-destructive/90 flex h-5 w-5 items-center justify-center rounded-md shadow-md transition-all duration-200 hover:shadow-lg">
				<X className="h-3.5 w-3.5"></X>
			</div>
		</button>
	</Fragment>) : null}

	{/*  缩略图或图标（带悬停预览）  */}
	<Tooltip.Root delayDuration={$hoverPreviewDelayMs}>
		<Tooltip.Trigger>
			<div className="relative flex shrink-0 items-center justify-center self-stretch overflow-hidden rounded" style={`width: ${thumbnailSize}px; min-width: ${thumbnailSize}px;`}>
				{showFolderPreviewGrid ? (<Fragment>
					<FolderPreviewGrid thumbnails={folderThumbnails} folderName={item.name} loading={folderPreviewLoading} expectedCount={folderPreviewExpectedCount}></FolderPreviewGrid>
				</Fragment>) : (<Fragment>{thumbnail ? (<Fragment>
					<img src={thumbnail} alt={item.name} loading="lazy" decoding="async" className="h-full w-full object-cover transition-transform group-hover/item:scale-105" />
				</Fragment>) : (<Fragment>
					{/*  骨架屏占位：缩略图加载中显示动画  */}
					<div className="bg-accent absolute inset-0 animate-pulse rounded"></div>
					{/*  图标叠加在骨架屏上  */}
					{item.isDir ? (<Fragment>
						<Folder className="text-primary/50 group-hover/item:text-primary relative h-8 w-8 transition-colors"></Folder>
					</Fragment>) : (<Fragment>{isArchive ? (<Fragment>
						<FileArchive className="text-primary/50 group-hover/item:text-primary relative h-8 w-8 transition-colors"></FileArchive>
					</Fragment>) : (<Fragment>{item.isImage ? (<Fragment>
						<Image className="text-primary/50 group-hover/item:text-primary relative h-8 w-8 transition-colors"></Image>
					</Fragment>) : (<Fragment>
						<File className="text-muted-foreground/50 group-hover/item:text-muted-foreground relative h-8 w-8 transition-colors"></File>
					</Fragment>)}</Fragment>)}</Fragment>)}
				</Fragment>)}</Fragment>)}

				{/*  阅读标记  */}
				{showReadMark ? (<Fragment>
					{isReadCompleted ? (<Fragment>
						<div className="bg-primary absolute top-0 right-0 rounded-full p-0.5">
							<Check className="h-3 w-3 text-white"></Check>
						</div>
					</Fragment>) : (<Fragment>
						<div className="border-primary bg-background/80 absolute top-0 right-0 rounded-full border border-dashed p-0.5">
							<Check className="text-primary h-3 w-3"></Check>
						</div>
					</Fragment>)}
				</Fragment>) : null}

				{/*  收藏标记  */}
				{isBookmarked ? (<Fragment>
					<div className="bg-primary absolute right-0 bottom-0 rounded-full p-0.5">
						<Star className="h-3 w-3 fill-white text-white"></Star>
					</div>
				</Fragment>) : null}
			</div>
		</Tooltip.Trigger>
		{/*  悬停预览大图（仅在启用时显示）  */}
		{thumbnail && $hoverPreviewEnabled ? (<Fragment>
			<Tooltip.Content side="right" className="border-0 bg-transparent p-0 shadow-xl">
				<img src={thumbnail} alt={item.name} className="bg-background max-h-100 max-w-75 rounded-lg border object-contain shadow-lg" />
			</Tooltip.Content>
		</Fragment>) : null}
	</Tooltip.Root>

	{/*  信息  */}
	<div className="min-w-0 flex-1">
		{/*  原文件名  */}
		<div className="flex flex-wrap items-center gap-2 font-medium wrap-break-word" title={item.name}>
			<span>{item.name}</span>
			{/*  文件夹统计信息  */}
			{item.isDir ? (<Fragment>
				<div className="flex items-center gap-1.5 text-xs">
					{item.imageCount !== undefined && item.imageCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-1 rounded-md px-2 py-0.5">
									<Images className="h-3 w-3"></Images>
									<span className="font-medium">{item.imageCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>图片数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{item.folderCount !== undefined && item.folderCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-1 rounded-md px-2 py-0.5">
									<FolderOpen className="h-3 w-3"></FolderOpen>
									<span className="font-medium">{item.folderCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>子文件夹数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{item.archiveCount !== undefined && item.archiveCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-1 rounded-md px-2 py-0.5">
									<Package className="h-3 w-3"></Package>
									<span className="font-medium">{item.archiveCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>压缩包数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{item.videoCount !== undefined && item.videoCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-1 rounded-md px-2 py-0.5">
									<Video className="h-3 w-3"></Video>
									<span className="font-medium">{item.videoCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>视频数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{/*  纯媒体文件夹标识（穿透模式下点击直接打开）  */}
					{isPureMediaFolder ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-primary/20 text-primary border-primary/30 inline-flex items-center gap-1 rounded-md border px-2 py-0.5">
									<Image className="h-3 w-3"></Image>
									<span className="text-xs font-medium">媒体</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>纯媒体文件夹，点击直接打开</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{getEffectiveRating() !== null || item.isDir ? (<Fragment>
						<FolderRatingBadge effectiveRating={getEffectiveRating()} manualRating={folderManualRating} averageRating={folderAverageRating} size="md" onSetRating={onSetRating}></FolderRatingBadge>
					</Fragment>) : null}
					{/*  预览图标  */}
					<Tooltip.Root>
						<Tooltip.Trigger>
							<button className="hover:bg-accent inline-flex items-center justify-center rounded-md p-1 transition-colors" onMouseEnter={onPreviewEnter} onMouseLeave={onPreviewLeave} onClick={(e) => e.stopPropagation()}>
								<Eye className="text-muted-foreground h-3.5 w-3.5"></Eye>
							</button>
						</Tooltip.Trigger>
						<Tooltip.Content><p>预览文件夹内容</p></Tooltip.Content>
					</Tooltip.Root>
					{/*  作为书籍打开  */}
					<Tooltip.Root>
						<Tooltip.Trigger>
							<button className="hover:bg-accent inline-flex items-center justify-center rounded-md p-1 transition-colors" onClick={(e) => {
									e.stopPropagation();
									onOpenAsBook?.();
								}}>
								<BookOpen className="text-muted-foreground h-3.5 w-3.5"></BookOpen>
							</button>
						</Tooltip.Trigger>
						<Tooltip.Content><p>作为书籍打开此文件夹</p></Tooltip.Content>
					</Tooltip.Root>
					{/*  在新标签页打开  */}
					<Tooltip.Root>
						<Tooltip.Trigger>
							<button className="hover:bg-accent inline-flex items-center justify-center rounded-md p-1 transition-colors" onClick={(e) => {
									e.stopPropagation();
									onOpenInNewTab?.();
								}} onContextmenu={(e) => {
									// 右键穿透：触发父元素的右键菜单，但阻止事件继续冒泡避免重复触发
									e.stopPropagation();
									onContextMenu?.(e);
								}}>
								<PanelRight className="text-muted-foreground h-3.5 w-3.5"></PanelRight>
							</button>
						</Tooltip.Trigger>
						<Tooltip.Content><p>在新标签页打开</p></Tooltip.Content>
					</Tooltip.Root>
				</div>
			</Fragment>) : null}
		</div>

		{/*  预览弹窗  */}
		{item.isDir && showPreview ? (<Fragment>
			<div className="border-border bg-popover/80 absolute top-full left-0 z-50 mt-1 w-64 rounded-md border p-2 shadow-lg backdrop-blur-md" role="tooltip" tabIndex="-1" onMouseEnter={onPreviewEnter} onMouseLeave={onPreviewLeave}>
				<div className="text-popover-foreground mb-2 text-xs font-medium">文件夹预览</div>
				{previewLoading ? (<Fragment>
					<div className="text-muted-foreground py-2 text-center text-xs">加载中...</div>
				</Fragment>) : (<Fragment>{previewItems.length === 0 ? (<Fragment>
					<div className="text-muted-foreground py-2 text-center text-xs">空文件夹</div>
				</Fragment>) : (<Fragment>
					<div className="max-h-64 space-y-1 overflow-y-auto">
						{previewItems.map((previewItem) => (<Fragment>
							<div className="hover:bg-accent flex items-center gap-2 rounded px-2 py-1 text-xs">
								{previewItem.isDir ? (<Fragment>
									<Folder className="h-3 w-3 shrink-0 text-blue-500"></Folder>
								</Fragment>) : (<Fragment>{previewItem.isImage ? (<Fragment>
									<Image className="h-3 w-3 shrink-0 text-green-500"></Image>
								</Fragment>) : (<Fragment>{previewItem.name.endsWith('.zip') || previewItem.name.endsWith('.cbz') || previewItem.name.endsWith('.rar') || previewItem.name.endsWith('.cbr') ? (<Fragment>
									<FileArchive className="h-3 w-3 shrink-0 text-purple-500"></FileArchive>
								</Fragment>) : (<Fragment>
									<File className="text-muted-foreground h-3 w-3 shrink-0"></File>
								</Fragment>)}</Fragment>)}</Fragment>)}
								<span className="text-foreground truncate">{previewItem.name}</span>
							</div>
						</Fragment>))}
						{item.size > 10 ? (<Fragment>
							<div className="text-muted-foreground border-border mt-1 border-t px-2 py-1 text-center text-xs">
								还有 {item.size - 10} 个项目...
							</div>
						</Fragment>) : null}
					</div>
				</Fragment>)}</Fragment>)}
			</div>
		</Fragment>) : null}

		{/*  翻译标题  */}
		{emmMetadata && emmMetadata.translatedTitle && emmMetadata.translatedTitle !== item.name ? (<Fragment>
			<div className="mt-1">
				<span className="border-primary/20 bg-primary/10 text-primary rounded border px-1.5 py-0.5 text-xs wrap-break-word" title={emmMetadata.translatedTitle}>
					{emmMetadata.translatedTitle}
				</span>
			</div>
		</Fragment>) : null}

		{/*  穿透模式：内部压缩包信息列表（允许换行显示完整）  */}
		{penetrateInfoList && penetrateInfoList.length > 0 ? (<Fragment>
			<div className="mt-1 space-y-1">
				{penetrateInfoList.map((info, idx) => (<Fragment>
					<div className={`space-y-0.5 ${idx > 0 ? 'border-muted border-t border-dashed pt-0.5' : ''}`}>
						<div className="flex items-start gap-1">
							<Package className="text-muted-foreground mt-0.5 h-3 w-3 shrink-0"></Package>
							<span className="text-muted-foreground text-xs leading-tight break-all">
								{info.originalName}
							</span>
						</div>
						{info.translatedTitle ? (<Fragment>
							<div className="text-primary pl-4 text-xs leading-tight break-all">
								{info.isAiTranslated ? '🤖 ' : ''}{info.translatedTitle}
							</div>
						</Fragment>) : null}
					</div>
				</Fragment>))}
			</div>
		</Fragment>) : null}

		<div className="mt-1 flex flex-wrap items-center gap-1.5">
			{/*  文件类型 icon  */}
			<FileTypeIcon name={item.targetPath ?? item.name} isDir={item.isDir} size="sm"></FileTypeIcon>
			{/*  视频进度信息（时:分:秒格式）  */}
			{videoPosition !== undefined && videoDuration !== undefined && videoDuration > 0 ? (<Fragment>
				<MetadataBadge text={`${formatDuration(videoPosition)}/${formatDuration(videoDuration)}`} icon={Play} tooltip="视频进度" size="sm" variant="primary"></MetadataBadge>
			</Fragment>) : (<Fragment>{currentPage !== undefined && totalPages !== undefined && totalPages > 0 ? (<Fragment>
				{/*  非视频进度信息  */}
				<MetadataBadge text={`${currentPage}/${totalPages}`} icon={BookOpen} tooltip="阅读进度" size="sm" variant="primary"></MetadataBadge>
			</Fragment>) : null}</Fragment>)}
			{showSizeAndModified ? (<Fragment>
				<MetadataBadge text={item.isDir
						? getFolderSizeDisplay(folderSizeLoading, folderTotalSize, item.size)
						: formatSize(item.size || 0, false)} icon={HardDrive} tooltip="文件大小" size="sm" variant="secondary"></MetadataBadge>
				{timestamp ? (<Fragment>
					<MetadataBadge text={formatRelativeTime(timestamp)} icon={Clock} tooltip="修改时间" size="sm" variant="secondary"></MetadataBadge>
				</Fragment>) : null}
			</Fragment>) : (<Fragment>
				{timestamp ? (<Fragment>
					<MetadataBadge text={formatRelativeTime(timestamp)} icon={Clock} tooltip="修改时间" size="sm" variant="secondary"></MetadataBadge>
				</Fragment>) : null}
				{!currentPage && !timestamp ? (<Fragment>
					<MetadataBadge text={item.isDir
							? getFolderSizeDisplay(folderSizeLoading, folderTotalSize, item.size)
							: formatSize(item.size || 0, false)} icon={HardDrive} tooltip="文件大小" size="sm" variant="secondary"></MetadataBadge>
				</Fragment>) : null}
			</Fragment>)}
			{/*  评分放在大小和时间后面  */}
			{emmMetadata?.rating !== undefined && emmMetadata.rating > 0 ? (<Fragment>
				<MetadataBadge text={emmMetadata.rating.toFixed(1)} icon={Star} tooltip={`评分: ${emmMetadata.rating.toFixed(2)}`} size="sm" variant="accent"></MetadataBadge>
			</Fragment>) : null}
		</div>

		{displayTags().length > 0 ? (<Fragment>
			<div className="mt-1 flex flex-wrap items-center gap-1">
				{displayTags().map((tagInfo) => (<Fragment>
					<TagChip tag={tagInfo.tag} display={tagInfo.display} color={tagInfo.color} isCollect={tagInfo.isCollect} isMixedVariant={tagInfo.isMixedVariant} isManual={tagInfo.isManual} size="md"></TagChip>
				</Fragment>))}
			</div>
		</Fragment>) : null}
	</div>
</div></Fragment>
  )
}
