/**
 * @migrated-from src/lib/components/panels/file/components/FileItemGridView.svelte
 * @source-hash sha256:c43539dd546fbe732390dd65b3597b40b5606d236fa323a2c7872abeb6342c4e
 * @features file-browser-navigation
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import {
		Folder,
		File,
		Image,
		FileArchive,
		Check,
		Star,
		FolderOpen,
		Package,
		Video,
		BookOpen,
		HardDrive,
		Clock,
		Play,
		Images
	} from 'lucide-react';
import type { FsItem } from '$lib/types';
import * as Tooltip from '$lib/components/ui/tooltip';
import FolderRatingBadge from './FolderRatingBadge.js';
import TagChip from '$lib/components/ui/TagChip.js';
import MetadataBadge from '$lib/components/ui/MetadataBadge.js';
import FileTypeIcon from '$lib/components/ui/FileTypeIcon.js';
import FolderPreviewGrid from './FolderPreviewGrid.js';
import {
		formatDuration,
		formatRelativeTime,
		formatBytes,
		formatSize,
		getFolderSizeDisplay
	} from '$lib/utils/formatters';
interface Props {
		item: FsItem;
		thumbnail?: string;
		folderThumbnails?: string[];
		folderPreviewGridEnabled?: boolean;
		folderPreviewLoading?: boolean;
		folderPreviewExpectedCount?: number;
		isSelected?: boolean;
		showReadMark?: boolean;
		showSizeAndModified?: boolean;
		currentPage?: number;
		totalPages?: number;
		videoPosition?: number;
		videoDuration?: number;
		timestamp?: number;
		// 文件夹总大小（异步加载）
		folderTotalSize?: number | null;
		folderSizeLoading?: boolean;
		// 计算状态
		isBookmarked: boolean;
		isArchive: boolean;
		isReadCompleted: boolean;
		emmMetadata: {
			translatedTitle?: string;
			tags?: Record<string, string[]>;
			rating?: number;
		} | null;
		// 穿透模式：纯媒体文件夹（只包含图片/视频/文本，点击直接作为 book 打开）
		isPureMediaFolder?: boolean;
		folderAverageRating: number | null;
		folderManualRating: number | null;
		displayTags: () => {
			tag: string;
			display: string;
			isCollect: boolean;
			color?: string;
			isMixedVariant?: boolean;
			isManual?: boolean;
		}[];
		getEffectiveRating: () => number | null;
		// 事件
		onClick?: () => void;
		onDoubleClick?: () => void;
		onContextMenu?: (e: MouseEvent) => void;
		onOpenAsBook?: () => void;
		onSetRating: (rating: number | null) => void;
	}
import { fileBrowserStore } from '$lib/stores/fileBrowser.js';
import { globalImageAspectRatios } from './scrollCache.js';

export function FileItemGridView(props: Props) {
  const {
		item,
		thumbnail,
		folderThumbnails = [],
		folderPreviewGridEnabled = false,
		folderPreviewLoading = false,
		folderPreviewExpectedCount = 0,
		isSelected = false,
		showReadMark = false,
		showSizeAndModified = false,
		currentPage,
		totalPages,
		videoPosition,
		videoDuration,
		timestamp,
		folderTotalSize = null,
		folderSizeLoading = false,
		isBookmarked,
		isArchive,
		isReadCompleted,
		emmMetadata,
		isPureMediaFolder = false,
		folderAverageRating,
		folderManualRating,
		displayTags,
		getEffectiveRating,
		onClick,
		onDoubleClick,
		onContextMenu,
		onOpenAsBook,
		onSetRating
	} = props
  const isCompact = $derived($fileBrowserStore.compactGridMode);

  const showFolderPreviewGrid = $derived(
      item.isDir && folderPreviewGridEnabled && (folderPreviewLoading || folderThumbnails.length > 0)
    );

  function handleImageLoad(e: Event) {
      const img = e.target as HTMLImageElement;
      if (img.naturalWidth && img.naturalHeight) {
        const aspect = img.naturalWidth / img.naturalHeight;
        // 限制宽高比在合理范围内，避免极度扁平或高瘦的卡片导致布局畸形
        const clampedAspect = Math.max(0.5, Math.min(2.5, aspect));
        globalImageAspectRatios.set(item.path, clampedAspect);
      }
    }
  return (
    <Fragment>

<div className={`border-border group/card relative flex cursor-pointer flex-col overflow-hidden rounded border transition-all hover:shadow-md ${isSelected
		? 'border-primary ring-2'
		: ''}`} onClick={(e) => {
		e.stopPropagation();
		onClick?.();
	}} onDoubleClick={(e) => {
		e.stopPropagation();
		onDoubleClick?.();
	}} onContextmenu={onContextMenu} role="button" tabIndex="0" onKeyDown={(e) => {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			onClick?.();
		}
	}}>
	{/*  缩略图区域  */}
	<div className={`bg-secondary relative w-full overflow-hidden ${isCompact ? 'h-full flex-1' : 'h-[148px]'}`}>
		{showFolderPreviewGrid ? (<Fragment>
			{/*  文件夹多图自适应网格预览模式  */}
			<FolderPreviewGrid thumbnails={folderThumbnails} folderName={item.name} loading={folderPreviewLoading} expectedCount={folderPreviewExpectedCount}></FolderPreviewGrid>
		</Fragment>) : (<Fragment>{thumbnail ? (<Fragment>
			<img src={thumbnail} alt={item.name} loading="lazy" decoding="async" className="h-full w-full object-cover transition-transform group-hover/card:scale-105" onLoad={handleImageLoad} />
		</Fragment>) : (<Fragment>
			{/*  骨架屏占位：缩略图加载中显示动画  */}
			<div className="bg-accent absolute inset-0 animate-pulse"></div>
			{/*  图标叠加在骨架屏上  */}
			{item.isDir ? (<Fragment>
				<div className="relative flex h-full w-full items-center justify-center">
					<Folder className="text-primary/50 h-16 w-16"></Folder>
				</div>
			</Fragment>) : (<Fragment>{isArchive ? (<Fragment>
				<div className="relative flex h-full w-full items-center justify-center">
					<FileArchive className="text-primary/50 h-16 w-16"></FileArchive>
				</div>
			</Fragment>) : (<Fragment>{item.isImage ? (<Fragment>
				<div className="relative flex h-full w-full items-center justify-center">
					<Image className="text-primary/50 h-16 w-16"></Image>
				</div>
			</Fragment>) : (<Fragment>
				<div className="relative flex h-full w-full items-center justify-center">
					<File className="text-muted-foreground/50 h-16 w-16"></File>
				</div>
			</Fragment>)}</Fragment>)}</Fragment>)}
		</Fragment>)}</Fragment>)}

		{/*  阅读标记  */}
		{showReadMark ? (<Fragment>
			{isReadCompleted ? (<Fragment>
				<div className="bg-primary absolute top-2 right-2 rounded-full p-1">
					<Check className="h-4 w-4 text-white"></Check>
				</div>
			</Fragment>) : (<Fragment>
				<div className="border-primary bg-background/80 absolute top-2 right-2 rounded-full border border-dashed p-1">
					<Check className="text-primary h-4 w-4"></Check>
				</div>
			</Fragment>)}
		</Fragment>) : null}

		{/*  收藏标记  */}
		{isBookmarked ? (<Fragment>
			<div className="bg-primary absolute top-2 left-2 rounded-full p-1">
				<Star className="h-4 w-4 fill-white text-white"></Star>
			</div>
		</Fragment>) : null}

		{/*  进度条  */}
		{currentPage !== undefined && totalPages !== undefined && totalPages > 0 ? (<Fragment>
			<div className="absolute right-0 bottom-0 left-0 h-1 bg-black/20">
				<div className="bg-primary h-full transition-all" style={`width: ${(currentPage / totalPages) * 100}%`}></div>
			</div>
		</Fragment>) : null}

		{/*  紧凑模式信息叠加层  */}
		{isCompact ? (<Fragment>
			<div className="pointer-events-none absolute right-0 bottom-0 left-0 flex flex-col gap-1 bg-gradient-to-t from-black/95 via-black/70 to-transparent p-2 text-white">
				{/*  文件/文件夹名  */}
				<div className="line-clamp-2 text-[11px] leading-tight font-semibold break-all text-white/95 drop-shadow-md" title={item.name}>
					{emmMetadata?.translatedTitle ? (<Fragment>
						<span className="text-primary-foreground font-semibold">{emmMetadata.translatedTitle}</span>
					</Fragment>) : (<Fragment>
						<span>{item.name}</span>
					</Fragment>)}
				</div>

				<div className="flex flex-wrap items-center gap-1">
					{/*  文件类型 icon  */}
					<FileTypeIcon name={item.targetPath ?? item.name} isDir={item.isDir} size="xs"></FileTypeIcon>

					{/*  视频/阅读进度  */}
					{videoPosition !== undefined && videoDuration !== undefined && videoDuration > 0 ? (<Fragment>
						<span className="bg-primary/90 rounded px-1 text-[9px] font-medium text-white">
							{formatDuration(videoPosition)}/{formatDuration(videoDuration)}
						</span>
					</Fragment>) : (<Fragment>{currentPage !== undefined && totalPages !== undefined && totalPages > 0 ? (<Fragment>
						<span className="bg-primary/90 rounded px-1 text-[9px] font-medium text-white">
							{currentPage}/{totalPages}
						</span>
					</Fragment>) : null}</Fragment>)}

					{/*  文件夹统计  */}
					{item.isDir ? (<Fragment>
						{item.imageCount !== undefined && item.imageCount > 0 ? (<Fragment>
							<span className="inline-flex items-center gap-0.5 rounded bg-black/60 px-1 text-[9px] font-medium text-white">
								<Images className="h-2.5 w-2.5"></Images>
								{item.imageCount}
							</span>
						</Fragment>) : null}
						{item.folderCount !== undefined && item.folderCount > 0 ? (<Fragment>
							<span className="inline-flex items-center gap-0.5 rounded bg-black/60 px-1 text-[9px] font-medium text-white">
								<FolderOpen className="h-2.5 w-2.5"></FolderOpen>
								{item.folderCount}
							</span>
						</Fragment>) : null}
						{item.archiveCount !== undefined && item.archiveCount > 0 ? (<Fragment>
							<span className="inline-flex items-center gap-0.5 rounded bg-black/60 px-1 text-[9px] font-medium text-white">
								<Package className="h-2.5 w-2.5"></Package>
								{item.archiveCount}
							</span>
						</Fragment>) : null}
					</Fragment>) : null}

					{/*  文件大小  */}
					<span className="rounded bg-black/45 px-1 text-[9px] font-medium text-white/90">
						{item.isDir
							? getFolderSizeDisplay(folderSizeLoading, folderTotalSize, item.size)
							: formatSize(item.size || 0, false)}
					</span>

					{/*  评分  */}
					{getEffectiveRating() !== null ? (<Fragment>
						<span className="inline-flex items-center gap-0.5 rounded bg-yellow-500/90 px-1 text-[9px] font-bold text-white">
							<Star className="h-2 w-2 fill-white"></Star>
							{getEffectiveRating()?.toFixed(1)}
						</span>
					</Fragment>) : null}
				</div>
			</div>
		</Fragment>) : null}
	</div>

	{/*  信息区域  */}
	{!isCompact ? (<Fragment>
		<div className="bg-background p-2">
			{/*  原文件名  */}
			<div className="text-sm font-medium wrap-break-word" title={item.name}>
				<span className="truncate">{item.name}</span>
			</div>

			{/*  文件夹统计信息  */}
			{item.isDir ? (<Fragment>
				<div className="mt-1 flex flex-wrap items-center gap-1">
					{item.imageCount !== undefined && item.imageCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-0.5 rounded-md px-1.5 py-0.5 text-[10px]">
									<Images className="h-2.5 w-2.5"></Images>
									<span className="font-medium">{item.imageCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>图片数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{item.folderCount !== undefined && item.folderCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-0.5 rounded-md px-1.5 py-0.5 text-[10px]">
									<FolderOpen className="h-2.5 w-2.5"></FolderOpen>
									<span className="font-medium">{item.folderCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>子文件夹数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{item.archiveCount !== undefined && item.archiveCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-0.5 rounded-md px-1.5 py-0.5 text-[10px]">
									<Package className="h-2.5 w-2.5"></Package>
									<span className="font-medium">{item.archiveCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>压缩包数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{item.videoCount !== undefined && item.videoCount > 0 ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-secondary text-secondary-foreground inline-flex items-center gap-0.5 rounded-md px-1.5 py-0.5 text-[10px]">
									<Video className="h-2.5 w-2.5"></Video>
									<span className="font-medium">{item.videoCount}</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>视频数量</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{/*  纯媒体文件夹标识（穿透模式下点击直接打开）  */}
					{isPureMediaFolder ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<span className="bg-primary/20 text-primary border-primary/30 inline-flex items-center gap-0.5 rounded-md border px-1.5 py-0.5 text-[10px]">
									<Image className="h-2.5 w-2.5"></Image>
									<span className="font-medium">媒体</span>
								</span>
							</Tooltip.Trigger>
							<Tooltip.Content><p>纯媒体文件夹，点击直接打开</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
					{getEffectiveRating() !== null || item.isDir ? (<Fragment>
						<FolderRatingBadge effectiveRating={getEffectiveRating()} manualRating={folderManualRating} averageRating={folderAverageRating} size="sm" onSetRating={onSetRating}></FolderRatingBadge>
					</Fragment>) : null}
					{onOpenAsBook ? (<Fragment>
						<Tooltip.Root>
							<Tooltip.Trigger>
								<button className="hover:bg-accent inline-flex items-center justify-center rounded-md p-1 text-[10px] transition-colors" onClick={(e) => {
										e.stopPropagation();
										onOpenAsBook?.();
									}}>
									<BookOpen className="text-muted-foreground h-3 w-3"></BookOpen>
								</button>
							</Tooltip.Trigger>
							<Tooltip.Content><p>作为书籍打开此文件夹</p></Tooltip.Content>
						</Tooltip.Root>
					</Fragment>) : null}
				</div>
			</Fragment>) : null}

			{/*  翻译标题和评分  */}
			{emmMetadata && (emmMetadata.translatedTitle || emmMetadata.rating !== undefined) ? (<Fragment>
				<div className="mt-1 flex flex-wrap items-center gap-1">
					{emmMetadata.translatedTitle && emmMetadata.translatedTitle !== item.name ? (<Fragment>
						<span className="border-primary/20 bg-primary/10 text-primary rounded border px-1 py-0.5 text-[10px] wrap-break-word" title={emmMetadata.translatedTitle}>
							{emmMetadata.translatedTitle}
						</span>
					</Fragment>) : null}
					{emmMetadata.rating !== undefined && emmMetadata.rating > 0 ? (<Fragment>
						<MetadataBadge text={emmMetadata.rating.toFixed(1)} icon={Star} tooltip={`评分: ${emmMetadata.rating.toFixed(2)}`} size="xs" variant="accent"></MetadataBadge>
					</Fragment>) : null}
				</div>
			</Fragment>) : null}

			<div className="mt-1 flex flex-wrap items-center gap-1">
				{/*  文件类型 icon  */}
				<FileTypeIcon name={item.targetPath ?? item.name} isDir={item.isDir} size="xs"></FileTypeIcon>
				{/*  视频进度信息（时:分:秒格式）  */}
				{videoPosition !== undefined && videoDuration !== undefined && videoDuration > 0 ? (<Fragment>
					<MetadataBadge text={`${formatDuration(videoPosition)}/${formatDuration(videoDuration)}`} icon={Play} tooltip="视频进度" size="xs" variant="primary"></MetadataBadge>
				</Fragment>) : (<Fragment>{currentPage !== undefined && totalPages !== undefined && totalPages > 0 ? (<Fragment>
					<MetadataBadge text={`${currentPage}/${totalPages}`} icon={BookOpen} tooltip="阅读进度" size="xs" variant="primary"></MetadataBadge>
				</Fragment>) : null}</Fragment>)}
				{showSizeAndModified ? (<Fragment>
					<MetadataBadge text={item.isDir
							? getFolderSizeDisplay(folderSizeLoading, folderTotalSize, item.size)
							: formatSize(item.size || 0, false)} icon={HardDrive} tooltip="文件大小" size="xs" variant="secondary"></MetadataBadge>
					{timestamp ? (<Fragment>
						<MetadataBadge text={formatRelativeTime(timestamp)} icon={Clock} tooltip="修改时间" size="xs" variant="secondary"></MetadataBadge>
					</Fragment>) : null}
				</Fragment>) : (<Fragment>{timestamp ? (<Fragment>
					<MetadataBadge text={formatRelativeTime(timestamp)} icon={Clock} tooltip="修改时间" size="xs" variant="secondary"></MetadataBadge>
				</Fragment>) : (<Fragment>{!(currentPage !== undefined && totalPages !== undefined && totalPages > 0) ? (<Fragment>
					<MetadataBadge text={item.isDir
							? getFolderSizeDisplay(folderSizeLoading, folderTotalSize, item.size)
							: formatSize(item.size || 0, false)} icon={HardDrive} tooltip="文件大小" size="xs" variant="secondary"></MetadataBadge>
				</Fragment>) : null}</Fragment>)}</Fragment>)}
			</div>

			{displayTags().length > 0 ? (<Fragment>
				<div className="mt-1 flex flex-wrap items-center gap-1">
					{displayTags().map((tagInfo) => (<Fragment>
						<TagChip tag={tagInfo.tag} display={tagInfo.display} color={tagInfo.color} isCollect={tagInfo.isCollect} isMixedVariant={tagInfo.isMixedVariant} isManual={tagInfo.isManual} size="sm"></TagChip>
					</Fragment>))}
				</div>
			</Fragment>) : null}
		</div>
	</Fragment>) : null}
</div></Fragment>
  )
}
