/**
 * @migrated-from src/lib/cards/ai/VoiceControlCard.svelte
 * @source-hash sha256:ccc038692ffc76040acaeeeab6c336a0df4a3f4b2133f479aefd312a3400edc2
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute BindDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Switch } from '$lib/components/ui/switch';
import { Button } from '$lib/components/ui/button';
import { Label } from '$lib/components/ui/label';
import { NativeSelect, NativeSelectOption } from '$lib/components/ui/native-select';
import { voiceStore } from '$lib/stores/voice/voiceStore.js';
import { DEFAULT_VOICE_COMMANDS, getActiveCommands } from '$lib/services/voice/commandDict';
import { keyBindingsStore } from '$lib/stores/keybindings';
import {
		Mic,
		MicOff,
		Volume2,
		AlertCircle,
		CheckCircle,
		Settings,
		History,
		Info,
		Edit2,
		Save,
		RotateCcw
	} from 'lucide-react';
import * as Tooltip from '$lib/components/ui/tooltip';
import { toast } from 'svelte-sonner';

export function VoiceControlCard() {
  let isSupported = $state(false);

  let isEnabled = $state(false);

  let isListening = $state(false);

  let status = $state<'idle' | 'listening' | 'processing' | 'error'>('idle');

  let lastRecognizedText = $state('');

  let interimText = $state('');

  let errorMessage = $state<string | null>(null);

  let showSettings = $state(false);

  let showHistory = $state(false);

  let showCommandEditor = $state(false);

  let triggerMode = $state<'button' | 'hotkey' | 'wakeword' | 'always'>('button');

  let minConfidence = $state(0.6);

  let showFeedback = $state(true);

  let playSound = $state(true);

  let continuous = $state(false);

  let editingAction = $state<string>(Object.keys(DEFAULT_VOICE_COMMANDS)[0]);

  let editingPhrases = $state<string>('');

  let totalCommands = $state(0);

  let successfulCommands = $state(0);

  let commandHistory = $state<
      Array<{
        action: string;
        transcript: string;
        time: number;
        success: boolean;
      }>
    >([]);

  const supportedCommandsCount = Object.keys(DEFAULT_VOICE_COMMANDS).length;

  let dispatchAction: ((action: string) => void) | null = null;

  let interimUpdateInterval: ReturnType<typeof setInterval> | null = null;

  function startInterimUpdate() {
      stopInterimUpdate();
      interimUpdateInterval = setInterval(() => {
        const interim = voiceStore.getService().getInterimTranscript();
        if (interim) {
          interimText = interim;
        }
      }, 100);
    }

  function stopInterimUpdate() {
      if (interimUpdateInterval) {
        clearInterval(interimUpdateInterval);
        interimUpdateInterval = null;
      }
    }

  function handleVoiceExecute(event: CustomEvent) {
      // 用于外部触发语音命令执行
    }

  onMount(() => {
      // 初始化语音服务
      voiceStore.initialize();

      // 同步状态
      syncState();

      // 设置命令识别回调
      voiceStore.getService().setCallbacks({
        onStatusChange: (newStatus) => {
          status = newStatus;
          if (newStatus === 'error') {
            errorMessage = voiceStore.errorMessage;
          } else {
            errorMessage = null;
          }
          isListening = newStatus === 'listening';

          // 开始监听时，启动中间结果更新
          if (newStatus === 'listening') {
            startInterimUpdate();
          } else {
            stopInterimUpdate();
          }
        },
        onCommandRecognized: (match) => {
          lastRecognizedText = match.transcript;
          interimText = ''; // 清除中间结果

          // 执行命令
          executeCommand(match.action, match.transcript);
        },
        onError: (error) => {
          errorMessage = error;
          toast.error(error);
        },
        onSpeechStart: () => {
          // 检测到语音开始
          interimText = '正在识别...';
        },
        onSpeechEnd: () => {
          // 语音结束
        }
      });

      // 获取全局的 dispatchAction 函数
      // 通过自定义事件与 App.svelte 通信
      if (typeof window !== 'undefined') {
        window.addEventListener('neoview-voice-execute', handleVoiceExecute as EventListener);
      }
    });

  onDestroy(() => {
      stopInterimUpdate();
      if (typeof window !== 'undefined') {
        window.removeEventListener('neoview-voice-execute', handleVoiceExecute as EventListener);
      }
    });

  function syncState() {
      isSupported = voiceStore.isSupported;
      isEnabled = voiceStore.config.enabled;
      isListening = voiceStore.isListening;
      status = voiceStore.status;
      lastRecognizedText = voiceStore.lastRecognizedText;
      errorMessage = voiceStore.errorMessage;

      // 配置
      triggerMode = voiceStore.config.triggerMode;
      minConfidence = voiceStore.config.minConfidence;
      showFeedback = voiceStore.config.showFeedback;
      playSound = voiceStore.config.playSound;
      continuous = voiceStore.config.continuous;

      // 统计
      totalCommands = voiceStore.stats.totalCommands;
      successfulCommands = voiceStore.stats.successfulCommands;
      commandHistory = voiceStore.commandHistory;
    }

  function executeCommand(action: string, transcript: string) {
      console.log(`[VoiceCard] 执行命令: ${action}`);

      // 通过全局事件派发命令
      if (typeof window !== 'undefined') {
        window.dispatchEvent(
          new CustomEvent('neoview-voice-command', {
            detail: { action, transcript }
          })
        );
      }

      // 记录成功
      voiceStore.recordCommand(
        { action, transcript, confidence: 1, matchedPhrase: transcript },
        true
      );

      // 同步状态
      syncState();

      // 显示反馈
      if (showFeedback) {
        const binding = keyBindingsStore.getBinding(action);
        const actionName = binding?.name || action;
        toast.success(`🎤 ${actionName}`, {
          description: `"${transcript}"`,
          duration: 2000
        });
      }
    }

  function toggleEnabled() {
      isEnabled = !isEnabled;
      voiceStore.setEnabled(isEnabled);

      if (isEnabled) {
        toast.success('语音控制已启用');
      } else {
        toast.info('语音控制已禁用');
        if (isListening) {
          voiceStore.stopListening();
        }
      }
    }

  function toggleListening() {
      if (!isEnabled) {
        toast.warning('请先启用语音控制');
        return;
      }

      if (isListening) {
        voiceStore.stopListening();
        isListening = false;
      } else {
        const success = voiceStore.startListening();
        if (success) {
          isListening = true;
          toast.info('🎤 开始监听...', { duration: 1500 });
        }
      }
    }

  function updateTriggerMode(mode: string) {
      triggerMode = mode as typeof triggerMode;
      voiceStore.updateConfig({ triggerMode });
    }

  function updateMinConfidence(value: number) {
      minConfidence = value;
      voiceStore.updateConfig({ minConfidence: value });
    }

  function toggleShowFeedback() {
      showFeedback = !showFeedback;
      voiceStore.updateConfig({ showFeedback });
    }

  function togglePlaySound() {
      playSound = !playSound;
      voiceStore.updateConfig({ playSound });
    }

  function toggleContinuous() {
      continuous = !continuous;
      voiceStore.updateConfig({ continuous });

      // 如果正在监听，需要重启才能生效
      if (isListening) {
        toast.info('重启监听以应用持续模式');
        voiceStore.stopListening();
        setTimeout(() => {
          if (isEnabled) voiceStore.startListening();
        }, 500);
      }
    }

  function resetStats() {
      voiceStore.resetStats();
      syncState();
      toast.success('统计数据已重置');
    }

  function saveCustomCommand() {
      if (!editingPhrases.trim()) {
        toast.error('命令短语不能为空');
        return;
      }

      const phrases = editingPhrases
        .split(/[,，\n]/)
        .map((p) => p.trim())
        .filter((p) => p);
      if (phrases.length === 0) {
        toast.error('有效命令短语不能为空');
        return;
      }

      voiceStore.updateCommandPhrases(editingAction, phrases);
      toast.success(`已更新 "${getActionName(editingAction)}" 的语音命令`);
    }

  function resetCustomCommand() {
      const defaultPhrases = DEFAULT_VOICE_COMMANDS[editingAction];
      if (defaultPhrases) {
        editingPhrases = defaultPhrases.join(', ');
        saveCustomCommand();
      }
    }

  const commandOptions = Object.keys(DEFAULT_VOICE_COMMANDS)
      .map((action) => ({
        value: action,
        get label() {
          return getActionName(action);
        }
      }))
      .sort((a, b) => a.value.localeCompare(b.value));

  $effect(() => {
      const activeMap = getActiveCommands();
      const phrases = activeMap[editingAction] || DEFAULT_VOICE_COMMANDS[editingAction] || [];
      editingPhrases = phrases.join(', ');
    });

  function formatTime(timestamp: number): string {
      const date = new Date(timestamp);
      return date.toLocaleTimeString('zh-CN', {
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit'
      });
    }

  function getActionName(action: string): string {
      const binding = keyBindingsStore.getBinding(action);
      return binding?.name || action;
    }

  const statusColors = {
      idle: 'bg-gray-400',
      listening: 'bg-green-500 animate-pulse',
      processing: 'bg-yellow-500',
      error: 'bg-red-500'
    };

  const statusText = {
      idle: '待机',
      listening: '监听中',
      processing: '处理中',
      error: '错误'
    };
  return (
    <Fragment>

<div className="space-y-4">
	{/*  不支持提示  */}
	{!isSupported ? (<Fragment>
		<div className="flex items-center gap-2 rounded-md border border-amber-500/50 bg-amber-500/10 p-3 text-sm">
			<AlertCircle className="h-4 w-4 text-amber-500"></AlertCircle>
			<span className="text-amber-700 dark:text-amber-400">当前浏览器不支持语音识别</span>
		</div>
	</Fragment>) : (<Fragment>
		{/*  主开关  */}
		<div className="flex items-center justify-between">
			<div className="flex items-center gap-2">
				<Mic className="text-muted-foreground h-4 w-4"></Mic>
				<Label>启用语音控制</Label>
				<Tooltip.Root>
					<Tooltip.Trigger>
						<Info className="text-muted-foreground h-3 w-3"></Info>
					</Tooltip.Trigger>
					<Tooltip.Content>
						<p className="max-w-xs text-xs">
							使用语音命令控制应用，支持 {supportedCommandsCount} 种操作
						</p>
					</Tooltip.Content>
				</Tooltip.Root>
			</div>
			<Switch checked={isEnabled} onCheckedChange={toggleEnabled}></Switch>
		</div>

		{isEnabled ? (<Fragment>
			{/*  状态显示  */}
			<div className="bg-muted/30 flex items-center justify-between rounded-md border p-3">
				<div className="flex items-center gap-3">
					{/*  状态指示器  */}
					<div className="flex items-center gap-2">
						<span className="relative flex h-3 w-3">
							<span className={`${statusColors[
									status
								]} absolute inline-flex h-full w-full rounded-full opacity-75`}></span>
							<span className={`${statusColors[status]} relative inline-flex h-3 w-3 rounded-full`}></span>
						</span>
						<span className="text-sm font-medium">{statusText[status]}</span>
					</div>
				</div>

				<div className="flex items-center gap-2">
					<Label className="cursor-pointer text-xs" htmlFor="continuous-mode">持续模式</Label>
					<Switch id="continuous-mode" checked={continuous} onCheckedChange={toggleContinuous} className="origin-right scale-75"></Switch>
				</div>

				{/*  监听按钮  */}
				<Button variant={isListening ? 'destructive' : 'default'} size="sm" onClick={toggleListening} className="gap-2">
					{isListening ? (<Fragment>
						<MicOff className="h-4 w-4"></MicOff>
						停止
					</Fragment>) : (<Fragment>
						<Mic className="h-4 w-4"></Mic>
						开始监听
					</Fragment>)}
				</Button>
			</div>

			{/*  实时识别文字显示  */}
			{isListening && interimText ? (<Fragment>
				<div className="flex items-start gap-2 rounded-md border border-blue-500/30 bg-blue-500/10 p-3">
					<Mic className="mt-0.5 h-4 w-4 animate-pulse text-blue-500"></Mic>
					<div className="flex-1">
						<p className="text-muted-foreground text-xs">正在识别...</p>
						<p className="text-sm font-medium text-blue-700 dark:text-blue-300">"{interimText}"</p>
					</div>
				</div>
			</Fragment>) : null}

			{/*  最近识别结果显示  */}
			{lastRecognizedText ? (<Fragment>
				<div className="flex items-start gap-2 rounded-md border border-green-500/30 bg-green-500/10 p-3">
					<Volume2 className="mt-0.5 h-4 w-4 text-green-500"></Volume2>
					<div className="flex-1">
						<p className="text-muted-foreground text-xs">最近识别 (已执行)</p>
						<p className="text-sm font-medium">"{lastRecognizedText}"</p>
					</div>
				</div>
			</Fragment>) : null}

			{/*  错误显示  */}
			{errorMessage ? (<Fragment>
				<div className="flex items-center gap-2 rounded-md border border-red-500/50 bg-red-500/10 p-3 text-sm">
					<AlertCircle className="h-4 w-4 text-red-500"></AlertCircle>
					<span className="text-red-700 dark:text-red-400">{errorMessage}</span>
				</div>
			</Fragment>) : null}

			{/*  统计信息  */}
			<div className="grid grid-cols-2 gap-2 text-sm">
				<div className="bg-muted/30 rounded-md border p-2 text-center">
					<p className="text-primary text-lg font-bold">{totalCommands}</p>
					<p className="text-muted-foreground text-xs">总命令数</p>
				</div>
				<div className="bg-muted/30 rounded-md border p-2 text-center">
					<p className="text-lg font-bold text-green-500">{successfulCommands}</p>
					<p className="text-muted-foreground text-xs">成功执行</p>
				</div>
			</div>

			{/*  设置和历史按钮  */}
			<div className="flex gap-2">
				<Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => (showSettings = !showSettings)}>
					<Settings className="mr-1 h-3 w-3"></Settings>
					{showSettings ? '收起设置' : '高级设置'}
				</Button>
				<Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => (showCommandEditor = !showCommandEditor)}>
					<Edit2 className="mr-1 h-3 w-3"></Edit2>
					{showCommandEditor ? '收起编辑' : '命令编辑'}
				</Button>
				<Button variant="outline" size="sm" className="flex-1 text-xs" onClick={() => (showHistory = !showHistory)}>
					<History className="mr-1 h-3 w-3"></History>
					{showHistory ? '收起历史' : '命令历史'}
				</Button>
			</div>

			{/*  命令编辑区域  */}
			{showCommandEditor ? (<Fragment>
				<div className="bg-muted/20 space-y-3 rounded-md border p-3">
					<h4 className="text-muted-foreground text-xs font-medium">自定义命令字典</h4>

					<div className="space-y-2">
						<Label className="text-xs">选择操作</Label>
						<NativeSelect className="h-8 w-full text-xs" value={editingAction} onChange={(e) => (editingAction = (e.target as HTMLSelectElement).value)}>
							{commandOptions.map((option) => (<Fragment>
								<NativeSelectOption value={option.value}>{option.label}</NativeSelectOption>
							</Fragment>))}
						</NativeSelect>
					</div>

					<div className="space-y-2">
						<Label className="text-xs">语音指令 (用逗号分隔)</Label>
						<textarea className="border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring h-20 w-full rounded-md border px-3 py-2 text-xs focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none" placeholder="例如：放大, 变大, 放大图片"></textarea>
					</div>

					<div className="flex gap-2">
						<Button size="sm" className="flex-1 text-xs" onClick={saveCustomCommand}>
							<Save className="mr-1 h-3 w-3"></Save> 保存
						</Button>
						<Button variant="outline" size="sm" className="flex-1 text-xs" onClick={resetCustomCommand}>
							<RotateCcw className="mr-1 h-3 w-3"></RotateCcw> 重置默认
						</Button>
					</div>
				</div>
			</Fragment>) : null}

			{/*  高级设置  */}
			{showSettings ? (<Fragment>
				<div className="bg-muted/20 space-y-3 rounded-md border p-3">
					<h4 className="text-muted-foreground text-xs font-medium">高级设置</h4>

					{/*  触发模式  */}
					<div className="flex items-center justify-between">
						<Label className="text-xs">触发模式</Label>
						<NativeSelect className="h-7 w-24 text-xs" value={triggerMode} onChange={(e) => updateTriggerMode((e.target as HTMLSelectElement).value)}>
							<NativeSelectOption value="button">按钮</NativeSelectOption>
							<NativeSelectOption value="hotkey">热键</NativeSelectOption>
						</NativeSelect>
					</div>

					{/*  最低置信度  */}
					<div className="flex items-center justify-between">
						<Label className="text-xs">最低置信度: {(minConfidence * 100).toFixed(0)}%</Label>
						<input type="range" min="0.3" max="0.9" step="0.1" value={minConfidence} onInput={(e) => updateMinConfidence(parseFloat((e.target as HTMLInputElement).value))} className="h-2 w-24" />
					</div>

					{/*  显示反馈  */}
					<div className="flex items-center justify-between">
						<Label className="text-xs">显示命令反馈</Label>
						<Switch checked={showFeedback} onCheckedChange={toggleShowFeedback}></Switch>
					</div>

					{/*  重置统计  */}
					<Button variant="ghost" size="sm" className="w-full text-xs" onClick={resetStats}>
						重置统计数据
					</Button>
				</div>
			</Fragment>) : null}

			{/*  命令历史  */}
			{showHistory ? (<Fragment>
				<div className="bg-muted/20 max-h-48 space-y-2 overflow-y-auto rounded-md border p-3">
					<h4 className="text-muted-foreground text-xs font-medium">命令历史</h4>
					{commandHistory.length === 0 ? (<Fragment>
						<p className="text-muted-foreground py-2 text-center text-xs">暂无历史记录</p>
					</Fragment>) : (<Fragment>
						{commandHistory.slice(0, 10).map((item) => (<Fragment>
							<div className="border-border/50 flex items-center justify-between border-b py-1 text-xs last:border-0">
								<div className="flex items-center gap-2">
									{item.success ? (<Fragment>
										<CheckCircle className="h-3 w-3 text-green-500"></CheckCircle>
									</Fragment>) : (<Fragment>
										<AlertCircle className="h-3 w-3 text-red-500"></AlertCircle>
									</Fragment>)}
									<span className="font-medium">{getActionName(item.action)}</span>
								</div>
								<span className="text-muted-foreground">{formatTime(item.time)}</span>
							</div>
						</Fragment>))}
					</Fragment>)}
				</div>
			</Fragment>) : null}

			{/*  支持的命令提示  */}
			<div className="text-muted-foreground text-xs">
				<p>💡 提示：说出命令如 "下一页"、"放大"、"全屏" 等</p>
			</div>
		</Fragment>) : null}
	</Fragment>)}
</div></Fragment>
  )
}
