/**
 * @migrated-from src/lib/components/cards/CollapsibleCard.svelte
 * @source-hash sha256:517de356df45c43dc30c31f9b4bd2ef63a32dfc60cdf41063ab1bb062aa2ff04
 * @features card-windows-tabs
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute BindDirective; attribute TransitionDirective; template node RenderTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { cardConfigStore, type PanelId } from '$lib/stores/cardConfig.js';
import { cardRegistry } from '$lib/cards/registry';
import {
		ChevronDown,
		ChevronRight,
		ChevronUp,
		ChevronLeft,
		GripVertical,
		ArrowUp,
		ArrowDown,
		RotateCcw,
		EyeOff,
		ExternalLink
	} from 'lucide-react';
import { openCardInNewWindow } from '$lib/core/windows/cardWindowManager';
import type { IconName } from '$lib/utils/iconMap';
import MagicCard from '$lib/components/ui/MagicCard.js';
import GenericIcon from '$lib/components/ui/Icon.js';
interface Props {
		id: string;
		panelId: PanelId;
		title: string;
		icon?: IconName | Component; // 支持 Lucide 图标名或 Svelte 组件
		defaultExpanded?: boolean;
		showDragHandle?: boolean;
		showMoveButtons?: boolean;
		height?: number; // 自定义高度
		onHeightChange?: (height: number | undefined) => void;
		fullHeight?: boolean; // 是否占满剩余高度（用于虚拟列表等）
		// 新增：简化模式选项
		hideIcon?: boolean; // 隐藏图标
		hideTitle?: boolean; // 隐藏标题
		hideHeader?: boolean; // 完全隐藏头部（用于紧凑布局）
		compact?: boolean; // 紧凑模式（更小的 padding）
		orientation?: 'vertical' | 'horizontal'; // 展开方向
		className?: string;
		canHide?: boolean;
		children?: import('svelte').Snippet;
	}

export function CollapsibleCard(props: Props) {
  const {
		id,
		panelId,
		title,
		icon: Icon,
		defaultExpanded = true,
		showDragHandle = false,
		showMoveButtons = true,
		height = $bindable(),
		onHeightChange,
		fullHeight = false,
		hideIcon = false,
		hideTitle = false,
		hideHeader = false,
		compact = false,
		className = '',
		orientation = 'vertical',
		canHide = true,
		children
	} = props
  let isResizing = $state(false);

  let startY = $state(0);

  let startHeight = $state(0);

  let contentRef = $state<HTMLDivElement | null>(null);

  const cardConfig = $derived.by(() => {
      const cards = cardConfigStore.getPanelCards(panelId);
      return cards.find((c) => c.id === id);
    });

  const panelCards = $derived(cardConfigStore.getPanelCards(panelId));

  const isExpanded = $derived(cardConfig?.expanded ?? defaultExpanded);

  const cardOrder = $derived(cardConfig?.order ?? 0);

  const canMoveUp = $derived(cardOrder > 0);

  const canMoveDown = $derived(cardOrder < panelCards.length - 1);

  const canHideActual = $derived(canHide && (cardRegistry[id]?.canHide ?? true));

  function toggleExpanded() {
      cardConfigStore.setCardExpanded(panelId, id, !isExpanded);
    }

  function moveUp(e: MouseEvent) {
      e.stopPropagation();
      if (canMoveUp) cardConfigStore.moveCard(panelId, id, cardOrder - 1);
    }

  function moveDown(e: MouseEvent) {
      e.stopPropagation();
      if (canMoveDown) cardConfigStore.moveCard(panelId, id, cardOrder + 1);
    }

  function startResize(e: MouseEvent) {
      if (!contentRef) return;
      e.preventDefault();
      isResizing = true;
      startY = e.clientY;
      startHeight = height ?? contentRef.offsetHeight;

      document.addEventListener('mousemove', onResize);
      document.addEventListener('mouseup', stopResize);
    }

  function onResize(e: MouseEvent) {
      if (!isResizing) return;
      const deltaY = e.clientY - startY;
      const newHeight = Math.max(50, startHeight + deltaY); // 最小 50px
      onHeightChange?.(newHeight);
    }

  function stopResize() {
      isResizing = false;
      document.removeEventListener('mousemove', onResize);
      document.removeEventListener('mouseup', stopResize);
    }

  function resetHeight(e: MouseEvent) {
      e.stopPropagation();
      onHeightChange?.(undefined);
    }

  function hideCard(e: MouseEvent) {
      e.stopPropagation();
      if (canHideActual) cardConfigStore.setCardVisible(panelId, id, false);
    }

  async function handleOpenInNewWindow(e: MouseEvent) {
      e.stopPropagation();
      await openCardInNewWindow(id);
    }

  $effect(() => {
      if (id && Icon) {
        import('$lib/stores/iconRegistry.svelte').then(({ iconRegistry }) => {
          iconRegistry.register(id, Icon, title);
        });
      }
    });
  return (
    <Fragment>

<MagicCard className={`collapsible-card ${hideHeader
		? ''
		: 'bg-muted/10 hover:border-primary/60 rounded-lg border'} transition-all ${fullHeight
		? 'flex min-h-0 flex-1 flex-col'
		: ''} ${orientation === 'horizontal' ? 'flex flex-row' : ''} ${className}`} gradientSize={120} gradientOpacity={0.5}>
	{/*  标题栏（可隐藏）  */}
	{!hideHeader ? (<Fragment>
		<div className={`flex items-center justify-between ${compact
				? 'px-2 py-1'
				: 'px-3 py-2'} ${orientation === 'horizontal' ? 'flex-col border-r px-1 py-2' : ''}`}>
			<button type="button" className={`flex items-center gap-1.5 text-left ${orientation === 'horizontal' ? 'flex-col' : ''}`} onClick={toggleExpanded}>
				{showDragHandle ? (<Fragment>
					<GripVertical className="text-muted-foreground h-3.5 w-3.5 cursor-grab"></GripVertical>
				</Fragment>) : null}

				{!hideIcon ? (<Fragment>
					<GenericIcon name={id} fallback={typeof Icon === 'string' ? undefined : Icon} className="h-3.5 w-3.5"></GenericIcon>
				</Fragment>) : null}

				{!hideTitle ? (<Fragment>
					<span className={`text-xs font-medium ${orientation === 'horizontal'
							? 'writing-mode-vertical'
							: ''}`}>{title}</span>
				</Fragment>) : null}
			</button>

			<div className={`group/buttons flex items-center gap-0.5 ${orientation === 'horizontal'
					? 'mt-1 flex-col'
					: ''}`}>
				{/*  在新窗口打开按钮（悬停按钮区域显示）  */}
				<button type="button" className="text-muted-foreground hover:bg-primary/20 hover:text-primary inline-flex h-5 w-5 items-center justify-center rounded opacity-0 transition-opacity group-hover/buttons:opacity-100" onClick={handleOpenInNewWindow} title="在新窗口打开">
					<ExternalLink className="h-3 w-3"></ExternalLink>
				</button>
				{/*  隐藏卡片按钮（悬停按钮区域显示）  */}
				{canHideActual ? (<Fragment>
					<button type="button" className="text-muted-foreground hover:bg-destructive/20 hover:text-destructive inline-flex h-5 w-5 items-center justify-center rounded opacity-0 transition-opacity group-hover/buttons:opacity-100" onClick={hideCard} title="隐藏卡片">
						<EyeOff className="h-3 w-3"></EyeOff>
					</button>
				</Fragment>) : null}
				{/*  恢复默认高度按钮  */}
				{height && onHeightChange ? (<Fragment>
					<button type="button" className="text-muted-foreground hover:bg-muted hover:text-primary inline-flex h-5 w-5 items-center justify-center rounded" onClick={resetHeight} title="恢复默认高度">
						<RotateCcw className="h-3 w-3"></RotateCcw>
					</button>
				</Fragment>) : null}
				{/*  展开/收起按钮  */}
				<button type="button" className="text-muted-foreground hover:bg-muted inline-flex h-5 w-5 items-center justify-center rounded" onClick={toggleExpanded} title={isExpanded ? '收起' : '展开'}>
					{orientation === 'horizontal' ? (<Fragment>
						{isExpanded ? (<Fragment>
							<ChevronLeft className="h-3 w-3"></ChevronLeft>
						</Fragment>) : (<Fragment>
							<ChevronRight className="h-3 w-3"></ChevronRight>
						</Fragment>)}
					</Fragment>) : (<Fragment>{isExpanded ? (<Fragment>
						<ChevronUp className="h-3 w-3"></ChevronUp>
					</Fragment>) : (<Fragment>
						<ChevronDown className="h-3 w-3"></ChevronDown>
					</Fragment>)}</Fragment>)}
				</button>

				{showMoveButtons ? (<Fragment>
					<button type="button" className="text-muted-foreground hover:bg-muted inline-flex h-5 w-5 items-center justify-center rounded disabled:opacity-40" onClick={moveUp} disabled={!canMoveUp} title="上移">
						<ArrowUp className="h-3 w-3"></ArrowUp>
					</button>
					<button type="button" className="text-muted-foreground hover:bg-muted inline-flex h-5 w-5 items-center justify-center rounded disabled:opacity-40" onClick={moveDown} disabled={!canMoveDown} title="下移">
						<ArrowDown className="h-3 w-3"></ArrowDown>
					</button>
				</Fragment>) : null}
			</div>
		</div>
	</Fragment>) : null}

	{/*  内容区  */}
	{isExpanded || hideHeader ? (<Fragment>
		<div className={`${hideHeader ? '' : compact ? 'px-2 pb-2' : 'px-3 pb-3'} ${fullHeight
				? 'relative flex min-h-0 flex-1 flex-col overflow-hidden'
				: 'overflow-auto'} ${orientation === 'horizontal' ? 'flex-1' : ''}`} style={height ? `height: ${height}px` : fullHeight ? '' : ''}>
			{/* TODO unsupported RenderTag */}
		</div>

		{/*  拖拽调整高度/宽度手柄  */}
		{onHeightChange && !hideHeader ? (<Fragment>
			<button type="button" className={`${orientation === 'horizontal'
					? 'w-2 cursor-ew-resize'
					: 'h-2 cursor-ns-resize'} hover:bg-primary/20 group flex items-center justify-center`} onMouseDown={startResize} onDoubleClick={resetHeight} aria-label="调整卡片大小" title="拖拽调整大小，双击重置">
				<div className={`${orientation === 'horizontal'
						? 'h-8 w-0.5'
						: 'h-0.5 w-8'} bg-muted-foreground/30 group-hover:bg-primary/50 rounded-full`}></div>
			</button>
		</Fragment>) : null}
	</Fragment>) : null}
</MagicCard></Fragment>
  )
}
