import {
  Activity,
  Archive,
  AudioLines,
  Brush,
  Calculator,
  CalendarClock,
  CheckSquare,
  Clapperboard,
  CircleHelp,
  Clock,
  Clock3,
  FileArchive,
  FileCode,
  FilePenLine,
  FileText,
  Film,
  Filter,
  FolderInput,
  FolderSync,
  FolderTree,
  Gauge,
  GitCommitHorizontal,
  History,
  Image,
  Images,
  Languages,
  LayoutDashboard,
  Link,
  ListOrdered,
  Mic,
  MousePointerClick,
  Music2,
  Package,
  PackageOpen,
  Plus,
  Rocket,
  ScanSearch,
  Search,
  Settings,
  TableProperties,
  Tags,
  Trash2,
  Video,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react"

/**
 * Icons referenced by the serializable module registry.
 *
 * Do not replace this with `import * as LucideIcons`: namespace imports make
 * Vite retain the entire Lucide catalogue in the application entry chunk.
 */
const MODULE_ICON_REGISTRY: Readonly<Record<string, LucideIcon>> = {
  Activity,
  Archive,
  AudioLines,
  Brush,
  Calculator,
  CalendarClock,
  CheckSquare,
  Clapperboard,
  Clock,
  Clock3,
  FileArchive,
  FileCode,
  FilePenLine,
  FileText,
  Film,
  Filter,
  FolderInput,
  FolderSync,
  FolderTree,
  Gauge,
  GitCommitHorizontal,
  History,
  Image,
  Images,
  Languages,
  LayoutDashboard,
  Link,
  ListOrdered,
  Mic,
  MousePointerClick,
  Music2,
  Package,
  PackageOpen,
  Plus,
  Rocket,
  ScanSearch,
  Search,
  Settings,
  TableProperties,
  Tags,
  Trash2,
  Video,
  Workflow,
  Zap,
}

export function resolveModuleIcon(icon: string, fallback: LucideIcon = CircleHelp): LucideIcon {
  return MODULE_ICON_REGISTRY[icon] ?? fallback
}
