// @generated by scripts/generate-host-capabilities.ts — do not edit.
//
// The operation vocabulary is owned by `crates/quickjs-host-protocol` (`HostOperation::ALL`) and read
// from the compiled binary, never scraped from source text. Regenerate with
// `bun scripts/generate-host-capabilities.ts`; the --check form fails when this file is stale.

/** One host operation name, exactly as the host resolves it. */
export type HostOperationName =
  | "fs.stat"
  | "fs.list"
  | "fs.readText"
  | "fs.writeText"
  | "fs.ensureDir"
  | "fs.move"
  | "fs.delete"
  | "fs.mkdtemp"
  | "fs.copy"
  | "fs.appendText"
  | "fs.utimes"
  | "fs.readBytes"
  | "fs.writeBytes"
  | "fs.link"
  | "fs.symlink"
  | "fs.readlink"
  | "fs.realpath"
  | "proc.exec"
  | "proc.spawn"
  | "proc.poll"
  | "proc.wait"
  | "proc.kill"
  | "clock.now"
  | "crypto.randomUUID"
  | "crypto.randomBytes"
  | "crypto.digest"
  | "os.tmpdir"
  | "os.homedir"
  | "os.cpus"
  | "service.invoke"

/** Every operation the host answers, in the crate's own order. */
export const HOST_OPERATION_NAMES: readonly HostOperationName[] = [
  "fs.stat",
  "fs.list",
  "fs.readText",
  "fs.writeText",
  "fs.ensureDir",
  "fs.move",
  "fs.delete",
  "fs.mkdtemp",
  "fs.copy",
  "fs.appendText",
  "fs.utimes",
  "fs.readBytes",
  "fs.writeBytes",
  "fs.link",
  "fs.symlink",
  "fs.readlink",
  "fs.realpath",
  "proc.exec",
  "proc.spawn",
  "proc.poll",
  "proc.wait",
  "proc.kill",
  "clock.now",
  "crypto.randomUUID",
  "crypto.randomBytes",
  "crypto.digest",
  "os.tmpdir",
  "os.homedir",
  "os.cpus",
  "service.invoke",
]

/** Operations whose payload crosses the byte channel rather than the JSON envelope. */
export const BYTE_PAYLOAD_OPERATIONS: readonly HostOperationName[] = [
  "fs.writeBytes",
  "crypto.digest",
]

/** Operations whose answer is a buffer rather than a JSON document. */
export const BYTE_ANSWER_OPERATIONS: readonly HostOperationName[] = [
  "fs.readBytes",
]
