/**
 * @migrated-from src/lib/cards/properties/AiApiConfigCard.svelte
 * @source-hash sha256:dcf897ea2a892b3330643b55a6056122cc4129e99aff1fe0473f18129a67c25b
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported attribute BindDirective; template node ConstTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Settings, Plus, Trash2, Check, X, Loader2, Download, Upload } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import { Input } from '$lib/components/ui/input';
import * as Tabs from '$lib/components/ui/tabs';
import * as Select from '$lib/components/ui/select';
import {
		aiApiConfigStore,
		AI_PROVIDER_PRESETS,
		type AiProvider,
		type AiApiConfigJson
	} from '$lib/stores/aiApiConfig.js';

export function AiApiConfigCard() {
  let providers = $state<AiProvider[]>([]);

  let activeIndex = $state(0);

  let showAddForm = $state(false);

  let testingIndex = $state<number | null>(null);

  let testResult = $state<{ success: boolean; message: string } | null>(null);

  let newPreset = $state('deepseek');

  let newApiKey = $state('');

  $effect(() => {
      const unsub = aiApiConfigStore.subscribe((state) => {
        providers = state.providers;
        activeIndex = state.activeIndex;
      });
      return unsub;
    });

  function handleAdd() {
      if (!newPreset) return;
      aiApiConfigStore.addFromPreset(newPreset, newApiKey);
      newApiKey = '';
      showAddForm = false;
    }

  function handleRemove(index: number) {
      aiApiConfigStore.removeProvider(index);
    }

  async function handleTest(index: number, provider: AiProvider) {
      testingIndex = index;
      testResult = null;

      const result = await aiApiConfigStore.testConnection(provider);
      testResult = result;
      testingIndex = null;

      setTimeout(() => {
        testResult = null;
      }, 3000);
    }

  function handleUpdate(index: number, field: keyof AiProvider, value: string) {
      aiApiConfigStore.updateProvider(index, { [field]: value });
    }

  function handleTabChange(value: string) {
      const index = parseInt(value);
      if (!isNaN(index)) {
        aiApiConfigStore.setActiveIndex(index);
      }
    }

  function handleExport() {
      const config = aiApiConfigStore.exportConfig();
      const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'api_config.json';
      a.click();
      URL.revokeObjectURL(url);
    }

  function handleImport() {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = '.json';
      input.onchange = async (e) => {
        const file = (e.target as HTMLInputElement).files?.[0];
        if (!file) return;
        try {
          const text = await file.text();
          const config: AiApiConfigJson = JSON.parse(text);
          aiApiConfigStore.importConfig(config);
          testResult = {
            success: true,
            message: `导入成功: ${config.providers?.length || 0} 个提供商`
          };
          setTimeout(() => {
            testResult = null;
          }, 3000);
        } catch (err) {
          testResult = {
            success: false,
            message: `导入失败: ${err instanceof Error ? err.message : '无效的 JSON'}`
          };
          setTimeout(() => {
            testResult = null;
          }, 3000);
        }
      };
      input.click();
    }
  return (
    <Fragment>

<div className="space-y-3">
	{/*  头部  */}
	<div className="flex items-center justify-between">
		<div className="flex items-center gap-2">
			<Settings className="h-4 w-4 text-blue-500"></Settings>
			<span className="text-sm font-medium">AI API 配置</span>
		</div>
		<div className="flex items-center gap-1">
			<Button variant="ghost" size="icon" className="h-6 w-6" onClick={handleImport} title="导入配置">
				<Download className="h-3.5 w-3.5"></Download>
			</Button>
			<Button variant="ghost" size="icon" className="h-6 w-6" onClick={handleExport} title="导出配置" disabled={providers.length === 0}>
				<Upload className="h-3.5 w-3.5"></Upload>
			</Button>
			<Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => {
					showAddForm = !showAddForm;
				}} title="添加提供商">
				{showAddForm ? (<Fragment>
					<X className="h-3.5 w-3.5"></X>
				</Fragment>) : (<Fragment>
					<Plus className="h-3.5 w-3.5"></Plus>
				</Fragment>)}
			</Button>
		</div>
	</div>

	{/*  添加表单  */}
	{showAddForm ? (<Fragment>
		<div className="bg-muted/30 space-y-2 rounded border p-2">
			<Select.Root type="single">
				<Select.Trigger className="h-8 text-xs">
					<span>{AI_PROVIDER_PRESETS[newPreset]?.name || '选择提供商'}</span>
				</Select.Trigger>
				<Select.Content>
					{Object.entries(AI_PROVIDER_PRESETS).map(([id, preset]) => (<Fragment>
						<Select.Item value={id}>{preset.name}</Select.Item>
					</Fragment>))}
				</Select.Content>
			</Select.Root>
			<Input placeholder="API Key (Ollama 可留空)" type="password" className="h-8 text-xs"></Input>
			<div className="flex gap-2">
				<Button variant="outline" size="sm" className="h-7 flex-1" onClick={() => {
						showAddForm = false;
					}}>
					取消
				</Button>
				<Button variant="default" size="sm" className="h-7 flex-1" onClick={handleAdd}>添加</Button>
			</div>
		</div>
	</Fragment>) : null}

	{/*  提供商列表 - Tab 切换  */}
	{providers.length === 0 ? (<Fragment>
		<div className="text-muted-foreground py-4 text-center text-xs">
			<p>暂无配置</p>
			<p className="mt-1">点击 + 添加提供商，或导入 api_config.json</p>
		</div>
	</Fragment>) : (<Fragment>
		<Tabs.Root value={activeIndex.toString()} onValueChange={handleTabChange}>
			{/*  Tab 列表  */}
			<Tabs.List className="flex h-auto w-full flex-wrap gap-1 p-1">
				{providers.map((provider, index) => (<Fragment key={index}>
					<Tabs.Trigger value={index.toString()} className="h-7 flex-shrink-0 px-2 text-xs">
						{provider.name}
					</Tabs.Trigger>
				</Fragment>))}
			</Tabs.List>

			{/*  Tab 内容  */}
			{providers.map((provider, index) => (<Fragment key={index}>
				{/* TODO unsupported ConstTag */}
				<Tabs.Content value={index.toString()} className="space-y-2 pt-2">
					<Input value={provider.apiKey} placeholder="API Key" type="password" className="h-7 text-xs" onInput={(e) => handleUpdate(index, 'apiKey', (e.target as HTMLInputElement).value)}></Input>
					<Input value={provider.baseUrl} placeholder="API URL" className="h-7 text-xs" onInput={(e) => handleUpdate(index, 'baseUrl', (e.target as HTMLInputElement).value)}></Input>
					<Input value={provider.model} placeholder="模型名称" className="h-7 text-xs" onInput={(e) => handleUpdate(index, 'model', (e.target as HTMLInputElement).value)}></Input>
					<div className="flex gap-2">
						<Button variant="outline" size="sm" className="h-7 flex-1 text-xs" disabled={isTesting} onClick={() => handleTest(index, provider)}>
							{isTesting ? (<Fragment>
								<Loader2 className="mr-1 h-3 w-3 animate-spin"></Loader2>
								测试中
							</Fragment>) : (<Fragment>
								测试连接
							</Fragment>)}
						</Button>
						<Button variant="destructive" size="icon" className="h-7 w-7" onClick={() => handleRemove(index)}>
							<Trash2 className="h-3 w-3"></Trash2>
						</Button>
					</div>
				</Tabs.Content>
			</Fragment>))}
		</Tabs.Root>
	</Fragment>)}

	{/*  测试结果  */}
	{testResult ? (<Fragment>
		<div className={`rounded px-2 py-1 text-xs ${testResult.success
				? 'bg-green-500/10 text-green-500'
				: 'bg-destructive/10 text-destructive'}`}>
			{testResult.success ? (<Fragment>
				<Check className="mr-1 inline h-3 w-3"></Check>
			</Fragment>) : (<Fragment>
				<X className="mr-1 inline h-3 w-3"></X>
			</Fragment>)}
			{testResult.message}
		</div>
	</Fragment>) : null}

	{/*  使用说明  */}
	<div className="text-muted-foreground space-y-1 text-[10px]">
		<p>💡 推荐 DeepSeek (约¥0.001/次) 或 Ollama (免费本地)</p>
		<p>🔗 此配置供 AI 标签推断、翻译等功能共享使用</p>
		<p>📁 支持导入/导出 EMM 的 api_config.json 格式</p>
	</div>
</div></Fragment>
  )
}
