/**
 * @migrated-from src/lib/cards/properties/EmmRawDataCard.svelte
 * @source-hash sha256:15b65a69f7b7225df35baa20fb3841cb17f32ceb1cce68d9143869dcfbbe03a9
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported template node ConstTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import * as Table from '$lib/components/ui/table';
import * as Tooltip from '$lib/components/ui/tooltip';
import * as Input from '$lib/components/ui/input';
import { FlexRender, createSvelteTable } from '$lib/components/ui/data-table';
import type { ColumnDef, SortingState, ColumnFiltersState } from '@tanstack/table-core';
import { getCoreRowModel, getSortedRowModel, getFilteredRowModel } from '@tanstack/table-core';
import { FileSystemAPI } from '$lib/api';
import { infoPanelStore, type ViewerBookInfo } from '$lib/stores/infoPanel.js';
type EMMRawRow = { key: string; value: string };
type EMMFieldType = 'string' | 'path' | 'url' | 'datetime' | 'timestamp' | 'number' | 'boolean';

export function EmmRawDataCard() {
  const EMM_FIELD_META: Record<string, { label: string; type: EMMFieldType }> = {
      bundleSize: { label: '打包大小', type: 'number' },
      category: { label: '类别', type: 'string' },
      coverHash: { label: '封面哈希', type: 'string' },
      coverPath: { label: '封面路径', type: 'path' },
      createdAt: { label: '创建时间', type: 'datetime' },
      updatedAt: { label: '更新时间', type: 'datetime' },
      mtime: { label: '修改时间', type: 'datetime' },
      exist: { label: '存在', type: 'boolean' },
      filecount: { label: '文件数', type: 'number' },
      filepath: { label: '文件路径', type: 'path' },
      filesize: { label: '文件大小', type: 'number' },
      hash: { label: '哈希', type: 'string' },
      hiddenBook: { label: '隐藏书籍', type: 'boolean' },
      id: { label: 'ID', type: 'string' },
      mark: { label: '标记', type: 'number' },
      pageCount: { label: '页数', type: 'number' },
      posted: { label: '发布时间', type: 'timestamp' },
      readCount: { label: '阅读次数', type: 'number' },
      title: { label: '标题', type: 'string' },
      title_jpn: { label: '日文标题', type: 'string' },
      type: { label: '类型', type: 'string' },
      url: { label: '链接', type: 'url' },
      rating: { label: '评分', type: 'number' },
      status: { label: '状态', type: 'string' },
      date: { label: '日期', type: 'timestamp' }
    };

  let bookInfo = $state<ViewerBookInfo | null>(null);

  $effect(() => {
      const unsubscribe = infoPanelStore.subscribe((state) => {
        bookInfo = state.bookInfo;
      });
      return unsubscribe;
    });

  const emmRawEntries = $derived.by(() => {
      const raw = bookInfo?.emmMetadata?.raw as Record<string, unknown> | undefined;
      if (!raw) return [] as EMMRawRow[];
      const entries: EMMRawRow[] = [];
      for (const [key, value] of Object.entries(raw)) {
        if (value === undefined || value === null) continue;
        entries.push({ key, value: String(value) });
      }
      entries.sort((a, b) => a.key.localeCompare(b.key));
      return entries;
    });

  function getFieldMeta(key: string): { label: string; type: EMMFieldType } {
      return EMM_FIELD_META[key] ?? { label: key, type: 'string' };
    }

  function formatFileSizeNumber(bytes: number): string {
      if (!Number.isFinite(bytes) || bytes < 0) return String(bytes);
      if (bytes < 1024) return `${bytes} B`;
      if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
      if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
      return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
    }

  function formatDateTime(value: string): string {
      const d = new Date(value);
      if (!Number.isFinite(d.getTime())) return value;
      return d.toLocaleString('zh-CN');
    }

  function formatTimestampSeconds(value: string): string {
      const n = Number(value);
      if (!Number.isFinite(n)) return value;
      const d = new Date(n * 1000);
      if (!Number.isFinite(d.getTime())) return value;
      return d.toLocaleString('zh-CN');
    }

  function formatNumberValue(key: string, value: string): string {
      const n = Number(value);
      if (!Number.isFinite(n)) return value;
      if (key === 'filesize' || key === 'bundleSize') return formatFileSizeNumber(n);
      if (key === 'rating') return n.toFixed(1);
      return value;
    }

  function formatBoolean(value: string): string {
      return value === '1' || value.toLowerCase() === 'true' ? '是' : '否';
    }

  async function openPath(path: string) {
      try {
        await FileSystemAPI.showInFileManager(path);
      } catch (err) {
        console.error('[EmmRawDataCard] 打开路径失败:', err);
      }
    }

  function openUrl(url: string) {
      window.open(url, '_blank');
    }

  const columns: ColumnDef<EMMRawRow>[] = [
      {
        accessorKey: 'key',
        header: '字段',
        cell: ({ row }) => row.getValue('key') as string,
        filterFn: (row, _columnId, value) => {
          const v = (value as string | undefined)?.toLowerCase() ?? '';
          if (!v) return true;
          const key = String(row.getValue('key') ?? '').toLowerCase();
          const val = String(row.getValue('value') ?? '').toLowerCase();
          return (key + ' ' + val).includes(v);
        }
      },
      {
        accessorKey: 'value',
        header: '值',
        cell: ({ row }) => row.getValue('value') as string
      }
    ];

  let sorting = $state<SortingState>([]);

  let columnFilters = $state<ColumnFiltersState>([]);

  const table = createSvelteTable({
      get data() {
        return emmRawEntries;
      },
      columns,
      state: {
        get sorting() {
          return sorting;
        },
        get columnFilters() {
          return columnFilters;
        }
      },
      getCoreRowModel: getCoreRowModel(),
      getSortedRowModel: getSortedRowModel(),
      getFilteredRowModel: getFilteredRowModel(),
      onSortingChange: (updater) => {
        sorting = typeof updater === 'function' ? updater(sorting) : updater;
      },
      onColumnFiltersChange: (updater) => {
        columnFilters = typeof updater === 'function' ? updater(columnFilters) : updater;
      }
    });
  return (
    <Fragment>

<div className="space-y-2">
	{emmRawEntries.length === 0 ? (<Fragment>
		<p className="text-muted-foreground py-4 text-center text-xs">暂无 EMM 数据库记录</p>
	</Fragment>) : (<Fragment>
		{/*  过滤输入  */}
		<div className="flex items-center gap-2">
			<Input.Root className="h-6 flex-1 px-2 text-[10px]" placeholder="过滤字段/值..." value={String(table.getColumn('key')?.getFilterValue() ?? '')} onInput={(e) => {
					const v = e.currentTarget.value;
					table.getColumn('key')?.setFilterValue(v);
				}}></Input.Root>
			<span className="text-muted-foreground text-[10px]">{emmRawEntries.length} 条</span>
		</div>

		{/*  数据表格  */}
		<div className="max-h-48 overflow-auto rounded-md border">
			<Table.Root className="text-xs">
				<Table.Header>
					{table.getHeaderGroups().map((headerGroup) => (<Fragment key={headerGroup.id}>
						<Table.Row>
							{headerGroup.headers.map((header) => (<Fragment key={header.id}>
								<Table.Head className="text-muted-foreground px-2 py-1 text-[11px] first:text-left last:text-right">
									{!header.isPlaceholder ? (<Fragment>
										<button type="button" className="hover:text-foreground flex w-full items-center justify-between gap-1" onClick={header.column.getToggleSortingHandler()}>
											<FlexRender content={header.column.columnDef.header} context={header.getContext()}></FlexRender>
										</button>
									</Fragment>) : null}
								</Table.Head>
							</Fragment>))}
						</Table.Row>
					</Fragment>))}
				</Table.Header>
				<Table.Body>
					{table.getRowModel().rows.map((row) => (<Fragment key={row.id}>
						<Table.Row>
							{row.getVisibleCells().map((cell) => (<Fragment key={cell.id}>
								{cell.column.id === 'key' ? (<Fragment>
									{/* TODO unsupported ConstTag */}
									{/* TODO unsupported ConstTag */}
									<Table.Cell className="text-muted-foreground max-w-[140px] truncate px-2 py-0.5 align-top">
										<Tooltip.Root>
											<Tooltip.Trigger>
												<span className="inline-block w-full truncate text-left">{meta.label}</span>
											</Tooltip.Trigger>
											<Tooltip.Content>
												<p className="text-[10px]">{original.key}</p>
											</Tooltip.Content>
										</Tooltip.Root>
									</Table.Cell>
								</Fragment>) : (<Fragment>
									{/* TODO unsupported ConstTag */}
									{/* TODO unsupported ConstTag */}
									<Table.Cell className="max-w-[200px] truncate px-2 py-0.5 text-right align-top">
										<Tooltip.Root>
											<Tooltip.Trigger>
												<span className="inline-block w-full truncate">
													{meta.type === 'url' ? (<Fragment>
														<button type="button" className="text-primary w-full text-right text-xs underline-offset-2 hover:underline" onClick={() => openUrl(original.value)}>
															{original.value}
														</button>
													</Fragment>) : (<Fragment>{meta.type === 'path' ? (<Fragment>
														<button type="button" className="text-foreground/80 w-full text-right text-xs underline-offset-2 hover:underline" onClick={() => openPath(original.value)}>
															{original.value}
														</button>
													</Fragment>) : (<Fragment>{meta.type === 'datetime' ? (<Fragment>
														{formatDateTime(original.value)}
													</Fragment>) : (<Fragment>{meta.type === 'timestamp' ? (<Fragment>
														{formatTimestampSeconds(original.value)}
													</Fragment>) : (<Fragment>{meta.type === 'number' ? (<Fragment>
														{formatNumberValue(original.key, original.value)}
													</Fragment>) : (<Fragment>{meta.type === 'boolean' ? (<Fragment>
														{formatBoolean(original.value)}
													</Fragment>) : (<Fragment>
														{original.value}
													</Fragment>)}</Fragment>)}</Fragment>)}</Fragment>)}</Fragment>)}</Fragment>)}
												</span>
											</Tooltip.Trigger>
											<Tooltip.Content>
												<p className="max-w-xs text-[10px] break-all">{original.value}</p>
											</Tooltip.Content>
										</Tooltip.Root>
									</Table.Cell>
								</Fragment>)}
							</Fragment>))}
						</Table.Row>
					</Fragment>))}
				</Table.Body>
			</Table.Root>
		</div>
	</Fragment>)}
</div></Fragment>
  )
}
