/**
 * @migrated-from src/lib/cards/properties/EmmTagsCard.svelte
 * @source-hash sha256:12dc7b10bcbdac94c659d88b8573bf35bbe85b26409dd90dda3e347c703307d3
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported template node ConstTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { infoPanelStore, type ViewerBookInfo } from '$lib/stores/infoPanel.js';
import { emmMetadataStore } from '$lib/stores/emmMetadata.js';

export function EmmTagsCard() {
  let bookInfo = $state<ViewerBookInfo | null>(null);

  $effect(() => {
      const unsubscribe = infoPanelStore.subscribe((state) => {
        bookInfo = state.bookInfo;
      });
      return unsubscribe;
    });

  const allTags = $derived.by(() => {
      if (!bookInfo?.emmMetadata?.tags) {
        return [] as string[];
      }
      const tags = bookInfo.emmMetadata.tags;
      // 如果 tags 是对象，提取所有值
      if (typeof tags === 'object' && !Array.isArray(tags)) {
        return Object.values(tags).flat() as string[];
      }
      return tags as string[];
    });

  function getTagTranslation(tag: string): string {
      const dict = emmMetadataStore.getTranslationDict();
      if (!dict) return tag;
      const record = dict[tag];
      if (record && typeof record === 'object' && 'cn' in record) {
        return (record as { cn?: string }).cn || tag;
      }
      return tag;
    }
  return (
    <Fragment>

<div className="space-y-2 text-[11px]">
	{!bookInfo ? (<Fragment>
		<div className="text-muted-foreground py-4 text-center">
			<p>未打开书籍</p>
			<p className="mt-1 text-[10px]">打开书籍后显示标签</p>
		</div>
	</Fragment>) : (<Fragment>{!bookInfo.emmMetadata ? (<Fragment>
		<div className="text-muted-foreground py-4 text-center">
			<p>无 EMM 数据</p>
			<p className="mt-1 text-[10px]">此书籍没有关联的 EMM 元数据</p>
		</div>
	</Fragment>) : (<Fragment>{allTags.length === 0 ? (<Fragment>
		<div className="text-muted-foreground py-4 text-center">
			<p>暂无标签</p>
		</div>
	</Fragment>) : (<Fragment>
		<div className="flex flex-wrap gap-1">
			{allTags.map((tag) => (<Fragment>
				{/* TODO unsupported ConstTag */}
				<span className="border-border hover:bg-muted/50 inline-flex items-center rounded border px-1.5 py-0.5 text-[10px]" title={tag !== translated ? tag : undefined}>
					{translated}
				</span>
			</Fragment>))}
		</div>
		<div className="text-muted-foreground pt-1 text-[10px]">
			共 {allTags.length} 个标签
		</div>
	</Fragment>)}</Fragment>)}</Fragment>)}
</div></Fragment>
  )
}
