/**
 * @migrated-from src/lib/cards/properties/FileListTagDisplayCard.svelte
 * @source-hash sha256:372ef11a089413c212e2cfde37e77d7787dd2a4abe9e1ff42a42ca79ab776e33
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import FileListTagDisplay from '$lib/components/panels/emm/FileListTagDisplayCard.js';

export function FileListTagDisplayCard() {
  return (
    <Fragment>

<FileListTagDisplay></FileListTagDisplay></Fragment>
  )
}
