// Generated by scripts/generate-node-registries.ts. Do not edit by hand.

import { nodeCliName } from "@xiranite/cli-runtime"

export const GENERATED_NODE_CLI_REGISTRY = [
  {
    id: "bandia",
    packageName: "@xiranite/node-bandia",
    bin: nodeCliName("bandia"),
    description: "Batch extract, compress, repack, and export archive paths with Bandizip.",
  },
  {
    id: "bitv",
    packageName: "@xiranite/node-bitv",
    bin: nodeCliName("bitv"),
    description: "Analyze video bitrate with ffprobe and classify files without overwriting existing data.",
  },
  {
    id: "classf",
    packageName: "@xiranite/node-classf",
    bin: nodeCliName("classf"),
    description: "Orchestrate SameA artist extraction, CrashU matching, and MigrateF classification transfers.",
  },
  {
    id: "classq",
    packageName: "@xiranite/node-classq",
    bin: nodeCliName("classq"),
    description: "Find keyword folders and plan sibling items into wait folders.",
  },
  {
    id: "cleanf",
    packageName: "@xiranite/node-cleanf",
    bin: nodeCliName("cleanf"),
    description: "Remove empty folders, backup files, temp folders, and trash patterns.",
  },
  {
    id: "crashu",
    packageName: "@xiranite/node-crashu",
    bin: nodeCliName("crashu"),
    description: "Match similar folder names and optionally move matched folders.",
  },
  {
    id: "dissolvef",
    packageName: "@xiranite/node-dissolvef",
    bin: nodeCliName("dissolvef"),
    description: "Dissolve nested, single-media, single-archive, or direct folders with undo history.",
  },
  {
    id: "encodeb",
    packageName: "@xiranite/node-encodeb",
    bin: nodeCliName("encodeb"),
    description: "Preview and recover garbled filenames by re-decoding path components.",
  },
  {
    id: "enginev",
    packageName: "@xiranite/node-enginev",
    bin: nodeCliName("enginev"),
    description: "Scan, filter, rename, delete, and export Wallpaper Engine workshop folders.",
  },
  {
    id: "findz",
    packageName: "@xiranite/node-findz",
    bin: nodeCliName("findz"),
    description: "Incrementally index ZIP and CBZ libraries, then analyze image headers on demand.",
  },
  {
    id: "formatv",
    packageName: "@xiranite/node-formatv",
    bin: nodeCliName("formatv"),
    description: "Scan video folders, add/remove .nov suffixes, and check prefixed duplicates.",
  },
  {
    id: "gifu",
    packageName: "@xiranite/node-gifu",
    bin: nodeCliName("gifu"),
    description: "Convert archive image sequences with a native TypeScript, 7-Zip, and ffmpeg workflow.",
  },
  {
    id: "kisaki",
    packageName: "@xiranite/node-kisaki",
    bin: nodeCliName("kisaki"),
    description: "Scan files with eleven Czkawka tools and manage results safely.",
  },
  {
    id: "linedup",
    packageName: "@xiranite/node-linedup",
    bin: nodeCliName("linedup"),
    description: "Filter source lines by removing any line containing a filter token.",
  },
  {
    id: "linku",
    packageName: "@xiranite/node-linku",
    bin: nodeCliName("linku"),
    description: "Create, move, list, and recover symlink records.",
  },
  {
    id: "logx",
    packageName: "@xiranite/node-logx",
    bin: nodeCliName("logx"),
    description: "Inspect, query, aggregate, and diagnose structured Xiranite logs.",
  },
  {
    id: "marku",
    packageName: "@xiranite/node-marku",
    bin: nodeCliName("marku"),
    description: "Run Markdown cleanup and conversion modules with preview diff.",
  },
  {
    id: "migratef",
    packageName: "@xiranite/node-migratef",
    bin: nodeCliName("migratef"),
    description: "Move or copy files with preserve, flat, and direct modes plus undo history.",
  },
  {
    id: "mvz",
    packageName: "@xiranite/node-mvz",
    bin: nodeCliName("mvz"),
    description: "Delete, extract, move, or rename files inside archives from findz output.",
  },
  {
    id: "nameu",
    packageName: "@xiranite/node-nameu",
    bin: nodeCliName("nameu"),
    description: "Preview and apply archive filename cleanup for artist folders.",
  },
  {
    id: "rawfilter",
    packageName: "@xiranite/node-rawfilter",
    bin: nodeCliName("rawfilter"),
    description: "Group similar archives and move duplicate/raw versions to trash or multi.",
  },
  {
    id: "recycleu",
    packageName: "@xiranite/node-recycleu",
    bin: nodeCliName("recycleu"),
    description: "Empty the Windows recycle bin immediately or on a bounded timer.",
  },
  {
    id: "repacku",
    packageName: "@xiranite/node-repacku",
    bin: nodeCliName("repacku"),
    description: "Analyze folder structures and repack matching folders into zip archives.",
  },
  {
    id: "samea",
    packageName: "@xiranite/node-samea",
    bin: nodeCliName("samea"),
    description: "Extract artist metadata from archive names and organize matching archives.",
  },
  {
    id: "sleept",
    packageName: "@xiranite/node-sleept",
    bin: nodeCliName("sleept"),
    description: "System timer for countdown, scheduled time, network, and CPU triggers.",
  },
  {
    id: "smartzip",
    packageName: "@xiranite/node-smartzip",
    bin: nodeCliName("smartzip"),
    description: "TypeScript archive workflows with automatic 7-Zip discovery.",
  },
  {
    id: "timeu",
    packageName: "@xiranite/node-timeu",
    bin: nodeCliName("timeu"),
    description: "Back up and restore file timestamps from JSON records.",
  },
  {
    id: "trename",
    packageName: "@xiranite/node-trename",
    bin: nodeCliName("trename"),
    description: "Scan folders into rename JSON, validate translated targets, rename, and undo.",
  },
]
