import { access, mkdir, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"

import { analyzeTauriProject } from "./analyze.js"
import type { GenerateMigrationOptions, TauriMigrationInventory } from "./types.js"

export async function generateMigrationArtifacts(
  options: GenerateMigrationOptions,
): Promise<TauriMigrationInventory> {
  const inventory = await analyzeTauriProject(options)
  const outputDir = resolve(options.outputDir)
  await mkdir(outputDir, { recursive: true })

  const artifacts = new Map([
    ["inventory.json", `${JSON.stringify(inventory, null, 2)}\n`],
    ["commands.ts", generateCommands(inventory)],
    ["adapter.ts", generateAdapter()],
    ["REPORT.md", generateReport(inventory)],
  ])

  if (!options.force) {
    for (const name of artifacts.keys()) {
      const target = join(outputDir, name)
      if (await exists(target)) {
        throw new Error(`Refusing to overwrite ${target}. Pass --force to replace generated artifacts.`)
      }
    }
  }
  for (const [name, content] of artifacts) {
    const target = join(outputDir, name)
    await writeFile(target, content, "utf8")
  }
  return inventory
}

function generateCommands(inventory: TauriMigrationInventory): string {
  const argumentEntries = inventory.commands.map((command) => {
    const parameters = command.parameters.filter((parameter) => !parameter.tauriInjected)
    const body = parameters.length
      ? `{ ${parameters.map((parameter) => `${safeProperty(parameter.name)}: ${parameter.tsType}`).join("; ")} }`
      : "Record<string, never>"
    return `  ${safeProperty(command.name)}: ${body}`
  })
  const resultEntries = inventory.commands.map(
    (command) => `  ${safeProperty(command.name)}: ${command.tsReturnType}`,
  )
  const sourceComments = inventory.commands.map(
    (command) => `  ${safeProperty(command.name)}: ${JSON.stringify(`${command.location.file}:${command.location.line}`)}`,
  )

  return `// Generated by @xiranite/tauri-migrate. Do not edit by hand.\n\n` +
    `export interface TauriCommandArguments {\n${argumentEntries.join("\n")}\n}\n\n` +
    `export interface TauriCommandResults {\n${resultEntries.join("\n")}\n}\n\n` +
    `export type TauriCommandName = keyof TauriCommandArguments\n\n` +
    `export const tauriCommandSources = {\n${sourceComments.join("\n")}\n} as const satisfies Record<TauriCommandName, string>\n`
}

function generateAdapter(): string {
  return `// Generated by @xiranite/tauri-migrate. This adapter has no Tauri dependency.\n` +
    `import type { TauriCommandArguments, TauriCommandName, TauriCommandResults } from "./commands.js"\n\n` +
    `export type CommandInvoker = <Name extends TauriCommandName>(\n` +
    `  command: Name,\n` +
    `  arguments_: TauriCommandArguments[Name],\n` +
    `) => Promise<TauriCommandResults[Name]>\n\n` +
    `export interface MigratedTauriBackend {\n` +
    `  invoke: CommandInvoker\n` +
    `}\n\n` +
    `export function createMigratedTauriBackend(invoke: CommandInvoker): MigratedTauriBackend {\n` +
    `  return { invoke }\n` +
    `}\n`
}

function generateReport(inventory: TauriMigrationInventory): string {
  const rows = inventory.commands.map((command) =>
    `| ${escapeTable(command.name)} | ${command.disposition} | ${command.classificationSource} | ${command.registered ? "yes" : "no"} | ${command.events.map((event) => escapeTable(event.name ?? event.expression)).join(", ") || "-"} | ${command.nativeReasons.map(escapeTable).join(", ") || "-"} | ${command.location.file}:${command.location.line} |`,
  )
  return `# Tauri backend migration report\n\n` +
    `Generated from \`${inventory.projectRoot}\`. The report is an AST inventory, not a claim that Rust business logic was automatically translated.\n\n` +
    `- Rust files: ${inventory.rustFiles}\n` +
    `- Commands: ${inventory.commands.length}\n` +
    `- TypeScript portable: ${inventory.summary["typescript-portable"]}\n` +
    `- Native required: ${inventory.summary["native-required"]}\n` +
    `- Manual review: ${inventory.summary["manual-review"]}\n\n` +
    `| Command | Disposition | Classification | Registered | Events | Native evidence | Source |\n` +
    `| --- | --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\n` +
    `## Unannotated registrations\n\n` +
    `${inventory.unannotatedRegistrations.length ? inventory.unannotatedRegistrations.map((name) => `- ${name}`).join("\n") : "None."}\n`
}

function safeProperty(value: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value)
}

function escapeTable(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ")
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}
