/**
 * @migrated-from src/lib/components/panels/PlaylistPanel.svelte
 * @source-hash sha256:7d99337c304832c02161b56a71851eccb78b4f9cc2cb5f3b8efb23ea518999ce
 * @features
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported attribute BindDirective
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Button } from '$lib/components/ui/button';
import { Input } from '$lib/components/ui/input';
import { ListMusic, Plus, Trash2, Play, Folder, FileArchive, GripVertical } from 'lucide-react';
import { confirm } from '$lib/stores/confirmDialog.js';
import { showInfoToast } from '$lib/utils/toast';
interface PlaylistItem {
		path: string;
		name: string;
		type: 'archive' | 'folder';
		pages: number;
	}
interface Playlist {
		id: string;
		name: string;
		items: PlaylistItem[];
		createdAt: Date;
	}

export function PlaylistPanel() {
  const STORAGE_KEY = 'neoview-playlists';

  const ACTIVE_PLAYLIST_KEY = 'neoview-active-playlist';

  function loadPlaylists(): Playlist[] {
      try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored) {
          const parsed = JSON.parse(stored);
          return parsed.map((p: any) => ({
            ...p,
            createdAt: new Date(p.createdAt)
          }));
        }
      } catch (e) {
        console.error('Failed to load playlists:', e);
      }
      return [];
    }

  function savePlaylists() {
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(playlists));
        if (activePlaylist) {
          localStorage.setItem(ACTIVE_PLAYLIST_KEY, activePlaylist);
        }
      } catch (e) {
        console.error('Failed to save playlists:', e);
      }
    }

  let playlists = $state<Playlist[]>(loadPlaylists());

  let activePlaylist = $state<string | null>(localStorage.getItem(ACTIVE_PLAYLIST_KEY) || null);

  $effect(() => {
      if (activePlaylist === null && playlists.length > 0) {
        activePlaylist = playlists[0].id;
      }
    });

  let newPlaylistName = $state('');

  let isCreating = $state(false);

  const currentPlaylist = $derived(playlists.find((p) => p.id === activePlaylist) || null);

  function createPlaylist() {
      if (newPlaylistName.trim()) {
        const newList: Playlist = {
          id: Date.now().toString(),
          name: newPlaylistName.trim(),
          items: [],
          createdAt: new Date()
        };
        playlists = [...playlists, newList];
        activePlaylist = newList.id;
        newPlaylistName = '';
        isCreating = false;
        savePlaylists();
      }
    }

  async function deletePlaylist(id: string) {
      const confirmed = await confirm({
        title: '确认删除',
        description: '确定要删除此播放列表吗？',
        confirmText: '删除',
        cancelText: '取消',
        variant: 'destructive'
      });
      if (confirmed) {
        playlists = playlists.filter((p) => p.id !== id);
        if (activePlaylist === id) {
          activePlaylist = playlists[0]?.id || null;
        }
        savePlaylists();
      }
    }

  function removeItem(itemPath: string) {
      if (currentPlaylist) {
        currentPlaylist.items = currentPlaylist.items.filter((item) => item.path !== itemPath);
        playlists = [...playlists];
        savePlaylists();
      }
    }

  async function playItem(item: PlaylistItem) {
      const { bookStore } = await import('$lib/stores/book.svelte');
      await bookStore.openBook(item.path);
    }

  async function addToPlaylist() {
      const { open } = await import('@tauri-apps/plugin-dialog');
      const selected = await open({
        multiple: true,
        directory: false,
        filters: [{ name: '压缩包', extensions: ['zip', 'rar', '7z', 'cbz', 'cbr'] }]
      });
      if (selected && currentPlaylist) {
        const paths = Array.isArray(selected) ? selected : [selected];
        for (const path of paths) {
          const name = path.split(/[\\/]/).pop() || path;
          currentPlaylist.items.push({
            path,
            name,
            type: 'archive',
            pages: 0
          });
        }
        playlists = [...playlists];
        savePlaylists();
      }
    }
  return (
    <Fragment>

<div className="flex h-full flex-col">
	{/*  头部  */}
	<div className="border-b p-3">
		<div className="mb-2 flex items-center justify-between">
			<h3 className="flex items-center gap-2 text-sm font-semibold">
				<ListMusic className="h-4 w-4"></ListMusic>
				播放列表
			</h3>
			<Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => (isCreating = !isCreating)} title="新建播放列表">
				<Plus className="h-3 w-3"></Plus>
			</Button>
		</div>

		{/*  新建播放列表  */}
		{isCreating ? (<Fragment>
			<div className="flex gap-1">
				<Input type="text" placeholder="播放列表名称" className="h-7 text-xs" onKeyDown={(e) => e.key === 'Enter' && createPlaylist()}></Input>
				<Button variant="default" size="sm" className="h-7 px-2" onClick={createPlaylist}>创建</Button>
			</div>
		</Fragment>) : null}

		{/*  播放列表标签  */}
		<div className="mt-2 flex gap-1 overflow-x-auto">
			{playlists.map((list) => (<Fragment>
				<button className={`rounded-md px-3 py-1 text-xs whitespace-nowrap transition-colors ${activePlaylist ===
					list.id
						? 'bg-primary text-primary-foreground'
						: 'bg-muted hover:bg-muted/80'}`} onClick={() => (activePlaylist = list.id)}>
					{list.name} ({list.items.length})
				</button>
			</Fragment>))}
		</div>
	</div>

	{/*  播放列表内容  */}
	{currentPlaylist ? (<Fragment>
		<div className="bg-background flex flex-1 flex-col overflow-hidden">
			{/*  工具栏  */}
			<div className="flex items-center justify-between border-b p-2">
				<span className="text-muted-foreground text-xs">{currentPlaylist.items.length} 项</span>
				<div className="flex gap-1">
					<Button variant="ghost" size="sm" className="h-6 px-2 text-xs" onClick={addToPlaylist}>
						<Plus className="mr-1 h-3 w-3"></Plus>
						添加
					</Button>
					<Button variant="ghost" size="sm" className="text-destructive hover:text-destructive h-6 px-2 text-xs" onClick={() => deletePlaylist(currentPlaylist.id)}>
						<Trash2 className="mr-1 h-3 w-3"></Trash2>
						删除列表
					</Button>
				</div>
			</div>

			{/*  项目列表  */}
			<div className="flex-1 overflow-y-auto p-2">
				{currentPlaylist.items.length === 0 ? (<Fragment>
					<div className="text-muted-foreground py-8 text-center text-sm">
						<ListMusic className="mx-auto mb-2 h-8 w-8 opacity-50"></ListMusic>
						<p>播放列表为空</p>
						<p className="mt-1 text-xs">点击"添加"按钮添加书籍</p>
					</div>
				</Fragment>) : (<Fragment>
					<div className="space-y-1">
						{currentPlaylist.items.map((item) => (<Fragment>
							<div className="hover:bg-accent hover:border-border group flex items-center gap-2 rounded-md border border-transparent p-2 transition-colors">
								{/*  拖动手柄  */}

								{/*  操作按钮  */}
								<div className="flex gap-1 opacity-0 transition-opacity group-hover:opacity-100">
									<Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => playItem(item)} title="播放">
										<Play className="h-3 w-3"></Play>
									</Button>
									<Button variant="ghost" size="icon" className="text-destructive hover:text-destructive h-6 w-6" onClick={() => removeItem(item.path)} title="移除">
										<Trash2 className="h-3 w-3"></Trash2>
									</Button>
								</div>
							</div>
						</Fragment>))}
					</div>
				</Fragment>)}
			</div>
		</div>
	</Fragment>) : (<Fragment>
		<div className="text-muted-foreground flex flex-1 items-center justify-center text-sm">
			<div className="text-center">
				<ListMusic className="mx-auto mb-2 h-12 w-12 opacity-30"></ListMusic>
				<p>暂无播放列表</p>
				<Button variant="outline" size="sm" className="mt-3" onClick={() => (isCreating = true)}>
					<Plus className="mr-1 h-3 w-3"></Plus>
					创建播放列表
				</Button>
			</div>
		</div>
	</Fragment>)}
</div></Fragment>
  )
}
