// @vitest-environment happy-dom
import { afterEach, describe, expect, test, vi } from "vitest"
import { cleanup, render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import type { NodeHostApi, NodeRunEvent, NodeRunResult } from "@xiranite/contract"
import type { BitvData, BitvInput } from "@xiranite/node-bitv/core"
import { NODE_SURFACE_TEST_MODES, NODE_SURFACE_TEST_SPECS } from "@/nodes/shared/nodeSurfaceTestUtils"
import type { NodeSurfaceMode } from "@/nodes/shared/useNodeSurface"
import { Component } from "./Component"
import type { BitvCardState } from "./types"

const surface = vi.hoisted(() => ({ height: 420, width: 720 }))
vi.mock("@/nodes/shared/useNodeSurface", async (original) => { const actual = await original<typeof import("@/nodes/shared/useNodeSurface")>(); return { ...actual, useNodeSurface: () => ({ ref: { current: null }, width: surface.width, height: surface.height, mode: actual.resolveNodeSurfaceMode(surface), density: actual.resolveNodeSurfaceDensity(actual.resolveNodeSurfaceMode(surface)) }) } })
afterEach(() => { cleanup(); vi.clearAllMocks(); Object.assign(surface, NODE_SURFACE_TEST_SPECS.regular) })

describe("native BitV component", () => {
  test.each(NODE_SURFACE_TEST_MODES)("renders the %s surface", (mode) => { Object.assign(surface, NODE_SURFACE_TEST_SPECS[mode]); render(<Component compId="bitv-1" host={createHost({ pathsText: "D:/videos/clip.mp4" })} />); expect(screen.getByText("BitV")).toBeTruthy(); if (mode === "collapsed") expect(screen.getByTestId("bitv-collapsed-view")).toBeTruthy(); else { expect(screen.getByTestId("bitv-path-tree")).toBeTruthy(); expect(screen.getByLabelText("bitv 视频路径")).toBeTruthy() } })
  test("sends directory paths to the native analyzer, starts on the tree, then shows videos after scanning", async () => { const host = createHost({ action: "analyze", pathsText: "D:/videos/Season 1\nD:/videos/clip.mp4" }); render(<Component compId="bitv-1" host={host} />); expect(screen.getByRole("tab", { name: "文件树" }).getAttribute("data-state")).toBe("active"); expect(screen.getByText("Season 1")).toBeTruthy(); expect(screen.getByText("clip.mp4")).toBeTruthy(); await userEvent.setup().click(screen.getByRole("button", { name: "开始分析" })); await waitFor(() => expect(host.runCalls).toHaveLength(1)); expect(host.runCalls[0]?.input.paths).toEqual(["D:/videos/Season 1", "D:/videos/clip.mp4"]); await waitFor(() => expect(screen.getByRole("tab", { name: "视频" }).getAttribute("data-state")).toBe("active")) })
  test("requires confirmation for live classification", async () => { const host = createHost({ action: "classify", pathsText: "D:/videos/clip.mp4", targetPath: "D:/sorted", dryRun: false }); render(<Component compId="bitv-1" host={host} />); const user = userEvent.setup(); await user.click(screen.getByRole("button", { name: "复制并分类" })); expect(host.runCalls).toHaveLength(0); await user.click(screen.getByRole("button", { name: "确认分类" })); await waitFor(() => expect(host.runCalls).toHaveLength(1)); expect(host.runCalls[0]?.input).toEqual(expect.objectContaining({ action: "classify", dryRun: false })) })
})

type TestHost = NodeHostApi<BitvCardState, Partial<BitvCardState>> & { cardState: BitvCardState; runCalls: Array<{ nodeId: string; input: BitvInput }> }
function createHost(initial: BitvCardState): TestHost { const host = { cardState: { ...initial }, runCalls: [], contract: { name: "xiranite.node-host", version: "1", supportedCapabilities: ["contract", "state", "runner", "clipboard"], hasCapability: () => true }, env: { theme: "light", platform: "web" }, state: { getData: () => host.cardState, patchData: (patch: Partial<BitvCardState>) => { host.cardState = { ...host.cardState, ...patch } } }, runner: { run: async <TInput, TData>(nodeId: string, input: TInput, onEvent?: (event: NodeRunEvent) => void): Promise<NodeRunResult<TData>> => { host.runCalls.push({ nodeId, input: input as BitvInput }); onEvent?.({ type: "progress", progress: 50, message: "Analyzing clip.mp4." }); return { success: true, message: "Analyzed 1 video(s).", data: result as TData } } }, clipboard: { readText: async () => "D:/videos/clip.mp4", writeText: async () => undefined }, getData: <T,>() => host.cardState as T, patchData: (_compId: string, patch: Partial<BitvCardState>) => host.state.patchData(patch), listComponents: () => [], updateComponent: () => undefined } satisfies TestHost; return host }
const result: BitvData = { action: "analyze", requestedPaths: ["D:/videos/clip.mp4"], ffprobePath: "ffprobe", dryRun: true, errors: [], operations: [], videos: [{ path: "D:/videos/clip.mp4", relativePath: "clip.mp4", filename: "clip.mp4", durationSeconds: 20, bitrateBps: 2_000_000, bitrateMbps: 2, width: 1920, height: 1080, fps: 30, sizeBytes: 5_000_000, resolution: "1920x1080", bitrateLevel: "5Mbps" }], stats: { totalVideos: 1, totalSizeBytes: 5_000_000, totalDurationSeconds: 20, averageBitrateMbps: 2, bitrateDistribution: { "5Mbps": 1 } } }
