#!/usr/bin/env bun
/**
 * Publish the built node bundles where the **embedded** executor reads them.
 *
 * ADR-0074 §6 says the host binary carries every linked node, and `crates/xiranite-quickjs-executor`
 * expresses that with `include_str!("../bundles/<id>.js")` at the registration site. `include_str!` is a
 * *compile-time* read: the artifact must exist in the source tree before `cargo build` runs, which makes
 * `crates/xiranite-quickjs-executor/bundles/` a checked-in generated directory, not a build cache. This
 * script is the only thing allowed to write it.
 *
 * Input is the manifest `bun run build:node-bundles` produces (`artifacts/node-bundles/manifest.json`), so
 * the universe here is derived, never hand-maintained: a node enters `bundles/` exactly when its host bundle
 * (core `run` plus, for a platform node, `createRuntime`) built successfully.
 *
 * Usage:
 *   bun scripts/embed-node-bundles.ts          write bundles/ from the current manifest
 *   bun scripts/embed-node-bundles.ts --check  exit 1 if the tree and the manifest disagree (gate mode)
 */
import { createHash } from "node:crypto"
import { mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises"
import { dirname, join, resolve } from "node:path"

interface BundleArtifact {
  path: string
  bytes: number
  ok: boolean
  error: string | null
}

interface ManifestNode {
  id: string
  run: string | null
  createRuntime: string | null
  host: BundleArtifact | null
}

interface Manifest {
  generatedAt: string
  scope: string
  nodes: Record<string, ManifestNode>
}

const repoRoot = resolve(import.meta.dirname, "..")
const manifestPath = join(repoRoot, "artifacts", "node-bundles", "manifest.json")
const bundleSourceRoot = join(repoRoot, "artifacts", "node-bundles")
const embedDir = join(repoRoot, "crates", "xiranite-quickjs-executor", "bundles")
const indexName = "index.json"

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex")
}

async function readManifest(): Promise<Manifest> {
  try {
    return JSON.parse(await readFile(manifestPath, "utf8")) as Manifest
  } catch (error) {
    throw new Error(`read ${manifestPath} first with \`bun run build:node-bundles\` (${(error as Error).message})`)
  }
}

/** The nodes that have a usable embedded artifact: a registered `run` and a host bundle that built. */
function embeddable(manifest: Manifest): ManifestNode[] {
  return Object.values(manifest.nodes)
    .filter((node) => node.run !== null && node.host?.ok)
    .sort((left, right) => left.id.localeCompare(right.id))
}

interface PolicyRow {
  id: string
  status: string
  requirements: {
    roots: Array<{ role: string; access: "ReadOnly" | "ReadWrite" }>
    walkTree: boolean
    network: string
    services: string[]
    pendingGrants: string[]
    accessSource: string
  }
}

interface IndexEntry {
  id: string
  file: string
  run: string
  createRuntime: string | null
  bytes: number
  sha256: string
  /** Where the artifact came from, so a stale file is traceable to its producer. */
  source: string
}

/**
 * The registration table for `crates/xiranite-scripted-nodes`, generated from three sources that already
 * exist: the built bundle index (which node answers which export names), `node-runner.generated.ts` (the
 * message a pure node's envelope carries), and the retained-node manifest (which host requirements the node
 * was measured to need). A node is registered only when its policy is **derivable** from those; everything
 * else lands in `UNREGISTERED_BUNDLES` with the reason it is not, so a half-wired host cannot read as done.
 *
 * Today that means `pure-logic` nodes with a wasm-era manifest left to supply the version and the memory
 * ceiling. Root roles, per-node read/write, program names and host-service names are not authored anywhere
 * in the tree for the other nodes — the analyzer's `hostRequirements` describe `platform.ts`, the half that
 * moves into the host — so inventing them here would be a grant with no source behind it.
 */
const GENERATED_HEADER = "// @generated by scripts/embed-node-bundles.ts — do not edit; rerun the script instead.\n"

interface ManifestNodeEntry {
  id: string
  disposition: string
  hostRequirements: string[] | null
}

function constName(id: string): string {
  return id.toUpperCase().replace(/[^A-Z0-9]/g, "_")
}

function escapeRust(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/"/g, "\\\"")
}

/**
 * The programs a node may be allowed to run, or `null` when it still has an unanswered name.
 *
 * Two conditions have to hold at once: every outstanding grant item is about a *program* (a pending
 * `os-native` or `no-host-free-answer` item is a missing service, and no program list answers it), and the
 * grants pass resolved every name it found into a literal with no interpreter among them (`--grants` calls
 * that status `named`; `named-but-interpreter-needs-a-human` and `unresolved-program-name` both stay out).
 */
function resolvedPrograms(
  id: string,
  policy: PolicyRow | undefined,
  grants: Map<string, { status: string; programs: Array<{ name: string; evidence: string; interpreter: boolean }> }>,
): Array<{ name: string; evidence: string }> | null {
  if (policy === undefined || policy.requirements.pendingGrants.length === 0) return null
  if (!policy.requirements.pendingGrants.every((item) => item.startsWith("external-process"))) return null
  const row = grants.get(id)
  return row !== undefined && row.status === "named" ? row.programs : null
}

async function buildRegistration(entries: IndexEntry[]): Promise<{ text: string; registered: string[]; unregistered: Array<[string, string]> }> {
  const targetManifest = JSON.parse(await readFile(join(repoRoot, "docs", "xiranite-target-node-manifest.json"), "utf8")) as {
    nodes: ManifestNodeEntry[]
  }
  const requirements = new Map(targetManifest.nodes.map((node) => [node.id, node.hostRequirements]))
  const runnerTable = await readFile(join(repoRoot, "packages", "runtime", "src", "node-runner.generated.ts"), "utf8")

  // The derived policy, from `bun scripts/derive-scripted-policy.ts --requirements`. Refusing a platform
  // node because "no source describes its grants" was true when this file was written and is not true
  // any more, so the refusal has to be read from the same artifact the grants live in — otherwise this
  // generator is a table of stale claims rather than a gate.
  const policyPath = join(repoRoot, "artifacts", "node-scripted-requirements.json")
  const policyText = await readFile(policyPath, "utf8").catch(() => null)
  const policies = new Map(
    policyText === null
      ? []
      : ((JSON.parse(policyText).nodes as PolicyRow[]).map((row) => [row.id, row] as const)),
  )

  // A `needs-named-grants` refusal is only final until the names exist. `--grants` quotes them out of the
  // node's own sources, so a row whose only outstanding item is `external-process` AND whose names are all
  // literal (status `named`, no interpreter in them) becomes registrable here, with the programs written
  // into the descriptor as the host's allowlist (`proc_operations.rs` refuses anything not listed).
  const grantsText = await readFile(join(repoRoot, "artifacts", "node-scripted-grants.json"), "utf8").catch(() => null)
  const grants = new Map<string, { status: string; programs: Array<{ name: string; evidence: string; interpreter: boolean }> }>(
    grantsText === null
      ? []
      : ((JSON.parse(grantsText).nodes as Array<{ id: string; status: string; programs: Array<{ name: string; evidence: string; interpreter: boolean }> }>)
          .map((row) => [row.id, row] as const)),
  )

  const registered: string[] = []
  const unregistered: Array<[string, string]> = []
  const bodies: string[] = []

  for (const entry of entries) {
    const nodeRequirements = requirements.get(entry.id) ?? null
    const isPlatform = entry.createRuntime !== null
    const policy = policies.get(entry.id) ?? null

    if (isPlatform) {
      if (policyText === null) {
        unregistered.push([entry.id, "platform node, and no artifacts/node-scripted-requirements.json to read grants from (run `bun scripts/derive-scripted-policy.ts --requirements`)"])
        continue
      }
      if (policy === undefined || policy.status === "not-analyzed") {
        unregistered.push([entry.id, `platform node with no row in the requirements artifact (hostRequirements ${JSON.stringify(nodeRequirements)})`])
        continue
      }
      if (policy.status === "needs-named-grants" && resolvedPrograms(entry.id, policy, grants) === null) {
        unregistered.push([entry.id, `platform node whose grants name nothing yet — ${policy.requirements.pendingGrants.join("; ")}`])
        continue
      }
      if (policy.requirements.network !== "Disabled") {
        unregistered.push([entry.id, "platform node reaches the network, and the analyzer proves only that, not which hosts"])
        continue
      }
      if (policy.requirements.services.length > 0) {
        unregistered.push([entry.id, "platform node declares host services this table does not name"])
        continue
      }
    } else if (policy === undefined && policyText !== null) {
      // A pure node still needs its runner-table message below, so it does not have to appear in the
      // requirements artifact; if it does, it must not be a refusal row.
      if (policy.status === "needs-named-grants") {
        unregistered.push([entry.id, `pure node marked unregistrable: ${policy.requirements.pendingGrants.join("; ")}`])
        continue
      }
    }
    if (nodeRequirements === null) {
      unregistered.push([entry.id, "not in the retained-node manifest, so nothing states what the core may reach"])
      continue
    }
    if (!isPlatform && nodeRequirements.join("|") !== "pure-logic") {
      unregistered.push([entry.id, `hostRequirements ${JSON.stringify(nodeRequirements)} need grants no source in this tree describes (root role/access, program names, service names)`])
      continue
    }

    // Version comes from the node's own package (every node carries one); the byte ceiling only exists in
    // the wasm-era `plugins/<id>/manifest.toml`, so a node without that file gets no `.budget()` call at
    // all rather than a number this script made up.
    const packageVersion = /"version"\s*:\s*"([^"]+)"/.exec(
      await readFile(join(repoRoot, "packages", "nodes", entry.id, "package.json"), "utf8").catch(() => ""),
    )?.[1] ?? null
    const manifestPath = join(repoRoot, "plugins", entry.id, "manifest.toml")
    const manifestText = await readFile(manifestPath, "utf8").catch(() => null)
    const version = /version\s*=\s*"([^"]+)"/.exec(manifestText ?? "")?.[1] ?? packageVersion
    const pages = Number(/memory_max_pages\s*=\s*(\d+)/.exec(manifestText ?? "")?.[1] ?? "0")
    if (version === null) {
      unregistered.push([entry.id, "neither plugins/<id>/manifest.toml nor packages/<id>/package.json states a version, so the descriptor would be invented"])
      continue
    }
    const block = new RegExp(`^  ${entry.id}: \\{[\\s\\S]*?^  \\}`, "m").exec(runnerTable)?.[0] ?? ""
    const message = /message:\s*"([^"]*)"/.exec(block)?.[1] ?? null
    if (!isPlatform && message === null) {
      unregistered.push([entry.id, "the generated runner table states no pure message for it"])
      continue
    }
    const upper = constName(entry.id)
    registered.push(entry.id)
    // Built as a list of Rust method calls so a missing ceiling simply emits no call. The first draft put
    // a `//` comment inside the chain, which is not valid Rust in the middle of a const expression — the
    // reason that fact belongs in the doc line above the static instead.
    const chain: string[] = []
    if (isPlatform && policy.requirements.roots.length > 0) {
      chain.push(`.with_roots(&[${policy.requirements.roots
        .map((root) => `RootRequirement { role: ${JSON.stringify(root.role)}, access: RootAccess::${root.access} }`)
        .join(", ")}])`)
    }
    if (isPlatform && policy.requirements.walkTree) chain.push(".walk_tree(true)")
    const programs = isPlatform ? resolvedPrograms(entry.id, policy, grants) : null
    if (programs !== null && programs.length > 0) {
      // `confirm_before_run: false` because these are the tools the node exists to drive (an archive or
      // media binary on its own granted files); the interpreter-shaped and system-state names that would
      // need a gate never reach here — `--grants` keeps them in
      // `named-but-interpreter-needs-a-human`, which this function refuses outright.
      chain.push(`.with_processes(&[${programs
        .map((program) => `ProcessGrant { program: ${JSON.stringify(program.name)}, confirm_before_run: false }`)
        .join(", ")}])`)
    }
    if (Number.isFinite(pages) && pages > 0) chain.push(`.budget(${pages * 65536}, 1)`)
    const ceilingNote = Number.isFinite(pages) && pages > 0 ? "" : ` — no memory ceiling authored in \`plugins/${entry.id}/manifest.toml\`, so none is invented; the ${isPlatform ? "grants come from " : ""}\`accessSource\` in the requirements artifact`
    bodies.push(`/// ${entry.id}: bundled TypeScript, run by the host's QuickJS executor.${ceilingNote}\n${
      `static ${upper}_BUNDLE: &str = include_str!("../../xiranite-quickjs-executor/bundles/${entry.file}");\n` +
      `static ${upper}_SPEC: JsNodeSpec = JsNodeSpec::${isPlatform ? "platform" : "pure"}(\n` +
      `    NodeDescriptor::new(${JSON.stringify(entry.id)}, ${JSON.stringify(version)}, 1)${chain.join("")},\n` +
      `    ${upper}_BUNDLE,\n` +
      `    ${JSON.stringify(entry.run)},\n` +
      (isPlatform ? `    ${JSON.stringify(entry.createRuntime)},\n` : `    ${JSON.stringify(message)},\n`) +
      `);\n` +
      `static ${upper}_NODE: JsNode = JsNode::new(&${upper}_SPEC);\n` +
      `pub static ${upper}_RUNNABLE: &'static dyn BuiltInNode = &${upper}_NODE;\n\n` +
      `xiranite_node_registry::register_node!(${upper}_SPEC.descriptor);\n` +
      `xiranite_node_registry::register_node!(${upper}_RUNNABLE);\n`
    }`)
  }

  const text = `${GENERATED_HEADER}//! Generated by \`bun scripts/embed-node-bundles.ts\`; edit the manifest or the script, not this file.\n\n` +
    `use xiranite_node_registry::{BuiltInNode, NodeDescriptor, NodeLink` +
    (bodies.some((body) => body.includes("RootRequirement")) ? ", RootAccess, RootRequirement" : "") +
    (bodies.some((body) => body.includes("ProcessGrant")) ? ", ProcessGrant" : "") +
    `};\n` +
    `use xiranite_quickjs_executor::{JsNode, JsNodeSpec};\n\n` +
    `${bodies.join("\n")}\n` +
    `/// Every scripted node this crate anchors. A host binary spreads this into its own \`link_nodes!\` list.\n` +
    `/// Both halves of every registered node, in one table, so a host can assemble its registry without\n` +
    `/// naming one static per node. That is the shape AGENTS.md asks for now that the per-node\n` +
    `/// \`register_node!\`/\`link_nodes!\` ceremony is retired: one data table in, one \`NodeRegistry\` out.\n` +
    `pub const SCRIPTED_REGISTRATIONS: &[(&NodeDescriptor, &dyn BuiltInNode)] = &[\n` +
    registered.map((id) => `    (&${constName(id)}_SPEC.descriptor, ${constName(id)}_RUNNABLE),\n`).join("") +
    `];\n\n` +
    `/// The anchors a host binary spreads into its own \`link_nodes!\`, kept for the inventory path.\n` +
    `pub const SCRIPTED_LINKED_NODES: &[NodeLink] = &[\n` +
    registered.map((id) => `    NodeLink::new(${constName(id)}_RUNNABLE),\n`).join("") +
    `];\n\n` +
    `/// The ids this crate can serve today, in the order the index listed them.\n` +
    `pub const SCRIPTED_NODE_IDS: &[&str] = &[${registered.map((id) => `"${id}"`).join(", ")}];\n\n` +
    `/// Embedded bundles that are built but deliberately not registered, each with the reason. A host that\n` +
    `/// reports "migration done" while this list is non-empty is lying about the missing policy, not the code.\n` +
    `pub const UNREGISTERED_BUNDLES: &[(&str, &str)] = &[\n` +
    unregistered.map(([id, reason]) => `    ("${id}", "${escapeRust(reason)}"),\n`).join("") +
    `];\n`

  return { text, registered, unregistered }
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check")
  const manifest = await readManifest()
  const wanted = embeddable(manifest)

  const entries: IndexEntry[] = []
  const writes: Array<{ path: string; text: string }> = []
  for (const node of wanted) {
    const source = join(repoRoot, node.host!.path)
    const text = await readFile(source, "utf8")
    entries.push({
      id: node.id,
      file: `${node.id}.js`,
      run: node.run!,
      createRuntime: node.createRuntime,
      bytes: Buffer.byteLength(text),
      sha256: sha256(text),
      source: node.host!.path,
    })
    writes.push({ path: join(embedDir, `${node.id}.js`), text })
  }

  const index = {
    generatedAt: new Date().toISOString(),
    producer: "scripts/embed-node-bundles.ts",
    manifestGeneratedAt: manifest.generatedAt,
    nodes: entries,
  }
  const indexText = `${JSON.stringify(index, null, 2)}\n`
  const registrationPath = join(repoRoot, "crates", "xiranite-scripted-nodes", "src", "registration.rs")
  const registration = await buildRegistration(entries)

  if (check) {
    const problems: string[] = []
    const current = await readdir(embedDir).catch(() => [])
    const expected = new Set([...entries.map((entry) => entry.file), indexName])
    for (const name of current.filter((name) => !name.startsWith("."))) {
      if (!expected.has(name)) problems.push(`stale file in bundles/: ${name}`)
    }
    for (const entry of entries) {
      const onDisk = await readFile(join(embedDir, entry.file), "utf8").catch(() => null)
      if (onDisk === null) problems.push(`missing embedded bundle: ${entry.file}`)
      else if (sha256(onDisk) !== entry.sha256) problems.push(`embedded bundle is stale vs the manifest: ${entry.file}`)
    }
    const onDiskIndex = await readFile(join(embedDir, indexName), "utf8").catch(() => null)
    if (onDiskIndex === null) problems.push(`missing ${indexName}`)
    else {
      const recorded = ((JSON.parse(onDiskIndex).nodes ?? []) as IndexEntry[]).map((n) => `${n.id}:${n.sha256}`).join(",")
      const fresh = entries.map((n) => `${n.id}:${n.sha256}`).join(",")
      if (recorded !== fresh) problems.push(`${indexName} does not describe the current bundles/`)
    }
    const onDiskRegistration = await readFile(registrationPath, "utf8").catch(() => null)
    if (onDiskRegistration === null) problems.push(`missing ${registrationPath.replace(`${repoRoot}/`, "")}`)
    else if (onDiskRegistration !== registration.text) {
      problems.push(`${registrationPath.replace(`${repoRoot}/`, "")} is stale: rerun bun scripts/embed-node-bundles.ts`)
    }
    if (problems.length > 0) {
      for (const problem of problems) console.error(`FAIL ${problem}`)
      throw new Error(`embed:node-bundles --check found ${problems.length} problem(s).`)
    }
    console.log(
      `OK bundles/: ${entries.length} embedded node bundle(s) matching the manifest; registered ${registration.registered.length}, unregistered ${registration.unregistered.length}.`,
    )
    return
  }

  await mkdir(embedDir, { recursive: true })
  // Drop leftovers from nodes that no longer qualify, so `include_str!` can never read a retired bundle.
  const keep = new Set([...writes.map((write) => write.path), join(embedDir, indexName)])
  for (const name of await readdir(embedDir).catch(() => [])) {
    const path = join(embedDir, name)
    if (!keep.has(path) && !name.startsWith(".")) await rm(path, { force: true })
  }
  for (const write of writes) {
    await writeFile(write.path, write.text)
    // Compare bytes to bytes: the bundles carry non-ASCII text, so a character count would read smaller
    // than the file size and turn a whole write into a false alarm.
    const onDisk = await readFile(write.path)
    if (onDisk.byteLength !== (await stat(write.path)).size || onDisk.toString("utf8") !== write.text) {
      throw new Error(`${write.path} did not land whole`)
    }
  }
  await writeFile(join(embedDir, indexName), indexText)
  await mkdir(dirname(registrationPath), { recursive: true })
  await writeFile(registrationPath, registration.text)

  const totalBytes = entries.reduce((sum, entry) => sum + entry.bytes, 0)
  console.log(
    `registered ${registration.registered.length} scripted node(s) (${registration.registered.join(", ") || "none"}); ` +
      `${registration.unregistered.length} embedded but unregistered, each with a reason`,
  )
  console.log(
    `wrote ${embedDir.replace(`${repoRoot}/`, "")}: ${entries.length} bundle(s), ${(totalBytes / 1048576).toFixed(2)} MiB, index ${indexName}`,
  )
}

await main()
