#!/usr/bin/env bun
/**
 * Generate the host-operation list the capability package is checked against.
 *
 * Why generated: `crates/quickjs-host-protocol` owns the closed operation vocabulary, and the capability
 * surface a node's `platform.ts` calls must cover exactly it. Reading the names out of the Rust source was
 * measured (in `scripts/audit-quickjs-host-ops.ts`'s own preamble) to lie: string scanning returns 31 names
 * for a 30-variant enum because one is a negative-test fixture. So the list comes from the *compiled*
 * `HostOperation::ALL`, via the `print-host-ops` binary, same as the audit does.
 *
 * Usage:
 *   bun scripts/generate-host-capabilities.ts          write the file
 *   bun scripts/generate-host-capabilities.ts --check  fail if it is stale (the delivery gate form)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const repoRoot = process.cwd()
const outFile = join(repoRoot, "packages", "host-capabilities", "src", "operations.generated.ts")
const checkOnly = process.argv.slice(2).includes("--check")

interface HostOpRow {
  name: string
  takes_payload: boolean
  answers_bytes: boolean
}

function inventory(): HostOpRow[] {
  // `--quiet` keeps cargo's own progress out of stdout; the bin prints exactly one JSON document.
  const built = Bun.spawnSync({
    cmd: ["cargo", "run", "--quiet", "-p", "xiranite-quickjs-executor", "--bin", "print-host-ops"],
    cwd: repoRoot,
    stdout: "pipe",
    stderr: "pipe",
    env: { ...process.env, RUSTC_WRAPPER: process.env.RUSTC_WRAPPER ?? "sccache" },
  })
  if (built.exitCode !== 0) {
    throw new Error(`print-host-ops failed (rc=${built.exitCode}): ${built.stderr.toString().slice(0, 800)}`)
  }
  const parsed = JSON.parse(built.stdout.toString()) as { schema_version: number; ops: HostOpRow[] }
  if (parsed.schema_version !== 1) {
    throw new Error(`unsupported host op inventory schema_version ${parsed.schema_version}`)
  }
  if (parsed.ops.length === 0) {
    // An empty vocabulary would generate an empty capability surface and every gate would still be green.
    throw new Error("print-host-ops answered zero operations")
  }
  return parsed.ops
}

const ops = inventory()
const lines: string[] = [
  "// @generated by scripts/generate-host-capabilities.ts — do not edit.",
  "//",
  "// The operation vocabulary is owned by `crates/quickjs-host-protocol` (`HostOperation::ALL`) and read",
  "// from the compiled binary, never scraped from source text. Regenerate with",
  "// `bun scripts/generate-host-capabilities.ts`; the --check form fails when this file is stale.",
  "",
  "/** One host operation name, exactly as the host resolves it. */",
  "export type HostOperationName =",
  ops.map((op) => `  | "${op.name}"`).join("\n"),
  "",
  "/** Every operation the host answers, in the crate's own order. */",
  "export const HOST_OPERATION_NAMES: readonly HostOperationName[] = [",
  ops.map((op) => `  "${op.name}",`).join("\n"),
  "]",
  "",
  "/** Operations whose payload crosses the byte channel rather than the JSON envelope. */",
  "export const BYTE_PAYLOAD_OPERATIONS: readonly HostOperationName[] = [",
  ops
    .filter((op) => op.takes_payload)
    .map((op) => `  "${op.name}",`)
    .join("\n"),
  "]",
  "",
  "/** Operations whose answer is a buffer rather than a JSON document. */",
  "export const BYTE_ANSWER_OPERATIONS: readonly HostOperationName[] = [",
  ops
    .filter((op) => op.answers_bytes)
    .map((op) => `  "${op.name}",`)
    .join("\n"),
  "]",
  "",
]
const generated = lines.join("\n")

if (checkOnly) {
  if (!existsSync(outFile)) {
    console.error(`generate-host-capabilities --check: ${outFile} does not exist — run bun scripts/generate-host-capabilities.ts`)
    process.exit(1)
  }
  const current = readFileSync(outFile, "utf8")
  if (current !== generated) {
    console.error(
      `generate-host-capabilities --check: ${outFile} is stale against the compiled HostOperation::ALL (${ops.length} ops) — run bun scripts/generate-host-capabilities.ts`,
    )
    process.exit(1)
  }
  console.log(`generate-host-capabilities --check: OK (${ops.length} operations)`)
} else {
  writeFileSync(outFile, generated)
  console.log(`generate:host-capabilities: wrote ${ops.length} operations to ${outFile}`)
}
