#!/usr/bin/env bun
import { access, readdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import * as ts from "typescript"

interface NodePackageJson {
  name?: string
  exports?: Record<string, unknown>
}

interface NodePackage {
  id: string
  packageName: string
  hasPlatform: boolean
  hasAppEntry: boolean
  def: NodeDefLiteral
}

interface NodeDefLiteral {
  id: string
  name: string
  version: string
  category: string
  description: string
  icon: string
  keywords?: string[]
}

type RuntimeOverride =
  | { kind?: "platform"; run?: string; runtime?: string }
  | { kind: "pure"; run: string; message: string }

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const nodesRoot = join(repoRoot, "packages", "nodes")

const runtimeOverrides: Record<string, RuntimeOverride> = {
  enginev: { run: "runEngineV", runtime: "createNodeEngineVRuntime" },
  linedup: { kind: "pure", run: "filterLines", message: "Filtered lines." },
}

const header = "// Generated by scripts/generate-node-registries.ts. Do not edit by hand.\n\n"

const nodes = await discoverNodePackages()

await writeIfChanged(
  join(repoRoot, "packages", "runtime", "src", "node-runner.generated.ts"),
  generateRuntimeRegistry(nodes),
)
await writeIfChanged(
  join(repoRoot, "src", "components", "modules", "packageModules.generated.ts"),
  generatePackageModuleRegistry(nodes),
)

console.log(`Generated node registries for ${nodes.length} node package(s).`)

async function discoverNodePackages(): Promise<NodePackage[]> {
  const packages: NodePackage[] = []
  for (const entry of await readdir(nodesRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue

    const packagePath = join(nodesRoot, entry.name, "package.json")
    const pkg = JSON.parse(await readFile(packagePath, "utf8")) as NodePackageJson
    if (!pkg.name?.startsWith("@xiranite/node-")) continue

    const def = await readNodeDef(join(nodesRoot, entry.name, "src", "index.ts"))
    if (def.id !== entry.name) {
      throw new Error(`Node package ${pkg.name} def.id (${def.id}) must match directory id (${entry.name}).`)
    }

    packages.push({
      id: entry.name,
      packageName: pkg.name,
      hasPlatform: Boolean(pkg.exports?.["./platform"]),
      hasAppEntry: await hasCompleteAppEntry(entry.name),
      def,
    })
  }

  return packages.sort((a, b) => a.id.localeCompare(b.id))
}

async function readNodeDef(indexPath: string): Promise<NodeDefLiteral> {
  const sourceText = await readFile(indexPath, "utf8")
  const source = ts.createSourceFile(indexPath, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  let found: NodeDefLiteral | undefined

  function visit(node: ts.Node) {
    if (found) return
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.name.text === "def" && node.initializer) {
      const object = objectLiteralFromExpression(node.initializer)
      const def = object ? parseNodeDefLiteral(object) : undefined
      if (def) found = def
    }
    if (ts.isPropertyAssignment(node) && propertyName(node.name) === "def") {
      const object = objectLiteralFromExpression(node.initializer)
      const def = object ? parseNodeDefLiteral(object) : undefined
      if (def) found = def
    }
    ts.forEachChild(node, visit)
  }

  visit(source)
  if (!found) throw new Error(`Unable to find NodeEntry def literal in ${indexPath}.`)
  return found
}

function parseNodeDefLiteral(object: ts.ObjectLiteralExpression): NodeDefLiteral | undefined {
  const strings = new Map<string, string>()
  let keywords: string[] | undefined

  for (const property of object.properties) {
    if (!ts.isPropertyAssignment(property)) continue
    const name = propertyName(property.name)
    if (!name) continue

    const value = property.initializer
    if (ts.isStringLiteralLike(value)) {
      strings.set(name, value.text)
    } else if (name === "keywords" && ts.isArrayLiteralExpression(value)) {
      keywords = value.elements.map((element) => ts.isStringLiteralLike(element) ? element.text : undefined)
        .filter((item): item is string => typeof item === "string")
    }
  }

  const required = ["id", "name", "version", "category", "description", "icon"] as const
  if (!required.every((key) => strings.has(key))) return undefined

  return {
    id: strings.get("id")!,
    name: strings.get("name")!,
    version: strings.get("version")!,
    category: strings.get("category")!,
    description: strings.get("description")!,
    icon: strings.get("icon")!,
    ...(keywords?.length ? { keywords } : {}),
  }
}

function objectLiteralFromExpression(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
  if (ts.isObjectLiteralExpression(expression)) return expression
  if (ts.isSatisfiesExpression(expression) || ts.isAsExpression(expression)) return objectLiteralFromExpression(expression.expression)
  if (ts.isParenthesizedExpression(expression)) return objectLiteralFromExpression(expression.expression)
  return undefined
}

function generateRuntimeRegistry(nodes: NodePackage[]): string {
  const lines = nodes.map((node) => `  ${objectKey(node.id)}: ${runtimeSpec(node)},`)
  return `${header}import type { NodeSpec } from "./node-runner.js"

export const generatedNodeSpecs: Record<string, NodeSpec> = {
${lines.join("\n")}
}

export const generatedNodeIds = Object.keys(generatedNodeSpecs).sort()
`
}

function runtimeSpec(node: NodePackage): string {
  const override = runtimeOverrides[node.id]
  if (override?.kind === "pure") {
    return `{
    loadCore: () => import(${stringLiteral(`${node.packageName}/core`)}),
    run: ${stringLiteral(override.run)},
    message: ${stringLiteral(override.message)},
  }`
  }

  if (!node.hasPlatform) {
    throw new Error(`Node package ${node.packageName} has no ./platform export. Add a runtime override if it is intentionally pure.`)
  }

  const pascalName = pascalCase(node.id)
  const run = override?.run ?? `run${pascalName}`
  const runtime = override?.runtime ?? `createNode${pascalName}Runtime`
  return `{
    loadCore: () => import(${stringLiteral(`${node.packageName}/core`)}),
    run: ${stringLiteral(run)},
    loadPlatform: () => import(${stringLiteral(`${node.packageName}/platform`)}),
    createRuntime: ${stringLiteral(runtime)},
  }`
}

function generatePackageModuleRegistry(nodes: NodePackage[]): string {
  const modules = nodes.map((node) => `  ${nodeDefLiteral(node.def)},`).join("\n")
  const loaders = nodes
    .map((node) => {
      const target = node.hasAppEntry ? `@/nodes/${node.id}/entry` : node.packageName
      const entryType = node.hasAppEntry ? "AppNodeEntry" : "NodeEntry"
      return `  ${objectKey(node.id)}: () => import(${stringLiteral(target)}) as Promise<{ default: ${entryType} }>,`
    })
    .join("\n")

  return `${header}import type { AppNodeEntry, NodeDef, NodeEntry } from "@xiranite/contract"

export const PACKAGE_MODULES = [
${modules}
] satisfies NodeDef[]

export const packageModuleLoaders = {
${loaders}
} satisfies Partial<Record<string, () => Promise<{ default: NodeEntry | AppNodeEntry }>>>
`
}

async function writeIfChanged(filePath: string, nextContent: string): Promise<void> {
  const current = await readFile(filePath, "utf8").catch(() => undefined)
  if (current === nextContent) return

  await writeFile(filePath, nextContent, "utf8")
  console.log(`updated ${filePath}`)
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath)
    return true
  } catch {
    return false
  }
}

async function hasCompleteAppEntry(nodeId: string): Promise<boolean> {
  return await fileExists(join(repoRoot, "src", "nodes", nodeId, "entry.ts"))
    && await fileExists(join(repoRoot, "src", "nodes", nodeId, "Component.tsx"))
}

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("")
}

function nodeDefLiteral(def: NodeDefLiteral): string {
  const lines = [
    `id: ${stringLiteral(def.id)}`,
    `name: ${stringLiteral(def.name)}`,
    `version: ${stringLiteral(def.version)}`,
    `category: ${stringLiteral(def.category)}`,
    `description: ${stringLiteral(def.description)}`,
    `icon: ${stringLiteral(def.icon)}`,
  ]
  if (def.keywords?.length) {
    lines.push(`keywords: [${def.keywords.map(stringLiteral).join(", ")}]`)
  }
  return `{ ${lines.join(", ")} }`
}

function propertyName(name: ts.PropertyName): string | undefined {
  if (ts.isIdentifier(name) || ts.isStringLiteralLike(name) || ts.isNumericLiteral(name)) return name.text
  return undefined
}

function objectKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : stringLiteral(value)
}

function stringLiteral(value: string): string {
  return JSON.stringify(value)
}
