/**
 * @migrated-from src/lib/components/ui/alert-dialog/alert-dialog-portal.svelte
 * @source-hash sha256:053b95e4d39547f6e0b9028f8889a877233092be9f7d5cfda4f302b38f3a92c2
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { AlertDialog as AlertDialogPrimitive } from 'bits-ui';

export function AlertDialogPortal(props: AlertDialogPrimitive.PortalProps) {
  const { ...restProps } = props
  return (
    <Fragment>

<AlertDialogPrimitive.Portal {...restProps}></AlertDialogPrimitive.Portal></Fragment>
  )
}
