import { useCallback, useMemo, useState, type ReactNode } from "react"
import type { NodeLocalFilesCapability } from "@xiranite/contract"
import type { Column, RowSelectionState, SortingState, Updater } from "@tanstack/react-table"
import { ArrowDown, ArrowUp, CaseSensitive, CheckCheck, ChevronRight, Eraser, Eye, EyeOff, FileImage, FilePlus, FileSpreadsheet, FileType, Folder, FolderPlus, FolderTree, Plus, Rows3, Trash2, Weight } from "lucide-react"
import { DataTable } from "@/components/niko-table/core/data-table"
import { DataTableRoot } from "@/components/niko-table/core/data-table-root"
import { DataTableBody, DataTableHeader } from "@/components/niko-table/core/data-table-structure"
import { DataTableVirtualizedBody, DataTableVirtualizedHeader } from "@/components/niko-table/core/data-table-virtualized-structure"
import type { DataTableColumnDef } from "@/components/niko-table/types"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { ContextMenuItem } from "@/components/ui/context-menu"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"
import { ScrollArea } from "@/components/ui/scroll-area"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"
import { useLocalFileDrop } from "@/nodes/shared/useLocalFileDrop"
import { LOCAL_IMAGE_EXTENSIONS, LocalImagePreview } from "@/nodes/shared/LocalImagePreview"
import type { XlchemyData } from "@xiranite/node-xlchemy/core"
import type { XlchemyCardState } from "./types"

type ViewMode = "list" | "tree"
type SortField = "name" | "ext" | "size" | "dir"
type FileEntry = { path: string; name: string; ext: string; dir: string; size: number }
type TreeNode = { id: string; name: string; path: string; kind: "folder" | "file"; size: number; count: number; entry?: FileEntry; children: TreeNode[] }
type TreeModel = { rootLabel: string; nodes: TreeNode[] }
const VIRTUALIZE_TABLE_AT = 200
const XLCHEMY_INPUT_EXTENSIONS = [...LOCAL_IMAGE_EXTENSIONS, ".psd", ".psb", ".clip"]

export function InputFilesWorkbench(props: { clipboardAction?: ReactNode; data: XlchemyCardState; disabled?: boolean; footer: ReactNode; getFileUrl?: (path: string) => string; result: XlchemyData | null; onCopyPath: (path: string) => void; onPatch: (patch: Partial<XlchemyCardState>) => void; onPickFiles: () => Promise<string[]>; onPickDirectory: () => Promise<string | undefined>; onImportEfu: () => Promise<void>; onListFiles?: (path: string, options?: { recursive?: boolean; extensions?: string[]; limit?: number }) => Promise<Array<{ path: string; isDirectory: boolean; sizeBytes: number }>>; onSubscribeDrops?: NodeLocalFilesCapability["subscribeDrops"] }) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const [discoveredSizes, setDiscoveredSizes] = useState<Map<string, number>>(new Map())
  const entries = useMemo(() => deriveEntries(props.data.pathsText, props.result, discoveredSizes), [discoveredSizes, props.data.pathsText, props.result])
  const selected = useMemo(() => new Set(props.data.selectedPaths ?? entries.map((entry) => entry.path)), [props.data.selectedPaths, entries])
  const viewMode = props.data.inputViewMode ?? "tree", sortField = props.data.inputSortField ?? "name", sortDesc = props.data.inputSortDesc ?? false
  const sorted = useMemo(() => props.data.disableSorting ? entries : [...entries].sort((a, b) => compareEntries(a, b, sortField) * (sortDesc ? -1 : 1)), [entries, props.data.disableSorting, sortDesc, sortField])
  const tree = useMemo(() => viewMode === "tree" ? buildTree(sorted) : { rootLabel: "", nodes: [] }, [sorted, viewMode]), totalBytes = entries.reduce((sum, entry) => sum + entry.size, 0)
  const fileDrop = useLocalFileDrop({ disabled: props.disabled, subscribeDrops: props.onSubscribeDrops, onDropPaths: (paths) => void addLocalPaths(paths) })

  function togglePath(path: string, checked: boolean) { const next = new Set(selected); if (checked) next.add(path); else next.delete(path); props.onPatch({ selectedPaths: [...next] }) }
  function togglePaths(paths: string[], checked: boolean) { const next = new Set(selected); for (const path of paths) { if (checked) next.add(path); else next.delete(path) } props.onPatch({ selectedPaths: [...next] }) }
  function removeSelected() { props.onPatch({ pathsText: entries.filter((entry) => !selected.has(entry.path)).map((entry) => entry.path).join("\n"), selectedPaths: [] }) }
  function addPaths(paths: string[]) { const accepted = paths.filter((path) => inputFormatEnabled(path, props.data.excludedFormatsText)); if (!accepted.length) return; const next = [...new Set([...splitLines(props.data.pathsText), ...accepted])]; props.onPatch({ pathsText: next.join("\n"), selectedPaths: next }) }
  function addListed(entries: Array<{ path: string; isDirectory: boolean; sizeBytes: number }>, fallback: string[]) { const candidates = entries.filter((entry) => !entry.isDirectory), files = candidates.filter((entry) => inputFormatEnabled(entry.path, props.data.excludedFormatsText)); if (files.length) setDiscoveredSizes((current) => new Map([...current, ...files.map((entry) => [entry.path, entry.sizeBytes] as const)])); addPaths(candidates.length ? files.map((entry) => entry.path) : fallback) }
  async function addLocalPaths(paths: string[]) { if (!paths.length) return; if (!props.onListFiles) { addPaths(paths); return } const listed = (await Promise.all(paths.map((path) => props.onListFiles!(path, { recursive: props.data.recursive !== false, extensions: XLCHEMY_INPUT_EXTENSIONS, limit: 10_000 }).catch(() => [])))).flat(); addListed(listed, paths) }
  async function pickFiles() { const paths = await props.onPickFiles(); if (!paths.length) return; if (!props.onListFiles) { addPaths(paths); return } const entries = (await Promise.all(paths.map((path) => props.onListFiles!(path, { extensions: XLCHEMY_INPUT_EXTENSIONS, limit: 1 }).catch(() => [])))).flat(); addListed(entries, paths) }
  async function pickDirectory() { const path = await props.onPickDirectory(); if (!path) return; const files = await props.onListFiles?.(path, { recursive: props.data.recursive !== false, extensions: XLCHEMY_INPUT_EXTENSIONS, limit: 10_000 }); addListed(files ?? [], [path]) }
  function selectAll(checked: boolean) { props.onPatch({ selectedPaths: checked ? entries.map((entry) => entry.path) : [] }) }

  return <div className="flex min-h-0 flex-1 flex-col gap-2" data-testid="xlchemy-input-workbench">
    <div className="flex flex-wrap items-center gap-2 rounded-md border bg-card px-2.5 py-2">
      <div className="flex items-center gap-1"><AddInputMenu disabled={props.disabled} onFiles={() => void pickFiles()} onFolder={() => void pickDirectory()} onImportEfu={() => void props.onImportEfu()} />{props.clipboardAction}<IconButton icon={Eraser} label="清空" disabled={!entries.length || props.disabled} onClick={() => props.onPatch({ pathsText: "", selectedPaths: [] })} /><IconButton icon={CheckCheck} label="移除已完成" disabled={!props.result?.files.length || props.disabled} onClick={() => { const done = new Set(props.result?.files.filter((file) => file.status === "converted").map((file) => file.sourcePath)); props.onPatch({ pathsText: entries.filter((entry) => !done.has(entry.path)).map((entry) => entry.path).join("\n") }) }} /><IconButton icon={Trash2} label="删除已选" disabled={!selected.size || props.disabled} onClick={removeSelected} /><IconButton icon={props.data.showOriginalPreview ? Eye : EyeOff} label={props.data.showOriginalPreview ? "隐藏预览" : "显示预览"} onClick={() => props.onPatch({ showOriginalPreview: !props.data.showOriginalPreview })} /></div>
      <div className="ml-auto flex flex-wrap items-center justify-end gap-1.5">{totalBytes > 0 && <Badge variant="outline">{formatBytes(totalBytes)}</Badge>}{selected.size > 0 && <Badge variant="outline">已选 {selected.size}</Badge>}<SortFieldMenu value={sortField} onChange={(inputSortField) => props.onPatch({ inputSortField })} /><IconButton icon={sortDesc ? ArrowDown : ArrowUp} label={sortDesc ? "降序" : "升序"} onClick={() => props.onPatch({ inputSortDesc: !sortDesc })} /><ToggleGroup type="single" value={viewMode} variant="outline" size="sm" className="w-auto shrink-0" onValueChange={(value) => value && props.onPatch({ inputViewMode: value as ViewMode })}><ToggleGroupItem value="list" aria-label="列表视图"><Rows3 /></ToggleGroupItem><ToggleGroupItem value="tree" aria-label="文件树视图"><FolderTree /></ToggleGroupItem></ToggleGroup></div>
    </div>
    <div {...fileDrop.targetProps} className={cn("overflow-hidden rounded-md border bg-card", entries.length ? "min-h-0 flex-1" : "shrink-0")}>{entries.length ? viewMode === "list" ? <FileTable entries={entries} selected={selected} sortingDisabled={props.data.disableSorting ?? false} sortDesc={sortDesc} sortField={sortField} showPreview={props.data.showOriginalPreview ?? false} getFileUrl={props.getFileUrl} onCopyPath={props.onCopyPath} onSelectionChange={(selectedPaths) => props.onPatch({ selectedPaths })} onSortingChange={(inputSortField, inputSortDesc) => props.onPatch({ inputSortField, inputSortDesc })} onRemove={(path) => props.onPatch({ pathsText: entries.filter((entry) => entry.path !== path).map((entry) => entry.path).join("\n"), selectedPaths: [...selected].filter((item) => item !== path) })} /> : <FileTree model={tree} selected={selected} expanded={expanded} showPreview={props.data.showOriginalPreview ?? false} getFileUrl={props.getFileUrl} onExpanded={setExpanded} onSelect={togglePath} onSelectMany={togglePaths} onSelectAll={selectAll} /> : <EmptyInput onFiles={() => void pickFiles()} onFolder={() => void pickDirectory()} />}</div>
    <div className="shrink-0" data-testid="xlchemy-run-footer">{props.footer}</div>
  </div>
}

function FileTable(props: { entries: FileEntry[]; selected: Set<string>; sortingDisabled: boolean; sortDesc: boolean; sortField: SortField; showPreview: boolean; getFileUrl?: (path: string) => string; onCopyPath: (path: string) => void; onSelectionChange: (paths: string[]) => void; onSortingChange: (field: SortField, desc: boolean) => void; onRemove: (path: string) => void }) {
  const virtualized = props.entries.length >= VIRTUALIZE_TABLE_AT
  const sorting = useMemo<SortingState>(() => props.sortingDisabled ? [] : [{ id: props.sortField, desc: props.sortDesc }], [props.sortDesc, props.sortField, props.sortingDisabled])
  const rowSelection = useMemo<RowSelectionState>(() => Object.fromEntries(props.entries.filter((entry) => props.selected.has(entry.path)).map((entry) => [entry.path, true])), [props.entries, props.selected])
  const columns = useMemo<DataTableColumnDef<FileEntry>[]>(() => [
    { id: "select", size: 40, enableSorting: false, enableHiding: false, header: ({ table }) => <Checkbox aria-label="选择全部输入" checked={table.getIsAllRowsSelected() ? true : table.getIsSomeRowsSelected() ? "indeterminate" : false} onCheckedChange={(checked) => table.toggleAllRowsSelected(checked === true)} />, cell: ({ row }) => <Checkbox aria-label={`选择 ${row.original.name}`} checked={row.getIsSelected()} onCheckedChange={(checked) => row.toggleSelected(checked === true)} /> },
    { accessorKey: "name", header: ({ column }) => <NikoSortHeader column={column} label="名称" />, cell: ({ row }) => <div className="flex min-w-0 items-center gap-3"><LocalImagePreview path={row.original.path} enabled={props.showPreview} getFileUrl={props.getFileUrl} className="size-9" /><div className="min-w-0"><div className="truncate text-xs font-medium" title={row.original.path}>{row.original.name}</div><div className="text-[11px] text-muted-foreground">{row.original.ext ? `.${row.original.ext}` : "file"}</div></div></div>, meta: { label: "名称" } },
    { accessorKey: "ext", size: 80, header: ({ column }) => <NikoSortHeader column={column} label="扩展名" />, cell: ({ row }) => <Badge variant="outline" className="uppercase">{row.original.ext || "-"}</Badge>, meta: { label: "扩展名" } },
    { accessorKey: "size", size: 96, header: ({ column }) => <NikoSortHeader column={column} label="大小" align="right" />, cell: ({ row }) => <div className="text-right text-xs tabular-nums text-muted-foreground">{formatBytes(row.original.size)}</div>, meta: { label: "大小" } },
    { accessorKey: "dir", header: ({ column }) => <NikoSortHeader column={column} label="目录" />, cell: ({ row }) => <div className="max-w-56 truncate text-xs text-muted-foreground" title={row.original.dir}>{row.original.dir}</div>, meta: { label: "目录" } },
  ], [props.getFileUrl, props.showPreview])
  const handleSelection = useCallback((updater: Updater<RowSelectionState>) => { const next = typeof updater === "function" ? updater(rowSelection) : updater; props.onSelectionChange(Object.keys(next).filter((path) => next[path])) }, [props.onSelectionChange, rowSelection])
  const handleSorting = useCallback((updater: Updater<SortingState>) => { const next = typeof updater === "function" ? updater(sorting) : updater, first = next[0]; if (first && isSortField(first.id)) props.onSortingChange(first.id, first.desc) }, [props.onSortingChange, sorting])
  const renderContextMenu = useCallback((entry: FileEntry) => <><ContextMenuItem onSelect={() => props.onCopyPath(entry.path)}>复制路径</ContextMenuItem><ContextMenuItem variant="destructive" onSelect={() => props.onRemove(entry.path)}>从队列移除</ContextMenuItem></>, [props.onCopyPath, props.onRemove])
  return <div className="h-full" data-testid="xlchemy-niko-table" data-virtualized={virtualized ? "true" : "false"}><DataTableRoot<FileEntry, unknown> className="h-full space-y-0" columns={columns} data={props.entries} config={{ enableFilters: false, enablePagination: false, enableRowSelection: true, enableSorting: !props.sortingDisabled, enableMultiSort: false }} getRowId={(entry) => entry.path} state={{ rowSelection, sorting }} onRowSelectionChange={handleSelection} onSortingChange={handleSorting}><DataTable className="h-full rounded-none border-0" height="100%">{virtualized ? <><DataTableVirtualizedHeader /><DataTableVirtualizedBody estimateSize={53} overscan={12} renderRowContextMenu={renderContextMenu} /></> : <><DataTableHeader /><DataTableBody renderRowContextMenu={renderContextMenu} /></>}</DataTable></DataTableRoot></div>
}

function NikoSortHeader({ align, column, label }: { align?: "left" | "right"; column: Column<FileEntry, unknown>; label: string }) { const state = column.getIsSorted(); return <button type="button" className={cn("flex w-full min-w-0 items-center gap-1.5", align === "right" ? "justify-end text-right" : "text-left")} aria-label={`按${label}排序`} onClick={column.getToggleSortingHandler()}><span className="truncate">{label}</span>{state === "desc" ? <ArrowDown /> : state === "asc" ? <ArrowUp /> : null}</button> }

function FileTree(props: { model: TreeModel; selected: Set<string>; expanded: Set<string>; showPreview: boolean; getFileUrl?: (path: string) => string; onExpanded: (value: Set<string>) => void; onSelect: (path: string, checked: boolean) => void; onSelectMany: (paths: string[], checked: boolean) => void; onSelectAll: (checked: boolean) => void }) { const visible = props.model.nodes.flatMap(collectFiles), selectedCount = visible.filter((entry) => props.selected.has(entry.path)).length, all = visible.length > 0 && selectedCount === visible.length, partial = selectedCount > 0 && !all; return <ScrollArea className="h-full"><div className="py-1">{props.model.rootLabel && <div className="flex items-center gap-2 border-b px-3 py-2 text-[11px] text-muted-foreground"><Checkbox aria-label="选择文件树全部输入" checked={all ? true : partial ? "indeterminate" : false} onCheckedChange={(value) => props.onSelectAll(value === true)} /><span className="truncate">{props.model.rootLabel}</span>{selectedCount > 0 && <span className="ml-auto text-[10px]">已选 {selectedCount}</span>}</div>}{props.model.nodes.map((node) => <TreeRow key={node.id} node={node} depth={0} {...props} />)}</div></ScrollArea> }
function TreeRow(props: { node: TreeNode; depth: number; selected: Set<string>; expanded: Set<string>; showPreview: boolean; getFileUrl?: (path: string) => string; onExpanded: (value: Set<string>) => void; onSelect: (path: string, checked: boolean) => void; onSelectMany: (paths: string[], checked: boolean) => void }) { const files = collectFiles(props.node), checked = files.length > 0 && files.every((file) => props.selected.has(file.path)), partial = !checked && files.some((file) => props.selected.has(file.path)), open = props.expanded.has(props.node.id) || props.depth === 0; if (props.node.kind === "file" && props.node.entry) return <div className="flex items-center gap-2 px-3 py-2 hover:bg-muted/50" style={{ paddingLeft: 12 + props.depth * 16 }}><Checkbox aria-label={`选择 ${props.node.name}`} checked={props.selected.has(props.node.path)} onCheckedChange={(value) => props.onSelect(props.node.path, value === true)} /><LocalImagePreview path={props.node.entry.path} enabled={props.showPreview} getFileUrl={props.getFileUrl} className="size-7" /><div className="min-w-0 flex-1"><div className="truncate text-xs">{props.node.name}</div><div className="text-[10px] text-muted-foreground">{props.node.entry.ext ? `.${props.node.entry.ext}` : "file"}</div></div><Badge variant="outline">{props.node.entry.ext || "-"}</Badge><span className="w-16 text-right text-xs tabular-nums text-muted-foreground">{formatBytes(props.node.size)}</span></div>; return <><div className="flex items-center gap-2 px-3 py-2 hover:bg-muted/50" style={{ paddingLeft: 12 + props.depth * 16 }}><Checkbox aria-label={`选择文件夹 ${props.node.name}`} checked={checked ? true : partial ? "indeterminate" : false} onCheckedChange={(value) => props.onSelectMany(files.map((file) => file.path), value === true)} /><button type="button" className="flex min-w-0 flex-1 items-center gap-2 text-left" onClick={() => { const next = new Set(props.expanded); if (open) next.delete(props.node.id); else next.add(props.node.id); props.onExpanded(next) }}><ChevronRight className={cn("size-4 text-muted-foreground transition-transform", open && "rotate-90")} /><Folder className="size-4 text-muted-foreground" /><span className="truncate text-xs font-medium">{props.node.name}</span></button><span className="text-[10px] text-muted-foreground">{props.node.count}</span><span className="w-16 text-right text-xs tabular-nums text-muted-foreground">{formatBytes(props.node.size)}</span></div>{open && props.node.children.map((child) => <TreeRow key={child.id} {...props} node={child} depth={props.depth + 1} />)}</> }
function EmptyInput({ onFiles, onFolder }: { onFiles: () => void; onFolder: () => void }) {
  return <Empty className="relative min-h-[220px] gap-4 rounded-none border-0 p-0 px-6 md:p-0 md:px-6" data-testid="xlchemy-input-empty">
      <EmptyMedia className="mb-0 size-14 rounded-md border bg-card" variant="icon"><FileImage className="text-primary" /></EmptyMedia>
      <EmptyHeader className="gap-1">
        <EmptyTitle className="text-sm font-semibold">添加待转换图片</EmptyTitle>
        <EmptyDescription className="max-w-[26rem] text-xs leading-5">支持拖入文件或文件夹。这里会保留预览、筛选、排序和批量选择，适合先整理再开始转换。</EmptyDescription>
      </EmptyHeader>
      <EmptyContent className="max-w-none flex-row flex-wrap justify-center gap-2">
        <Button size="sm" variant="default" onClick={onFiles}><FilePlus data-icon="inline-start" />添加文件</Button>
        <Button size="sm" variant="outline" onClick={onFolder}><FolderPlus data-icon="inline-start" />添加文件夹</Button>
      </EmptyContent>
      <span aria-hidden="true" className="absolute left-2 top-2 size-3 border-l-2 border-t-2 border-primary/50" /><span aria-hidden="true" className="absolute right-2 top-2 size-3 border-r-2 border-t-2 border-primary/50" /><span aria-hidden="true" className="absolute bottom-2 left-2 size-3 border-b-2 border-l-2 border-primary/50" /><span aria-hidden="true" className="absolute bottom-2 right-2 size-3 border-b-2 border-r-2 border-primary/50" />
  </Empty>
}
function IconButton({ disabled, icon: Icon, label, onClick }: { disabled?: boolean; icon: typeof FilePlus; label: string; onClick: () => void }) { return <Tooltip><TooltipTrigger asChild><Button aria-label={label} disabled={disabled} size="icon-sm" variant="ghost" onClick={onClick}><Icon /></Button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip> }

function AddInputMenu({ disabled, onFiles, onFolder, onImportEfu }: { disabled?: boolean; onFiles: () => void; onFolder: () => void; onImportEfu: () => void }) {
  return <DropdownMenu><Tooltip><TooltipTrigger asChild><DropdownMenuTrigger asChild><Button aria-label="添加输入" disabled={disabled} size="icon-sm" variant="ghost"><Plus /></Button></DropdownMenuTrigger></TooltipTrigger><TooltipContent>添加输入</TooltipContent></Tooltip><DropdownMenuContent align="start" className="min-w-44"><DropdownMenuItem onSelect={onFiles}><FilePlus />添加文件</DropdownMenuItem><DropdownMenuItem onSelect={onFolder}><FolderPlus />添加文件夹</DropdownMenuItem><DropdownMenuItem onSelect={onImportEfu}><FileSpreadsheet />导入 EFU 文件列表</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
}

function SortFieldMenu({ onChange, value }: { onChange: (value: SortField) => void; value: SortField }) {
  const CurrentIcon = value === "name" ? CaseSensitive : value === "ext" ? FileType : value === "size" ? Weight : Folder
  const currentLabel = value === "name" ? "名称" : value === "ext" ? "扩展名" : value === "size" ? "大小" : "目录"
  return <DropdownMenu><Tooltip><TooltipTrigger asChild><DropdownMenuTrigger asChild><Button aria-label="排序方式" size="icon-sm" variant="ghost"><CurrentIcon /></Button></DropdownMenuTrigger></TooltipTrigger><TooltipContent>排序方式：{currentLabel}</TooltipContent></Tooltip><DropdownMenuContent align="end" className="min-w-40"><DropdownMenuRadioGroup value={value} onValueChange={(next) => isSortField(next) && onChange(next)}><DropdownMenuRadioItem value="name"><CaseSensitive />名称</DropdownMenuRadioItem><DropdownMenuRadioItem value="ext"><FileType />扩展名</DropdownMenuRadioItem><DropdownMenuRadioItem value="size"><Weight />大小</DropdownMenuRadioItem><DropdownMenuRadioItem value="dir"><Folder />目录</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu>
}

function deriveEntries(pathsText: string | undefined, result: XlchemyData | null, discoveredSizes: ReadonlyMap<string, number>): FileEntry[] { const sizes = new Map(discoveredSizes); for (const file of result?.files ?? []) sizes.set(file.sourcePath, file.sourceBytes ?? sizes.get(file.sourcePath) ?? 0); return [...new Set([...(result?.files.map((file) => file.sourcePath) ?? []), ...splitLines(pathsText)])].map((path) => { const normalized = path.replace(/\\/g, "/"), name = normalized.split("/").at(-1) ?? path, dot = name.lastIndexOf("."), ext = dot > 0 ? name.slice(dot + 1).toLowerCase() : "", dir = normalized.includes("/") ? normalized.slice(0, normalized.lastIndexOf("/")) : ""; return { path, name, ext, dir, size: sizes.get(path) ?? 0 } }) }
function compareEntries(a: FileEntry, b: FileEntry, field: SortField) { if (field === "size") return a.size - b.size || a.name.localeCompare(b.name); return String(a[field]).localeCompare(String(b[field]), undefined, { numeric: true, sensitivity: "base" }) }
function isSortField(value: string): value is SortField { return value === "name" || value === "ext" || value === "size" || value === "dir" }
function buildTree(entries: FileEntry[]): TreeModel { const rootLabel = commonRoot(entries), root: TreeNode = { id: "root", name: rootLabel || "输入", path: "", kind: "folder", size: 0, count: 0, children: [] }; const prefix = commonRootSegments(entries); for (const entry of entries) { const allParts = entry.path.replace(/\\/g, "/").split("/").filter(Boolean), fileName = allParts.pop() ?? entry.name, parts = allParts.slice(prefix.length); let parent = root; for (const part of parts) { let folder = parent.children.find((child) => child.kind === "folder" && child.name === part); if (!folder) { folder = { id: `${parent.id}/${part}`, name: part, path: `${parent.path}/${part}`, kind: "folder", size: 0, count: 0, children: [] }; parent.children.push(folder) } parent = folder } parent.children.push({ id: entry.path, name: fileName, path: entry.path, kind: "file", size: entry.size, count: 1, entry, children: [] }) } aggregate(root); return { rootLabel, nodes: root.children } }
function aggregate(node: TreeNode): [number, number] { if (node.kind === "file") return [node.size, 1]; let size = 0, count = 0; for (const child of node.children) { const [childSize, childCount] = aggregate(child); size += childSize; count += childCount } node.size = size; node.count = count; return [size, count] }
function collectFiles(node: TreeNode): FileEntry[] { if (node.entry) return [node.entry]; return node.children.flatMap(collectFiles) }
function commonRootSegments(entries: FileEntry[]) { if (!entries.length) return []; const paths = entries.map((entry) => entry.dir.split("/").filter(Boolean)), first = paths[0] ?? []; let index = 0; while (index < first.length && paths.every((parts) => parts[index] === first[index])) index += 1; return first.slice(0, index) }
function commonRoot(entries: FileEntry[]) { const segments = commonRootSegments(entries); return segments.length ? segments.join("/") : entries.length > 1 ? "多个位置" : entries[0]?.dir || "" }
function splitLines(value?: string) { return String(value ?? "").split(/\r?\n/).map((line) => line.trim()).filter(Boolean) }
function inputFormatEnabled(path: string, excludedFormatsText?: string) { const name = path.replace(/\\/g, "/").split("/").at(-1) ?? path, dot = name.lastIndexOf("."); if (dot <= 0) return true; const extension = name.slice(dot + 1).toLowerCase(); const excluded = new Set(String(excludedFormatsText ?? "avif,jxl,webp,gif").split(/[,;\s]+/).map((value) => value.replace(/^\./, "").toLowerCase()).filter(Boolean)); return !excluded.has(extension) }
function formatBytes(bytes: number) { if (!bytes) return "0 B"; const units = ["B", "KB", "MB", "GB", "TB"], index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}` }
