/**
 * @migrated-from src/lib/cards/properties/AiTagsCard.svelte
 * @source-hash sha256:6d74157d5660c8732448c982329e5c98d6169caf4a4da82efc5c014c8805bf49
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported Svelte runtime import; attribute BindDirective; template node ConstTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import {
		Bot,
		Play,
		Loader2,
		Check,
		Plus,
		AlertCircle,
		Settings,
		ChevronDown,
		ChevronUp
	} from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import * as Select from '$lib/components/ui/select';
import {
		addManualTag,
		NAMESPACE_LABELS,
		TAG_NAMESPACES
	} from '$lib/stores/emm/manualTagStore.js';
import { emmTranslationStore, emmMetadataStore } from '$lib/stores/emmMetadata.js';
import { favoriteTagStore } from '$lib/stores/emm/favoriteTagStore.js';
import { infoPanelStore } from '$lib/stores/infoPanel.js';
import { aiApiConfigStore, type AiProvider } from '$lib/stores/aiApiConfig.js';
interface InferredTag {
		namespace: string;
		tag: string;
		confidence?: number;
	}

export function AiTagsCard() {
  let isInferring = $state(false);

  let inferredTags = $state<InferredTag[]>([]);

  let errorMessage = $state('');

  let hasConfig = $state(false);

  let providers = $state<AiProvider[]>([]);

  let activeIndex = $state(0);

  let selectedProviderIndex = $state<number | null>(null);

  let showSettings = $state(false);

  let customPrompt = $state('');

  let useCustomPrompt = $state(false);

  $effect(() => {
      const unsub = aiApiConfigStore.subscribe((state) => {
        hasConfig = state.providers.length > 0;
        providers = state.providers;
        activeIndex = state.activeIndex;
      });
      return unsub;
    });

  function getSelectedProvider(): AiProvider | undefined {
      if (selectedProviderIndex !== null) {
        return providers[selectedProviderIndex];
      }
      return undefined; // 使用默认
    }

  function getProviderDisplayName(): string {
      if (selectedProviderIndex !== null) {
        return providers[selectedProviderIndex]?.name || '未知';
      }
      return providers[activeIndex]?.name || '默认';
    }

  function getCurrentPath(): string {
      const state = get(infoPanelStore);
      return state.bookInfo?.path || '';
    }

  function getFileName(path: string): string {
      return path.split(/[\\/]/).pop() || path;
    }

  function buildPrompt(fileName: string): string {
      // 获取收藏标签作为参考
      const favTags = favoriteTagStore.tags.slice(0, 50).map((t) => t.tag);

      // 获取翻译字典中的常用标签
      const dict = emmMetadataStore.getTranslationDict();
      const sampleTags: Record<string, string[]> = {};
      if (dict) {
        for (const ns of ['parody', 'character', 'artist', 'group', 'female', 'male']) {
          const nsDict = dict[ns];
          if (nsDict) {
            sampleTags[ns] = Object.keys(nsDict).slice(0, 30);
          }
        }
      }

      return `你是一个专业的漫画/图集标签分类助手。根据以下文件名推断标签。

  文件名：${fileName}

  **关键指令**：
  1. 严格从文件名中提取信息，不要凭空捏造
  2. 括号 [] 中通常是社团名，() 中通常是作者名
  3. 识别原作(parody)、角色(character)、画师(artist)、社团(group)
  4. 对于角色，如果是别名/简称，请识别出完整角色名和原作

  可参考的标签示例（仅供拼写参考）：
  ${JSON.stringify(sampleTags, null, 2)}

  我的收藏标签（仅供拼写参考）：
  ${JSON.stringify(favTags)}

  请返回 JSON 格式：
  {
    "tags": [
      { "namespace": "artist", "tag": "xxx" },
      { "namespace": "group", "tag": "xxx" },
      { "namespace": "parody", "tag": "xxx" },
      { "namespace": "character", "tag": "xxx" }
    ]
  }

  namespace 可选值：${TAG_NAMESPACES.join(', ')}
  只返回 JSON，不要其他文字。`;
    }

  async function handleInfer() {
      const path = getCurrentPath();
      if (!path) {
        errorMessage = '请先打开一个文件';
        return;
      }

      if (!hasConfig) {
        errorMessage = '请先在「AI API 配置」卡片中添加提供商';
        return;
      }

      isInferring = true;
      errorMessage = '';
      inferredTags = [];

      try {
        const fileName = getFileName(path);
        const prompt =
          useCustomPrompt && customPrompt.trim()
            ? customPrompt.replace('{fileName}', fileName)
            : buildPrompt(fileName);

        // 使用选中的提供商或默认
        const response = await aiApiConfigStore.chat(
          [
            { role: 'system', content: '你是一个专业的漫画标签分类助手。只返回 JSON 格式。' },
            { role: 'user', content: prompt }
          ],
          { jsonMode: true, provider: getSelectedProvider() }
        );

        // 解析 JSON
        const jsonMatch = response.match(/\{[\s\S]*\}/);
        if (!jsonMatch) {
          throw new Error('无法解析 AI 返回的 JSON');
        }

        const result = JSON.parse(jsonMatch[0]);
        inferredTags = result.tags || [];
        console.log('[AiTagsCard] 推断结果:', inferredTags);
      } catch (e) {
        console.error('[AiTagsCard] 推断失败:', e);
        errorMessage = e instanceof Error ? e.message : '推断失败';
      } finally {
        isInferring = false;
      }
    }

  async function handleAddTag(tag: InferredTag) {
      const path = getCurrentPath();
      if (!path) return;

      const success = await addManualTag(path, tag.namespace, tag.tag);
      if (success) {
        // 从推断列表中移除已添加的标签
        inferredTags = inferredTags.filter(
          (t) => !(t.namespace === tag.namespace && t.tag === tag.tag)
        );
      }
    }

  async function handleAddAllTags() {
      const path = getCurrentPath();
      if (!path) return;

      for (const tag of inferredTags) {
        await addManualTag(path, tag.namespace, tag.tag);
      }
      inferredTags = [];
    }

  function translateTag(namespace: string, tag: string): string {
      const dict = emmMetadataStore.getTranslationDict();
      return emmTranslationStore.translateTag(tag, namespace, dict);
    }

  let activeProviderName = $derived.by(() => {
      return getProviderDisplayName();
    });

  const DEFAULT_PROMPT_TEMPLATE = `根据文件名推断标签。

  文件名：{fileName}

  返回 JSON 格式：
  {
    "tags": [
      { "namespace": "artist", "tag": "xxx" },
      { "namespace": "parody", "tag": "xxx" }
    ]
  }

  namespace 可选值：artist, group, parody, character, female, male, mixed, other, cosplayer, language, reclass`;
  return (
    <Fragment>

<div className="space-y-3">
	{/*  头部  */}
	<div className="flex items-center justify-between">
		<div className="flex items-center gap-2">
			<Bot className="h-4 w-4 text-purple-500"></Bot>
			<span className="text-sm font-medium">AI 标签推断</span>
		</div>
		<div className="flex items-center gap-1">
			{hasConfig ? (<Fragment>
				<span className="text-muted-foreground bg-muted rounded px-1.5 py-0.5 text-[10px]">
					{activeProviderName}
				</span>
			</Fragment>) : null}
			<Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => {
					showSettings = !showSettings;
				}}>
				{showSettings ? (<Fragment>
					<ChevronUp className="h-3.5 w-3.5"></ChevronUp>
				</Fragment>) : (<Fragment>
					<Settings className="h-3.5 w-3.5"></Settings>
				</Fragment>)}
			</Button>
		</div>
	</div>

	{/*  设置面板  */}
	{showSettings && hasConfig ? (<Fragment>
		<div className="bg-muted/30 space-y-2 rounded border p-2">
			{/*  模型选择  */}
			<div className="space-y-1">
				<span className="text-muted-foreground text-[10px]">使用模型</span>
				<Select.Root type="single" value={selectedProviderIndex?.toString() ?? 'default'} onValueChange={(v) => {
						selectedProviderIndex = v === 'default' ? null : parseInt(v);
					}}>
					<Select.Trigger className="h-7 text-xs">
						<span>{selectedProviderIndex !== null
								? providers[selectedProviderIndex]?.name
								: `默认 (${providers[activeIndex]?.name})`}</span>
					</Select.Trigger>
					<Select.Content>
						<Select.Item value="default">默认 ({providers[activeIndex]?.name})</Select.Item>
						{providers.map((provider, i) => (<Fragment key={i}>
							<Select.Item value={i.toString()}>{provider.name}</Select.Item>
						</Fragment>))}
					</Select.Content>
				</Select.Root>
			</div>

			{/*  自定义 Prompt  */}
			<div className="space-y-1">
				<div className="flex items-center justify-between">
					<span className="text-muted-foreground text-[10px]">自定义 Prompt</span>
					<button type="button" className="text-primary text-[10px] hover:underline" onClick={() => {
							useCustomPrompt = !useCustomPrompt;
						}}>
						{useCustomPrompt ? '使用默认' : '自定义'}
					</button>
				</div>
				{useCustomPrompt ? (<Fragment>
					<textarea placeholder="输入自定义 prompt，使用 {fileName} 代表文件名" className="bg-background min-h-[80px] w-full resize-y rounded border p-2 text-xs"></textarea>
					<p className="text-muted-foreground text-[10px]">
						提示：使用 &#123;fileName&#125; 插入文件名
					</p>
				</Fragment>) : null}
			</div>
		</div>
	</Fragment>) : null}

	{/*  未配置提示  */}
	{!hasConfig ? (<Fragment>
		<div className="flex items-center gap-2 rounded bg-amber-500/10 px-2 py-1.5 text-xs text-amber-500">
			<AlertCircle className="h-3.5 w-3.5 shrink-0"></AlertCircle>
			<span>请先在「AI API 配置」卡片中添加提供商</span>
		</div>
	</Fragment>) : null}

	{/*  推断按钮  */}
	<Button variant="outline" size="sm" className="w-full" disabled={isInferring || !hasConfig} onClick={handleInfer}>
		{isInferring ? (<Fragment>
			<Loader2 className="mr-2 h-4 w-4 animate-spin"></Loader2>
			推断中...
		</Fragment>) : (<Fragment>
			<Play className="mr-2 h-4 w-4"></Play>
			根据文件名推断标签
		</Fragment>)}
	</Button>

	{/*  错误信息  */}
	{errorMessage ? (<Fragment>
		<div className="text-destructive bg-destructive/10 rounded px-2 py-1 text-xs">
			{errorMessage}
		</div>
	</Fragment>) : null}

	{/*  推断结果  */}
	{inferredTags.length > 0 ? (<Fragment>
		<div className="space-y-2">
			<div className="flex items-center justify-between">
				<span className="text-muted-foreground text-xs">推断结果 ({inferredTags.length})</span>
				<Button variant="ghost" size="sm" className="h-6 text-xs" onClick={handleAddAllTags}>
					<Check className="mr-1 h-3 w-3"></Check>
					全部添加
				</Button>
			</div>
			<div className="flex flex-wrap gap-1.5">
				{inferredTags.map((tag) => (<Fragment>
					{/* TODO unsupported ConstTag */}
					<button type="button" className="inline-flex items-center gap-1 rounded border border-dashed border-purple-500/50 bg-purple-500/10 px-2 py-1 text-xs transition-colors hover:bg-purple-500/20" onClick={() => handleAddTag(tag)} title={`点击添加: ${NAMESPACE_LABELS[tag.namespace]}: ${tag.tag}${translated !== tag.tag
							? ` (${translated})`
							: ''}`}>
						<span className="text-purple-400 opacity-70">{tag.namespace.slice(0, 1)}:</span>
						<span className="text-purple-300">{translated}</span>
						<Plus className="h-3 w-3 text-purple-400"></Plus>
					</button>
				</Fragment>))}
			</div>
		</div>
	</Fragment>) : null}

	{/*  使用说明  */}
	{hasConfig && inferredTags.length === 0 && !isInferring ? (<Fragment>
		<p className="text-muted-foreground py-2 text-center text-[10px]">
			点击上方按钮，AI 将根据文件名推断标签
		</p>
	</Fragment>) : null}
</div></Fragment>
  )
}
