/**
 * @migrated-from src/lib/cards/properties/EmmConfigCard.svelte
 * @source-hash sha256:31aa9e3785d5fbac55a4a07944820b5912c398f644811044026247877dee38a4
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import EmmConfig from '$lib/components/panels/emm/EmmConfigCard.js';

export function EmmConfigCard() {
  return (
    <Fragment>

<EmmConfig></EmmConfig></Fragment>
  )
}
