/**
 * @migrated-from src/lib/cards/properties/EmmSyncCard.svelte
 * @source-hash sha256:3ba07ed1c95f283dff66592d7b97962cd90b5fe698a57bcae96d875cd5442942
 * @features ai-ollama-translation,card-windows-tabs,emm-ratings-tags-translation,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import EmmSync from '$lib/components/panels/emm/EmmSyncCard.js';

export function EmmSyncCard() {
  return (
    <Fragment>

<EmmSync></EmmSync></Fragment>
  )
}
