import type { ReaderInputAction } from "@xiranite/node-neoview/ui-core"

// Keep unsupported legacy IDs in the shared registry for migration/reporting, but do not let
// the GUI persist bindings that the current Reader surface cannot execute.
export const GUI_READER_INPUT_ACTIONS = [
  "reader.previous-page",
  "reader.next-page",
  "reader.first-page",
  "reader.last-page",
  "reader.page-left",
  "reader.page-right",
  "reader.next-book",
  "reader.previous-book",
  "reader.zoom-in",
  "reader.zoom-out",
  "reader.fit-window",
  "reader.actual-size",
  "reader.toggle-temporary-fit",
  "reader.fullscreen",
  "workspace.toggle-layout-mode",
  "workspace.focus-reader",
  "workspace.focus-previous-lane",
  "workspace.focus-next-lane",
  "workspace.toggle-active-lane-fullscreen",
  "workspace.fit-lanes",
  "shell.toggle-left-sidebar",
  "shell.toggle-right-sidebar",
  "shell.toggle-top-toolbar-pin",
  "shell.toggle-bottom-thumbnail-pin",
  "reader.toggle-reading-direction",
  "reader.toggle-book-mode",
  "reader.rotate-clockwise",
  "reader.rotate-180",
  "reader.toggle-single-panorama",
  "reader.reset-view",
  "viewer.toggle-sidebar-control",
  "viewer.toggle-progress-bar",
  "viewer.toggle-page-info",
  "viewer.toggle-progress-bar-glow",
  "viewer.toggle-page-switch-toast",
  "viewer.toggle-book-switch-toast",
  "viewer.toggle-boundary-toast",
  "viewer.toggle-info-overlay",
  "viewer.toggle-hover-scroll",
  "file.open",
  "file.close",
  "file.delete-current",
  "reader.open-settings",
  "radial.open-default",
  "radial.confirm",
  "video.play-pause",
  "video.seek-forward",
  "video.seek-backward",
  "video.toggle-mute",
  "video.cycle-loop-mode",
  "video.volume-up",
  "video.volume-down",
  "video.speed-up",
  "video.speed-down",
  "video.toggle-speed",
  "video.toggle-seek-mode",
  "slideshow.toggle",
  "slideshow.play-pause",
  "slideshow.stop",
  "slideshow.skip",
] as const satisfies readonly ReaderInputAction[]

export const GUI_READER_INPUT_ACTION_SET: ReadonlySet<ReaderInputAction> = new Set(GUI_READER_INPUT_ACTIONS)
