/**
 * @migrated-from src/lib/cards/history/HistoryListCard.svelte
 * @source-hash sha256:91b086362ec3bc31550a6b6d76e0f6d48bc4af85eb38f54dfaaf63e7c7c7fd1b
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { FileListPanel } from '$lib/cards/shared';
import { VIRTUAL_PATHS } from '$lib/components/panels/folderPanel/stores/folderTabStore';

export function HistoryListCard() {
  return (
    <Fragment>

{/*  使用共享的文件列表面板  */}
<FileListPanel initialPath={VIRTUAL_PATHS.HISTORY} mode="history"></FileListPanel></Fragment>
  )
}
