/**
 * @migrated-from src/lib/cards/insights/ReadingHeatmapCard.svelte
 * @source-hash sha256:e56723336019055c9ac16dbacaf802d18e0ef823ba8870aa01e8a50bab909f15
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { unifiedHistoryStore, type UnifiedHistoryEntry } from '$lib/stores/unifiedHistory.js';
import ReadingHeatmapChart, {
		type HeatmapCell
	} from '$lib/components/panels/insights/ReadingHeatmapChart.js';

export function ReadingHeatmapCard() {
  let historyEntries = $state<UnifiedHistoryEntry[]>([]);

  const weekdayLabelMap = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];

  $effect(() => {
      const unsubscribe = unifiedHistoryStore.subscribe((value) => {
        historyEntries = value ?? [];
      });
      return unsubscribe;
    });

  function buildReadingHeatmapData() {
      const matrix = Array.from({ length: 7 }, () => Array(24).fill(0));

      for (const entry of historyEntries) {
        const date = new Date(entry.timestamp);
        if (Number.isNaN(date.getTime())) continue;
        const weekday = date.getDay();
        const hour = date.getHours();
        matrix[weekday][hour]++;
      }

      let maxCount = 0;
      const cells: HeatmapCell[] = [];
      let topSlot: HeatmapCell | null = null;

      for (let weekday = 0; weekday < 7; weekday++) {
        for (let hour = 0; hour < 24; hour++) {
          const count = matrix[weekday][hour];
          if (count > maxCount) maxCount = count;
          const cell: HeatmapCell = {
            weekday,
            hour,
            count,
            weekdayLabel: weekdayLabelMap[weekday],
            hourLabel: `${String(hour).padStart(2, '0')}:00`
          };
          cells.push(cell);
          if (!topSlot || cell.count > topSlot.count) topSlot = cell;
        }
      }

      return { cells, maxCount, topSlot };
    }

  const heatmap = $derived(buildReadingHeatmapData());
  return (
    <Fragment>

<div className="space-y-3 overflow-hidden">
	{heatmap.topSlot && heatmap.topSlot.count > 0 ? (<Fragment>
		<p className="text-muted-foreground text-xs">
			高峰时段: <span className="text-foreground font-medium">{heatmap.topSlot.weekdayLabel} {heatmap.topSlot.hourLabel}</span>
		</p>
	</Fragment>) : null}
	<div className="overflow-hidden">
		<ReadingHeatmapChart cells={heatmap.cells} maxCount={heatmap.maxCount}></ReadingHeatmapChart>
	</div>
</div></Fragment>
  )
}
