/**
 * @migrated-from src/lib/cards/insights/SourceBreakdownCard.svelte
 * @source-hash sha256:a1d54eecc905de25a70161e3d938589cb8508870b003752be758ca3af5d05000
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { unifiedHistoryStore, type UnifiedHistoryEntry } from '$lib/stores/unifiedHistory.js';
import { Progress } from '$lib/components/ui/progress';

export function SourceBreakdownCard() {
  let historyEntries = $state<UnifiedHistoryEntry[]>([]);

  $effect(() => {
      const unsubscribe = unifiedHistoryStore.subscribe((value) => {
        historyEntries = value ?? [];
      });
      return unsubscribe;
    });

  function buildSourceStats() {
      const bySource: Record<string, number> = {};
      for (const entry of historyEntries) {
        // 从路径推断来源类型
        const path = entry.pathStack?.[0]?.path || '';
        let source = '本地';
        if (
          path.includes('.zip') ||
          path.includes('.cbz') ||
          path.includes('.cbr') ||
          path.includes('.rar')
        ) {
          source = '压缩包';
        } else if (path.includes('.pdf')) {
          source = 'PDF';
        }
        bySource[source] = (bySource[source] ?? 0) + 1;
      }
      const total = historyEntries.length;
      const sorted = Object.entries(bySource)
        .sort((a, b) => b[1] - a[1])
        .map(([source, count]) => ({
          source,
          count,
          percent: total > 0 ? Math.round((count / total) * 100) : 0
        }));
      return { sorted, total };
    }

  const stats = $derived(buildSourceStats());
  return (
    <Fragment>

<div className="space-y-3">
	{stats.sorted.length > 0 ? (<Fragment>
		{stats.sorted.map((item) => (<Fragment>
			<div className="space-y-1">
				<div className="flex items-center justify-between text-xs">
					<span>{item.source}</span>
					<span className="text-muted-foreground">{item.count} ({item.percent}%)</span>
				</div>
				<Progress value={item.percent} className="h-1.5"></Progress>
			</div>
		</Fragment>))}
	</Fragment>) : (<Fragment>
		<p className="text-muted-foreground py-4 text-center text-xs">暂无来源数据</p>
	</Fragment>)}
</div></Fragment>
  )
}
