/**
 * @migrated-from src/lib/components/ui/popover/popover-portal.svelte
 * @source-hash sha256:fb6faa25d48bb4ae6d020cc7e2a2ddc037a14da134b6902348510e1289f785b1
 * @features 
 * @source-disposition converted
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import { Popover as PopoverPrimitive } from 'bits-ui';

export function PopoverPortal(props: PopoverPrimitive.PortalProps) {
  const { ...restProps } = props
  return (
    <Fragment>

<PopoverPrimitive.Portal {...restProps}></PopoverPrimitive.Portal></Fragment>
  )
}
