export {
  DEFAULT_READER_INFO_OVERLAY,
  READER_INFO_OVERLAY_HEIGHT_MAX,
  READER_INFO_OVERLAY_HEIGHT_MIN,
  READER_INFO_OVERLAY_OPACITY_MAX,
  READER_INFO_OVERLAY_OPACITY_MIN,
  READER_INFO_OVERLAY_WIDTH_MAX,
  READER_INFO_OVERLAY_WIDTH_MIN,
  applyReaderInfoOverlayPatch,
  normalizeReaderInfoOverlay,
  parseReaderInfoOverlayPatch,
  type ReaderInfoOverlayMutation,
  type ReaderInfoOverlayPatch,
  type ReaderInfoOverlaySettings,
} from "./application/info-overlay/ReaderInfoOverlay.js"
