/**
 * @migrated-from src/lib/cards/settings/BookSettingsCard.svelte
 * @source-hash sha256:9b769409edeaf84889918e74cd023ebfd88343196ad9feaa08332cc374326694
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import BookSettingsPanel from '$lib/components/panels/BookSettingsPanel.js';

export function BookSettingsCard() {
  return (
    <Fragment>

<div className="settings-card-wrapper">
	<BookSettingsPanel></BookSettingsPanel>
</div>

</Fragment>
  )
}
