/**
 * @migrated-from src/lib/cards/settings/CardManagementCard.svelte
 * @source-hash sha256:4525a078f2d5937ce70db549ecb16db7c63597a17a8c590b1bbde48140e10fa6
 * @features ai-ollama-translation,card-windows-tabs,file-browser-navigation,history-bookmarks-progress,input-bindings-radial-voice,metadata-dimensions-properties,page-index-navigation,page-layout-modes,panels-toolbar-shell,performance-benchmark-diagnostics,playlist-quick-library,search-sort-filter-library,settings-import-export-backup,startup-window-cli-lifecycle,super-resolution,theme-background-empty-state
 * @source-disposition manual
 * @migration-status review-scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import CardPanelManager from '$lib/components/settings/CardPanelManager.js';

export function CardManagementCard() {
  return (
    <Fragment>

<div className="settings-card-wrapper">
	<CardPanelManager></CardPanelManager>
</div>

</Fragment>
  )
}
