/**
 * @migrated-from src/lib/components/layout/MainLayout.svelte
 * @source-hash sha256:6d7539a648dd4e0b96f714723e61ec71b8afdae91521427e3b501b756b68f303
 * @features panels-toolbar-shell,startup-window-cli-lifecycle,theme-background-empty-state
 * @source-disposition manual
 * @migration-status partial-scaffold
 * @unsupported attribute BindDirective; template node RenderTag
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import {
		leftSidebarOpen,
		leftSidebarWidth,
		rightSidebarOpen,
		rightSidebarWidth,
		pageLeft,
		pageRight,
		zoomIn,
		zoomOut,
		sidebarLeftPanels,
		sidebarRightPanels,
		activePanel,
		// 高度配置
		leftSidebarHeight,
		leftSidebarCustomHeight,
		leftSidebarVerticalAlign,
		leftSidebarHorizontalPos,
		rightSidebarHeight,
		rightSidebarCustomHeight,
		rightSidebarVerticalAlign,
		rightSidebarHorizontalPos,
		getSidebarHeightPercent,
		getVerticalAlignStyle
	} from '$lib/stores';
import { bookStore } from '$lib/stores/book.js';
import LeftSidebar from './LeftSidebar.js';
import RightSidebar from './RightSidebar.js';
import { TopToolbar } from './TopToolbar/index';
import BottomThumbnailBar from './BottomThumbnailBar.js';
import { StackView } from '$lib/stackview';
import AreaOverlay from '../ui/AreaOverlay.js';
import HoverAreasOverlay from '../ui/HoverAreasOverlay.js';
import { settingsManager } from '$lib/settings/settingsManager';

export function MainLayout(props: Record<string, unknown>) {
  const { children } = props
  let settings = $state(settingsManager.getSettings());

  let hoverAreas = $derived(settings.panels?.hoverAreas);

  const MAIN_LAYOUT_DEBUG = false;

  function debugMainLayout(...args: unknown[]): void {
      if (MAIN_LAYOUT_DEBUG) {
        console.debug(...args);
      }
    }

  let leftHeightPercent = $derived(
      getSidebarHeightPercent($leftSidebarHeight, $leftSidebarCustomHeight)
    );

  let leftVerticalStyle = $derived(
      getVerticalAlignStyle($leftSidebarVerticalAlign, leftHeightPercent)
    );

  let leftHeightStyle = $derived(`height: ${leftHeightPercent}%;`);

  let leftWidth = $derived(
      $leftSidebarOpen ? $leftSidebarWidth : (hoverAreas?.leftTriggerWidth ?? 32)
    );

  let leftXOffset = $derived(
      $leftSidebarHorizontalPos > 0 ? `left: ${$leftSidebarHorizontalPos * 0.5}%;` : 'left: 0;'
    );

  let rightHeightPercent = $derived(
      getSidebarHeightPercent($rightSidebarHeight, $rightSidebarCustomHeight)
    );

  let rightVerticalStyle = $derived(
      getVerticalAlignStyle($rightSidebarVerticalAlign, rightHeightPercent)
    );

  let rightHeightStyle = $derived(`height: ${rightHeightPercent}%;`);

  let rightWidth = $derived(
      $rightSidebarOpen ? $rightSidebarWidth : (hoverAreas?.rightTriggerWidth ?? 32)
    );

  let rightXOffset = $derived(
      $rightSidebarHorizontalPos > 0 ? `right: ${$rightSidebarHorizontalPos * 0.5}%;` : 'right: 0;'
    );

  $effect(() => {
      debugMainLayout('[MainLayout] Left:', {
        preset: $leftSidebarHeight,
        percent: leftHeightPercent,
        width: leftWidth,
        style: leftHeightStyle,
        alignStyle: leftVerticalStyle
      });
      debugMainLayout('[MainLayout] Right:', {
        preset: $rightSidebarHeight,
        percent: rightHeightPercent,
        width: rightWidth,
        style: rightHeightStyle,
        alignStyle: rightVerticalStyle
      });
    });

  function handleSidebarResize(width: number) {
      leftSidebarWidth.set(width);
    }

  function handleRightSidebarResize(width: number) {
      rightSidebarWidth.set(width);
    }

  let showAreaOverlay = $state(false);

  let showHoverAreasOverlay = $state(false);

  $effect(() => {
      const handleAreaOverlayToggle = (e: CustomEvent) => {
        showAreaOverlay = e.detail.show;
      };

      window.addEventListener('areaOverlayToggle', handleAreaOverlayToggle as EventListener);
      return () => {
        window.removeEventListener('areaOverlayToggle', handleAreaOverlayToggle as EventListener);
      };
    });

  $effect(() => {
      const handleHoverAreasToggle = (e: CustomEvent) => {
        showHoverAreasOverlay = e.detail.show;
      };

      window.addEventListener('hoverAreasOverlayToggle', handleHoverAreasToggle as EventListener);
      return () => {
        window.removeEventListener(
          'hoverAreasOverlayToggle',
          handleHoverAreasToggle as EventListener
        );
      };
    });

  $effect(() => {
      settingsManager.addListener((newSettings) => {
        settings = newSettings;
      });
    });

  function handleAreaAction(e: CustomEvent) {
      const { action } = e.detail;
      debugMainLayout('执行区域操作:', action);

      // 这里可以根据action执行相应的操作
      // 例如：翻页、缩放等
      switch (action) {
        case 'nextPage': {
          void pageRight();
          break;
        }
        case 'prevPage': {
          void pageLeft();
          break;
        }
        case 'pageLeft': {
          const settings = settingsManager.getSettings();
          const readingDirection = settings.book.readingDirection;
          if (readingDirection === 'right-to-left') {
            // 右开模式下，逻辑“向左翻页”对应物理向右翻
            void pageRight();
          } else {
            void pageLeft();
          }
          break;
        }
        case 'pageRight': {
          const settings = settingsManager.getSettings();
          const readingDirection = settings.book.readingDirection;
          if (readingDirection === 'right-to-left') {
            // 右开模式下，逻辑“向右翻页”对应物理向左翻
            void pageLeft();
          } else {
            void pageRight();
          }
          break;
        }
        case 'zoomIn':
          zoomIn();
          break;
        case 'zoomOut':
          zoomOut();
          break;
        // 其他操作...
      }
    }
  return (
    <Fragment>

<div className="bg-background fixed inset-0" role="application" aria-label="NeoView 主界面">
	{/*  自动隐藏顶部工具栏（包含标题栏）  */}
	<TopToolbar></TopToolbar>

	{/*  主内容区域（全屏）  */}
	<div className="absolute inset-0 overflow-hidden">
		{bookStore.viewerOpen ? (<Fragment>
			{/*  图片查看器  */}
			<StackView showPageInfo={true} showProgress={true}></StackView>
		</Fragment>) : (<Fragment>
			{/*  默认内容  */}
			{/* TODO unsupported RenderTag */}
		</Fragment>)}
	</div>

	{/*  自动隐藏底部缩略图栏  */}
	<BottomThumbnailBar></BottomThumbnailBar>

	{/*  左侧边栏（悬浮，支持自由移动）  */}
	<div className="pointer-events-none absolute z-[55]" style={`${leftXOffset} ${leftVerticalStyle} ${leftHeightStyle} width: ${leftWidth}px;`}>
		<div className="pointer-events-auto h-full w-full">
			<LeftSidebar onResize={handleSidebarResize}></LeftSidebar>
		</div>
	</div>

	{/*  右侧边栏（悬浮，支持自由移动）  */}
	<div className="pointer-events-none absolute z-[55]" style={`${rightXOffset} ${rightVerticalStyle} ${rightHeightStyle} width: ${rightWidth}px;`}>
		<div className="pointer-events-auto h-full w-full">
			<RightSidebar onResize={handleRightSidebarResize}></RightSidebar>
		</div>
	</div>

	{/*  区域覆盖层  */}
	<AreaOverlay onAreaAction={handleAreaAction} sidebarOpen={$leftSidebarOpen} rightSidebarOpen={$rightSidebarOpen}></AreaOverlay>
	<HoverAreasOverlay></HoverAreasOverlay>
</div></Fragment>
  )
}
