/**
 * @migrated-from src/lib/components/browser/FileSystemBrowser.svelte
 * @source-hash sha256:035e1305dbafbb398e58ae6b64685208ee747551d70ba4a2f227ca64f95024eb
 * @features file-browser-navigation
 * @migration-status scaffold
 * Generated by @xiranite/svelte-migrate; move to production only after behavior tests pass.
 */
import { Fragment } from "react"
import FolderPanel from '../panels/folderPanel/FolderPanel.js';

export function FileSystemBrowser() {
  return (
    <Fragment>

<FolderPanel></FolderPanel></Fragment>
  )
}
