/* @jsxImportSource @opentui/react */
import { useKeyboard } from "@opentui/react"
import { useState } from "react"
import type { TerminalUiScreenProps } from "@xiranite/cli-runtime/terminal"
import { ActionTabs,ExecutionActions,ProgressBar,TerminalThemeProvider,WorkbenchField,WorkbenchPanel,resolveTerminalTheme,terminalIcon,useAnimation,useTerminalChromeActions,useTerminalTheme,useTerminalUiSession } from "@xiranite/cli-runtime/terminal/opentui"
import { createTerminalTranslator } from "@xiranite/cli-runtime/i18n"
import type { CoveruInput,CoveruResult } from "./core.js"
export function CoveruTui(p:TerminalUiScreenProps<CoveruInput,CoveruResult>){const [x]=useState(p.theme??p.preferences?.current.theme??"inherit");return <TerminalThemeProvider theme={resolveTerminalTheme(x==="inherit"?"nord":x)}><Desk {...p}/></TerminalThemeProvider>}
function Desk({definition,language,onExit}:TerminalUiScreenProps<CoveruInput,CoveruResult>){const th=useTerminalTheme(),t=createTerminalTranslator(language),s=useTerminalUiSession(definition),f=useAnimation({intervalMs:s.phase==="running"?90:500}),d=s.result?.data,a=String(s.values.action??"scan");useTerminalChromeActions({onReset:s.reset,onExit});useKeyboard(k=>{if(k.name==="escape")onExit()});const field=(id:string)=>definition.schema.fields.find(x=>x.id===id)!;const F=({id,w}:{id:string;w?:`${number}%`})=><box width={w} flexGrow={w?0:1}><WorkbenchField field={field(id)} value={s.values[id]} error={s.fieldErrors[id]} focused={s.focusedControlId===id} disabled={s.phase==="running"} t={t} onFocus={()=>s.focus(id)} onChange={v=>s.setField(id,v)}/></box>;return <box width="100%" height="100%" paddingLeft={1} paddingRight={1} flexDirection="column" overflow="hidden"><box height={4} borderStyle="single" borderColor={th.colors.border} paddingLeft={1} flexDirection="row" justifyContent="space-between"><box flexDirection="column"><text fg={th.colors.primary}><b>{`${terminalIcon("status")} COVERU // COVER SCANNER`}</b></text><text fg={th.colors.mutedForeground}>归档候选评分 · 输出冲突检查 · 安全提取</text></box><text fg={th.colors.success}>{`SCAN READY ${["·","•","●","•"][f%4]}`}</text></box><box height={3} marginTop={1}><ActionTabs id="action" options={field("action").options??[]} value={a} focused={false} onFocus={()=>s.focus("action")} onChange={v=>s.setField("action",v)}/></box><box height={7} flexDirection="row" gap={1}><F id="paths" w="48%"/><F id="outputMode" w="16%"/><F id="dryRun" w="14%"/><box width="19%" flexDirection="column" borderStyle="rounded" borderColor={s.dangerous?th.colors.error:th.colors.border} paddingLeft={1}><text fg={th.colors.mutedForeground}>{s.dangerous?"! LIVE EXTRACT":"◌ PLAN ONLY"}</text><box flexGrow={1}/><ExecutionActions session={s} executeLabel="⌕ 扫描候选" confirmLabel="! 确认提取"/></box></box><box flexGrow={1} minHeight={0} marginTop={1} flexDirection="row" gap={1}><WorkbenchPanel title={`候选封面 · ${d?.candidates.length??0}`} description="来源、评分和目标路径" width="66%"><scrollbox flexGrow={1}>{d?.candidates.map((c,i)=><box key={`${c.sourcePath}-${i}`} flexDirection="column" borderStyle="single" borderColor={c.status==="error"?th.colors.error:th.colors.border} paddingLeft={1}><text fg={c.status==="ready"?th.colors.success:th.colors.primary}>{`▹ ${c.sourcePath}`}</text><text fg={th.colors.mutedForeground}>{`★ ${c.score} · ${c.sourceEntry||"image"} → ${c.outputPath}`}</text>{c.reason?<text fg={th.colors.error}>{`! ${c.reason}`}</text>:null}</box>)}</scrollbox></WorkbenchPanel><WorkbenchPanel title="提取状态" description="计数、错误与进度" flexGrow={1}><text>{`✓ Ready ${d?.readyCount??0}`}</text><text>{`▣ Extracted ${d?.extractedCount??0}`}</text><text fg={th.colors.error}>{`! Errors ${d?.errorCount??0}`}</text><box flexGrow={1}/><ProgressBar value={s.progress} label={s.status||"READY"}/></WorkbenchPanel></box></box>}
